Repository apache/tvm, pull requests merged in 2018-08, with the labels that each got.

#1503 [TVM][CUDA] NVIDIA GPU Int8 Support
  src/codegen/codegen_cuda.cc
  src/codegen/codegen_cuda.h
  src/codegen/opt/build_cuda_on.cc
  tests/python/unittest/test_codegen_cuda.py
Labels: status: need update

#1520 [MXNET] LRN support in MXNET frontend
  nnvm/python/nnvm/frontend/mxnet.py
  nnvm/tests/python/frontend/mxnet/test_forward.py
Labels: status: need review

#1518 [FRONTEND][ONNX]LRN support for ONNX
  nnvm/python/nnvm/frontend/onnx.py
  nnvm/tests/python/frontend/onnx/test_forward.py
Labels: status: need update

#1548 [NNVM] Enhance operator fusion for more element wise patterns
  nnvm/src/compiler/graph_fuse.cc
  nnvm/tests/python/compiler/test_op_fusion.py
  topi/python/topi/arm_cpu/conv2d.py
  topi/python/topi/util.py
Labels: status: need review, status: need update, status: review in progress

#1528 [NNVM][TENSORFLOW]L2_normalization operator support for tensorflow
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/tests/python/frontend/tensorflow/test_forward.py
Labels: status: accepted

#1564 Separate fusion and Compilation
  nnvm/python/nnvm/compiler/build_module.py
  nnvm/src/compiler/graph_compile.cc
  nnvm/src/compiler/graph_fuse.cc
  nnvm/src/compiler/graph_fuse.h
Labels: status: review in progress

#1553 [TOPI] add injective scheduler for HLS backends
  src/codegen/build_module.cc
  src/codegen/codegen_vhls.cc
  src/codegen/codegen_vhls.h
  src/codegen/intrin_rule_vhls.cc
  topi/python/topi/__init__.py
  topi/python/topi/hls/__init__.py
  topi/python/topi/hls/injective.py
  topi/tests/python/test_topi_broadcast.py
  topi/tests/python/test_topi_clip.py
  topi/tests/python/test_topi_math.py
  topi/tests/python/test_topi_relu.py
  topi/tests/python/test_topi_transform.py
Labels: status: need update, type: topi

#1569 Use int for int8x4 due to performance overhead of char4
  src/codegen/codegen_cuda.cc
  tests/python/unittest/test_codegen_cuda.py
Labels: status: need update

#1533 [DOCS] Neural network Deployment Guide with System Module Mode #1523
  docs/deploy/nnvm.md
Labels: beginner-friendly, status: need update, status: review in progress

#1566 [TOPI] Add conv2d transpose for arm cpu
  nnvm/include/nnvm/top/nn.h
  nnvm/python/nnvm/testing/dcgan.py
  nnvm/python/nnvm/top/nn.py
  nnvm/src/top/nn/convolution.cc
  nnvm/tests/python/frontend/mxnet/model_zoo/dcgan.py
  python/tvm/autotvm/measure/measure_methods.py
  python/tvm/autotvm/task/dispatcher.py
  python/tvm/autotvm/task/nnvm_integration.py
  python/tvm/autotvm/tophub.py
  python/tvm/autotvm/tuner/callback.py
  topi/python/topi/arm_cpu/__init__.py
  topi/python/topi/arm_cpu/conv2d.py
  topi/python/topi/arm_cpu/conv2d_transpose.py
  topi/python/topi/arm_cpu/depthwise_conv2d.py
  topi/python/topi/nn/conv2d_transpose.py
  topi/tests/python/test_topi_conv2d.py
  topi/tests/python/test_topi_conv2d_transpose_nchw.py
  tutorials/autotvm/tune_nnvm_arm.py
  tutorials/nnvm_quick_start.py
Labels: status: need review

#1571 Vulkan TVM Android Support
  apps/android_rpc/README.md
  apps/android_rpc/app/src/main/jni/Application.mk
  apps/android_rpc/tests/android_rpc_test.py
  jvm/core/src/main/java/ml/dmlc/tvm/TVMContext.java
  jvm/core/src/main/java/ml/dmlc/tvm/rpc/RPCSession.java
  python/tvm/rpc/client.py
  web/tvm_runtime.js
Labels: status: need review

#1573 DLPack Conversion API
  include/tvm/runtime/c_runtime_api.h
  include/tvm/runtime/ndarray.h
  python/tvm/_ffi/ndarray.py
  python/tvm/contrib/dlpack.py
  python/tvm/ndarray.py
  src/runtime/ndarray.cc
  tests/python/contrib/test_dlpack.py
Labels: status: need update

#1595 [Topi] Split_indices negative axis added
  topi/include/topi/transform.h
  topi/tests/python_cpp/test_topi_transform.py
Labels: type: topi

#1546 [FRONTEND][TENSORFLOW] Optimized tensorflow testcases
  nnvm/tests/python/frontend/tensorflow/test_forward.py
Labels: status: accepted

#1576 [FRONTEND][DARKNET]LSTM and GRU support
  nnvm/python/nnvm/frontend/darknet.py
  nnvm/python/nnvm/testing/darknet.py
  nnvm/tests/python/frontend/darknet/test_forward.py
Labels: status: review in progress

#1591 [NNVM] Add ONNX upsample converter
  nnvm/python/nnvm/frontend/onnx.py
  nnvm/tests/python/frontend/onnx/test_forward.py
Labels: status: review in progress

#1612 Add -mattr=+neon for all arm cpu targets
  apps/benchmark/README.md
  python/tvm/target.py
  tutorials/nnvm/deploy_model_on_rasp.py
Labels: status: accepted

#1608 [NNVM] Bug fix Prevent fusing convolution with injective op
  nnvm/src/compiler/graph_fuse.cc
  nnvm/tests/python/compiler/test_op_fusion.py
Labels: status: need review

#1570 [NNVM] TF: Add Pack operation
  nnvm/include/nnvm/top/tensor.h
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/src/top/tensor/transform.cc
  nnvm/tests/python/frontend/tensorflow/test_forward.py
Labels: status: review in progress

#1501 [NNVM][DARKNET]Yolo and Upsample frontend support
  nnvm/python/nnvm/frontend/darknet.py
  nnvm/python/nnvm/testing/darknet.py
  nnvm/python/nnvm/top/vision.py
  nnvm/src/top/vision/yolo/yolo.cc
  nnvm/tests/python/frontend/darknet/test_forward.py
  tutorials/nnvm/from_darknet.py
Labels: status: need update, status: review in progress

#1506 Improve x86 Inception
  nnvm/python/nnvm/top/nn.py
  nnvm/python/nnvm/top/transform.py
  nnvm/src/top/tensor/transform.cc
  nnvm/tests/python/unittest/test_correct_layout.py
  topi/include/topi/nn/pooling.h
  topi/python/topi/cuda/pooling.py
  topi/python/topi/generic/injective.py
  topi/python/topi/generic/nn.py
  topi/python/topi/opengl/pooling.py
  topi/python/topi/x86/injective.py
  topi/python/topi/x86/pooling.py
  topi/tests/python/test_topi_pooling.py
Labels: status: need update, type: topi

#1614 Add int8 gemm recipe
  topi/recipe/gemm/gemm_int8.py
Labels: status: need review

#1615 [AUTOTVM] Allow fallback for template & Fix bugs in tuners
  nnvm/python/nnvm/compiler/build_module.py
  nnvm/tests/python/compiler/test_autotvm_task_extraction.py
  python/tvm/autotvm/__init__.py
  python/tvm/autotvm/measure/measure.py
  python/tvm/autotvm/measure/measure_methods.py
  python/tvm/autotvm/task/__init__.py
  python/tvm/autotvm/task/dispatcher.py
  python/tvm/autotvm/task/nnvm_integration.py
  python/tvm/autotvm/task/space.py
  python/tvm/autotvm/task/task.py
  python/tvm/autotvm/tophub.py
  python/tvm/autotvm/tuner/ga_tuner.py
  python/tvm/autotvm/tuner/model_based_tuner.py
  python/tvm/autotvm/tuner/sa_model_optimizer.py
  python/tvm/autotvm/tuner/tuner.py
  python/tvm/autotvm/tuner/xgboost_cost_model.py
  python/tvm/autotvm/tuner/xgboost_tuner.py
  python/tvm/exec/tophub.py
  python/tvm/target.py
  tests/python/unittest/test_autotvm_dispatch_context.py
  tests/python/unittest/test_autotvm_space.py
  tests/python/unittest/test_autotvm_xgboost_model.py
  topi/python/topi/arm_cpu/conv2d.py
  topi/python/topi/arm_cpu/depthwise_conv2d.py
  topi/python/topi/x86/injective.py
  topi/tests/python/common.py
  topi/tests/python/test_topi_bitserial_conv2d.py
  topi/tests/python/test_topi_bitserial_conv2d_rasp.py
  topi/tests/python/test_topi_bnn.py
  topi/tests/python/test_topi_broadcast.py
  topi/tests/python/test_topi_clip.py
  topi/tests/python/test_topi_conv2d.py
  topi/tests/python/test_topi_conv2d_hwcn.py
  topi/tests/python/test_topi_conv2d_nchw.py
  topi/tests/python/test_topi_conv2d_transpose_nchw.py
  topi/tests/python/test_topi_dense.py
  topi/tests/python/test_topi_depthwise_conv2d.py
  tutorials/autotvm/tune_nnvm_arm.py
Labels: status: need review

#1505 [NNVM][TEST] Test against numerical grad
  docs/api/python/nnvm/index.rst
  docs/api/python/nnvm/testing.rst
  docs/api/python/nnvm/testing_new_ops.rst
  nnvm/python/nnvm/testing/__init__.py
  nnvm/python/nnvm/testing/check_computation.py
  nnvm/tests/python/compiler/test_top_level1.py
  nnvm/tests/python/compiler/test_top_level3.py
  nnvm/tests/python/compiler/test_top_level4.py
Labels: status: need review, status: need update, status: review in progress

#1653 [CODEGEN][AOCL] Add math intrinsic rules
  docs/deploy/aocl_fpga.md
  python/tvm/_ffi/runtime_ctypes.py
  src/codegen/build_module.cc
  src/codegen/codegen_aocl.cc
  src/codegen/intrin_rule_aocl.cc
  tests/python/integration/test_ewise_fpga.py
  topi/tests/python/test_topi_math.py
Labels: status: need update

#1645 [FRONTEND][ONNX]HardSigmoid, min, max, mean ops support
  nnvm/python/nnvm/frontend/onnx.py
  nnvm/tests/python/frontend/onnx/test_forward.py
Labels: status: need review

#1654 [FRONTEND][TENSORFLOW] fix the convertion of sum and add testcase for it
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/tests/python/frontend/tensorflow/test_forward.py
Labels: status: review in progress

#1661 [AUTOTVM] (API CHANGE) Decouple build and run in measurement
  docs/api/python/autotvm.rst
  python/tvm/autotvm/__init__.py
  python/tvm/autotvm/measure/__init__.py
  python/tvm/autotvm/measure/local_executor.py
  python/tvm/autotvm/measure/measure.py
  python/tvm/autotvm/measure/measure_methods.py
  python/tvm/autotvm/tuner/ga_tuner.py
  python/tvm/autotvm/tuner/sa_model_optimizer.py
  tests/python/integration/test_tuning.py
  tests/python/unittest/test_autotvm_common.py
  tests/python/unittest/test_autotvm_database.py
  tests/python/unittest/test_autotvm_measure.py
  topi/recipe/gemm/gemm_int8.py
  tutorials/autotvm/tune_conv2d_cuda.py
  tutorials/autotvm/tune_nnvm_arm.py
  tutorials/autotvm/tune_simple_template.py
Labels: status: need review

#1663 [TOPI] add nn schedulers for HLS backends
  nnvm/python/nnvm/testing/config.py
  src/codegen/codegen_aocl.cc
  topi/python/topi/hls/__init__.py
  topi/python/topi/hls/nn.py
  topi/tests/python/common.py
  topi/tests/python/test_topi_pooling.py
  topi/tests/python/test_topi_reduce.py
  topi/tests/python/test_topi_relu.py
  topi/tests/python/test_topi_softmax.py
  topi/tests/python/test_topi_transform.py
Labels: status: need review

#1660 [PASS] Enhance gpu verify pass
  src/pass/verify_gpu_code.cc
  tests/python/unittest/test_pass_verify_gpu_code.py
Labels: status: need review

#1664 Support FoldScaleAxis for depthwise convolution
  nnvm/src/compiler/fold_scale_axis.cc
  nnvm/tests/python/compiler/test_fold_axis.py
Labels: status: need update

#1665 [FRONTEND][TENSORFLOW] Add Transpose support.
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/tests/python/frontend/tensorflow/test_forward.py
Labels: status: need update
