Repository apache/tvm, pull requests merged in 2018-06, with the labels that each got.

#1199 [NNVM] Elu support added in darknet frontend
  nnvm/python/nnvm/frontend/darknet.py
  nnvm/tests/python/frontend/darknet/test_forward.py
Labels: status: review in progress

#1201 [NNVM] Fix softmax gradient
  nnvm/src/top/nn/nn.cc
  nnvm/tests/python/compiler/test_top_level1.py
Labels: status: accepted

#1235 [CODEGEN] ARM Popcount lowering rule and codegen updates
  src/codegen/llvm/codegen_arm.cc
  src/codegen/llvm/codegen_llvm.cc
  src/codegen/llvm/llvm_module.cc
  tests/python/unittest/test_codegen_arm.py
Labels: status: accepted

#1188 [NNVM][FRONTEND] Tensorflow frontend support
  nnvm/python/nnvm/compiler/build_module.py
  nnvm/python/nnvm/frontend/__init__.py
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/python/nnvm/testing/tf.py
  nnvm/python/nnvm/top/tensor.py
  nnvm/tests/python/frontend/tensorflow/test_forward.py
  tests/scripts/task_python_nnvm.sh
  tutorials/nnvm/from_tensorflow.py
Labels: status: accepted

#1274 fix ctx errors in copro_sync.cc
  src/pass/coproc_sync.cc
  tests/python/unittest/test_pass_storage_sync.py
Labels: status: accepted

#1294 [NNVM][TESTING] Add two testing symbols: dqn and dcgan
  nnvm/python/nnvm/testing/__init__.py
  nnvm/python/nnvm/testing/dcgan.py
  nnvm/python/nnvm/testing/dqn.py
  nnvm/tests/python/frontend/mxnet/model_zoo/__init__.py
  nnvm/tests/python/frontend/mxnet/model_zoo/dcgan.py
  nnvm/tests/python/frontend/mxnet/model_zoo/dqn.py
  nnvm/tests/python/frontend/mxnet/test_graph.py
Labels: status: need update

#1288 [FRONTEND][MXNET] Add squeeze_axis support to split operator
  nnvm/python/nnvm/frontend/mxnet.py
  nnvm/tests/python/frontend/mxnet/test_forward.py
Labels: status: accepted

#1290 [TOPI] Conv2d Added and Optimized for Intel HD Graphics
  include/tvm/build_module.h
  python/tvm/target.py
  src/codegen/build_module.cc
  src/codegen/codegen_opencl.cc
  src/runtime/opencl/opencl_device_api.cc
  tests/python/integration/test_ewise.py
  tests/python/unittest/test_lang_target.py
  topi/python/topi/__init__.py
  topi/python/topi/cuda/pooling.py
  topi/python/topi/intel_graphics/__init__.py
  topi/python/topi/intel_graphics/conv2d.py
Labels: status: need update, status: review in progress

#1251 [FRONTEND] A Python hybrid frontend
  docs/api/python/hybrid.rst
  docs/api/python/index.rst
  docs/dev/hybrid_script.rst
  docs/dev/index.rst
  docs/langref/hybrid_script.rst
  docs/langref/index.rst
  python/tvm/build_module.py
  python/tvm/hybrid/__init__.py
  python/tvm/hybrid/api.py
  python/tvm/hybrid/intrin.py
  python/tvm/hybrid/parser.py
  python/tvm/hybrid/util.py
  python/tvm/hybrid/var_decl.py
  tests/python/unittest/test_hybrid_script.py
Labels: status: need update, status: review in progress

#1296 [PASS] Add GPU IR verifier
  include/tvm/ir_pass.h
  include/tvm/runtime/device_api.h
  python/tvm/_ffi/runtime_ctypes.py
  src/api/api_pass.cc
  src/pass/verify_gpu_code.cc
  src/runtime/cuda/cuda_device_api.cc
  src/runtime/metal/metal_device_api.mm
  src/runtime/opencl/opencl_device_api.cc
  src/runtime/opengl/opengl_device_api.cc
  src/runtime/rocm/rocm_device_api.cc
  src/runtime/vulkan/vulkan_device_api.cc
  tests/python/unittest/test_pass_verify_gpu_code.py
Labels: status: need update

#1239 [NNVM][TOPI] Add FTVMCompute for matmul
  nnvm/python/nnvm/top/nn.py
  nnvm/src/top/tensor/matrix_op.cc
  topi/include/topi/nn.h
  topi/include/topi/tags.h
Labels: status: need update, status: review in progress

#1300 Support onnx tensor attribute and Constant op
  nnvm/python/nnvm/frontend/onnx.py
Labels: status: need update, status: review in progress

#1335 [NNVM][TENSORFLOW] Mobilenet support.
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/python/nnvm/testing/tf.py
  nnvm/tests/python/frontend/tensorflow/test_forward.py
Labels: status: need update, status: review in progress

#1333 [NNVM][ONNX] Shape operator support (limited/differed) - #1297
  nnvm/python/nnvm/frontend/onnx.py
  nnvm/tests/python/frontend/onnx/test_forward.py
Labels: status: need update

#1234 [NNVM][TOPI] Add gradients for broadcast_* ops
  nnvm/include/nnvm/tuple.h
  nnvm/python/nnvm/top/reduction.py
  nnvm/src/top/tensor/broadcast.cc
  nnvm/src/top/tensor/reduce.cc
  nnvm/src/top/tensor/transform.cc
  nnvm/tests/python/compiler/test_top_level4.py
  topi/include/topi/reduction.h
  topi/python/topi/cuda/reduction.py
  topi/tests/python_cpp/test_topi_reduce.py
Labels: status: need update, status: review in progress

#1299 Improve schedule load, add slice_like
  nnvm/include/nnvm/top/tensor.h
  nnvm/python/nnvm/frontend/mxnet.py
  nnvm/python/nnvm/top/nn.py
  nnvm/python/nnvm/top/transform.py
  nnvm/src/top/elemwise_op_common.h
  nnvm/src/top/tensor/transform.cc
  nnvm/tests/python/compiler/test_top_level4.py
  topi/python/topi/generic/nn.py
  topi/python/topi/nn/conv2d.py
  topi/python/topi/x86/conv2d.py
  topi/tests/python_cpp/test_topi_transform.py
Labels: status: accepted

#1318 Strided_slice added in NNVM
  nnvm/include/nnvm/top/tensor.h
  nnvm/python/nnvm/top/transform.py
  nnvm/src/top/tensor/transform.cc
  nnvm/tests/python/compiler/test_top_level1.py
Labels: status: need update
