Repository apache/tvm, pull requests merged in 2018-09, with the labels that each got.

#1683 Rename axis parameter in onnx squeeze
  nnvm/python/nnvm/frontend/onnx.py
  nnvm/tests/python/frontend/onnx/test_forward.py
Labels: status: need update

#1685 expose SaveToFile symbol on windows
  include/tvm/runtime/module.h
Labels: status: need review

#1671 [Tutorial] tutorial to writing a costumized pass
  docs/conf.py
  python/tvm/build_module.py
  tutorials/dev/README.txt
  tutorials/dev/low_level_custom_pass.py
Labels: status: need review

#1684 Allow log_softmax on explicit trailing dim
  nnvm/src/top/nn/nn.cc
Labels: status: need update

#1289 [Sparse] add sparse tensor computation support
  python/tvm/autotvm/task/dispatcher.py
  python/tvm/contrib/sparse.py
  tests/python/contrib/test_sparse.py
  topi/python/topi/__init__.py
  topi/python/topi/sparse/__init__.py
  topi/python/topi/sparse/csrmm.py
  topi/python/topi/sparse/csrmv.py
  topi/python/topi/sparse/dense.py
  topi/tests/python/test_topi_sparse.py
Labels: status: need review, status: need update

#1666 [NNVM]Tensorflow and Onnx basic ops
  nnvm/python/nnvm/frontend/onnx.py
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/tests/python/frontend/onnx/test_forward.py
  nnvm/tests/python/frontend/tensorflow/test_forward.py
Labels: status: need update

#1707 [TOPI] Add dp4a intrinsic to CUDA
  topi/python/topi/cuda/tensor_intrin.py
  topi/recipe/gemm/gemm_int8.py
Labels: status: need update

#1646 Add demo_android Dockerfile
  apps/android_deploy/README.md
  apps/android_deploy/build.gradle
  apps/android_deploy/dev_tools/sign_apk.sh
  apps/android_rpc/build.gradle
  apps/android_rpc/dev_tools/sign_apk.sh
  docker/Dockerfile.demo_android
  docker/bash.sh
  docker/build.sh
  docker/install/ubuntu_install_androidsdk.sh
  docker/install/ubuntu_install_gradle.sh
  docker/install/ubuntu_install_java.sh
Labels: status: need update

#1697 [FRONTEND][TENSORFLOW] Helper function to add shapes into the graph. Use temp folder for models and clean it.
  nnvm/python/nnvm/testing/tf.py
  tutorials/nnvm/from_tensorflow.py
Labels: status: need review

#1696 Allow inplace memory optimization for different data type
  nnvm/src/pass/plan_memory.cc
Labels: status: need update

#1715 [Keras] fix weight shape in dilated conv
  nnvm/python/nnvm/frontend/keras.py
  nnvm/tests/python/frontend/keras/test_forward.py
Labels: status: need review

#1628 [NNVM][TOPI] Add mean and product operators
  docs/api/python/topi.rst
  docs/nnvm_top.rst
  include/tvm/expr.h
  include/tvm/ir_operator.h
  nnvm/python/nnvm/top/reduction.py
  nnvm/src/top/tensor/reduce.cc
  nnvm/tests/python/compiler/test_top_level4.py
  src/lang/ir_operator.cc
  topi/include/topi/reduction.h
  topi/python/topi/reduction.py
  topi/src/topi.cc
  topi/tests/python/test_topi_reduce.py
  topi/tests/python_cpp/test_topi_reduce.py
Labels: status: need update

#1686 [NNVM][KERAS]LSTMCell support
  nnvm/python/nnvm/frontend/keras.py
  nnvm/tests/python/frontend/keras/test_forward.py
Labels: status: need update

#1672 [High level OPT][RFC] NNVMv2 IR - Relay
  CMakeLists.txt
  docs/conf.py
  include/tvm/relay/base.h
  include/tvm/relay/environment.h
  include/tvm/relay/error.h
  include/tvm/relay/expr.h
  include/tvm/relay/expr_functor.h
  include/tvm/relay/logging.h
  include/tvm/relay/op.h
  include/tvm/relay/pass.h
  include/tvm/relay/type.h
  python/tvm/relay/__init__.py
  python/tvm/relay/_env.py
  python/tvm/relay/_env.pyi
  python/tvm/relay/_ir_pass.py
  python/tvm/relay/_ir_pass.pyi
  python/tvm/relay/_make.py
  python/tvm/relay/base.py
  python/tvm/relay/env.py
  python/tvm/relay/expr.py
  python/tvm/relay/expr.pyi
  python/tvm/relay/ir_builder.py
  python/tvm/relay/ir_pass.py
  python/tvm/relay/op/__init__.py
  python/tvm/relay/op/_make.py
  python/tvm/relay/op/_tensor.py
  python/tvm/relay/op/op.py
  python/tvm/relay/op/tensor.py
  python/tvm/relay/ty.py
  python/tvm/relay/ty.pyi
  python/tvm/tensor.py
  src/relay/ir/base.cc
  src/relay/ir/environment.cc
  src/relay/ir/expr.cc
  src/relay/ir/expr_functor.cc
  src/relay/ir/op.cc
  src/relay/ir/type.cc
  src/relay/op/tensor/elemwise.cc
  src/relay/op/type_relations.cc
  src/relay/op/type_relations.h
  src/relay/pass/alpha_eq.cc
  src/relay/pass/incomplete_type.h
  src/relay/pass/kind_check.cc
  src/relay/pass/resolve.cc
  src/relay/pass/resolve.h
  src/relay/pass/type_functor.h
  src/relay/pass/type_infer.cc
  src/relay/pass/type_subst.cc
  src/relay/pass/type_subst.h
  src/relay/pass/type_visitor.h
  src/relay/pass/unifier.cc
  src/relay/pass/unifier.h
  tests/python/relay/test_ir_builder.py
  tests/python/relay/test_ir_nodes.py
  tests/python/relay/test_relay_op.py
  tests/python/relay/test_tyck_eval_integration.py
  tests/scripts/task_python_integration.sh
Labels: status: RFC, status: need review

#1642 Fix Softmax in onnx frontend
  nnvm/python/nnvm/frontend/onnx.py
  nnvm/tests/python/frontend/onnx/model_zoo/squeezenet.py
  nnvm/tests/python/frontend/onnx/test_forward.py
  nnvm/tests/python/frontend/onnx/test_graph.py
Labels: status: need update

#1748 [RELAY] IR Wellform Checker
  include/tvm/relay/error.h
  include/tvm/relay/expr.h
  include/tvm/relay/pass.h
  python/tvm/relay/_ir_pass.pyi
  python/tvm/relay/ir_pass.py
  src/relay/pass/well_formed.cc
  tests/python/relay/test_relay_op.py
  tests/python/relay/test_well_formed.py
Labels: status: need update

#1695 Heterogeneous Runtime
  python/tvm/build_module.py
  python/tvm/contrib/graph_runtime.py
  src/runtime/graph/graph_runtime.cc
  tests/python/unittest/test_runtime_heterogeneous.py
Labels: status: accepted

#1729 [NNVM]Keras SimpleRnn and GRU support
  nnvm/python/nnvm/frontend/keras.py
  nnvm/tests/python/frontend/keras/test_forward.py
Labels: status: need review

#1760 [NNVM] Bugfix operator fusion for residual block with layout transform
  nnvm/src/compiler/graph_compile.cc
  nnvm/src/compiler/graph_fuse.cc
  nnvm/tests/python/compiler/test_op_fusion.py
Labels: status: need review

#1680 INT8 conv operator implementation with NCHWc data layout for Intel machines
  topi/python/topi/nn/conv2d.py
  topi/python/topi/x86/check_targets.py
  topi/python/topi/x86/conv2d.py
  topi/python/topi/x86/conv2d_avx_1x1.py
  topi/python/topi/x86/conv2d_avx_common.py
  topi/python/topi/x86/tensor_intrin.py
  topi/recipe/conv/test_conv_int8_intel.py
Labels: status: need update

#1744 [TOPI] Access topi::matmul from Python
  nnvm/src/top/tensor/matrix_op.cc
  python/tvm/api.py
  python/tvm/tag.py
  topi/include/topi/nn.h
  topi/include/topi/transform.h
  topi/python/topi/reduction.py
  topi/python/topi/tensor.py
  topi/python/topi/transform.py
  topi/src/topi.cc
  topi/tests/python/test_topi_matmul.py
Labels: status: need review

#1764 [ONNX][FRONTEND] Constantfill - #1539
  nnvm/python/nnvm/frontend/onnx.py
  nnvm/tests/python/frontend/onnx/test_forward.py
Labels: status: need review

#1771 Adding source types to C++ reduce functions to pass the type check for Tensorize
  src/lang/ir_operator.cc
  tests/python/unittest/test_lang_tensor.py
Labels: status: need update

#1770 Added Dockerfile demonstrating OpenCL & OpenGL installation
  docker/Dockerfile.demo_opencl
Labels: status: need update

#1731 [NNVM][TENSORFLOW]Fix lstm testcase to support get_output without size input
  nnvm/tests/python/frontend/tensorflow/test_forward.py
Labels: status: WIP, status: need update

#1773 support of multiple devices for tvm.build
  python/tvm/build_module.py
  tests/python/unittest/test_runtime_heterogeneous.py
Labels: status: WIP, status: need review

#1714 Feature: Tensorflow relational operators
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review
