Repository apache/tvm, pull requests merged in 2018-12, with the labels that each got.

#2123 Add Split and realdiv op support
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#2258 Generate predicates for non-root iteration variables as well
  src/schedule/message_passing.cc
Labels: status: accepted

#1470 [RUNTIME][GOLANG] TVM runtime for golang v0.1
  golang/Makefile
  golang/README.md
  golang/sample/Makefile
  golang/sample/complex.go
  golang/sample/deploy.py
  golang/sample/pack_func_closure_arg.go
  golang/sample/pack_func_closure_return.go
  golang/sample/pack_func_convert.go
  golang/sample/pack_func_handle_arg.go
  golang/sample/pack_func_register.go
  golang/sample/simple.go
  golang/src/array_test.go
  golang/src/bytearray.go
  golang/src/bytearray_test.go
  golang/src/context.go
  golang/src/error.go
  golang/src/error_test.go
  golang/src/function.go
  golang/src/function_test.go
  golang/src/gotvm.cc
  golang/src/gotvm.go
  golang/src/gotvm.h
  golang/src/gotvm_test.go
  golang/src/module.go
  golang/src/module_test.go
  golang/src/ndarray.go
  golang/src/tvm_runtime_pack.cc
  golang/src/type.go
  golang/src/util.go
  golang/src/value.go
  golang/src/value_test.go
Labels: status: need update, status: review in progress

#2263 [RELAY] Fix serialization issue
  src/lang/reflection.cc
  src/relay/ir/op.cc
  tests/python/relay/test_ir_nodes.py
Labels: status: accepted

#1806 Allow long type values in shape list
  nnvm/python/nnvm/compiler/build_module.py
Labels: status: need update

#2105 [FRONTEND][TENSORFLOW] Support Unstack and Split
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review, status: need update

#2289 [RELAY] Fix alter_op_layout
  python/tvm/relay/op/nn/_nn.py
Labels: status: accepted

#2265 [TOPI] NCHWc added input shape 4 condition, intel graphics conv2d schedule debugged for inception_v3 workloads
  nnvm/python/nnvm/top/nn.py
  topi/python/topi/intel_graphics/conv2d.py
Labels: status: accepted

#2276 [RELAY] Add broadcast_to operator
  docs/langref/relay_op.rst
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/transform.py
  src/relay/op/nn/pooling.cc
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_op_level10.py
Labels: status: accepted

#2287 [Hybrid Script] Inter-function call supported!
  python/tvm/hybrid/api.py
  python/tvm/hybrid/calls.py
  python/tvm/hybrid/intrin.py
  python/tvm/hybrid/parser.py
  python/tvm/hybrid/util.py
  python/tvm/hybrid/var_decl.py
  tests/python/unittest/test_hybrid_script.py
Labels: status: need review

#2273 [DOC] Codebase walkthrough with vector add example
  docs/dev/codebase_walkthrough.rst
  docs/dev/index.rst
Labels: status: need review

#2322 [relay][frontend] Enable ssd test by attaching schedules to multibox and ssd ops
  python/tvm/relay/frontend/common.py
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/op/vision/__init__.py
  python/tvm/relay/op/vision/_multibox.py
  python/tvm/relay/op/vision/multibox.py
  tests/python/relay/test_op_level5.py
  topi/python/topi/util.py
  tutorials/nnvm/deploy_ssd.py
Labels: status: need review

#2219 Add a the ability to trigger debugging in the interpreter without recompiling
  include/tvm/relay/attrs/debug.h
  include/tvm/relay/op_attr_types.h
  python/tvm/relay/__init__.py
  python/tvm/relay/debug.py
  python/tvm/relay/op/__init__.py
  python/tvm/relay/op/op.py
  src/relay/backend/interpreter.cc
  src/relay/op/debug.cc
  tests/python/relay/test_debug.py
Labels: status: need update

#2242 [FRONTEND][TENSORFLOW] Simplify input shape
  nnvm/python/nnvm/frontend/tensorflow.py
Labels: status: need update

#2338 [TOPI, CUDA] Update cuda softmax schedule for spatial inputs
  topi/python/topi/cuda/softmax.py
  topi/tests/python/test_topi_softmax.py
Labels: status: need review

#2354 Mutate free variables in CommReducer in cache_write
  src/schedule/schedule_dataflow_rewrite.cc
  tests/python/unittest/test_schedule_schedule_ops.py
Labels: status: need update
