Repository apache/tvm, pull requests merged in 2018-07, with the labels that each got.

#1307 add take frontend
  nnvm/include/nnvm/top/tensor.h
  nnvm/python/nnvm/top/transform.py
  nnvm/src/top/tensor/transform.cc
  nnvm/tests/python/compiler/test_top_level1.py
Labels: status: accepted

#1346 [AVG POOL] Asymmetric padding (SAME) support.
  nnvm/include/nnvm/top/nn.h
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/src/top/nn/pooling.cc
  nnvm/tests/python/frontend/tensorflow/test_forward.py
  topi/include/topi/nn/pooling.h
  topi/python/topi/nn/pooling.py
  topi/tests/python/test_topi_pooling.py
  topi/tests/python_cpp/test_topi_pooling.py
Labels: status: accepted

#1373 support equal and not_equal in topi
  docs/api/python/topi.rst
  topi/include/topi/broadcast.h
  topi/python/topi/broadcast.py
  topi/src/topi.cc
  topi/tests/python/test_topi_broadcast.py
Labels: status: accepted

#1371 [NNVM][ONNX] Slice, Floor, Ceil, Clip and MatMul support for frontend #1297
  nnvm/python/nnvm/frontend/onnx.py
  nnvm/tests/python/frontend/onnx/test_forward.py
Labels: status: review in progress

#1352 Add normal distribution to random engines
  python/tvm/contrib/random.py
  src/contrib/random/mt_random_engine.cc
  src/contrib/random/random.cc
  src/contrib/random/sgx_random_engine.cc
  tests/python/contrib/test_random.py
Labels: status: need update, status: review in progress

#1345 Add support for multiple OpenCL platforms
  cmake/config.cmake
  cmake/modules/OpenCL.cmake
  include/tvm/runtime/c_runtime_api.h
  python/tvm/_ffi/runtime_ctypes.py
  python/tvm/contrib/sdaccel.py
  src/codegen/codegen_vhls.cc
  src/codegen/opt/build_sdaccel_off.cc
  src/pass/verify_memory.cc
  src/runtime/c_runtime_api.cc
  src/runtime/opencl/opencl_common.h
  src/runtime/opencl/opencl_device_api.cc
  src/runtime/opencl/opencl_module.cc
  src/runtime/opencl/opencl_module.h
  src/runtime/opencl/sdaccel/sdaccel_common.h
  src/runtime/opencl/sdaccel/sdaccel_device_api.cc
  src/runtime/opencl/sdaccel/sdaccel_module.cc
  src/runtime/opencl/sdaccel/sdaccel_module.h
Labels: status: need update, status: review in progress

#1400 [TVM] Fixed SPIR-V codegen incorrectly not declaring the interface for the entry point
  src/codegen/spirv/codegen_spirv.cc
  src/codegen/spirv/ir_builder.cc
  src/codegen/spirv/ir_builder.h
Labels: status: need update, status: review in progress

#1403 [RUNTIME] Support setting CPU affinity
  include/tvm/runtime/threading_backend.h
  src/runtime/sgx/trusted/threading_backend.cc
  src/runtime/thread_pool.cc
  src/runtime/threading_backend.cc
Labels: status: need update, status: review in progress

#1312 [AUTOTVM] Core part of auto-tuning module
  CMakeLists.txt
  docs/api/python/autotvm.rst
  docs/api/python/index.rst
  docs/conf.py
  include/tvm/ir_pass.h
  python/tvm/autotvm/__init__.py
  python/tvm/autotvm/database.py
  python/tvm/autotvm/env.py
  python/tvm/autotvm/feature.py
  python/tvm/autotvm/measure/__init__.py
  python/tvm/autotvm/measure/executor.py
  python/tvm/autotvm/measure/local_executor.py
  python/tvm/autotvm/measure/measure.py
  python/tvm/autotvm/measure/measure_methods.py
  python/tvm/autotvm/record.py
  python/tvm/autotvm/task/__init__.py
  python/tvm/autotvm/task/code_hash.py
  python/tvm/autotvm/task/dispatcher.py
  python/tvm/autotvm/task/space.py
  python/tvm/autotvm/task/task.py
  python/tvm/autotvm/tuner/__init__.py
  python/tvm/autotvm/tuner/callback.py
  python/tvm/autotvm/tuner/cost_model.py
  python/tvm/autotvm/tuner/ga_tuner.py
  python/tvm/autotvm/tuner/gridsearch_tuner.py
  python/tvm/autotvm/tuner/metric.py
  python/tvm/autotvm/tuner/model_based_tuner.py
  python/tvm/autotvm/tuner/sa_model_optimizer.py
  python/tvm/autotvm/tuner/tuner.py
  python/tvm/autotvm/tuner/xgboost_cost_model.py
  python/tvm/autotvm/tuner/xgboost_tuner.py
  python/tvm/autotvm/util.py
  python/tvm/rpc/client.py
  src/autotvm/feature_visitor.cc
  src/autotvm/feature_visitor.h
  src/autotvm/touch_extractor.cc
  src/autotvm/touch_extractor.h
  src/codegen/build_module.cc
  src/pass/verify_gpu_code.cc
  tests/python/integration/test_tuning.py
  tests/python/unittest/test_autotvm_common.py
  tests/python/unittest/test_autotvm_database.py
  tests/python/unittest/test_autotvm_dispatch_context.py
  tests/python/unittest/test_autotvm_executor.py
  tests/python/unittest/test_autotvm_feature.py
  tests/python/unittest/test_autotvm_flop_calculator.py
  tests/python/unittest/test_autotvm_record.py
  tests/python/unittest/test_autotvm_space.py
  tests/python/unittest/test_pass_verify_gpu_code.py
  tests/scripts/task_python_docs.sh
  tests/scripts/task_python_integration.sh
  tests/scripts/task_python_unittest.sh
  tutorials/autotvm/README.txt
  tutorials/autotvm/tune_cuda_conv2d.py
  tutorials/autotvm/tune_simple_template.py
Labels: status: need update, status: review in progress

#1416 [TOPI]Add where operator
  nnvm/python/nnvm/top/transform.py
  nnvm/src/top/tensor/transform.cc
  nnvm/tests/python/compiler/test_top_level4.py
  topi/include/topi/transform.h
  topi/src/topi.cc
  topi/tests/python_cpp/test_topi_transform.py
Labels: status: need review

#1406 Add support for absolute opeartion
  docs/api/python/intrin.rst
  docs/api/python/topi.rst
  docs/nnvm_top.rst
  include/tvm/ir_operator.h
  nnvm/python/nnvm/top/tensor.py
  nnvm/src/top/tensor/elemwise.cc
  nnvm/tests/python/compiler/test_top_level3.py
  python/tvm/intrin.py
  src/api/api_ir.cc
  src/codegen/intrin_rule_cuda.cc
  src/codegen/intrin_rule_metal.cc
  src/codegen/intrin_rule_opencl.cc
  src/codegen/llvm/intrin_rule_llvm.cc
  src/codegen/llvm/intrin_rule_nvptx.cc
  src/codegen/llvm/intrin_rule_rocm.cc
  src/codegen/spirv/intrin_rule_spirv.cc
  topi/include/topi/elemwise.h
  topi/python/topi/math.py
  topi/tests/python/test_topi_math.py
Labels: status: need update, status: review in progress

#1441 [RUNTIME][OPENCL] show correct device type name
  src/runtime/opencl/opencl_common.h
  src/runtime/opencl/opencl_device_api.cc
  src/runtime/opencl/opencl_module.cc
  src/runtime/opencl/sdaccel/sdaccel_device_api.cc
  src/runtime/opencl/sdaccel/sdaccel_module.cc
Labels: status: need review

#1432 [RPC] Added native debug logging to Android RPC
  apps/android_rpc/app/src/main/jni/tvm_runtime.h
Labels: status: need update, status: review in progress

#1440 [NNVM][TENSORFLOW] bug fix on bilinear and resize op integration in frontend.
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/python/nnvm/testing/tf.py
  nnvm/src/top/image/resize.cc
  nnvm/tests/python/compiler/test_top_level2.py
  nnvm/tests/python/frontend/tensorflow/test_forward.py
  topi/include/topi/image/resize.h
  topi/python/topi/testing/bilinear_resize_python.py
Labels: status: need review

#1443 [DARKNET]RNN Support for darknet
  nnvm/python/nnvm/frontend/darknet.py
  nnvm/python/nnvm/testing/darknet.py
  nnvm/tests/python/frontend/darknet/test_forward.py
  tutorials/nnvm/nlp/from_darknet_rnn.py
Labels: status: need update, status: review in progress

#1413 [CUDA] FP16 support
  python/tvm/contrib/nvcc.py
  src/codegen/codegen_cuda.cc
  src/codegen/codegen_cuda.h
  src/codegen/opt/build_cuda_on.cc
  tests/python/unittest/test_codegen_cuda.py
Labels: status: need update, status: review in progress

#1467 [AUTOTVM] Misc bug fix
  python/tvm/autotvm/measure/measure.py
  python/tvm/autotvm/measure/measure_methods.py
  python/tvm/autotvm/record.py
  python/tvm/autotvm/task/__init__.py
  python/tvm/autotvm/task/task.py
  python/tvm/autotvm/tuner/cost_model.py
  python/tvm/autotvm/tuner/model_based_tuner.py
  python/tvm/autotvm/tuner/sa_model_optimizer.py
  python/tvm/autotvm/tuner/tuner.py
  python/tvm/autotvm/tuner/xgboost_cost_model.py
  python/tvm/target.py
  tests/python/unittest/test_autotvm_xgboost_model.py
  tutorials/autotvm/tune_cuda_conv2d.py
  tutorials/autotvm/tune_simple_template.py
Labels: status: need review

#1332 [TOPI] Bitserial low-precision convolution
  python/tvm/intrin.py
  src/codegen/llvm/llvm_module.cc
  tests/python/unittest/test_codegen_llvm.py
  topi/python/topi/generic/nn.py
  topi/python/topi/nn/__init__.py
  topi/python/topi/nn/bitserial_conv2d.py
  topi/python/topi/rasp/__init__.py
  topi/python/topi/rasp/bitserial_conv2d.py
  topi/python/topi/x86/__init__.py
  topi/python/topi/x86/bitserial_conv2d.py
  topi/tests/python/test_topi_bitserial_conv2d.py
  topi/tests/python/test_topi_bitserial_conv2d_rasp.py
Labels: status: need update, status: review in progress

#1461 [BUILD] Fix LLVM libraries cmake symbol
  cmake/util/FindLLVM.cmake
Labels: status: need update, status: review in progress

#1472 [tvm4j] add GraphRuntime
  jvm/core/src/main/java/ml/dmlc/tvm/Function.java
  jvm/core/src/main/java/ml/dmlc/tvm/Module.java
  jvm/core/src/main/java/ml/dmlc/tvm/NDArray.java
  jvm/core/src/main/java/ml/dmlc/tvm/NDArrayBase.java
  jvm/core/src/main/java/ml/dmlc/tvm/TVMType.java
  jvm/core/src/main/java/ml/dmlc/tvm/TVMValueHandle.java
  jvm/core/src/main/java/ml/dmlc/tvm/contrib/GraphModule.java
  jvm/core/src/main/java/ml/dmlc/tvm/contrib/GraphRuntime.java
  jvm/core/src/main/java/ml/dmlc/tvm/rpc/RPC.java
  jvm/core/src/main/java/ml/dmlc/tvm/rpc/RPCSession.java
  jvm/core/src/main/java/ml/dmlc/tvm/rpc/TVMRemoteContext.java
  jvm/core/src/test/java/ml/dmlc/tvm/TestUtils.java
  jvm/core/src/test/java/ml/dmlc/tvm/contrib/GraphRuntimeTest.java
  jvm/core/src/test/java/ml/dmlc/tvm/rpc/RPCTest.java
  jvm/core/src/test/scripts/test_graph_runtime.py
  jvm/native/src/main/native/jni_helper_func.h
  tests/scripts/task_java_unittest.sh
Labels: status: need review

#1477 [NNVM][DARKNET]Logistic activation added
  nnvm/python/nnvm/frontend/darknet.py
  nnvm/tests/python/frontend/darknet/test_forward.py
Labels: status: need review

#1462 [NNVM] Add argmax and argmin operations from topi
  nnvm/python/nnvm/top/reduction.py
  nnvm/src/top/tensor/reduce.cc
  nnvm/tests/python/compiler/test_top_level4.py
Labels: status: need review

#1465 Fixed bugs for conv2d
  topi/python/topi/cuda/conv2d_nchw.py
  topi/python/topi/intel_graphics/conv2d.py
  topi/tests/python/test_topi_conv2d_nchw.py
Labels: status: need update, status: review in progress

#1455 [NNVM] Fix grads for sum and expand_like
  nnvm/python/nnvm/top/transform.py
  nnvm/src/top/tensor/reduce.cc
  nnvm/src/top/tensor/transform.cc
  nnvm/tests/python/compiler/test_top_level4.py
  topi/python/topi/transform.py
Labels: status: need update, status: review in progress

#1478 [BUILD] warning fix: new does not have an alignment parameter
  CMakeLists.txt
Labels: status: need update

#1492 [NNVM][FRONTEND]C-RNN layer support is added for darknet
  nnvm/python/nnvm/frontend/darknet.py
  nnvm/tests/python/frontend/darknet/test_forward.py
Labels: status: need review

#1474 Add initial support for Intel FPGA SDK for OpenCL (AOCL)
  cmake/config.cmake
  cmake/modules/OpenCL.cmake
  docs/deploy/aocl_fpga.md
  include/tvm/runtime/c_runtime_api.h
  python/tvm/_ffi/runtime_ctypes.py
  src/codegen/build_module.cc
  src/codegen/codegen_aocl.cc
  src/codegen/opt/build_aocl_off.cc
  src/pass/verify_memory.cc
  src/runtime/c_runtime_api.cc
  src/runtime/opencl/aocl/aocl_common.h
  src/runtime/opencl/aocl/aocl_device_api.cc
  src/runtime/opencl/aocl/aocl_module.cc
  src/runtime/opencl/aocl/aocl_module.h
  src/runtime/opencl/opencl_module.cc
  tests/python/integration/test_ewise_fpga.py
Labels: status: need update, status: review in progress
