Repository apache/tvm, pull requests merged in 2018-03, with the labels that each got.

#911 Yolo2 operators
  topi/python/topi/__init__.py
  topi/python/topi/cuda/__init__.py
  topi/python/topi/cuda/vision.py
  topi/python/topi/generic/__init__.py
  topi/python/topi/generic/vision.py
  topi/python/topi/rocm/__init__.py
  topi/python/topi/rocm/vision.py
  topi/python/topi/testing/__init__.py
  topi/python/topi/testing/region_python.py
  topi/python/topi/testing/reorg_python.py
  topi/python/topi/testing/shortcut_python.py
  topi/python/topi/vision/__init__.py
  topi/python/topi/vision/reorg.py
  topi/python/topi/vision/shortcut.py
  topi/python/topi/vision/yolo2/__init__.py
  topi/python/topi/vision/yolo2/region.py
  topi/tests/python/test_topi_region.py
  topi/tests/python/test_topi_reorg.py
  topi/tests/python/test_topi_shortcut.py
Labels: status: review in progress

#971 [RUNTIME] Better scalability for multi-thread parallelization of CPUs
  src/runtime/thread_pool.cc
Labels: status: accepted, type: backend

#991 Pluggable Thread Launching Mechanism
  apps/howto_deploy/tvm_runtime_pack.cc
  apps/sgx/Makefile
  apps/sgx/app.cc
  apps/sgx/enclave.cc
  apps/sgx/enclave_config.xml
  apps/sgx/prepare_test_libs.py
  apps/sgx/test_addone.edl
  apps/sgx/tvm_runtime_pack.cc
  include/tvm/runtime/threading_backend.h
  sgx/runtime_t.cc
  sgx/runtime_u.cc
  sgx/threading_backend.cc
  sgx/tvm.edl
  src/runtime/thread_pool.cc
  src/runtime/threading_backend.cc
Labels: status: accepted

#892 Implement C++ registry to back Python target.generic_func
  include/tvm/build_module.h
  python/tvm/target.py
  src/codegen/build_module.cc
  src/runtime/threading_backend.cc
  tests/cpp/build_module_test.cc
  tests/python/unittest/test_lang_target.py
  topi/include/topi/cuda/dense.h
  topi/include/topi/cuda/extern.h
  topi/include/topi/cuda/injective.h
  topi/include/topi/cuda/pooling.h
  topi/include/topi/cuda/reduction.h
  topi/include/topi/nn/dense.h
  topi/include/topi/rocm/dense.h
  topi/python/topi/__init__.py
  topi/python/topi/generic/injective.py
  topi/python/topi/generic/nn.py
  topi/python/topi/nn/dense.py
  topi/src/topi.cc
Labels: status: accepted

#1026 [RUNTIME] better parallel launcher and task distribution
  src/runtime/thread_pool.cc
  src/runtime/threading_backend.cc
Labels: status: accepted

#1029 [TOPI] Overload operators of Tensor when TOPI is imported
  python/tvm/__init__.py
  python/tvm/expr.py
  python/tvm/generic.py
  tests/python/unittest/test_lang_tensor_overload_op.py
  topi/python/topi/__init__.py
  topi/python/topi/generic_op_impl.py
Labels: status: accepted

#1008 [TOPI] PReLU Support
  topi/include/topi/nn.h
  topi/python/topi/nn/elemwise.py
  topi/src/topi.cc
  topi/tests/python/test_topi_relu.py
  topi/tests/python_cpp/test_topi_relu.py
Labels: status: review in progress

#1031 delete init part when keeping trivial loop
  include/tvm/operation.h
  include/tvm/schedule_pass.h
  src/api/api_schedule.cc
  src/codegen/build_module.cc
  src/op/compute_op.cc
  src/op/compute_op.h
  src/op/cross_thread_reduction.cc
  src/op/extern_op.cc
  src/op/op_util.cc
  src/op/op_util.h
  src/op/placeholder_op.cc
  src/op/scan_op.cc
  src/op/tensorize.cc
  src/schedule/schedule_ops.cc
Labels: status: accepted

#980 [WIP] Linux/Android native deploy
  Makefile
  apps/android_deploy/.gitignore
  apps/android_deploy/README.md
  apps/android_deploy/app/.gitignore
  apps/android_deploy/app/build.gradle
  apps/android_deploy/app/download-models.gradle
  apps/android_deploy/app/src/main/AndroidManifest.xml
  apps/android_deploy/app/src/main/java/ml/dmlc/tvm/android/demo/MainActivity.java
  apps/android_deploy/app/src/main/jni/Android.mk
  apps/android_deploy/app/src/main/jni/Application.mk
  apps/android_deploy/app/src/main/jni/build.sh
  apps/android_deploy/app/src/main/jni/make/config.mk
  apps/android_deploy/app/src/main/jni/tvm_runtime.h
  apps/android_deploy/app/src/main/res/layout/activity_main.xml
  apps/android_deploy/app/src/main/res/layout/content_main.xml
  apps/android_deploy/app/src/main/res/values/colors.xml
  apps/android_deploy/app/src/main/res/values/strings.xml
  apps/android_deploy/app/src/main/res/values/styles.xml
  apps/android_deploy/app/src/main/res/xml/provider_paths.xml
  apps/android_deploy/build.gradle
  apps/android_deploy/dev_tools/gen_keystore.sh
  apps/android_deploy/dev_tools/sign_apk.sh
  apps/android_deploy/settings.gradle
  docs/how_to/deploy_android.md
Labels: status: review in progress

#922 [TOPI] Enhance Conv2D for More Data Type
  topi/python/topi/nn/conv2d.py
  topi/python/topi/rasp/conv2d.py
  topi/python/topi/rasp/depthwise_conv2d.py
Labels: status: accepted

#1062 Fix an issue in ReplaceDataFlow for issue 1043
  src/schedule/schedule_dataflow_rewrite.cc
  tests/python/unittest/test_pass_storage_rewrite.py
Labels: status: review in progress
