Repository apache/tvm, pull requests merged in 2018-11, with the labels that each got.

#1923 [FRONTEND][TENSORFLOW] Enhancements.
  docs/frontend/tensorflow.md
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/python/nnvm/testing/tf.py
  nnvm/tests/python/frontend/tensorflow/test_forward.py
  tutorials/nnvm/from_tensorflow.py
Labels: status: need update

#2064 Print import_llvm ir in tensorize tutorial
  tutorials/language/tensorize.py
Labels: status: need review

#2038 [FRONTEND][ONNX] fixed operator converter for Split in onnx frontend
  nnvm/python/nnvm/frontend/onnx.py
  nnvm/tests/python/frontend/onnx/test_forward.py
Labels: status: need update

#2048 [Frontend][MXNet] argmax, argmin ops support
  nnvm/include/nnvm/top/tensor.h
  nnvm/python/nnvm/frontend/mxnet.py
  nnvm/src/top/tensor/reduce.cc
  nnvm/tests/python/frontend/mxnet/test_forward.py
  topi/python/topi/cuda/reduction.py
Labels: status: accepted

#2074 [TOPI] Improve conv2d int8 schedule on CUDA
  topi/python/topi/cuda/conv2d_int8.py
Labels: status: need review

#2075 [TOPI][CUDA] int8 group conv2d
  nnvm/python/nnvm/top/nn.py
  python/tvm/autotvm/task/nnvm_integration.py
  topi/python/topi/cuda/__init__.py
  topi/python/topi/cuda/group_conv2d_nchw.py
  topi/python/topi/generic/nn.py
  topi/python/topi/nn/conv2d.py
  topi/python/topi/testing/conv2d_nchw_python.py
  topi/tests/python/common.py
  topi/tests/python/test_topi_conv2d_int8.py
  topi/tests/python/test_topi_group_conv2d.py
Labels: status: need review

#2061 [FRONTEND][ONNX]add Pad, ReduceMax, ReduceMin, ReduceMean and ReduceSum OP
  nnvm/python/nnvm/frontend/onnx.py
  nnvm/tests/python/frontend/onnx/test_forward.py
Labels: status: need review, status: need update

#1929 [Relay][OP]NMS
  include/tvm/relay/attrs/vision.h
  python/tvm/relay/op/vision/__init__.py
  python/tvm/relay/op/vision/nms.py
  src/relay/op/vision/multibox_op.cc
  src/relay/op/vision/nms.cc
  tests/python/relay/test_op_level5.py
Labels: status: need review, status: need update

#2101 [Bugfix] Recover original layout when alter_layout function return None
  nnvm/src/compiler/alter_op_layout.cc
  nnvm/tests/python/compiler/test_alter_op_layout.py
Labels: status: need review

#2107 [TOPI] Improve performance for dilated convolution
  topi/python/topi/arm_cpu/conv2d.py
  topi/python/topi/mali/conv2d.py
  topi/python/topi/nn/conv2d.py
  topi/python/topi/nn/depthwise_conv2d.py
  topi/python/topi/x86/conv2d.py
Labels: status: need review

#1981 [nnvm] Add caffe2 frontend
  nnvm/python/nnvm/frontend/__init__.py
  nnvm/python/nnvm/frontend/caffe2.py
  nnvm/python/nnvm/frontend/onnx.py
  nnvm/python/nnvm/frontend/onnx_caffe2_utils.py
  nnvm/tests/python/frontend/caffe2/model_zoo/__init__.py
  nnvm/tests/python/frontend/caffe2/model_zoo/squeezenet.py
  nnvm/tests/python/frontend/caffe2/test_forward.py
  nnvm/tests/python/frontend/caffe2/test_graph.py
Labels: status: need review

#2127 [Relay] compute & schedule for relu, softmax
  python/tvm/relay/op/nn/_nn.py
  src/relay/op/nn/nn.cc
  tests/python/relay/test_op_level1.py
Labels: status: need review

#2126 [SCHEDULE] Fix boundary check
  src/schedule/message_passing.cc
  tests/python/unittest/test_schedule_schedule_ops.py
Labels: status: need update

#1757 [HYBRID FRONTEND] Modify hybrid script to new interface; hybrid op supported; enable compilation_database in CMakeList.txt
  CMakeLists.txt
  docs/langref/hybrid_script.rst
  include/tvm/operation.h
  python/tvm/build_module.py
  python/tvm/hybrid/__init__.py
  python/tvm/hybrid/api.py
  python/tvm/hybrid/intrin.py
  python/tvm/hybrid/parser.py
  python/tvm/hybrid/util.py
  python/tvm/hybrid/var_decl.py
  python/tvm/tensor.py
  src/api/api_lang.cc
  src/op/hybrid_op.cc
  src/op/op_util.cc
  src/op/op_util.h
  tests/python/unittest/test_hybrid_script.py
Labels: status: need review, status: need update

#2120 [RELAY][BACKEND] Enable PlanMemory in the graph runtime.
  include/tvm/relay/expr.h
  python/tvm/relay/backend/_backend.py
  python/tvm/relay/backend/graph_runtime_codegen.py
  python/tvm/relay/base.py
  src/relay/backend/graph_plan_memory.cc
  src/relay/ir/text_printer.cc
  src/relay/pass/fuse_ops.cc
  tests/python/relay/test_backend_graph_runtime.py
Labels: status: need review

#2014 [RELAY]Slice_like support
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/transform.h
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_op_level10.py
Labels: status: need review, status: need update

#1913 [TensorFlow] User can provide list of outputs to from_tensorflow()
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review, status: need update

#2002 [FRONTEND][TENSORFLOW] Enable strided_slice with fix.
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#2011 [Relay] Port LSTM to Relay for testing
  python/tvm/relay/testing/__init__.py
  python/tvm/relay/testing/layers.py
  python/tvm/relay/testing/lstm.py
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_ir_text_printer.py
  tests/python/relay/test_op_level3.py
Labels: status: need review

#2148 [TOPI][CUDA] Alter op layout for group_conv2d
  nnvm/python/nnvm/top/nn.py
  topi/python/topi/cuda/conv2d_winograd.py
Labels: status: accepted

#2089 [RELAY][PASS] CombineParallelConv2D
  python/tvm/relay/build_module.py
  python/tvm/relay/ir_pass.py
  src/relay/pass/combine_parallel_conv2d.cc
  src/relay/pass/expr_subst.cc
  src/relay/pass/expr_subst.h
  src/relay/pass/pattern_util.h
  tests/python/relay/test_pass_combine_parallel_conv2d.py
Labels: status: need review

#2013 [RELAY]Testing Inception, Squeezenet, VGG port
  python/tvm/relay/testing/__init__.py
  python/tvm/relay/testing/inception_v3.py
  python/tvm/relay/testing/squeezenet.py
  python/tvm/relay/testing/vgg.py
  tests/python/relay/test_ir_text_printer.py
Labels: status: need review

#2133 [Relay][Op] Add compute, schedule, and tests for expand_dims and squeeze
  python/tvm/relay/op/_transform.py
  tests/python/relay/test_op_level1.py
  tests/python/relay/test_op_level3.py
Labels: status: need review

#2158 Fix str decoding error on non-English Windows
  python/tvm/_ffi/base.py
Labels: status: need update

#2171 [Relay] Register compute and schedule for upsampling, with miscellaneous fixes
  python/tvm/relay/base.py
  python/tvm/relay/build_module.py
  python/tvm/relay/op/nn/_nn.py
  src/relay/op/nn/upsampling.cc
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_op_level2.py
Labels: status: need review

#2161 [BACKEND][CODEGEN] C codegen with tests
  python/tvm/_ffi/libinfo.py
  python/tvm/_ffi/runtime_ctypes.py
  python/tvm/contrib/cc.py
  python/tvm/module.py
  src/codegen/codegen_c.cc
  src/codegen/codegen_c.h
  src/codegen/codegen_c_host.cc
  src/codegen/codegen_c_host.h
  src/codegen/codegen_source_base.h
  src/codegen/source_module.cc
  tests/python/unittest/test_codegen_c_host.py
Labels: status: review in progress

#1815 [Tutorial]NLP Sequence to sequence model for translation
  nnvm/python/nnvm/frontend/keras.py
  nnvm/tests/python/frontend/keras/test_forward.py
  tutorials/nnvm/nlp/keras_s2s_translate.py
Labels: status: need review, status: need update

#2106 [TOPI] Add tensor multiplication.
  topi/include/topi/transform.h
  topi/python/topi/transform.py
  topi/src/topi.cc
  topi/tests/python/test_topi_matmul.py
Labels: status: need review

#2079 [PASS] InstrumentBoundCheckers pass
  include/tvm/build_module.h
  include/tvm/ir.h
  include/tvm/ir_pass.h
  python/tvm/build_module.py
  src/api/api_pass.cc
  src/codegen/build_module.cc
  src/pass/bound_checker.cc
  src/pass/storage_flatten.cc
  tests/python/unittest/test_codegen_llvm.py
  tests/python/unittest/test_pass_bound_checkers.py
Labels: status: need review, status: review in progress

#2187 [Relay] Add support for tuple node in operator fusion
  src/relay/pass/fuse_ops.cc
  tests/python/relay/test_pass_fuse_ops.py
Labels: status: accepted
