Repository apache/tvm, pull requests merged in 2018-10, with the labels that each got.

#1786 [Relay] Free Variables
  include/tvm/relay/pass.h
  python/tvm/relay/ir_pass.py
  src/relay/pass/type_visitor.h
  src/relay/pass/util.cc
  tests/python/relay/test_free_vars.py
Labels: status: need update

#1749 [RELAY] First pass at pretty printer
  include/tvm/relay/base.h
  include/tvm/relay/expr.h
  include/tvm/relay/expr_functor.h
  include/tvm/relay/type.h
  python/tvm/relay/__init__.py
  python/tvm/relay/_expr.py
  python/tvm/relay/expr.py
  python/tvm/relay/expr.pyi
  src/relay/ir/debug_printer.cc
  src/relay/ir/doc.h
  src/relay/ir/expr.cc
  src/relay/pass/type_functor.h
  tests/python/relay/test_debug_printer.py
Labels: status: need update

#1735 [TOPI] Add conv2d int8 template
  nnvm/python/nnvm/top/nn.py
  nnvm/src/top/nn/convolution.cc
  topi/python/topi/cuda/conv2d.py
  topi/python/topi/cuda/conv2d_direct.py
  topi/python/topi/cuda/conv2d_int8.py
  topi/python/topi/cuda/conv2d_winograd.py
  topi/python/topi/generic/nn.py
  topi/python/topi/nn/conv2d.py
  topi/tests/python/test_topi_conv2d_int8.py
Labels: status: WIP, status: review in progress

#1754 [NNVM][TEST] Numgrad: fix nan and multioutput
  nnvm/python/nnvm/testing/check_computation.py
  nnvm/tests/python/compiler/test_top_level1.py
Labels: status: need update

#1774 [Tutorial] tutorial for tensorize
  tutorials/language/tensorize.py
Labels: status: need review, status: need update

#1378 [DEBUG]Support a debug framework for TVM Runtime
  CMakeLists.txt
  Jenkinsfile
  docs/dev/debugger.rst
  python/tvm/contrib/debugger/__init__.py
  python/tvm/contrib/debugger/debug_result.py
  python/tvm/contrib/debugger/debug_runtime.py
  python/tvm/contrib/graph_runtime.py
  src/api/api_base.cc
  src/runtime/graph/debug/graph_runtime_debug.cc
  src/runtime/graph/graph_runtime.cc
  src/runtime/graph/graph_runtime.h
  tests/python/unittest/test_runtime_graph_debug.py
Labels: status: need update, status: review in progress

#1819 [RELAY][OP] expand_dims
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/transform.h
  python/tvm/relay/__init__.py
  python/tvm/relay/op/__init__.py
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_op_level1.py
  topi/include/topi/transform.h
Labels: status: need review

#1597 Add rust runtime
  .gitignore
  rust/.gitignore
  rust/.rustfmt.toml
  rust/.travis.yml
  rust/Cargo.toml
  rust/src/errors.rs
  rust/src/lib.rs
  rust/src/runtime/allocator.rs
  rust/src/runtime/array.rs
  rust/src/runtime/c_runtime_api.rs
  rust/src/runtime/graph.rs
  rust/src/runtime/mod.rs
  rust/src/runtime/module.rs
  rust/src/runtime/packed_func.rs
  rust/src/runtime/sgx.rs
  rust/src/runtime/threading.rs
  rust/src/runtime/workspace.rs
  rust/tests/.gitignore
  rust/tests/build_model.py
  rust/tests/test_graph_serde.rs
  rust/tests/test_nnvm/Cargo.toml
  rust/tests/test_nnvm/build.rs
  rust/tests/test_nnvm/src/build_test_graph.py
  rust/tests/test_nnvm/src/main.rs
  rust/tests/test_tvm_basic/Cargo.toml
  rust/tests/test_tvm_basic/build.rs
  rust/tests/test_tvm_basic/src/build_test_lib.py
  rust/tests/test_tvm_basic/src/main.rs
Labels: status: need update

#1776 [Relay] Dead Code Elimination
  include/tvm/relay/pass.h
  include/tvm/runtime/ndarray.h
  python/tvm/relay/_ir_pass.pyi
  python/tvm/relay/ir_builder.py
  python/tvm/relay/ir_pass.py
  python/tvm/relay/ty.py
  src/relay/pass/alpha_eq.cc
  src/relay/pass/dead_code.cc
  src/runtime/ndarray.cc
  tests/python/relay/test_dead_code_elimination.py
  tests/python/relay/test_pass_alpha_equal.py
  tests/python/relay/test_type_infer.py
Labels: status: need update

#1844 [Relay][Op] Clip
  python/tvm/relay/op/tensor.py
  src/relay/op/tensor/unary.cc
  tests/python/relay/test_op_level3.py
Labels: status: need update

#1849 [Relay] [Op] add relu
  docs/langref/relay_op.rst
  python/tvm/relay/op/nn/nn.py
  src/relay/op/nn/nn.cc
  src/relay/op/op_common.h
  src/relay/op/tensor/binary.cc
  src/relay/op/tensor/unary.cc
  tests/python/relay/test_op_level1.py
Labels: status: need update

#1845 [Relay][Op] Add operators full and full_like
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/transform.h
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_op_level3.py
Labels: status: need update

#1862 [RELAY][OP] conv2d_transpose
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/nn.h
  python/tvm/relay/op/nn/nn.py
  src/relay/op/nn/convolution.cc
  tests/python/relay/test_op_level2.py
Labels: status: need review

#1869 Add relay.where
  docs/langref/relay_op.rst
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_op_level4.py
Labels: status: need update

#1851 [Rust] Add rust runtime to CI
  apps/sgx/enclave/.rustfmt.toml
  docker/Dockerfile.ci_cpu
  docker/install/ubuntu_install_rust.sh
  rust/.rustfmt.toml
  rust/src/runtime/array.rs
  rust/src/runtime/graph.rs
  rust/src/runtime/threading.rs
  rust/tests/test_graph_serde.rs
  tests/scripts/task_rust.sh
Labels: status: need update

#1858 [Relay] [Op] Squeeze
  include/tvm/relay/attrs/transform.h
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_op_level3.py
Labels: status: need update

#1882 [Relay][OP] MultiboxPrior
  include/tvm/relay/attrs/vision.h
  python/tvm/relay/op/vision/__init__.py
  python/tvm/relay/op/vision/multibox.py
  src/relay/op/vision/multibox_op.cc
  tests/python/relay/test_op_level4.py
Labels: status: need review

#1865 [RELAY][OP]Reduction operator framework, argmax, argmin
  docs/langref/relay_op.rst
  include/tvm/relay/type.h
  python/tvm/relay/__init__.py
  python/tvm/relay/op/__init__.py
  python/tvm/relay/op/reduce.py
  src/relay/op/tensor/reduce.cc
  src/relay/pass/type_solver.cc
  tests/python/relay/test_op_level4.py
Labels: status: need update

#1910 [YOLO]Add the probability to the image
  nnvm/python/nnvm/testing/yolo_detection.py
Labels: status: need review

#1921 Check iter_type in vectorize
  src/schedule/schedule_lang.cc
  tests/python/unittest/test_lang_schedule.py
Labels: status: need update

#1932 Fix x86 Conv tuning tutorial
  tutorials/autotvm/tune_nnvm_x86.py
Labels: status: need review

#1814 [Frontend][MXNet] ones zeros ones_like zeros_like ops support
  nnvm/python/nnvm/frontend/mxnet.py
  nnvm/tests/python/frontend/mxnet/test_forward.py
Labels: status: need update

#1927 [RELAY]Reduce ops sum/max/min/mean/prod
  docs/langref/relay_op.rst
  python/tvm/relay/op/reduce.py
  src/relay/op/tensor/reduce.cc
  tests/python/relay/test_op_level4.py
Labels: status: need update

#1962 [RELAY][TypeSystem] Add support for populating type args
  include/tvm/relay/op.h
  src/relay/ir/text_printer.cc
  src/relay/pass/type_infer.cc
  tests/python/relay/test_type_infer.py
Labels: status: need update

#1959 Fix int8x4 broadcast value codegen in cuda
  src/codegen/codegen_cuda.cc
  tests/python/unittest/test_codegen_cuda.py
Labels: status: need review

#1916 [Frontend][Darknet] L2 normalization support in darknet
  nnvm/python/nnvm/frontend/darknet.py
  nnvm/python/nnvm/testing/darknet.py
  nnvm/tests/python/frontend/darknet/test_forward.py
Labels: status: need review

#1876 [RELAY][OP] Split
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/transform.h
  nnvm/src/top/tensor/transform.cc
  python/tvm/relay/expr.py
  python/tvm/relay/op/transform.py
  src/lang/attr_functor.h
  src/lang/attrs.cc
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_op_level3.py
Labels: status: need update, status: review in progress

#1950 [RELAY]reshape_like
  docs/langref/relay_op.rst
  include/tvm/relay/type.h
  python/tvm/relay/op/transform.py
  src/relay/ir/type.cc
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_op_level3.py
Labels: status: need review

#1961 [TOPI][CUDA] batched int8 conv2d
  topi/python/topi/cuda/conv2d_int8.py
  topi/tests/python/test_topi_conv2d_int8.py
Labels: status: need update

#2015 [Relay] visit span
  include/tvm/relay/expr.h
Labels: status: need update

#1964 [intrin]support fmod for cuda
  python/tvm/intrin.py
  src/codegen/intrin_rule_cuda.cc
  src/codegen/intrin_rule_metal.cc
  src/codegen/intrin_rule_opencl.cc
  src/lang/ir_operator.cc
  tests/python/integration/test_ewise.py
Labels: status: need review, status: need update

#2009 [Relay] DQN Port
  python/tvm/relay/testing/__init__.py
  python/tvm/relay/testing/dqn.py
  tests/python/relay/test_ir_text_printer.py
Labels: status: need review

#2010 [Relay][WIP] DCGAN port
  python/tvm/relay/testing/__init__.py
  python/tvm/relay/testing/dcgan.py
  python/tvm/relay/testing/dqn.py
  python/tvm/relay/testing/layers.py
  tests/python/relay/test_ir_text_printer.py
Labels: status: need review

#1993 Refine porting x86 NCHWc conv to AutoTVM
  nnvm/python/nnvm/top/nn.py
  python/tvm/autotvm/task/dispatcher.py
  python/tvm/autotvm/task/space.py
  python/tvm/autotvm/task/task.py
  python/tvm/autotvm/task/topi_integration.py
  topi/python/topi/generic/nn.py
  topi/python/topi/hls/nn.py
  topi/python/topi/intel_graphics/conv2d.py
  topi/python/topi/nn/conv2d.py
  topi/python/topi/x86/conv2d.py
  topi/python/topi/x86/conv2d_avx_1x1.py
  topi/python/topi/x86/conv2d_avx_common.py
  topi/recipe/conv/test_conv_int8_intel.py
  topi/tests/python/test_topi_conv2d_NCHWc.py
  tutorials/autotvm/tune_nnvm_x86.py
Labels: status: need update, status: review in progress

#1999 [PASS] add a pass for the specific hardware accelarator when it is not binded
  include/tvm/ir.h
  include/tvm/ir_pass.h
  src/api/api_pass.cc
  src/pass/detect_device.cc
  src/pass/split_host_device.cc
  tests/python/unittest/test_pass_decorate_device_scope.py
Labels: status: need review

#1797 Conditional Loop Partitioning - Extending to remove if conditions
  src/pass/loop_partition.cc
  tests/python/unittest/test_pass_loop_partition.py
Labels: status: need review

#1974 [YOLO]yolo op added in frontend and removed from topi
  nnvm/python/nnvm/frontend/darknet.py
  nnvm/python/nnvm/top/vision.py
  nnvm/src/top/vision/yolo/yolo.cc
  topi/include/topi/vision/yolo/yolo.h
  topi/python/topi/testing/__init__.py
  topi/python/topi/testing/yolo_python.py
  topi/python/topi/vision/yolo/__init__.py
  topi/python/topi/vision/yolo/yolo.py
  topi/src/topi.cc
  topi/tests/python_cpp/test_topi_yolo.py
Labels: status: need review

#2039 Fix a bug in inject-virtual-thread
  src/pass/inject_virtual_thread.cc
  tests/python/unittest/test_pass_inject_vthread.py
Labels: status: accepted

#1954 [RELAY][RUNTIME] Add Relay interpreter and compiler for TVM runtime system.
  include/tvm/relay/base.h
  include/tvm/relay/build_module.h
  include/tvm/relay/expr.h
  include/tvm/relay/interpreter.h
  include/tvm/relay/pass.h
  python/tvm/relay/__init__.py
  python/tvm/relay/_interpreter.py
  python/tvm/relay/env.py
  python/tvm/relay/graph_runtime_codegen.py
  python/tvm/relay/interpreter.py
  python/tvm/relay/ir_pass.py
  python/tvm/relay/op/_tensor.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/op.py
  python/tvm/relay/testing/mlp.py
  src/relay/interpreter.cc
  src/relay/ir/base.cc
  src/relay/ir/environment.cc
  src/relay/ir/expr.cc
  src/relay/ir/expr_functor.cc
  src/relay/ir/hash.cc
  src/relay/pass/fuse_ops.cc
  src/relay/pass/lower_ops.cc
  src/relay/pass/type_infer.cc
  src/relay/pass/util.cc
  tests/python/relay/test_graph_runtime.py
  tests/python/relay/test_interpreter.py
  tests/python/relay/test_type_infer.py
  tests/scripts/task_python_integration.sh
Labels: status: need review

#1967 Better gemm support for cublas and cpu
  cmake/util/FindCUDA.cmake
  src/contrib/cblas/cblas.cc
  src/contrib/cblas/gemm_common.h
  src/contrib/cublas/cublas.cc
  src/contrib/cublas/cublas_utils.cc
  src/contrib/cublas/cublas_utils.h
Labels: status: need review, status: need update

#2033 [RELAY/PASS] Simplify inference.
  nnvm/tests/python/compiler/test_simplify_inference.py
  python/tvm/relay/expr.py
  python/tvm/relay/ir_pass.py
  python/tvm/relay/op/__init__.py
  src/relay/pass/pattern_util.h
  src/relay/pass/simplify_inference.cc
  tests/python/relay/test_pass_simplify_inference.py
Labels: status: need review

#1997 [RELAY] MobileNet Port
  python/tvm/relay/testing/__init__.py
  python/tvm/relay/testing/mobilenet.py
  tests/python/relay/test_ir_text_printer.py
Labels: status: need review, status: need update
