Repository apache/tvm, pull requests merged in 2019-02, with the labels that each got.

#2524 [Rust] Update rustc
  docker/install/ubuntu_install_rust.sh
  docker/install/ubuntu_install_sgx.sh
Labels: status: need review

#2507 [Relay][Frontend] Caffe2 Support
  docker/Dockerfile.ci_gpu
  docker/install/ubuntu_install_caffe2.sh
  python/tvm/relay/frontend/__init__.py
  python/tvm/relay/frontend/caffe2.py
  tests/python/frontend/caffe2/model_zoo/__init__.py
  tests/python/frontend/caffe2/model_zoo/squeezenet.py
  tests/python/frontend/caffe2/test_forward.py
  tests/python/frontend/caffe2/test_graph.py
  tests/scripts/task_python_frontend.sh
  tutorials/frontend/from_caffe2.py
Labels: status: need review

#2531 Remove duplicate as Checks and CHECK value
  src/codegen/codegen_c.cc
  src/codegen/stackvm/codegen_stackvm.cc
  src/common/socket.h
  src/op/hybrid_op.cc
  src/pass/ir_util.cc
  src/pass/loop_partition.cc
  src/pass/split_host_device.cc
  src/pass/storage_rewrite.cc
  src/pass/verify_gpu_code.cc
  src/relay/backend/interpreter.cc
  src/relay/ir/base.cc
  src/relay/op/type_relations.cc
  src/relay/pass/fold_scale_axis.cc
  src/relay/pass/gradient.cc
  src/relay/pass/to_anf.cc
  src/relay/pass/type_infer.cc
  src/relay/pass/type_solver.cc
  src/runtime/rpc/rpc_session.cc
  src/runtime/stackvm/stackvm.cc
  src/runtime/stackvm/stackvm.h
  src/schedule/graph.cc
  src/schedule/message_passing.cc
  src/schedule/schedule_dataflow_rewrite.cc
  src/schedule/schedule_lang.cc
  src/schedule/schedule_ops.cc
Labels: status: need update

#2503 [Relay][OP] Add reverse_reshape
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/transform.h
  python/tvm/relay/frontend/nnvm_common.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_op_level10.py
  tests/python/relay/test_op_level3.py
Labels: status: need review

#2495 [TVM][BUGFIX] Fix missing reduction init predicates
  src/op/compute_op.cc
  src/op/tensor_compute_op.cc
  tests/python/unittest/test_schedule_schedule_ops.py
Labels: status: need review

#2477 [Hybrid script] Backend support
  CMakeLists.txt
  cmake/modules/contrib/HybridDump.cmake
  docs/langref/hybrid_script.rst
  python/tvm/build_module.py
  python/tvm/hybrid/__init__.py
  python/tvm/hybrid/api.py
  python/tvm/hybrid/calls.py
  python/tvm/hybrid/module.py
  python/tvm/hybrid/parser.py
  python/tvm/hybrid/runtime.py
  python/tvm/hybrid/util.py
  python/tvm/hybrid/var_decl.py
  src/codegen/build_module.cc
  src/contrib/hybrid/codegen_hybrid.cc
  src/contrib/hybrid/codegen_hybrid.h
  src/op/hybrid_op.cc
  tests/python/unittest/test_hybrid_script.py
Labels: status: accepted

#2580 [TVM][Bugfix] fix storage_rewrite bug when input is big
  src/pass/storage_rewrite.cc
  tests/python/unittest/test_pass_storage_rewrite.py
Labels: status: need review

#2610 [Bugfix] get layout in to_relay
  nnvm/python/nnvm/to_relay.py
Labels: status: need review

#2608 [RELAY][DOCS] Port from_mxnet tutorial to relay
  tutorials/relay/from_mxnet.py
Labels: status: accepted

#2602 [RELAY][TOPI] `alter_op_layout` for x86
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  src/relay/op/nn/convolution.cc
  topi/python/topi/x86/conv2d.py
Labels: status: accepted

#2575 [Relay][Docs] Documentation for Algebraic Data Types
  docs/langref/index.rst
  docs/langref/relay_adt.rst
  docs/langref/relay_expr.rst
  docs/langref/relay_type.rst
Labels: status: need review, status: need update

#2601 Fix issue mutating if expressions
  python/tvm/relay/expr_functor.py
Labels: status: need update

#2589 [EXPR] Expression-template based pattern matching.
  src/arithmetic/pattern_match.h
  src/pass/inject_copy_intrin.cc
  tests/cpp/pattern_match_test.cc
Labels: status: need review

#2615 [TVM][LANG] Add eager simplification for operations with FloatImm
  include/tvm/ir_operator.h
  python/tvm/generic.py
  python/tvm/intrin.py
  src/api/api_ir.cc
  src/lang/ir_operator.cc
  tests/python/unittest/test_arith_simplify.py
Labels: status: accepted

#2622 [Relay]fix heterogenous annotation bug
  src/relay/pass/device_annotation.cc
  tests/python/relay/test_pass_annotation.py
Labels: status: need review

#2609 [RELAY][PASS] add a relay pass to count #macs of a model
  python/tvm/relay/ir_pass.py
  src/relay/pass/mac_count.cc
  tests/python/relay/test_pass_mac_count.py
Labels: status: accepted

#2627 Fix missing argument for NCHWc in Relay
  python/tvm/relay/op/nn/_nn.py
Labels: status: accepted

#2479 [Tutorial][Frontend] move from_keras tutorial to frontend
  tutorials/frontend/from_keras.py
Labels: status: need update

#2637 [Relay] fix anf for reference and pattern matching
  src/relay/pass/to_anf.cc
  tests/python/relay/test_to_anf.py
Labels: status: need test case

#2633 [RELAY/OP] Gradient of relay level1 ops
  python/tvm/relay/expr.py
  python/tvm/relay/op/__init__.py
  python/tvm/relay/op/_tensor.py
  python/tvm/relay/op/_tensor_grad.py
  python/tvm/relay/op/op.py
  tests/python/relay/test_op_grad_level1.py
  tests/python/relay/test_op_level1.py
Labels: status: need review

#2492 [Relay] GNF
  include/tvm/relay/pass.h
  python/tvm/relay/ir_pass.py
  src/relay/pass/to_a_normal_form.cc
  src/relay/pass/to_graph_normal_form.cc
  tests/python/relay/test_to_a_normal_form.py
  tests/python/relay/test_to_graph_normal_form.py
Labels: status: accepted

#2621 [Relay/TOPI][OP] Add arange op in Relay and TOPI
  docs/api/python/topi.rst
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/transform.h
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  tests/python/frontend/mxnet/test_forward.py
  tests/python/relay/test_op_level3.py
  topi/include/topi/transform.h
  topi/python/topi/transform.py
  topi/src/topi.cc
  topi/tests/python/test_topi_transform.py
Labels: status: accepted

#2643 Add CONCATENATION to tflite frontend, support Inception V3
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#2569 [Graph Runtime] Run_individual for benchmarking individual layers
  python/tvm/contrib/debugger/debug_runtime.py
  src/runtime/graph/debug/graph_runtime_debug.cc
  tests/python/unittest/test_runtime_graph_debug.py
Labels: status: need update

#2275 REGION op removed from topi and added in darkent frontend
  nnvm/python/nnvm/frontend/darknet.py
  nnvm/python/nnvm/top/vision.py
  nnvm/src/top/vision/yolo/region.cc
  nnvm/src/top/vision/yolo/region.h
  topi/include/topi/cuda/vision.h
  topi/include/topi/rocm/vision.h
  topi/include/topi/vision/yolo/region.h
  topi/python/topi/cuda/vision.py
  topi/python/topi/generic/vision.py
  topi/python/topi/rocm/__init__.py
  topi/python/topi/rocm/vision.py
  topi/python/topi/testing/__init__.py
  topi/python/topi/testing/region_python.py
  topi/python/topi/testing/shortcut_python.py
  topi/python/topi/vision/__init__.py
  topi/python/topi/vision/shortcut.py
  topi/python/topi/vision/yolo/__init__.py
  topi/python/topi/vision/yolo/region.py
  topi/src/topi.cc
  topi/tests/python/test_topi_region.py
  topi/tests/python/test_topi_shortcut.py
Labels: status: need update

#1941 [RELAY]Vision ops for yolo
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/vision.h
  python/tvm/relay/op/vision/__init__.py
  python/tvm/relay/op/vision/_yolo.py
  python/tvm/relay/op/vision/yolo.py
  src/relay/op/vision/yolo.cc
  tests/python/relay/test_op_level5.py
Labels: status: need review

#2620 [Relay] Port param dict save/load from NNVM
  python/tvm/api.py
  python/tvm/relay/__init__.py
  python/tvm/relay/param_dict.py
  src/relay/backend/interpreter.cc
  src/relay/backend/param_dict.cc
  src/relay/backend/param_dict.h
  tests/python/relay/test_param_dict.py
Labels: status: need update

#2654 Adopt pylint suggestion to use dict.get.
  tests/lint/pylintrc
Labels: status: need update

#2509 [Lang] Layout in TVM node system
  docs/api/python/topi.rst
  include/tvm/data_layout.h
  nnvm/src/top/nn/nn.cc
  python/tvm/api.py
  python/tvm/tensor.py
  src/api/api_lang.cc
  src/lang/data_layout.cc
  src/relay/op/debug.cc
  src/relay/op/image/resize.cc
  src/relay/op/layout.cc
  src/relay/op/layout.h
  src/relay/op/nn/convolution.cc
  src/relay/op/nn/nn.cc
  src/relay/op/nn/pad.cc
  src/relay/op/nn/pooling.cc
  src/relay/op/nn/upsampling.cc
  src/relay/op/tensor/transform.cc
  src/relay/pass/alter_op_layout.cc
  src/relay/pass/alter_op_layout.h
  src/relay/pass/combine_parallel_conv2d.cc
  src/relay/pass/fold_scale_axis.cc
  src/relay/pass/mac_count.cc
  src/relay/pass/pattern_util.h
  tests/python/unittest/test_lang_data_layout.py
  topi/include/topi/nn.h
  topi/include/topi/transform.h
  topi/python/topi/transform.py
  topi/src/topi.cc
  topi/tests/python/test_topi_transform.py
Labels: status: need update
