Repository apache/tvm, pull requests merged in 2019-03, with the labels that each got.

#2705 [Relay] fix checkwellform
  src/relay/pass/well_formed.cc
  tests/python/relay/test_ir_well_formed.py
Labels: status: accepted

#2709 [Frontend] [MXNet] MXNet converter for _minimum and _maximum
  nnvm/python/nnvm/frontend/mxnet.py
  nnvm/tests/python/frontend/mxnet/test_forward.py
Labels: status: accepted

#2587 Defined a common base class for TensorComputeOp and ComputeOp
  include/tvm/operation.h
  python/tvm/tensor.py
  src/op/compute_op.cc
  src/op/compute_op.h
  src/op/tensor_compute_op.cc
  tests/python/unittest/test_schedule_tensorize.py
Labels: status: need review

#2561 [Relay/TOPI][Op] Add batch_matmul in relay and TOPI
  docs/api/python/topi.rst
  docs/langref/relay_op.rst
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  src/relay/op/nn/nn.cc
  tests/python/relay/test_op_level1.py
  tests/python/relay/test_op_level10.py
  tests/python/relay/test_pass_quantize.py
  topi/include/topi/nn/batch_matmul.h
  topi/python/topi/cuda/__init__.py
  topi/python/topi/cuda/batch_matmul.py
  topi/python/topi/generic/nn.py
  topi/python/topi/nn/__init__.py
  topi/python/topi/nn/batch_matmul.py
  topi/python/topi/testing/__init__.py
  topi/python/topi/testing/batch_matmul.py
  topi/python/topi/util.py
  topi/python/topi/x86/batch_matmul.py
  topi/python/topi/x86/dense.py
  topi/python/topi/x86/nn.py
  topi/src/topi.cc
  topi/tests/python/test_topi_batch_matmul.py
Labels: status: need review, status: need update

#2668 [ARITH] Analyzer Infra, ConstIntBound, Modular
  include/tvm/arithmetic.h
  include/tvm/ir.h
  python/tvm/arith.py
  src/api/api_arith.cc
  src/arithmetic/analyzer.cc
  src/arithmetic/const_int_bound.cc
  src/arithmetic/int_op_overflow.h
  src/arithmetic/int_set_internal.h
  src/arithmetic/modular.cc
  src/arithmetic/modular_set.cc
  src/arithmetic/pattern_match.h
  src/codegen/codegen_common.h
  src/codegen/llvm/codegen_llvm.cc
  src/codegen/llvm/codegen_llvm.h
  src/codegen/spirv/codegen_spirv.cc
  src/codegen/spirv/codegen_spirv.h
  src/pass/storage_rewrite.cc
  tests/cpp/pattern_match_test.cc
  tests/cpp/unittest.mk
  tests/python/unittest/test_arith_const_int_bound.py
  tests/python/unittest/test_arith_modular.py
  tests/python/unittest/test_arith_modular_set.py
Labels: status: need review

#2639 [RELAY][PASS] Common subexpression elimination
  python/tvm/relay/ir_pass.py
  src/relay/pass/eliminate_common_subexpr.cc
  src/relay/pass/pattern_util.h
  tests/python/relay/test_pass_eliminate_common_subexpr.py
Labels: status: need review

#2453 [Tensorflow, NNVM, TOPI] Support for logical operators
  docs/api/python/topi.rst
  docs/nnvm_top.rst
  nnvm/python/nnvm/compiler/graph_attr.py
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/python/nnvm/top/tensor.py
  nnvm/src/compiler/compile_engine.cc
  nnvm/src/top/tensor/elemwise.cc
  nnvm/tests/python/frontend/tensorflow/test_forward.py
  topi/include/topi/broadcast.h
  topi/include/topi/elemwise.h
  topi/src/topi.cc
Labels: status: need update

#2704 [Relay][Frontend] Add a few mxnet ops in relay frontend
  python/tvm/relay/frontend/mxnet.py
  tests/python/frontend/mxnet/test_forward.py
Labels: status: need review

#2706 [Relay][Frontend] Add slice axis op in mxnet converter
  python/tvm/relay/frontend/mxnet.py
  tests/python/frontend/mxnet/test_forward.py
Labels: status: accepted

#2713 use LLVM linker
  python/tvm/contrib/cc.py
Labels: status: need update

#2729 [Relay][TOPI][OP] intel_graphics conv2d alterlayout support relay, added stack op
  docs/api/python/topi.rst
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/transform.h
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  topi/include/topi/transform.h
  topi/python/topi/intel_graphics/conv2d.py
  topi/python/topi/transform.py
  topi/src/topi.cc
  topi/tests/python/test_topi_transform.py
Labels: status: need review

#2748 Fix vmlal.s16 code generation for int8 x int8 -> int32
  src/pass/lower_intrin.cc
  tests/python/unittest/test_codegen_arm.py
Labels: status: need review

#2741 [RUNTIME][OPENCL] set type_key even when platform is not available
  src/runtime/opencl/opencl_device_api.cc
Labels: status: need review

#2742 Improvements to the conda build
  conda/cross-linux.cmake
  conda/nnvm/meta.yaml
  conda/topi/meta.yaml
  conda/tvm-libs/build.sh
  conda/tvm-libs/meta.yaml
  conda/tvm/meta.yaml
Labels: status: need review

#2752 fix typo in backend interpreter
  python/tvm/relay/backend/interpreter.py
  tests/python/relay/test_backend_interpreter.py
Labels: status: need test case

#2722 [ARITH] Analyzer RewriteSimplifier: add/sub/mul/div/mod
  include/tvm/arithmetic.h
  python/tvm/arith.py
  src/api/api_arith.cc
  src/arithmetic/analyzer.cc
  src/arithmetic/const_fold.h
  src/arithmetic/pattern_match.h
  src/arithmetic/rewrite_simplify.cc
  tests/cpp/pattern_match_test.cc
  tests/python/unittest/test_arith_rewrite_simplify.py
Labels: status: need review

#2720 [Relay/TOPI][Frontend] Add tile and repeat operators in Relay and TOPI
  docs/api/python/topi.rst
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/transform.h
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  topi/include/topi/transform.h
  topi/python/topi/transform.py
  topi/src/topi.cc
  topi/tests/python/test_topi_transform.py
Labels: status: accepted

#2586 [relay][frontend] TensorFlow saved model support
  nnvm/python/nnvm/frontend/util/__init__.py
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/frontend/tensorflow_parser.py
Labels: status: need review, status: need update

#2353 [Object Detection] Gluoncv SSD support on CPU
  include/tvm/relay/attrs/vision.h
  nnvm/include/nnvm/top/nn.h
  nnvm/python/nnvm/frontend/mxnet.py
  nnvm/python/nnvm/top/vision.py
  nnvm/src/top/vision/nms.cc
  nnvm/tests/python/compiler/test_top_level4.py
  nnvm/tests/python/frontend/mxnet/test_forward.py
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/op/transform.py
  python/tvm/relay/op/vision/__init__.py
  python/tvm/relay/op/vision/_vision.py
  python/tvm/relay/op/vision/nms.py
  src/relay/op/tensor/transform.cc
  src/relay/op/vision/multibox_op.cc
  src/relay/op/vision/nms.cc
  tests/python/frontend/mxnet/test_forward.py
  tests/python/relay/test_op_level10.py
  tests/python/relay/test_op_level5.py
  topi/include/topi/nn/l2_normalize.h
  topi/python/topi/cuda/nms.py
  topi/python/topi/cuda/ssd/multibox.py
  topi/python/topi/cuda/vision.py
  topi/python/topi/generic/vision.py
  topi/python/topi/testing/__init__.py
  topi/python/topi/testing/slice_axis_python.py
  topi/python/topi/vision/nms.py
  topi/python/topi/vision/ssd/multibox.py
  topi/tests/python/test_topi_vision.py
  tutorials/frontend/deploy_ssd_gluoncv.py
  tutorials/nnvm/deploy_ssd_mxnet.py
Labels: status: need update

#2789 [COMMUNITY] @wweic -> Reviewer
  CONTRIBUTORS.md
Labels: status: accepted

#2797 Ensure loop count is a constant before trying to unroll.
  src/pass/unroll_loop.cc
  tests/python/unittest/test_pass_unroll.py
Labels: status: accepted

#2800 [Relay][Frontend] Add reverse op to relay
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/transform.h
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_op_level3.py
Labels: status: accepted

#2775 [Operator] Sign
  docs/api/python/topi.rst
  docs/langref/relay_op.rst
  python/tvm/relay/op/_tensor.py
  python/tvm/relay/op/tensor.py
  src/relay/op/tensor/unary.cc
  tests/python/relay/test_op_level3.py
  topi/include/topi/elemwise.h
  topi/python/topi/math.py
  topi/src/topi.cc
  topi/tests/python/test_topi_math.py
Labels: status: need review

#2733 [Bugfix][caffe2] Fix caffe2 relay frontend
  python/tvm/relay/frontend/caffe2.py
  tests/python/frontend/caffe2/test_forward.py
Labels: status: need review, status: need update

#2768 [ARITH] RewriteSimplifier: min/max, logical, select
  src/arithmetic/rewrite_simplify.cc
  tests/python/unittest/test_arith_rewrite_simplify.py
Labels: status: need review

#2770 [GRAPH] Include default metadata description in graph.
  python/tvm/relay/backend/graph_runtime_codegen.py
  src/runtime/graph/graph_runtime.h
Labels: status: need review

#2771 [Relay] Add hd,tl,nth for list in Prelude
  python/tvm/relay/prelude.py
  tests/python/relay/test_adt.py
Labels: status: need review

#2777 [Relay] Adding _contrib_BilinearResize2D op from mxnet
  python/tvm/relay/frontend/mxnet.py
Labels: status: need review

#2821 [CODEGEN][OPENCL] Fix compile error about ternary expression.
  src/codegen/codegen_opencl.cc
  src/codegen/codegen_opencl.h
  tests/python/unittest/test_codegen_opencl.py
Labels: status: need review

#2757 [FRONTEND][TENSORFLOW] Enhance with left over patches from NNVM.
  nnvm/tests/python/frontend/tensorflow/test_forward.py
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#2852 Pin rust version used to compile tools
  docker/install/ubuntu_install_rust.sh
Labels: status: need review

#2806 [AlterLayout] NCHWc upsampling, fix depthwise conv
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  src/relay/op/nn/convolution.cc
  src/relay/op/nn/upsampling.cc
  tests/lint/pylintrc
  tests/python/relay/test_pass_alter_op_layout.py
  tests/scripts/task_python_topi.sh
  topi/include/topi/image/resize.h
  topi/python/topi/nn/depthwise_conv2d.py
  topi/python/topi/nn/upsampling.py
  topi/python/topi/x86/conv2d.py
  topi/python/topi/x86/depthwise_conv2d.py
  topi/tests/python/test_topi_depthwise_conv2d.py
Labels: status: need review

#2865 fix typos: 4x "disbale" to "disable"
  cmake/config.cmake
Labels: status: accepted

#2863 Limit maximum `func_name` length
  src/relay/backend/compile_engine.cc
Labels: status: accepted

#2605 [Relay][Text Format] Text Printer Refactor and Debug Printing
  include/tvm/relay/expr.h
  python/tvm/relay/_parser.py
  python/tvm/relay/base.py
  python/tvm/relay/ir_pass.py
  src/relay/ir/doc.cc
  src/relay/ir/doc.h
  src/relay/ir/pretty_printer.cc
  src/relay/ir/text_printer.cc
  tests/python/relay/test_ir_text_printer.py
  tests/python/relay/test_type_infer.py
Labels: status: WIP

#2878 Add missing sgx includes
  cmake/modules/SGX.cmake
Labels: status: need review

#2886 [Rust] Use version invariant rustfmt
  docker/install/ubuntu_install_rust.sh
  rust/.rustfmt.toml
Labels: status: need review

#2855 Add dense schedules to __init__ for cpu
  topi/include/topi/transform.h
  topi/python/topi/x86/__init__.py
Labels: status: need update

#2861 [Relay] Fix Relay ARM CPU depthwise spatial pack schedule alter op layout issue.
  python/tvm/relay/op/nn/_nn.py
  tutorials/autotvm/tune_relay_arm.py
Labels: status: need review

#2842 [Relay] Allow converting keras.layers.Sequential
  python/tvm/relay/frontend/common.py
  python/tvm/relay/frontend/keras.py
  tests/python/frontend/keras/test_forward.py
Labels: status: need review

#2828 Unified error handling in NNVM and Relay frontends
  nnvm/python/nnvm/frontend/caffe2.py
  nnvm/python/nnvm/frontend/common.py
  nnvm/python/nnvm/frontend/coreml.py
  nnvm/python/nnvm/frontend/darknet.py
  nnvm/python/nnvm/frontend/keras.py
  nnvm/python/nnvm/frontend/mxnet.py
  nnvm/python/nnvm/frontend/onnx.py
  nnvm/python/nnvm/frontend/tensorflow.py
  python/tvm/relay/frontend/caffe2.py
  python/tvm/relay/frontend/coreml.py
  python/tvm/relay/frontend/keras.py
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/frontend/onnx.py
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/frontend/tflite.py
Labels: status: need review

#2908 [Relay, TOPI] Deformable conv2d
  include/tvm/relay/attrs/nn.h
  python/tvm/autotvm/task/relay_integration.py
  python/tvm/autotvm/task/topi_integration.py
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  src/relay/op/nn/convolution.cc
  tests/python/relay/test_op_level5.py
  topi/python/topi/cuda/__init__.py
  topi/python/topi/cuda/deformable_conv2d.py
  topi/python/topi/generic/nn.py
  topi/python/topi/nn/__init__.py
  topi/python/topi/nn/deformable_conv2d.py
  topi/python/topi/testing/__init__.py
  topi/python/topi/testing/deformable_conv2d_nchw_python.py
  topi/tests/python/test_topi_conv2d_nchw.py
  topi/tests/python/test_topi_deformable_conv2d.py
Labels: status: need review

#2922 [Debug Graph Runtime] Export TVM DebugResult trace to Chrome Tracing format
  python/tvm/contrib/debugger/debug_result.py
  python/tvm/contrib/debugger/debug_runtime.py
  tests/python/unittest/test_runtime_graph_debug.py
Labels: status: need review

#2754 [Relay] add test for second order ad
  python/tvm/relay/op/_tensor_grad.py
  tests/python/relay/test_pass_gradient.py
Labels: status: accepted

#2927 [AUTOTVM] Refactor measure build func
  python/tvm/autotvm/measure/measure_methods.py
  python/tvm/contrib/cc.py
  python/tvm/contrib/tar.py
  python/tvm/contrib/xcode.py
Labels: status: need review

#2904 [ARITH] Fix intersect of modular set
  src/arithmetic/modular_set.cc
  tests/python/unittest/test_arith_modular_set.py
Labels: status: need review

#2860 Consistent result of DetectLinearEquation() when an empy vars is passed
  src/arithmetic/detect_linear_equation.cc
  src/pass/inject_copy_intrin.cc
  tests/python/unittest/test_arith_detect_linear_equation.py
Labels: status: need review

#2864 [FRONTEND][TENSORFLOW] bug fix for tensorflow official slim models.
  python/tvm/relay/frontend/tensorflow.py
Labels: status: need review

#2925 [WIP] [CodeGen] Fix fp16 -> fp32 codegen on X86-64
  src/codegen/llvm/codegen_llvm.cc
  src/codegen/llvm/codegen_x86_64.cc
  tests/python/unittest/test_codegen_x86.py
Labels: status: need review
