Repository apache/tvm, pull requests merged in 2019-07, with the labels that each got.

#3368 [ARITH] Migrate simplifier to new infra
  CMakeLists.txt
  include/tvm/arithmetic.h
  include/tvm/ir_pass.h
  src/arithmetic/analyzer.cc
  src/arithmetic/bound_deducer.cc
  src/arithmetic/const_fold.h
  src/arithmetic/rewrite_simplify.cc
  src/arithmetic/stmt_simplify.cc
  src/lang/buffer.cc
  src/op/scan_op.cc
  src/pass/loop_partition.cc
  src/pass/narrow_channel_access.cc
  src/pass/storage_rewrite.cc
  src/pass/vectorize_loop.cc
  src/schedule/message_passing.cc
  src/schedule/schedule_dataflow_rewrite.cc
  tests/cpp/ir_simplify_test.cc
  tests/python/unittest/test_arith_deduce_bound.py
  tests/python/unittest/test_pass_basic.py
Labels: status: need review

#3469 [ANALYSIS] Mac count deconv
  python/tvm/relay/op/nn/nn.py
  src/relay/pass/mac_count.cc
  tests/python/relay/test_pass_mac_count.py
Labels: status: accepted

#3389 [Codegen] Support broadcast op with symbolic shape
  include/tvm/buffer.h
  python/tvm/api.py
  src/api/api_lang.cc
  src/codegen/build_module.cc
  src/lang/buffer.cc
  src/pass/arg_binder.cc
  src/pass/inject_copy_intrin.cc
  src/pass/storage_flatten.cc
  tests/python/unittest/test_lang_buffer.py
  topi/include/topi/detail/extern.h
Labels: status: accepted

#3456 [Relay] Continuation Passing Style
  include/tvm/relay/analysis.h
  include/tvm/relay/transform.h
  python/tvm/relay/testing/__init__.py
  python/tvm/relay/transform.py
  src/relay/ir/adt.cc
  src/relay/ir/module.cc
  src/relay/ir/pretty_printer.cc
  src/relay/ir/type_functor.cc
  src/relay/pass/de_duplicate.cc
  src/relay/pass/dependency_graph.h
  src/relay/pass/let_list.h
  src/relay/pass/partial_eval.cc
  src/relay/pass/to_a_normal_form.cc
  src/relay/pass/to_cps.cc
  src/relay/pass/type_infer.cc
  tests/python/relay/test_pass_fuse_ops.py
  tests/python/relay/test_pass_gradient.py
  tests/python/relay/test_pass_to_a_normal_form.py
  tests/python/relay/test_pass_to_cps.py
Labels: status: need review

#3482 [Relay] Fix PE
  include/tvm/relay/module.h
  src/relay/ir/expr_functor.cc
  src/relay/ir/type_functor.cc
  src/relay/ir/type_functor.h
  src/relay/pass/let_list.h
  src/relay/pass/partial_eval.cc
  src/relay/pass/type_infer.cc
  src/relay/pass/util.cc
  tests/python/relay/test_pass_partial_eval.py
Labels: status: need test case

#3510 Passing dilation argument to account for API change.
  topi/recipe/conv/test_conv_int8_intel.py
Labels: status: need test case

#3470 [Relay][VM]Compiling pattern matching
  include/tvm/runtime/vm.h
  src/relay/backend/vm/compiler.cc
  src/relay/pass/pass_util.h
  src/runtime/vm/vm.cc
  tests/python/relay/test_vm.py
Labels: status: need review

#3156 [Relay][Testing] Relay-to-Python compilation
  include/tvm/relay/adt.h
  include/tvm/relay/module.h
  python/tvm/relay/backend/interpreter.py
  python/tvm/relay/expr_functor.py
  python/tvm/relay/module.py
  python/tvm/relay/testing/__init__.py
  python/tvm/relay/testing/nat.py
  python/tvm/relay/testing/py_converter.py
  src/relay/ir/module.cc
  tests/python/relay/test_adt.py
  tests/python/relay/test_backend_interpreter.py
  tests/python/relay/test_py_converter.py
Labels: status: need review

#3221 [Relay][RFC] Implement type checking for Any
  include/tvm/ir.h
  include/tvm/relay/attrs/transform.h
  include/tvm/relay/error.h
  include/tvm/relay/expr.h
  include/tvm/relay/op_attr_types.h
  include/tvm/relay/type.h
  include/tvm/runtime/ndarray.h
  python/tvm/_ffi/base.py
  python/tvm/api.py
  python/tvm/relay/__init__.py
  python/tvm/relay/expr.py
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/loops.py
  python/tvm/relay/op/transform.py
  python/tvm/relay/scope_builder.py
  python/tvm/relay/ty.py
  src/codegen/llvm/codegen_llvm.cc
  src/lang/buffer.cc
  src/lang/ir.cc
  src/lang/tensor.cc
  src/relay/backend/build_module.cc
  src/relay/backend/compile_engine.cc
  src/relay/ir/error.cc
  src/relay/ir/expr.cc
  src/relay/ir/pretty_printer.cc
  src/relay/ir/type.cc
  src/relay/op/tensor/transform.cc
  src/relay/op/type_relations.cc
  src/relay/pass/type_infer.cc
  src/relay/pass/type_solver.cc
  src/relay/pass/type_solver.h
  src/runtime/ndarray.cc
  tests/python/relay/test_any.py
  tests/python/relay/test_op_level3.py
Labels: status: need review

#3526 [ARITH][BOUND] Fix bound inference to avoid allocating too much
  include/tvm/operation.h
  src/op/compute_op.cc
  src/op/extern_op.cc
  src/op/hybrid_op.cc
  src/op/placeholder_op.cc
  src/op/scan_op.cc
  src/op/tensor_compute_op.cc
  src/op/tensorize.cc
  src/schedule/bound.cc
  tests/python/unittest/test_schedule_bound_inference.py
  tests/python/unittest/test_schedule_schedule_ops.py
Labels: status: need review

#3416 [Runtime] Enable set_input_zero_copy in GraphRuntime
  src/runtime/graph/graph_runtime.cc
  src/runtime/graph/graph_runtime.h
  src/runtime/ndarray.cc
  tests/cpp/relay_build_module_test.cc
Labels: status: need review, status: need test case

#3514 [FRONTEND][TENSORFLOW] Some bug fixes for tensorflow NCHW data_format
  nnvm/python/nnvm/frontend/tensorflow.py
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#3515 [docs] Add a tutorial for the pass manager
  docs/dev/relay_pass_infra.rst
Labels: status: need update

#3073 Fixing performance issue in PassUpDomain when fusing and splitting axes
  src/schedule/message_passing.cc
  tests/python/unittest/test_schedule_bound_inference.py
Labels: status: need review

#3546 Support additional architectures beyond x86_64 in ubuntu_install_java
  docker/install/ubuntu_install_java.sh
Labels: status: need update

#3420 [codegen/llvm] Emit DWARF debug information for LoweredFunc instances
  src/codegen/llvm/codegen_cpu.cc
  src/codegen/llvm/codegen_cpu.h
  src/codegen/llvm/codegen_llvm.cc
  src/codegen/llvm/codegen_llvm.h
  src/codegen/llvm/llvm_common.h
  src/codegen/llvm/llvm_module.cc
  tests/python/unittest/test_codegen_llvm.py
Labels: status: accepted

#3582 Add printer for Layout/BijectiveLayout
  python/tvm/tensor.py
  src/lang/data_layout.cc
Labels: status: need review

#3574 [RPC] Better handle tempdir if subprocess killed.
  python/tvm/contrib/util.py
  python/tvm/module.py
  python/tvm/rpc/server.py
Labels: status: accepted

#3094 [TOPI][RELAY] Add op Size
  docs/api/python/topi.rst
  docs/langref/relay_op.rst
  include/tvm/operation.h
  include/tvm/relay/attrs/transform.h
  python/tvm/api.py
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/op/contrib/_contrib.py
  python/tvm/relay/op/contrib/contrib.py
  src/relay/op/tensor/unary.cc
  tests/python/frontend/tensorflow/test_forward.py
  tests/python/relay/test_op_level10.py
  topi/include/topi/transform.h
  topi/python/topi/transform.py
  topi/src/topi.cc
  topi/tests/python/test_topi_transform.py
Labels: status: need update

#3520 Add support for Tflite operator SPLIT
  docker/install/ubuntu_install_python_package.sh
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#3577 [Runtime] [ThreadPool] Make SpscTaskQueue::Pop(..) spin_count configurable
  src/runtime/thread_pool.cc
  tests/cpp/threading_backend_test.cc
Labels: status: need update

#3516 Checking the correct dtypes for choosing the Intel int8 instructions.
  tests/python/relay/test_op_level2.py
  topi/python/topi/nn/conv2d.py
  topi/python/topi/x86/check_targets.py
  topi/python/topi/x86/conv2d.py
  topi/python/topi/x86/conv2d_avx_1x1.py
  topi/python/topi/x86/conv2d_avx_common.py
  topi/tests/python/test_topi_group_conv2d_NCHWc_int8.py
Labels: status: need review

#3566 [Relay] [TOPI] `{relay,topi}.nn.sparse_dense` for block-sparse matrix multiplication
  include/tvm/relay/attrs/nn.h
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  src/relay/op/nn/sparse.cc
  topi/python/topi/generic/nn.py
  topi/python/topi/nn/__init__.py
  topi/python/topi/nn/sparse.py
  topi/python/topi/x86/sparse.py
  topi/tests/python/test_topi_sparse.py
Labels: status: need review

#3601 [TOPI][Relay] max_pool2d & avg_pool2d gradient
  python/tvm/relay/op/_tensor_grad.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  python/tvm/relay/op/op_attrs.py
  src/relay/op/nn/pooling.cc
  topi/include/topi/detail/ravel_unravel.h
  topi/include/topi/nn/pooling.h
  topi/include/topi/reduction.h
  topi/include/topi/transform.h
  topi/python/topi/generic/nn.py
  topi/python/topi/nn/pooling.py
  topi/python/topi/testing/__init__.py
  topi/python/topi/testing/pool_grad_python.py
  topi/src/topi.cc
  topi/tests/python/test_topi_pooling.py
Labels: status: need review

#3553 Add Winograd matrices computation.
  topi/python/topi/arm_cpu/conv2d.py
  topi/python/topi/cuda/conv2d_winograd.py
  topi/python/topi/mali/conv2d.py
  topi/python/topi/nn/conv2d.py
  topi/python/topi/nn/winograd_util.py
  topi/tests/python/test_topi_conv2d_winograd.py
Labels: status: need review

#3623 [TOPI] Fix traverse function not inline zero-input op
  topi/include/topi/transform.h
  topi/python/topi/arm_cpu/bitserial_conv2d.py
  topi/python/topi/arm_cpu/bitserial_dense.py
  topi/python/topi/cuda/conv2d_hwcn.py
  topi/python/topi/cuda/dense.py
  topi/python/topi/cuda/depthwise_conv2d.py
  topi/python/topi/cuda/pooling.py
  topi/python/topi/hls/nn.py
  topi/python/topi/intel_graphics/conv2d.py
  topi/python/topi/opengl/conv2d_nchw.py
  topi/python/topi/opengl/dense.py
  topi/python/topi/opengl/pooling.py
  topi/python/topi/transform.py
  topi/python/topi/util.py
  topi/python/topi/x86/binary_dense.py
  topi/python/topi/x86/bitserial_conv2d.py
  topi/python/topi/x86/bitserial_dense.py
  topi/python/topi/x86/conv2d.py
  topi/python/topi/x86/conv2d_transpose.py
  topi/python/topi/x86/depthwise_conv2d.py
  topi/python/topi/x86/pooling.py
  topi/tests/python/test_topi_transform.py
Labels: status: need test case
