Repository apache/tvm, pull requests merged in 2019-06, with the labels that each got.

#3261 [relay][heterogeneous] annotate using visitor
  src/relay/pass/device_annotation.cc
  tests/python/relay/test_pass_annotation.py
Labels: status: need review

#3286 [Frontend][Onnx] Bump ONNX version
  docker/install/ubuntu_install_onnx.sh
Labels: status: need review

#3256 [Relay/TOPI][Op] Add TopK operator
  docs/api/python/topi.rst
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/algorithm.h
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/op/_algorithm.py
  python/tvm/relay/op/algorithm.py
  python/tvm/relay/op/nn/nn.py
  python/tvm/relay/op/transform.py
  src/codegen/build_module.cc
  src/contrib/sort/sort.cc
  src/relay/op/algorithm/argsort.cc
  src/relay/op/algorithm/topk.cc
  tests/python/frontend/mxnet/test_forward.py
  tests/python/frontend/tensorflow/test_forward.py
  tests/python/relay/test_op_level6.py
  topi/python/topi/cuda/__init__.py
  topi/python/topi/cuda/nms.py
  topi/python/topi/cuda/sort.py
  topi/python/topi/generic/sort.py
  topi/python/topi/sort.py
  topi/python/topi/transform.py
  topi/python/topi/vision/nms.py
  topi/tests/python/test_topi_sort.py
Labels: status: need review

#3282 [IR] Try to improve nms and get_valid_count
  topi/python/topi/cuda/nms.py
Labels: status: need review

#3287 [Relay][VM] Fix code generation for packed functions + tuples
  src/relay/backend/vm/compiler.cc
  tests/python/relay/test_vm.py
Labels: status: accepted

#3258 [VTA] [Hardware] Chisel implementation
  cmake/config.cmake
  cmake/modules/VTA.cmake
  vta/apps/tsim_example/README.md
  vta/apps/tsim_example/cmake/modules/hw.cmake
  vta/hardware/chisel/Makefile
  vta/hardware/chisel/src/main/resources/verilog/VTAHostDPI.v
  vta/hardware/chisel/src/main/scala/core/Compute.scala
  vta/hardware/chisel/src/main/scala/core/Configs.scala
  vta/hardware/chisel/src/main/scala/core/Core.scala
  vta/hardware/chisel/src/main/scala/core/Decode.scala
  vta/hardware/chisel/src/main/scala/core/Fetch.scala
  vta/hardware/chisel/src/main/scala/core/ISA.scala
  vta/hardware/chisel/src/main/scala/core/Load.scala
  vta/hardware/chisel/src/main/scala/core/LoadUop.scala
  vta/hardware/chisel/src/main/scala/core/Semaphore.scala
  vta/hardware/chisel/src/main/scala/core/Store.scala
  vta/hardware/chisel/src/main/scala/core/TensorAlu.scala
  vta/hardware/chisel/src/main/scala/core/TensorGemm.scala
  vta/hardware/chisel/src/main/scala/core/TensorLoad.scala
  vta/hardware/chisel/src/main/scala/core/TensorStore.scala
  vta/hardware/chisel/src/main/scala/core/TensorUtil.scala
  vta/hardware/chisel/src/main/scala/core/package.scala
  vta/hardware/chisel/src/main/scala/dpi/VTAHostDPI.scala
  vta/hardware/chisel/src/main/scala/dpi/VTAMemDPI.scala
  vta/hardware/chisel/src/main/scala/interface/axi/AXI.scala
  vta/hardware/chisel/src/main/scala/shell/Configs.scala
  vta/hardware/chisel/src/main/scala/shell/SimShell.scala
  vta/hardware/chisel/src/main/scala/shell/VCR.scala
  vta/hardware/chisel/src/main/scala/shell/VME.scala
  vta/hardware/chisel/src/main/scala/shell/VTAShell.scala
  vta/hardware/chisel/src/main/scala/shell/XilinxShell.scala
  vta/hardware/chisel/src/main/scala/test/Test.scala
  vta/hardware/chisel/src/main/scala/util/Config.scala
  vta/hardware/chisel/src/main/scala/util/GenericParameterizedBundle.scala
  vta/hardware/chisel/src/main/scala/vta/Configs.scala
  vta/hardware/dpi/tsim_device.cc
  vta/include/vta/driver.h
  vta/python/vta/environment.py
  vta/python/vta/testing/simulator.py
  vta/python/vta/testing/util.py
  vta/src/runtime.cc
  vta/src/tsim/tsim_driver.cc
  vta/tests/python/unittest/test_vta_insn.py
Labels: priority: high, status: need review

#3168 Add support for overloading comparison operations in relay (#2910)
  python/tvm/relay/expr.py
  tests/python/relay/test_cmp_op.py
Labels: status: need test case

#2993 [Relay][Frontend] Simplify parameter handling in Tensorflow frontend
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
  topi/python/topi/util.py
Labels: status: need review

#3264 Fix x86 depthwise conv2d alter_op_layout
  tests/python/relay/test_pass_alter_op_layout.py
  topi/python/topi/arm_cpu/depthwise_conv2d.py
  topi/python/topi/util.py
  topi/python/topi/x86/conv2d.py
  topi/python/topi/x86/depthwise_conv2d.py
  topi/tests/python/test_topi_util.py
Labels: status: need review, status: need test case

#3311 [Relay][heterogeneous] Fix tuple annotation
  src/relay/pass/device_annotation.cc
  tests/python/relay/test_pass_annotation.py
Labels: status: accepted

#3313 Add LOGISTIC operator to relay tflite frontend
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review, status: need update

#3335 Non_maximum_suppression and get_valid_counts add new parameters
  topi/python/topi/cuda/nms.py
Labels: status: need review

#3326 [Relay][Frontend] Fix MxNet RNN without providing state initialization as input
  python/tvm/relay/frontend/mxnet.py
  tests/python/frontend/mxnet/test_forward.py
Labels: status: need review

#3203 [Relay] Check match expressions for completeness
  include/tvm/relay/pass.h
  python/tvm/relay/ir_pass.py
  python/tvm/relay/prelude.py
  src/relay/pass/match_exhaustion.cc
  src/relay/pass/type_infer.cc
  tests/python/relay/test_pass_unmatched_cases.py
Labels: status: need review

#3357 [Relay] Add Elemwise operator Sub, Divide, Power, Max, Min to tflite …
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need update

#3272 [ARITH] Revamp IntSet
  include/tvm/arithmetic.h
  python/tvm/arith.py
  src/api/api_arith.cc
  src/arithmetic/analyzer.cc
  src/arithmetic/bound_deducer.cc
  src/arithmetic/canonical_simplify.cc
  src/arithmetic/compute_expr.h
  src/arithmetic/const_fold.h
  src/arithmetic/detect_linear_equation.cc
  src/arithmetic/int_op_overflow.h
  src/arithmetic/int_set.cc
  src/arithmetic/int_set.h
  src/arithmetic/int_set_internal.h
  src/lang/expr_operator.cc
  src/pass/loop_partition.cc
  tests/python/unittest/test_arith_deduce_bound.py
  tests/python/unittest/test_arith_intset.py
Labels: status: need review

#3306 [Relay][VM] Add AllocTensor instruction and better instruction printer
  CMakeLists.txt
  include/tvm/runtime/vm.h
  src/relay/backend/vm/compiler.cc
  src/runtime/vm/vm.cc
Labels: status: need review

#3033 [Relay] Partial Eval now Support Interprocedural optimization and has termination check.
  include/tvm/relay/pass.h
  include/tvm/relay/transform.h
  python/tvm/relay/ir_pass.py
  src/relay/ir/expr.cc
  src/relay/pass/dead_code.cc
  src/relay/pass/partial_eval.cc
  tests/python/relay/test_pass_partial_eval.py
Labels: status: need review, status: need update

#3353 [relay][frontend] Return module from frontend parsers
  python/tvm/relay/backend/interpreter.py
  python/tvm/relay/backend/vm.py
  python/tvm/relay/build_module.py
  python/tvm/relay/frontend/caffe2.py
  python/tvm/relay/frontend/coreml.py
  python/tvm/relay/frontend/darknet.py
  python/tvm/relay/frontend/keras.py
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/frontend/onnx.py
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/caffe2/test_forward.py
  tests/python/frontend/caffe2/test_graph.py
  tests/python/frontend/coreml/test_forward.py
  tests/python/frontend/darknet/test_forward.py
  tests/python/frontend/keras/test_forward.py
  tests/python/frontend/mxnet/test_forward.py
  tests/python/frontend/mxnet/test_graph.py
  tests/python/frontend/onnx/test_forward.py
  tests/python/frontend/tensorflow/test_control_flow.py
  tests/python/frontend/tensorflow/test_forward.py
  tests/python/frontend/tflite/test_forward.py
  tests/python/relay/test_vm.py
  tutorials/frontend/deploy_model_on_android.py
  tutorials/frontend/deploy_model_on_rasp.py
  tutorials/frontend/deploy_ssd_gluoncv.py
  tutorials/frontend/from_caffe2.py
  tutorials/frontend/from_coreml.py
  tutorials/frontend/from_darknet.py
  tutorials/frontend/from_keras.py
  tutorials/frontend/from_mxnet.py
  tutorials/frontend/from_onnx.py
  tutorials/frontend/from_tensorflow.py
  tutorials/frontend/from_tflite.py
Labels: status: need update

#3280 [Relay][Pass] CanonicalizeCast
  include/tvm/relay/transform.h
  python/tvm/relay/transform.py
  src/relay/backend/build_module.cc
  src/relay/pass/canonicalize_cast.cc
  tests/python/relay/test_pass_canonicalize_cast.py
Labels: status: need review

#3372 TFLite: Add fused_activation_function for ADD, SUB, MUL, DIV
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need update

#3406 Add EtaExpand to transform API
  python/tvm/relay/transform.py
  src/relay/pass/eta_expand.cc
  tests/python/relay/test_pass_eta_expand.py
Labels: status: accepted

#3233 [QUANTIZE] Memorizing the quantize node mapping
  python/tvm/relay/backend/_backend.py
  python/tvm/relay/quantize/_annotate.py
  python/tvm/relay/quantize/quantize.py
  src/relay/pass/quantize.cc
  src/relay/pass/quantize.h
  tests/python/relay/test_pass_quantize.py
Labels: status: need review

#3397 [Frontend][MxNet] Support bidirectional RNN layer
  python/tvm/relay/frontend/mxnet.py
  tests/python/frontend/mxnet/test_forward.py
Labels: status: need review

#3384 [Runtime] Allow for parameter sharing in GraphRuntime
  python/tvm/contrib/graph_runtime.py
  src/runtime/graph/graph_runtime.cc
  src/runtime/graph/graph_runtime.h
  tests/python/unittest/test_runtime_graph.py
Labels: status: need review, status: need update

#3424 Add mod supoort in relay.build
  python/tvm/relay/build_module.py
  tests/python/frontend/caffe2/test_forward.py
  tests/python/frontend/coreml/test_forward.py
  tests/python/frontend/darknet/test_forward.py
  tests/python/frontend/keras/test_forward.py
  tests/python/frontend/mxnet/test_forward.py
  tests/python/frontend/onnx/test_forward.py
  tests/python/frontend/tensorflow/test_forward.py
  tests/python/frontend/tflite/test_forward.py
  tutorials/frontend/deploy_model_on_android.py
  tutorials/frontend/deploy_ssd_gluoncv.py
  tutorials/frontend/from_caffe2.py
  tutorials/frontend/from_coreml.py
  tutorials/frontend/from_darknet.py
  tutorials/frontend/from_tensorflow.py
  tutorials/frontend/from_tflite.py
Labels: status: accepted

#3419 [Relay][Parser] simplify build script, remove python 2 support
  cmake/modules/ANTLR.cmake
  python/tvm/relay/_parser.py
  python/tvm/relay/grammar/py2/.gitattributes
  python/tvm/relay/grammar/py2/Relay.interp
  python/tvm/relay/grammar/py2/Relay.tokens
  python/tvm/relay/grammar/py2/RelayLexer.interp
  python/tvm/relay/grammar/py2/RelayLexer.py
  python/tvm/relay/grammar/py2/RelayLexer.tokens
  python/tvm/relay/grammar/py2/RelayParser.py
  python/tvm/relay/grammar/py2/RelayVisitor.py
  python/tvm/relay/grammar/py2/__init__.py
  python/tvm/relay/grammar/py3/.gitattributes
  python/tvm/relay/grammar/py3/RelayLexer.py
  python/tvm/relay/grammar/py3/RelayParser.py
  python/tvm/relay/grammar/py3/RelayVisitor.py
  python/tvm/relay/grammar/py3/__init__.py
Labels: status: accepted

#3437 [RELAY] [OP] [MXNet Frontend] Add sequence_mask
  docs/api/python/topi.rst
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/transform.h
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  tests/python/frontend/mxnet/test_forward.py
  tests/python/relay/test_op_level10.py
  topi/include/topi/transform.h
  topi/python/topi/testing/__init__.py
  topi/python/topi/testing/sequence_mask_python.py
  topi/python/topi/transform.py
  topi/src/topi.cc
  topi/tests/python/test_topi_transform.py
Labels: status: accepted

#3382 Nested rfactor fix, update predicates as well as source.
  src/schedule/schedule_dataflow_rewrite.cc
Labels: status: need review

#3135 [VTA][Relay] Relay Compilation + AutoTVM compatible operator libraries for VTA
  apps/pynq_rpc/start_rpc_server_to_tracker.sh
  docs/conf.py
  nnvm/python/nnvm/top/nn.py
  python/tvm/autotvm/graph_tuner/utils/traverse_graph.py
  python/tvm/autotvm/measure/measure_methods.py
  python/tvm/autotvm/task/nnvm_integration.py
  python/tvm/autotvm/task/relay_integration.py
  python/tvm/autotvm/task/topi_integration.py
  python/tvm/autotvm/tophub.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/quantize/_annotate.py
  python/tvm/relay/quantize/quantize.py
  python/tvm/target.py
  src/codegen/build_module.cc
  src/pass/make_api.cc
  src/relay/backend/compile_engine.cc
  src/relay/op/annotation/annotation.cc
  src/relay/pass/pattern_util.h
  src/relay/pass/quantize.cc
  src/relay/pass/quantize.h
  src/schedule/schedule_lang.cc
  topi/python/topi/__init__.py
  topi/python/topi/util.py
  vta/include/vta/driver.h
  vta/python/vta/build_module.py
  vta/python/vta/environment.py
  vta/python/vta/exec/rpc_server.py
  vta/python/vta/pkg_config.py
  vta/python/vta/testing/simulator.py
  vta/python/vta/testing/util.py
  vta/python/vta/top/__init__.py
  vta/python/vta/top/bitpack.py
  vta/python/vta/top/graphpack.py
  vta/python/vta/top/nnvm_bitpack.py
  vta/python/vta/top/nnvm_graphpack.py
  vta/python/vta/top/nnvm_op.py
  vta/python/vta/top/op.py
  vta/python/vta/top/vta_conv2d.py
  vta/python/vta/top/vta_dense.py
  vta/scripts/tune_conv2d.py
  vta/scripts/tune_dense.py
  vta/scripts/tune_resnet.py
  vta/scripts/tune_resnet_nnvm.py
  vta/src/runtime.cc
  vta/src/sim/sim_driver.cc
  vta/tests/python/integration/test_benchmark_topi_conv2d.py
  vta/tests/python/integration/test_benchmark_topi_dense.py
  vta/tutorials/README.txt
  vta/tutorials/autotvm/README.txt
  vta/tutorials/autotvm/tune_relay_vta.py
  vta/tutorials/frontend/README.txt
  vta/tutorials/frontend/deploy_resnet_on_vta.py
  vta/tutorials/optimize/README.txt
  vta/tutorials/optimize/convolution_opt.py
  vta/tutorials/optimize/matrix_multiply_opt.py
  vta/tutorials/resnet.py
Labels: priority: high, status: need review

#3435 Update tflite wheel version to 1.13.1
  docker/install/ubuntu_install_tflite.sh
  tutorials/frontend/from_tflite.py
Labels: status: need update
