Repository apache/tvm, pull requests merged in 2019-08, with the labels that each got.

#3538 [Relay][Quantization] KL-divergence-based per-layer calibration
  python/tvm/relay/quantize/__init__.py
  python/tvm/relay/quantize/_annotate.py
  python/tvm/relay/quantize/kl_divergence.py
  python/tvm/relay/quantize/quantize.py
  src/relay/pass/quantize/calibrate.cc
  src/relay/pass/quantize/quantize.cc
  src/relay/pass/quantize/quantize.h
Labels: priority: high, status: need review

#3687 [TOPI] Memoize winograd matrix
  python/tvm/contrib/pickle_memoize.py
  topi/python/topi/nn/winograd_util.py
Labels: status: need update

#3442 Fix gather_nd in Relay
  src/relay/op/tensor/transform.cc
  tests/python/frontend/mxnet/test_forward.py
  tests/python/relay/test_op_level3.py
Labels: status: need test case

#3680 [TOPI] Update softmax compute and CPU schedule
  topi/include/topi/cuda/softmax.h
  topi/include/topi/nn/softmax.h
  topi/python/topi/cuda/softmax.py
  topi/python/topi/hls/nn.py
  topi/python/topi/nn/softmax.py
  topi/python/topi/opengl/softmax.py
  topi/python/topi/x86/nn.py
Labels: status: need review

#3640 Quit and clean when TVM is interrupted
  python/tvm/__init__.py
Labels: status: need update

#3712 [Bugfix] Fix the issue that function pass modifies original module
  python/tvm/relay/backend/interpreter.py
  src/relay/pass/pass_manager.cc
  tests/python/relay/test_pass_fuse_ops.py
Labels: status: need review

#3710 [relay][frontend] clean up tf frontend
  python/tvm/relay/frontend/common.py
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/frontend/tensorflow.py
Labels: status: need review

#3672 [Relay] Legalize pass
  include/tvm/relay/op_attr_types.h
  include/tvm/relay/transform.h
  python/tvm/relay/op/__init__.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/op.py
  python/tvm/relay/transform.py
  src/relay/backend/build_module.cc
  src/relay/pass/legalize.cc
  tests/python/relay/test_pass_legalize.py
Labels: status: api design review

#3701 [Frontend][MXNet] Fix mxnet converter for hybridblock and add div_sqrt_dim
  python/tvm/relay/frontend/mxnet.py
  tests/python/frontend/mxnet/test_forward.py
  topi/python/topi/cuda/batch_matmul.py
Labels: status: need review

#3700 [Relay/TOPI][Op] Add variance and layer norm op
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/nn.h
  include/tvm/relay/attrs/reduce.h
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/op/_reduce.py
  python/tvm/relay/op/nn/nn.py
  python/tvm/relay/op/reduce.py
  python/tvm/relay/testing/dcgan.py
  python/tvm/relay/testing/inception_v3.py
  src/relay/op/nn/nn.cc
  src/relay/op/tensor/reduce.cc
  src/relay/pass/pattern_util.h
  src/relay/pass/simplify_inference.cc
  tests/python/frontend/mxnet/test_forward.py
  tests/python/relay/test_op_level4.py
Labels: status: need review

#3531 [QNN] Requantize operator
  docs/langref/relay_op.rst
  include/tvm/relay/qnn/attrs.h
  python/tvm/relay/__init__.py
  python/tvm/relay/qnn/__init__.py
  python/tvm/relay/qnn/op/__init__.py
  python/tvm/relay/qnn/op/_make.py
  python/tvm/relay/qnn/op/qnn.py
  src/relay/pass/pattern_util.h
  src/relay/qnn/op/requantize.cc
  src/relay/qnn/util.h
  tests/python/relay/test_qnn_requantize.py
Labels: status: need review

#3723 [Bugfix] tvm.scan follow by tvm.compute segfault
  src/op/scan_op.cc
  tests/python/integration/test_scan.py
Labels: status: need review

#3408 Don't replace reduction init axis with new axis if bound to a thread.
  src/op/op_util.cc
  tests/python/unittest/test_codegen_cuda.py
  tests/python/unittest/test_pass_loop_partition.py
Labels: status: need test case, status: need update

#3718 [Relay] SpaceToDepth and MirrorPad Operators
  include/tvm/relay/attrs/nn.h
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  python/tvm/relay/op/op_attrs.py
  src/relay/op/nn/pad.cc
  tests/python/frontend/tensorflow/test_forward.py
  topi/python/topi/nn/__init__.py
  topi/python/topi/nn/pad.py
Labels: status: need review

#3758 [ARITH] Simplify casts of constants 0 and 1
  src/arithmetic/rewrite_simplify.cc
  src/arithmetic/rewrite_simplify.h
  src/lang/expr_operator.cc
  tests/python/unittest/test_arith_rewrite_simplify.py
Labels: status: need update

#3754 [Relay][Legalize][ARM_CPU] Handling NHWC layout for arm_cpu.
  python/tvm/relay/op/nn/_nn.py
  tests/python/relay/test_pass_legalize.py
  topi/python/topi/arm_cpu/conv2d.py
  topi/python/topi/nn/conv2d.py
Labels: status: need update

#3705 [Relay][Frontend][TFLite] transpose implementation for tflite.py
  CONTRIBUTORS.md
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: accepted

#3780 [dep] Add psutil by default
  python/setup.py
Labels: status: need review

#3788 [TOPI] Resize rework
  include/tvm/relay/attrs/image.h
  include/tvm/relay/attrs/nn.h
  nnvm/tests/python/compiler/test_top_level2.py
  nnvm/tests/python/frontend/onnx/test_forward.py
  python/tvm/relay/frontend/coreml.py
  python/tvm/relay/frontend/keras.py
  python/tvm/relay/frontend/onnx.py
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/frontend/tflite.py
  python/tvm/relay/op/image/_image.py
  python/tvm/relay/op/image/image.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  src/relay/op/image/resize.cc
  src/relay/op/nn/upsampling.cc
  tests/python/frontend/keras/test_forward.py
  tests/python/frontend/tensorflow/test_forward.py
  tests/python/relay/test_op_level2.py
  tests/python/relay/test_op_level5.py
  topi/include/topi/image/resize.h
  topi/python/topi/image/resize.py
  topi/python/topi/nn/upsampling.py
  topi/python/topi/testing/bilinear_resize_python.py
  topi/tests/python/test_topi_resize.py
  topi/tests/python/test_topi_upsampling.py
Labels: status: review in progress

#3668 [Relay][Keras] Dot
  python/tvm/relay/frontend/keras.py
  tests/python/frontend/keras/test_forward.py
Labels: status: need update

#3676 [TensorFlow] Fix limitation that depth_mult can only be 1 for DepthwiseConv2dNative
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/op/nn/_nn.py
  src/relay/op/nn/convolution.cc
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review
