Repository apache/tvm, pull requests merged in 2019-12, with the labels that each got.

#4395 [Relay][Frontend][TFlite] Add test for qnn_mul operator
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#4346 [Runtime] Make ADTObject POD container type
  include/tvm/runtime/container.h
  include/tvm/runtime/memory.h
  include/tvm/runtime/vm.h
  src/runtime/vm/object.cc
  src/runtime/vm/vm.cc
  tests/cpp/container_test.cc
Labels: status: need test case, status: need update

#4366 [DOCS] add benchmark log format doc
  docs/dev/benchmark.rst
  docs/dev/index.rst
Labels: status: need review

#4303 [TOPI][Relay][OP] Add a strided_set operation.
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_op_level4.py
  topi/python/topi/testing/__init__.py
  topi/python/topi/testing/strided_slice_python.py
  topi/python/topi/transform.py
  topi/python/topi/util.py
  topi/tests/python/test_topi_transform.py
Labels: status: need review

#4418 [RUNTIME] Add cudnn conv3d
  python/tvm/contrib/cudnn.py
  src/runtime/contrib/cudnn/conv_forward.cc
  src/runtime/contrib/cudnn/cudnn_utils.h
  tests/python/contrib/test_cudnn.py
  topi/python/topi/cuda/conv2d.py
  topi/python/topi/testing/__init__.py
  topi/python/topi/testing/conv3d_ncdhw_python.py
Labels: status: need review

#4400 implement conv3d op
  include/tvm/relay/attrs/nn.h
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  src/relay/op/nn/convolution.cc
  src/relay/op/nn/convolution.h
  tests/python/relay/test_op_level2.py
  topi/python/topi/cuda/__init__.py
  topi/python/topi/cuda/conv3d.py
  topi/python/topi/cuda/conv3d_direct.py
  topi/python/topi/generic/nn.py
  topi/python/topi/nn/__init__.py
  topi/python/topi/nn/conv3d.py
  topi/python/topi/nn/util.py
  topi/tests/python/test_topi_conv3d_ncdhw.py
Labels: status: need review

#4453 lldb pretty printers for relay
  apps/lldb/dot.lldbinit.in
  apps/lldb/tvm.py
Labels: status: need review, status: need update

#4439 [CONTRIB] TFLite Runtime
  CMakeLists.txt
  cmake/config.cmake
  cmake/modules/contrib/TFLite.cmake
  python/tvm/contrib/tflite_runtime.py
  src/runtime/contrib/tflite/tflite_runtime.cc
  src/runtime/contrib/tflite/tflite_runtime.h
  tests/python/contrib/test_tflite_runtime.py
Labels: status: need review

#4478 [TOPI] implement pool3d op
  include/tvm/relay/attrs/nn.h
  src/relay/op/nn/pooling.cc
  topi/include/topi/nn/pooling.h
  topi/python/topi/nn/pooling.py
  topi/src/topi.cc
  topi/tests/python/test_topi_pooling.py
Labels: status: need review

#4397 Use the best tuner possible
  tutorials/autotvm/tune_simple_template.py
Labels: status: need update

#4482 [Relay] External codegen
  CMakeLists.txt
  cmake/config.cmake
  cmake/modules/contrib/CODEGENC.cmake
  cmake/modules/contrib/DNNL.cmake
  include/tvm/build_module.h
  include/tvm/relay/expr.h
  python/tvm/module.py
  src/codegen/build_module.cc
  src/codegen/codegen.cc
  src/relay/backend/build_module.cc
  src/relay/backend/compile_engine.cc
  src/relay/backend/compile_engine.h
  src/relay/backend/contrib/codegen_c/codegen.cc
  src/relay/backend/contrib/codegen_c/codegen_c.h
  src/relay/backend/contrib/dnnl/codegen.cc
  src/relay/backend/graph_runtime_codegen.cc
  src/relay/backend/vm/lambda_lift.cc
  src/relay/ir/expr.cc
  src/relay/pass/fuse_ops.cc
  src/relay/pass/pass_manager.cc
  src/runtime/contrib/dnnl/dnnl.cc
  src/runtime/contrib/dnnl/dnnl_kernel.h
  src/runtime/library_module.cc
  tests/python/relay/test_external_codegen.py
Labels: status: need review

#4544 [relay][codegen] VM external codegen
  src/relay/backend/vm/compiler.cc
  src/runtime/vm/vm.cc
  tests/python/relay/test_external_codegen.py
Labels: status: need review

#4545 [VTA] improved virtual memory mapping
  vta/src/vmem/virtual_memory.cc
Labels: status: need review, status: need update

#4532 [RUNTIME] Support standardize runtime module
  python/tvm/_ffi/function.py
  python/tvm/module.py
  src/codegen/codegen.cc
  src/runtime/library_module.cc
  src/runtime/module.cc
  tests/python/unittest/test_runtime_module_export.py
Labels: status: need review, status: need update

#4573 [ONNX] Remove unnecessary cast of constants to int32
  python/tvm/relay/frontend/onnx.py
  tests/python/frontend/onnx/test_forward.py
Labels: status: need review

#4578 [RUNTIME] Remove Extension VTable in favor of Unified Object system.
  apps/extension/Makefile
  apps/extension/python/tvm_ext/__init__.py
  apps/extension/src/tvm_ext.cc
  include/tvm/runtime/c_runtime_api.h
  include/tvm/runtime/packed_func.h
  include/tvm/runtime/registry.h
  python/tvm/_ffi/ndarray.py
  python/tvm/ndarray.py
  src/runtime/registry.cc
  tests/cpp/packed_func_test.cc
Labels: status: need RFC

#4584 [TOPI] add 3D upsampling Op.
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/nn.h
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  python/tvm/relay/op/op_attrs.py
  src/relay/op/nn/upsampling.cc
  tests/python/relay/test_op_level2.py
  topi/python/topi/image/resize.py
  topi/python/topi/nn/upsampling.py
  topi/python/topi/testing/__init__.py
  topi/python/topi/testing/trilinear_resize3d_python.py
  topi/python/topi/testing/upsampling_python.py
  topi/tests/python/test_topi_resize.py
  topi/tests/python/test_topi_upsampling.py
Labels: status: need review

#4484 [FRONTEND][TF] conv2d_transpose 'SAME' support kernel more than 1x1
  python/tvm/relay/frontend/tensorflow.py
  src/relay/op/nn/convolution.cc
  tests/python/frontend/tensorflow/test_forward.py
  topi/python/topi/cuda/conv2d_transpose_nchw.py
  topi/python/topi/nn/util.py
Labels: status: need update

#4550 [Perf] Add CublasLt extern support for better Igemm performance
  python/tvm/contrib/cublaslt.py
  src/runtime/contrib/cublas/cublas.cc
  src/runtime/contrib/cublas/cublas_utils.h
  tests/python/contrib/test_cublas.py
Labels: status: need review
