Repository apache/tvm, pull requests merged in 2019-11, with the labels that each got.

#4233 [Relay][Prelude] Add more dtypes to tensor_t
  python/tvm/relay/prelude.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#4238 [Relay][Frontend][Tensorflow] Fix GatherV2, Add StopGradient
  python/tvm/relay/frontend/tensorflow.py
Labels: status: accepted

#4221 [Contrib] Fix error message at callback_get_section_size()
  python/tvm/contrib/binutil.py
Labels: status: need review

#4242 [AutoTVM] Add batch_matmul to tunable operations
  python/tvm/autotvm/task/relay_integration.py
  python/tvm/autotvm/task/topi_integration.py
  topi/python/topi/x86/batch_matmul.py
Labels: status: need review, status: need update

#4278 Fix the problem that android_rpc compilation failed
  apps/android_rpc/app/src/main/jni/tvm_runtime.h
Labels: status: accepted

#4268 [Codegen][cuda-fp16] fallback to fp32 simulation when cuda arch < sm53
  src/codegen/codegen_cuda.cc
  src/codegen/literal/cuda_half_t.h
Labels: status: need review, status: need update

#4281 [RUTNIME] Support C++ RPC
  apps/cpp_rpc/Makefile
  apps/cpp_rpc/README.md
  apps/cpp_rpc/main.cc
  apps/cpp_rpc/rpc_env.cc
  apps/cpp_rpc/rpc_env.h
  apps/cpp_rpc/rpc_server.cc
  apps/cpp_rpc/rpc_server.h
  apps/cpp_rpc/rpc_tracker_client.h
  src/common/socket.h
  src/common/util.h
  src/runtime/rpc/rpc_session.h
  src/runtime/rpc/rpc_socket_impl.h
Labels: status: need review

#4249 [TOPI][AlterOpLayout][ARM] Enabling NHWC to NCHW layout transformation.
  tests/python/relay/test_pass_alter_op_layout.py
  tests/python/relay/test_pass_legalize.py
  topi/python/topi/arm_cpu/conv2d.py
Labels: status: need review

#4083 [tutorial] Relay pass infra tutorial
  include/tvm/relay/transform.h
  python/tvm/relay/transform.py
  src/relay/pass/print_ir.cc
  tutorials/dev/relay_pass_infra.py
Labels: status: need update

#4289 [RUNTIME][REFACTOR] Use object protocol to support runtime::Module
  apps/android_deploy/app/src/main/jni/tvm_runtime.h
  apps/android_rpc/app/src/main/jni/tvm_runtime.h
  apps/bundle_deploy/runtime.cc
  apps/howto_deploy/tvm_runtime_pack.cc
  apps/ios_rpc/tvmrpc/TVMRuntime.mm
  golang/src/tvm_runtime_pack.cc
  include/tvm/runtime/module.h
  include/tvm/runtime/object.h
  include/tvm/runtime/packed_func.h
  include/tvm/runtime/vm.h
  python/tvm/relay/backend/vm.py
  src/codegen/llvm/llvm_module.cc
  src/codegen/source_module.cc
  src/relay/backend/build_module.cc
  src/relay/backend/graph_runtime_codegen.cc
  src/relay/backend/vm/compiler.cc
  src/relay/backend/vm/compiler.h
  src/relay/backend/vm/profiler/compiler.cc
  src/runtime/c_runtime_api.cc
  src/runtime/cuda/cuda_module.cc
  src/runtime/cuda/cuda_module.h
  src/runtime/dso_module.cc
  src/runtime/graph/debug/graph_runtime_debug.cc
  src/runtime/graph/graph_runtime.cc
  src/runtime/graph/graph_runtime.h
  src/runtime/metal/metal_module.mm
  src/runtime/micro/micro_device_api.cc
  src/runtime/micro/micro_module.cc
  src/runtime/micro/micro_session.cc
  src/runtime/micro/micro_session.h
  src/runtime/micro/tcl_socket.h
  src/runtime/module.cc
  src/runtime/module_util.cc
  src/runtime/module_util.h
  src/runtime/object.cc
  src/runtime/object_internal.h
  src/runtime/opencl/aocl/aocl_common.h
  src/runtime/opencl/aocl/aocl_device_api.cc
  src/runtime/opencl/aocl/aocl_module.h
  src/runtime/opencl/opencl_common.h
  src/runtime/opencl/opencl_module.cc
  src/runtime/opencl/opencl_module.h
  src/runtime/opengl/opengl_module.cc
  src/runtime/opengl/opengl_module.h
  src/runtime/rocm/rocm_module.cc
  src/runtime/rpc/rpc_module.cc
  src/runtime/rpc/rpc_session.cc
  src/runtime/rpc/rpc_session.h
  src/runtime/stackvm/stackvm.cc
  src/runtime/stackvm/stackvm_module.cc
  src/runtime/system_lib_module.cc
  src/runtime/vm/executable.cc
  src/runtime/vm/profiler/vm.cc
  src/runtime/vm/profiler/vm.h
  src/runtime/vm/vm.cc
  src/runtime/vulkan/vulkan.cc
  vta/src/dpi/module.cc
  web/web_runtime.cc
Labels: status: need review

#4104 Fix the TF tutorial to run against TF2.0 and TF1.x
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/testing/tf.py
  tutorials/frontend/from_tensorflow.py
Labels: status: need review

#4297 [TOPI][OP] Support Faster-RCNN Proposal OP on CPU
  tests/python/relay/test_op_level5.py
  topi/python/topi/vision/rcnn/proposal.py
  topi/tests/python/test_topi_vision.py
Labels: status: need review

#4333 Deprecate NNVM warning msg
  nnvm/python/nnvm/__init__.py
Labels: status: need review

#4275 imp module is deprecated
  python/tvm/hybrid/module.py
  topi/python/topi/cpp/__init__.py
  topi/python/topi/cpp/cuda.py
  topi/python/topi/cpp/generic.py
  topi/python/topi/cpp/image.py
  topi/python/topi/cpp/impl.py
  topi/python/topi/cpp/nn.py
  topi/python/topi/cpp/rocm.py
  topi/python/topi/cpp/vision/__init__.py
  topi/python/topi/cpp/vision/yolo.py
  topi/python/topi/cpp/x86.py
Labels: status: need update

#4293 [VTA] Bug fix for padded load with large inputs
  vta/hardware/chisel/src/main/scala/core/TensorLoad.scala
  vta/tests/python/unittest/test_vta_insn.py
Labels: status: need review

#4134 [TOPI] fix inconsistent tag name
  tests/python/relay/test_op_level2.py
  topi/python/topi/arm_cpu/depthwise_conv2d.py
Labels: status: need test case

#4292 Retain qnn input kernel scales
  include/tvm/relay/qnn/attrs.h
  python/tvm/relay/frontend/tflite.py
  python/tvm/relay/qnn/op/legalizations.py
  python/tvm/relay/qnn/op/qnn.py
  src/relay/qnn/op/convolution.cc
  src/relay/qnn/op/dense.cc
  tests/python/relay/test_op_qnn_conv2d.py
  tests/python/relay/test_op_qnn_dense.py
  tests/python/relay/test_pass_qnn_legalize.py
Labels: status: need review, status: need update

#4300 [Relay][Frontend][Tensorflow]Add conv2d_transpose
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#4357 [Relay tests] Temporary Attr Update for Order-Independent Testing
  include/tvm/relay/op.h
  python/tvm/relay/op/op.py
  python/tvm/relay/testing/__init__.py
  python/tvm/relay/testing/temp_op_attr.py
  src/relay/ir/op.cc
  tests/python/relay/test_ir_op.py
  tests/python/relay/test_op_qnn_conv2d.py
  tests/python/relay/test_op_qnn_dense.py
  tests/python/relay/test_pass_alter_op_layout.py
  tests/python/relay/test_pass_legalize.py
  tests/python/relay/test_pass_qnn_legalize.py
Labels: status: need test case, status: need update

#4158 [PERF] Parallelize reduction for CPU
  topi/python/topi/x86/__init__.py
  topi/python/topi/x86/reduction.py
Labels: status: accepted

#4295 [Relay][Quantize] Integrate data-aware calibration into quantization
  python/tvm/relay/quantize/__init__.py
  python/tvm/relay/quantize/_annotate.py
  python/tvm/relay/quantize/_calibrate.py
  python/tvm/relay/quantize/kl_divergence.py
  python/tvm/relay/quantize/quantize.py
  src/relay/pass/quantize/calibrate.cc
  src/relay/pass/quantize/quantize.cc
  src/relay/pass/quantize/quantize.h
Labels: status: need review

#4344 [ThreadPool] Solve thread transitions issue
  src/runtime/thread_pool.cc
  src/runtime/threading_backend.cc
Labels: status: need review

#4372 [Relay][Frontend][TF] Fix slice when begin or size is not Const
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need update

#4385 [Golang][Doc] improve the samples and doc
  golang/README.md
  golang/sample/Makefile
  golang/sample/complex.go
  golang/sample/gen_mobilenet_lib.py
Labels: status: need review

#4339 Added tflite frontend support for quantized mean
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#4280 [TVM][RUNTIME] A minimum example to generate external library wrappers for DSOModule
  CMakeLists.txt
  cmake/config.cmake
  include/tvm/runtime/module.h
  python/tvm/module.py
  src/codegen/source_module.cc
  src/runtime/contrib/example_ext_runtime/example_ext_runtime.cc
  src/runtime/dso_module.cc
  src/runtime/graph/graph_runtime.cc
  tests/python/relay/test_external_runtime.py
Labels: status: need update

#4399 [Relay][Legalize] Legalize conv2d_transpose for NHWC
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/op_attrs.py
  tests/python/relay/test_op_level2.py
  topi/python/topi/nn/conv2d_transpose.py
  topi/python/topi/testing/__init__.py
  topi/python/topi/testing/conv2d_transpose_python.py
Labels: status: need review

#4404 [AutoTVM] select model with the most tuned schedules
  python/tvm/autotvm/tophub.py
Labels: status: need update

#4384 [ARM CPU] Fix infer shape error of depthwise
  python/tvm/relay/op/nn/_nn.py
  tests/python/relay/test_op_level2.py
Labels: status: need review

#4392 [VTA] Enable streamlined GEMM execution
  vta/hardware/chisel/src/main/scala/core/TensorGemm.scala
Labels: status: need review
