Repository apache/tvm, pull requests merged in 2019-10, with the labels that each got.

#3994 [TOPI]Add op argwhere
  include/tvm/relay/attrs/transform.h
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_any.py
  topi/python/topi/__init__.py
  topi/python/topi/argwhere.py
  topi/python/topi/generic/__init__.py
  topi/python/topi/generic/search.py
Labels: status: need review

#3734 Fix extent one for the post_stmt in loop partition
  src/pass/loop_partition.cc
  tests/python/unittest/test_pass_bound_checkers.py
  topi/tests/python/test_topi_math.py
Labels: status: need review

#4004 [Relay][Op] Add instance norm op
  include/tvm/relay/attrs/nn.h
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/frontend/onnx.py
  python/tvm/relay/op/nn/nn.py
  src/relay/op/nn/nn.cc
  src/relay/pass/simplify_inference.cc
  tests/python/frontend/mxnet/test_forward.py
  tests/python/frontend/onnx/test_forward.py
Labels: status: need review

#4015 [Relay][TopHub] Add switch to disable TopHub download
  python/tvm/autotvm/tophub.py
Labels: status: need update

#4070 Fix wrong n_trial number in autotvm tutorials' progress bar if n_trial is larger then config space.
  nnvm/tutorials/tune_nnvm_arm.py
  nnvm/tutorials/tune_nnvm_cuda.py
  nnvm/tutorials/tune_nnvm_mobile_gpu.py
  tutorials/autotvm/tune_relay_arm.py
  tutorials/autotvm/tune_relay_cuda.py
  tutorials/autotvm/tune_relay_mobile_gpu.py
  vta/tutorials/autotvm/tune_relay_vta.py
Labels: status: need review

#4074 [Fix] Fix the logic of the number of nodes checking in op fusion
  src/relay/pass/fuse_ops.cc
  tests/python/relay/test_pass_fuse_ops.py
Labels: status: need test case

#4082 [VTA][TSIM] Serial GEMM Application Added
  vta/apps/gemm/CMakeLists.txt
  vta/apps/gemm/Makefile
  vta/apps/gemm/README.md
  vta/apps/gemm/hardware/chisel/Makefile
  vta/apps/gemm/hardware/chisel/build.sbt
  vta/apps/gemm/hardware/chisel/project/build.properties
  vta/apps/gemm/hardware/chisel/project/plugins.sbt
  vta/apps/gemm/hardware/chisel/src/main/scala/accel/Accel.scala
  vta/apps/gemm/hardware/chisel/src/main/scala/accel/Compute.scala
  vta/apps/gemm/hardware/chisel/src/main/scala/accel/RegFile.scala
  vta/apps/gemm/hardware/chisel/src/test/scala/dut/TestAccel.scala
  vta/apps/gemm/python/__init__.py
  vta/apps/gemm/python/tsim.py
  vta/apps/gemm/src/driver.cc
  vta/apps/gemm/tests/python/chisel_accel.py
Labels: status: need review

#4039 [TOPI] FIFO buffer op, to accelerate sequence modeling with dilated convolutions
  include/tvm/relay/attrs/nn.h
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  python/tvm/relay/op/op_attrs.py
  src/relay/op/nn/nn.cc
  topi/python/topi/nn/__init__.py
  topi/python/topi/nn/fifo_buffer.py
  topi/tests/python/test_fifo_buffer.py
Labels: status: need review

#4059 [Relay][AlterOp] NHWC to NCHWc support for Pool, concatenate, sum.
  python/tvm/relay/frontend/tflite.py
  src/relay/op/nn/pad.cc
  src/relay/op/nn/pooling.cc
  src/relay/op/tensor/reduce.cc
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_pass_alter_op_layout.py
Labels: status: need review, status: need update

#4056 [codegen] Add multiple operands and function support when using fp16 compilation
  src/codegen/codegen_cuda.cc
  tests/python/relay/test_op_level1.py
  topi/tests/python/test_topi_transform.py
Labels: status: need review

#4096 Add parser support for CAST tflite operator
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#4038 [Relay][Topi] Disable conv NHWC pack int8.
  tests/python/relay/test_backend_compile_engine.py
  topi/python/topi/x86/conv2d.py
Labels: status: need review

#4115 [RFC][RUNTIME] Introduce new object protocol.
  Makefile
  include/tvm/node/node.h
  include/tvm/runtime/memory.h
  include/tvm/runtime/object.h
  include/tvm/runtime/packed_func.h
  include/tvm/runtime/vm.h
  python/tvm/_ffi/vmobj.py
  src/api/dsl_api.cc
  src/lang/reflection.cc
  src/relay/backend/vm/compiler.cc
  src/relay/backend/vm/deserializer.cc
  src/relay/backend/vm/serializer.cc
  src/relay/ir/pretty_printer.cc
  src/runtime/object.cc
  src/runtime/vm/object.cc
  src/runtime/vm/profiler/vm.cc
  src/runtime/vm/profiler/vm.h
  src/runtime/vm/vm.cc
  tests/cpp/object_protocol_test.cc
  tests/python/relay/test_vm.py
Labels: status: need review

#4125 Fix infer type of kernel in dense.
  src/relay/op/nn/nn.h
  tests/python/relay/test_op_level1.py
Labels: status: need test case

#3865 Add lift_if_then_else pass
  include/tvm/ir_pass.h
  src/api/api_pass.cc
  src/pass/hoist_if_then_else.cc
  tests/python/unittest/test_pass_hoist_if.py
Labels: status: need review

#4089 [Runtime] Enable option to use OpenMP thread pool
  CMakeLists.txt
  cmake/config.cmake
  cmake/modules/OpenMP.cmake
  src/runtime/thread_pool.cc
Labels: status: need update

#4141 Add support for quantized multiply to Relay
  python/tvm/relay/qnn/op/qnn.py
  src/relay/qnn/op/mul.cc
  tests/python/relay/test_qnn_mul.py
Labels: status: need review

#4157 [Relay][Pass] Count MAC for BatchMatMul
  src/relay/pass/mac_count.cc
Labels: status: need update

#4147 [rpc] use callback func to do send & recv
  jvm/core/src/main/java/ml/dmlc/tvm/rpc/ConnectProxyServerProcessor.java
  jvm/core/src/main/java/ml/dmlc/tvm/rpc/ConnectTrackerServerProcessor.java
  jvm/core/src/main/java/ml/dmlc/tvm/rpc/NativeServerLoop.java
  jvm/core/src/main/java/ml/dmlc/tvm/rpc/RPCSession.java
  jvm/core/src/main/java/ml/dmlc/tvm/rpc/Server.java
  jvm/core/src/main/java/ml/dmlc/tvm/rpc/SocketChannel.java
  jvm/core/src/main/java/ml/dmlc/tvm/rpc/SocketFileDescriptorGetter.java
  jvm/core/src/main/java/ml/dmlc/tvm/rpc/StandaloneServerProcessor.java
  jvm/core/src/test/java/ml/dmlc/tvm/contrib/GraphRuntimeTest.java
  jvm/pom.xml
  python/tvm/rpc/tracker.py
  src/common/socket.h
  src/runtime/rpc/rpc_event_impl.cc
  src/runtime/rpc/rpc_session.cc
  src/runtime/rpc/rpc_session.h
  src/runtime/rpc/rpc_socket_impl.cc
Labels: status: need update

#4154 [DOCS] Add TensorFlow frontend docs
  docs/frontend/tensorflow.md
  docs/frontend/tensorflow.rst
  docs/index.rst
Labels: status: need review

#4186 Split adaptive_pool2d_avg into sum and div
  topi/include/topi/nn/pooling.h
  topi/python/topi/x86/pooling.py
Labels: status: need review

#4136 TensorCore Support using Intrinsic
  include/tvm/ir.h
  include/tvm/ir_pass.h
  python/tvm/build_module.py
  src/api/api_pass.cc
  src/codegen/build_module.cc
  src/codegen/codegen_cuda.cc
  src/codegen/codegen_cuda.h
  src/pass/infer_fragment.cc
  src/pass/storage_access.cc
  src/pass/storage_sync.cc
  src/runtime/thread_storage_scope.h
  tests/python/unittest/test_schedule_tensor_core.py
  topi/python/topi/testing/conv2d_nhwc_python.py
  tutorials/optimize/opt_conv_tensorcore.py
  vta/python/vta/build_module.py
Labels: status: need review, status: need update

#4075 [Relay] crossentropy_with_logits and its gradient
  python/tvm/relay/op/_reduce.py
  python/tvm/relay/op/_tensor_grad.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  src/relay/op/nn/nn.cc
  tests/python/relay/test_op_grad_level10.py
Labels: status: need review

#4160 [Relay][Quantize] Use fixed point mulplications
  python/tvm/relay/quantize/quantize.py
  src/relay/pass/quantize/quantize.cc
  src/relay/pass/quantize/quantize.h
  src/relay/pass/quantize/realize.cc
  src/relay/qnn/op/requantize.cc
  src/relay/qnn/util.cc
  src/relay/qnn/util.h
Labels: status: need review, status: need update

#4138 Optimizing autotvm task extraction speed
  python/tvm/autotvm/task/relay_integration.py
  python/tvm/relay/__init__.py
  python/tvm/relay/backend/graph_runtime_codegen.py
  python/tvm/relay/build_module.py
  src/relay/backend/build_module.cc
Labels: status: need review
