Repository apache/tvm, pull requests merged in 2019-01, with the labels that each got.

#2200 [RUNTIME] Add min_repeat_ms to time_evaluator
  python/tvm/autotvm/measure/measure.py
  python/tvm/autotvm/measure/measure_methods.py
  python/tvm/module.py
  src/runtime/rpc/rpc_module.cc
  src/runtime/rpc/rpc_session.cc
  src/runtime/rpc/rpc_session.h
  tests/python/unittest/test_autotvm_measure.py
  tests/python/unittest/test_runtime_measure.py
Labels: status: need review

#2232 [Relay][Docs] Relay Language Reference
  docs/langref/index.rst
  docs/langref/relay_expr.rst
  docs/langref/relay_type.rst
Labels: status: need review, status: need update

#2369 [nnpack] Preallocate workspace buffer
  src/contrib/nnpack/convolution.cc
Labels: status: need review

#2336 [Relay][Frontend] Keras Support
  python/tvm/relay/frontend/__init__.py
  python/tvm/relay/frontend/common.py
  python/tvm/relay/frontend/keras.py
  tests/python/frontend/keras/test_forward.py
  tests/scripts/task_python_frontend.sh
Labels: status: need review

#2386 Added LLVM TargetIRAnalysis pass
  src/codegen/llvm/codegen_llvm.cc
  src/codegen/llvm/llvm_common.h
Labels: status: need review

#1973 [RUNTIME][TRACE] Support trace primitive.
  include/tvm/ir.h
  python/tvm/intrin.py
  src/codegen/llvm/codegen_cpu.cc
  src/codegen/llvm/codegen_cpu.h
  src/pass/lower_tvm_builtin.cc
  tests/python/unittest/test_runtime_packed_func.py
Labels: status: need update

#2394 [PASS][TENSOR] Use correct select semantics
  docs/api/python/intrin.rst
  docs/api/python/tvm.rst
  include/tvm/ir_operator.h
  python/tvm/api.py
  python/tvm/expr.py
  python/tvm/intrin.py
  src/arithmetic/int_set.cc
  src/lang/ir_operator.cc
  src/pass/inject_copy_intrin.cc
  tests/python/integration/test_reduce.py
  tests/python/unittest/test_codegen_llvm.py
  tests/python/unittest/test_pass_inject_copy_intrin.py
  tests/python/unittest/test_pass_loop_partition.py
  tests/python/unittest/test_pass_rewrite_unsafe_select.py
  tests/python/unittest/test_schedule_schedule_ops.py
  topi/include/topi/image/resize.h
  topi/include/topi/nn.h
  topi/include/topi/nn/dilate.h
  topi/include/topi/reduction.h
  topi/include/topi/transform.h
  topi/python/topi/cuda/conv2d_transpose_nchw.py
  topi/python/topi/cuda/nms.py
  topi/python/topi/cuda/ssd/multibox.py
  topi/python/topi/mali/conv2d.py
  topi/python/topi/nn/dilate.py
  topi/python/topi/nn/elemwise.py
  topi/python/topi/nn/pad.py
  topi/python/topi/nn/util.py
  topi/python/topi/util.py
  topi/python/topi/vision/nms.py
  topi/python/topi/vision/rcnn/roi_align.py
  topi/python/topi/vision/ssd/multibox.py
  topi/tests/python/test_topi_conv2d_nchw.py
  tutorials/language/tuple_inputs.py
  tutorials/optimize/opt_conv_cuda.py
Labels: status: need review

#2284 [TVM] Reduction simplification improvements
  src/arithmetic/canonical.cc
  tests/python/unittest/test_pass_simplify.py
Labels: status: accepted

#2361 [relay][pass] Annotation for heterogeneous compilation
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/annotation.h
  include/tvm/relay/attrs/device_copy.h
  include/tvm/relay/attrs/transform.h
  include/tvm/relay/pass.h
  python/tvm/__init__.py
  python/tvm/relay/__init__.py
  python/tvm/relay/annotation.py
  python/tvm/relay/backend/_backend.py
  python/tvm/relay/backend/graph_runtime_codegen.py
  python/tvm/relay/build_module.py
  python/tvm/relay/ir_pass.py
  python/tvm/relay/op/__init__.py
  python/tvm/relay/op/annotation/__init__.py
  python/tvm/relay/op/annotation/_make.py
  python/tvm/relay/op/annotation/annotation.py
  python/tvm/relay/op/tensor.py
  src/relay/backend/compile_engine.cc
  src/relay/backend/graph_plan_memory.cc
  src/relay/op/annotation/annotation.cc
  src/relay/op/device_copy.cc
  src/relay/pass/device_annotation.cc
  tests/python/relay/test_backend_graph_runtime.py
  tests/python/relay/test_pass_annotation.py
Labels: status: need review

#2414 [FRONTEND][TEST] Remove duplicated frontend tests
  nnvm/python/nnvm/to_relay.py
  tests/python/frontend/nnvm_to_relay/test_forward.py
  tests/python/relay/frontend/mxnet/model_zoo/__init__.py
  tests/python/relay/frontend/mxnet/model_zoo/dcgan.py
  tests/python/relay/frontend/mxnet/model_zoo/dqn.py
  tests/python/relay/frontend/mxnet/model_zoo/inception_v3.py
  tests/python/relay/frontend/mxnet/model_zoo/mlp.py
  tests/python/relay/frontend/mxnet/model_zoo/resnet.py
  tests/python/relay/frontend/mxnet/model_zoo/squeezenet.py
  tests/python/relay/frontend/mxnet/model_zoo/vgg.py
  tests/python/relay/frontend/mxnet/test_forward.py
  tests/python/relay/frontend/mxnet/test_graph.py
  tests/python/relay/frontend/test_keras.py
  tests/scripts/task_python_frontend.sh
Labels: status: need review

#2285 [tensorflow frontend] Support for Crop
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/tests/python/frontend/tensorflow/test_forward.py
Labels: status: need update

#2321 [Relay] First order reverse mode Automatic Differentiation
  include/tvm/relay/op_attr_types.h
  include/tvm/relay/pass.h
  python/tvm/relay/backend/interpreter.py
  python/tvm/relay/ir_pass.py
  python/tvm/relay/op/_tensor.py
  python/tvm/relay/op/op.py
  python/tvm/relay/op/tensor.py
  src/relay/op/tensor/binary.cc
  src/relay/pass/fuse_ops.cc
  src/relay/pass/gradient.cc
  src/relay/pass/pattern_util.h
  tests/python/relay/test_ad.py
Labels: status: need review

#2412 [RELAY] Filter PlaceholderOp from schedule.
  src/relay/backend/compile_engine.cc
  tests/python/relay/test_backend_compile_engine.py
Labels: status: need update

#2352 [RELAY] Support recursive call syntax
  include/tvm/relay/module.h
  python/tvm/relay/_parser.py
  src/relay/ir/module.cc
  src/relay/pass/type_infer.cc
  tests/python/relay/test_ir_parser.py
Labels: status: accepted, status: need review

#2189 [Relay] Expand type unification and other utilities
  include/tvm/relay/pass.h
  python/tvm/relay/ir_pass.py
  src/relay/pass/type_infer.cc
  src/relay/pass/type_solver.cc
  src/relay/pass/type_solver.h
  src/relay/pass/util.cc
  tests/cpp/relay_pass_type_infer_test.cc
  tests/python/relay/test_pass_free_vars.py
  tests/python/relay/test_pass_vars.py
  tests/python/relay/test_type_infer.py
  tests/python/relay/test_type_solver.py
Labels: status: need review, status: need update

#2456 [relay][compilation] refactoring: move fallback out of the build interface
  python/tvm/relay/build_module.py
  tests/python/relay/test_pass_annotation.py
Labels: status: need review

#2462 [RPC] Add the IPV6 support for server side auto tuning
  python/tvm/exec/rpc_server.py
  python/tvm/rpc/base.py
  python/tvm/rpc/proxy.py
  python/tvm/rpc/server.py
  python/tvm/rpc/tracker.py
  src/common/socket.h
  src/runtime/rpc/rpc_socket_impl.cc
Labels: status: accepted

#2365 [TFLite] Support TFLite FP32 Relay frontend.
  python/tvm/relay/frontend/__init__.py
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
  tests/scripts/task_python_frontend.sh
Labels: status: need review

#2472 [RELAY] Fix ops in packed layout
  src/relay/op/nn/pooling.cc
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_pass_alter_op_layout.py
Labels: status: need update

#2478 [AUTOTVM] typo
  python/tvm/autotvm/task/topi_integration.py
Labels: status: accepted

#2484 fix for IPv4 vs IPv6 addr len (#2475)
  src/common/socket.h
Labels: status: need review

#2251 [Relay] A Normal Form Canonicalization
  include/tvm/relay/pass.h
  python/tvm/relay/ir_pass.py
  src/relay/pass/let_list.h
  src/relay/pass/to_anf.cc
  tests/python/relay/test_pass_dead_code_elimination.py
  tests/python/relay/test_to_anf.py
Labels: status: need update

#2508 [Doc] TFLite frontend tutorial
  tutorials/frontend/from_tflite.py
Labels: status: accepted

#2520 [BugFix] Copy intermediate result in debug runtime
  python/tvm/contrib/debugger/debug_runtime.py
Labels: status: accepted

#2116 [OPT] Low-bit Quantization
  include/tvm/relay/attrs/transform.h
  include/tvm/relay/op.h
  python/tvm/relay/__init__.py
  python/tvm/relay/build_module.py
  python/tvm/relay/quantize/__init__.py
  python/tvm/relay/quantize/_annotate.py
  python/tvm/relay/quantize/_quantize.py
  python/tvm/relay/quantize/quantize.py
  src/relay/ir/expr_functor.cc
  src/relay/op/tensor/transform.cc
  src/relay/op/tensor/unary.cc
  src/relay/pass/pattern_util.h
  src/relay/pass/quantize.cc
  src/relay/pass/quantize.h
  tests/python/relay/test_pass_gradient.py
  tests/python/relay/test_pass_quantize.py
Labels: status: need review, status: need update
