Repository apache/tvm, pull requests merged in 2019-09, with the labels that each got.

#3756 [WIP][µTVM] Add OpenOCD Low-Level Device (RISC-V Support)
  python/tvm/contrib/binutil.py
  python/tvm/micro/base.py
  src/runtime/micro/low_level_device.h
  src/runtime/micro/micro_common.cc
  src/runtime/micro/micro_session.cc
  src/runtime/micro/micro_session.h
  src/runtime/micro/openocd_low_level_device.cc
  src/runtime/micro/tcl_socket.cc
  src/runtime/micro/tcl_socket.h
  tests/python/unittest/test_codegen_c_host.py
  tests/python/unittest/test_codegen_c_host_fadd.py
  tests/python/unittest/test_runtime_micro.py
Labels: status: need review, status: need update

#3489 [Runtime] Allow parameter sharing between modules
  include/tvm/runtime/ndarray.h
  src/runtime/graph/graph_runtime.cc
  src/runtime/graph/graph_runtime.h
  src/runtime/ndarray.cc
  tests/cpp/build_module_test.cc
Labels: status: need RFC, status: need review

#3778 [Relay][Frontend][darknet] Solve tvm parsing darknet resnext failure bug
  .gitignore
  python/tvm/relay/frontend/darknet.py
  tests/python/frontend/darknet/test_forward.py
Labels: status: need review

#3736 [QNN] Add operator
  include/tvm/relay/qnn/attrs.h
  python/tvm/relay/qnn/op/qnn.py
  src/relay/qnn/op/add.cc
  src/relay/qnn/op/op_common.h
  tests/python/relay/test_qnn_add.py
Labels: status: need review, status: need update

#3871 [Relay] Fix operator fusion for multiple output
  src/relay/ir/pretty_printer.cc
  src/relay/pass/fuse_ops.cc
  tests/python/relay/test_pass_fuse_ops.py
Labels: status: need review

#3870 Fix int32 range overflow by using int64
  python/tvm/autotvm/task/space.py
Labels: status: need review

#3596 [Relay] add Tuple pattern
  include/tvm/relay/adt.h
  include/tvm/relay/pattern_functor.h
  python/tvm/relay/__init__.py
  python/tvm/relay/adt.py
  python/tvm/relay/prelude.py
  python/tvm/relay/testing/py_converter.py
  src/relay/backend/interpreter.cc
  src/relay/backend/vm/compiler.cc
  src/relay/ir/adt.cc
  src/relay/ir/alpha_equal.cc
  src/relay/ir/hash.cc
  src/relay/ir/pattern_functor.cc
  src/relay/pass/match_exhaustion.cc
  src/relay/pass/partial_eval.cc
  src/relay/pass/type_infer.cc
  tests/python/relay/test_pass_alpha_equal.py
  tests/python/relay/test_pass_partial_eval.py
  tests/python/relay/test_pass_unmatched_cases.py
Labels: status: need update

#3888 [PYTHON/FFI] Search PATH for DLLs
  python/tvm/_ffi/libinfo.py
Labels: status: need review

#3842 [schedule] Improve ceil_divide in tile/split
  src/schedule/message_passing.cc
  tests/python/unittest/test_schedule_bound_inference.py
Labels: status: need review

#3839 [TOPI] Intel graphics conv2d autotvm template added
  python/tvm/autotvm/tophub.py
  tests/python/frontend/nnvm_to_relay/test_alter_conv2d.py
  topi/python/topi/intel_graphics/conv2d.py
  topi/python/topi/intel_graphics/depthwise_conv2d.py
Labels: status: need review

#3907 Support LLVM trunk
  CMakeLists.txt
  src/codegen/llvm/codegen_llvm.cc
Labels: status: need review

#3917 [Relay][Frontend][Keras] Fix ReLU in Keras Converter missed the case
  python/tvm/relay/frontend/keras.py
  tests/python/frontend/keras/test_forward.py
Labels: status: need test case

#3388 [RFC] Add AVX512VNNI support for TVM
  tests/python/contrib/test_gemm_acc32_vnni.py
  topi/python/topi/x86/tensor_intrin.py
Labels: status: accepted

#3930 [Relay][TensorFlow] Add support for SquaredDifference
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#3952 Enable miopen transpose convolution and fp16 support
  python/tvm/contrib/miopen.py
  src/contrib/miopen/conv_forward.cc
  tests/python/contrib/test_miopen.py
  topi/python/topi/rocm/conv2d.py
Labels: status: need review

#3929 [TOPI] operator support: logical_and, logical_or, logical_not
  docs/api/python/topi.rst
  topi/python/topi/broadcast.py
  topi/python/topi/math.py
  topi/src/topi.cc
  topi/tests/python/test_topi_broadcast.py
Labels: status: need update

#3956 [tvm][codegen] Make buffer auto broadcast independent to the order of input args
  python/tvm/api.py
  src/pass/make_api.cc
  tests/python/unittest/test_lang_buffer.py
Labels: status: need review

#3926 [Graph Tuner] Fix benchmark layout in graph tuner
  python/tvm/autotvm/graph_tuner/base_graph_tuner.py
  tests/python/unittest/test_graph_tuner_core.py
Labels: status: need review

#3948 [TOPI] Improve conv2d_transpose schedule on X86 and CUDA
  python/tvm/autotvm/task/space.py
  topi/python/topi/cuda/conv2d_transpose_nchw.py
  topi/python/topi/nn/conv2d_transpose.py
  topi/python/topi/x86/__init__.py
  topi/python/topi/x86/conv2d_avx_1x1.py
  topi/python/topi/x86/conv2d_avx_common.py
  topi/python/topi/x86/conv2d_transpose.py
Labels: status: need review

#3937 [Relay] Keras frontend upsample and 1 channel conv2d fixes
  python/tvm/relay/frontend/keras.py
  src/relay/op/nn/convolution.h
  tests/python/frontend/keras/test_forward.py
Labels: status: need review

#3699 [Relay] Add shape check for ConcatenateRel and StackRel
  src/relay/op/tensor/transform.cc
  src/relay/op/tensor/transform.h
  tests/python/relay/test_op_level1.py
Labels: status: need review, status: need update

#3739 Add support for MXNet pad operator, for parameter 'None' in slice operator, 1D Convolution and 1D Deconvolution
  include/tvm/expr_operator.h
  include/tvm/relay/attrs/nn.h
  python/tvm/intrin.py
  python/tvm/relay/frontend/common.py
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/op/_tensor.py
  python/tvm/relay/op/_tensor_grad.py
  python/tvm/relay/op/nn/nn.py
  python/tvm/relay/op/tensor.py
  src/codegen/intrin_rule.cc
  src/codegen/intrin_rule_cuda.cc
  src/codegen/llvm/intrin_rule_nvptx.cc
  src/relay/op/nn/pad.cc
  src/relay/op/tensor/unary.cc
  tests/python/frontend/mxnet/test_forward.py
  tests/python/relay/test_op_grad_level1.py
  tests/python/relay/test_op_level1.py
  topi/include/topi/elemwise.h
  topi/include/topi/nn.h
  topi/python/topi/math.py
  topi/src/topi.cc
  topi/tests/python/test_topi_basic.py
Labels: status: need update

#3941 [Relay][Frontend][ONNX] operator support: Tile
  python/tvm/relay/frontend/onnx.py
  tests/python/frontend/onnx/test_forward.py
Labels: status: need review

#3850 [Relay][Frontend][TFLite] frontend operator support: batch_to_space_nd, space_to_batch_nd
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: accepted

#3979 Add operator `isnan`
  docs/api/python/intrin.rst
  docs/api/python/topi.rst
  include/tvm/expr_operator.h
  include/tvm/ir.h
  python/tvm/intrin.py
  src/api/api_ir.cc
  src/codegen/codegen_c.cc
  src/codegen/llvm/codegen_llvm.cc
  src/lang/expr_operator.cc
  tests/python/unittest/test_lang_basic.py
  topi/include/topi/elemwise.h
  topi/python/topi/math.py
  topi/tests/python/test_topi_math.py
Labels: status: need test case, status: need update

#3862 [Relay] Add new IR pass CombineParallelDense
  docs/api/python/relay/transform.rst
  include/tvm/relay/transform.h
  python/tvm/relay/transform.py
  src/relay/backend/build_module.cc
  src/relay/pass/combine_parallel_conv2d.cc
  src/relay/pass/combine_parallel_dense.cc
  src/relay/pass/combine_parallel_op.cc
  src/relay/pass/combine_parallel_op.h
  src/relay/pass/combine_parallel_op_batch.cc
  src/relay/pass/combine_parallel_op_batch.h
  src/relay/pass/pattern_util.h
  tests/python/relay/test_pass_combine_parallel_dense.py
Labels: status: need review

#3996 add parser support for TANH tflite operator
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#3981 Changes to make tensorize work. These changes also fix the previously broken test.
  include/tvm/arithmetic.h
  src/arithmetic/ir_visitor_with_analyzer.h
  src/op/tensorize.cc
  src/pass/arg_binder.cc
  src/pass/storage_flatten.cc
  tests/python/contrib/test_gemm_acc16.py
Labels: status: need update

#4001 Expose llvm.nearbyint intrinsic. This is a faster alternate to rounding.
  docs/api/python/intrin.rst
  include/tvm/expr_operator.h
  python/tvm/intrin.py
  src/api/api_ir.cc
  src/codegen/llvm/intrin_rule_llvm.cc
  src/lang/expr_operator.cc
  tests/python/unittest/test_tvm_intrin.py
Labels: status: need test case, status: need update

#3972 [TOPI] Move conv2d spatial pack schedule to dedicated file
  topi/python/topi/arm_cpu/conv2d.py
  topi/python/topi/arm_cpu/conv2d_spatial_pack.py
  topi/python/topi/arm_cpu/conv2d_transpose.py
  topi/python/topi/mali/conv2d.py
Labels: status: need review

#4023 [AUTOTVM][DOCS] Add a link to the defining network description of auto-tuning tutorial
  tutorials/autotvm/tune_relay_x86.py
Labels: status: need update
