Repository apache/tvm, pull requests merged in 2019-04, with the labels that each got.

#2934 Update schedule_dataflow_rewrite.cc
  src/schedule/schedule_dataflow_rewrite.cc
  tests/python/unittest/test_schedule_schedule_ops.py
Labels: status: need test case

#2673 [DOCKER][FRONTEND] Run DarkNet tests
  nnvm/tests/python/frontend/darknet/test_forward.py
  tests/scripts/task_python_frontend.sh
Labels: status: need review

#2913 [Relay, Quantization] Quantize all fields of concatenate
  python/tvm/relay/quantize/_annotate.py
Labels: status: need review

#2942 Fix makedirs() condition in contrib.
  python/tvm/contrib/download.py
Labels: status: accepted

#2945 [Relay][OP] Gather_nd exposed to relay
  docs/langref/relay_op.rst
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  tests/python/frontend/mxnet/test_forward.py
  tests/python/relay/test_op_level3.py
Labels: status: accepted

#2951 Add missing #!/bin/bash directive.
  tests/scripts/task_python_topi.sh
Labels: status: accepted

#2857 [Bugfix] Bilinear resize bug fix from PR #2777
  python/tvm/relay/frontend/mxnet.py
  tests/python/frontend/mxnet/test_forward.py
Labels: status: accepted

#2829 [Relay][OP] Fix bias_add default axis
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/testing/inception_v3.py
  python/tvm/relay/testing/layers.py
  python/tvm/relay/testing/mlp.py
  src/relay/pass/canonicalize_ops.cc
Labels: status: need review

#2950 [RUNTIME][OPENCL] Make OpenCL runtime Compatible with OpenCL2.0 #2897
  src/runtime/opencl/opencl_common.h
Labels: status: accepted

#2936 [Relay][Frontend] Support tf.where
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need update

#2819 [TOPI] bitserial_conv2d move to autotvm template and updates
  python/tvm/autotvm/task/task.py
  python/tvm/autotvm/task/topi_integration.py
  topi/python/topi/arm_cpu/bitserial_conv2d.py
  topi/python/topi/nn/bitserial_conv2d.py
  topi/python/topi/x86/bitserial_conv2d.py
  topi/tests/python/test_topi_bitserial_conv2d.py
  topi/tests/python/test_topi_bitserial_conv2d_rasp.py
Labels: status: need review, status: need update

#2664 [AUTOTVM][TOPI] Port x86 NCHWc to AutoTVM for Task Extraction
  python/tvm/autotvm/task/relay_integration.py
  python/tvm/autotvm/task/topi_integration.py
  topi/python/topi/nn/conv2d.py
  topi/python/topi/x86/conv2d.py
Labels: status: need review, status: need update

#2714 [Relay] Partial Evaluation
  include/tvm/relay/expr.h
  include/tvm/relay/expr_functor.h
  include/tvm/relay/pass.h
  include/tvm/relay/pattern_functor.h
  python/tvm/relay/ir_pass.py
  src/relay/backend/interpreter.cc
  src/relay/ir/expr_functor.cc
  src/relay/ir/pretty_printer.cc
  src/relay/ir/type_functor.h
  src/relay/pass/dead_code.cc
  src/relay/pass/partial_eval.cc
  src/relay/pass/pass_util.h
  src/relay/pass/to_a_normal_form.cc
  src/relay/pass/util.cc
  tests/python/relay/test_pass_dead_code_elimination.py
  tests/python/relay/test_pass_gradient.py
  tests/python/relay/test_pass_partial_eval.py
  tests/python/relay/test_pass_to_a_normal_form.py
  tests/python/relay/test_pass_to_graph_normal_form.py
Labels: status: WIP, status: need review

#2943 [Relay][Frontend] Implement SpaceToBatchND in Tensorflow frontend
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#2751 [Relay] Add gradient operator tutorial docs
  docs/dev/relay_add_op.rst
  src/relay/pass/pattern_util.h
Labels: status: need review

#2881 [Relay][Text Format] Pretty Printer Smart Inlining
  python/tvm/relay/ir_pass.py
  src/relay/ir/pretty_printer.cc
  src/relay/pass/dependency_graph.cc
  src/relay/pass/dependency_graph.h
  src/relay/pass/to_a_normal_form.cc
  tests/python/relay/test_ir_text_printer.py
  tests/python/relay/test_op_level1.py
  tests/python/relay/test_op_level4.py
  tests/python/relay/test_type_infer.py
Labels: status: need update

#2990 [Heterogeneous][Bugfix] Fix bug of wrongly generated device_map
  src/relay/pass/device_annotation.cc
  tests/python/relay/test_pass_annotation.py
Labels: status: accepted

#3024 [Relay] use unordered_map instead of map in ANF
  src/relay/pass/to_a_normal_form.cc
Labels: status: accepted

#2746 [Relay] Add compiler pass tutorial docs
  docs/dev/index.rst
  docs/dev/relay_add_pass.rst
  docs/dev/runtime.rst
  src/relay/pass/fold_constant.cc
Labels: status: need update

#2977 [DOC] Add Android Tutorial
  apps/android_rpc/app/src/main/jni/Application.mk
  docker/Dockerfile.demo_android
  tutorials/frontend/deploy_model_on_android.py
Labels: status: need review

#2960 [Relay][Frontend] TF Tile Round Sign Pow Exp Reverse
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#2834 [Frontend][TF] Fix Placeholder issue
  nnvm/python/nnvm/frontend/tensorflow.py
  nnvm/tests/python/frontend/tensorflow/test_forward.py
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need update

#3063 Fix code comment and typos
  include/tvm/arithmetic.h
Labels: status: accepted

#2968 Enhance upsample operator to adapt onnx opset version 9 for nnvm comp…
  nnvm/python/nnvm/frontend/onnx.py
  nnvm/tests/python/frontend/onnx/test_forward.py
Labels: status: need review, status: need test case

#2949 [Relay][TOPI] Add rsqrt operator
  docs/api/python/topi.rst
  docs/langref/relay_op.rst
  include/tvm/expr_operator.h
  python/tvm/hybrid/runtime.py
  python/tvm/intrin.py
  python/tvm/relay/op/_tensor.py
  python/tvm/relay/op/tensor.py
  src/codegen/intrin_rule.cc
  src/relay/op/tensor/unary.cc
  tests/python/relay/test_ir_op.py
  tests/python/relay/test_op_level1.py
  topi/include/topi/elemwise.h
  topi/python/topi/math.py
  topi/src/topi.cc
  topi/tests/python/test_topi_basic.py
  topi/tests/python/test_topi_math.py
Labels: status: need review

#3087 [Relay][TensorFlow] Remove 'input_0d_mismatch' special handling
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#2877 [Relay, Quantization, TOPI] int8 dense on CUDA & Dense op quantization
  include/tvm/relay/attrs/nn.h
  python/tvm/autotvm/task/topi_integration.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  python/tvm/relay/quantize/_annotate.py
  src/relay/op/nn/nn.cc
  src/relay/pass/quantize.cc
  topi/include/topi/cuda/dense.h
  topi/include/topi/nn/dense.h
  topi/include/topi/rocm/dense.h
  topi/python/topi/cuda/__init__.py
  topi/python/topi/cuda/dense.py
  topi/python/topi/nn/dense.py
  topi/python/topi/rocm/dense.py
  topi/python/topi/x86/dense.py
  topi/src/topi.cc
  topi/tests/python/common.py
  topi/tests/python/test_topi_conv2d_int8.py
  topi/tests/python/test_topi_dense.py
  topi/tests/python/test_topi_group_conv2d.py
Labels: status: need review

#2956 1) fixes in loop partitioning algorithm 2) added a testcase
  src/pass/loop_partition.cc
  tests/python/unittest/test_pass_loop_partition.py
Labels: status: need review

#3051 [TOPI] Bitserial dense operators for CPU
  python/tvm/autotvm/task/topi_integration.py
  topi/python/topi/arm_cpu/__init__.py
  topi/python/topi/arm_cpu/bitserial_conv2d.py
  topi/python/topi/arm_cpu/bitserial_dense.py
  topi/python/topi/generic/nn.py
  topi/python/topi/nn/__init__.py
  topi/python/topi/nn/bitserial_conv2d.py
  topi/python/topi/nn/bitserial_dense.py
  topi/python/topi/nn/bitserial_util.py
  topi/python/topi/x86/__init__.py
  topi/python/topi/x86/bitserial_dense.py
  topi/tests/python/test_topi_bitserial_dense.py
Labels: status: need review

#3092 [Relay, OpFusion] Better tuple fusion implementation
  include/tvm/relay/op_attr_types.h
  python/tvm/relay/op/op.py
  src/relay/pass/fuse_ops.cc
  tests/python/relay/test_backend_compile_engine.py
  tests/python/relay/test_pass_fuse_ops.py
Labels: status: need review

#3105 [Lang] Fix undef BijectiveLayout and add scalar layout support
  include/tvm/data_layout.h
  src/lang/data_layout.cc
  src/relay/pass/alter_op_layout.h
  tests/python/relay/test_pass_alter_op_layout.py
  tests/python/unittest/test_lang_data_layout.py
Labels: status: need update

#2784 [Relay][TOPI] Gluncv SSD support on the GPU
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/algorithm.h
  include/tvm/relay/attrs/vision.h
  nnvm/include/nnvm/top/nn.h
  nnvm/python/nnvm/top/vision.py
  nnvm/tests/python/compiler/test_top_level4.py
  python/tvm/relay/__init__.py
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/op/__init__.py
  python/tvm/relay/op/_algorithm.py
  python/tvm/relay/op/algorithm.py
  python/tvm/relay/op/tensor.py
  python/tvm/relay/op/transform.py
  python/tvm/relay/op/vision/_vision.py
  python/tvm/relay/op/vision/nms.py
  src/contrib/sort/sort.cc
  src/relay/op/algorithm/sort.cc
  src/relay/op/vision/nms.cc
  tests/python/contrib/test_sort.py
  tests/python/relay/test_op_level5.py
  tests/python/relay/test_op_level6.py
  topi/python/topi/__init__.py
  topi/python/topi/cuda/nms.py
  topi/python/topi/cuda/sort.py
  topi/python/topi/cuda/ssd/multibox.py
  topi/python/topi/cuda/vision.py
  topi/python/topi/generic/__init__.py
  topi/python/topi/generic/sort.py
  topi/python/topi/sort.py
  topi/python/topi/vision/nms.py
  topi/python/topi/vision/ssd/multibox.py
  topi/tests/python/test_topi_sort.py
  topi/tests/python/test_topi_vision.py
  tutorials/frontend/deploy_ssd_gluoncv.py
Labels: status: accepted

#3084 Fix bug in ONNX importer
  python/tvm/relay/frontend/onnx.py
  tests/python/frontend/onnx/test_forward.py
Labels: status: accepted
