Repository apache/tvm, pull requests merged in 2019-05, with the labels that each got.

#3050 [Bugfix] Fix type code error for StringImm
  src/pass/lower_tvm_builtin.cc
  tests/python/unittest/test_runtime_measure.py
Labels: status: need test case, status: need update

#3019 [FRONTEND][TFLITE] Add FULLY_CONNECTED op into tflite frontend, support Inception V4
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need update

#3013 Fix PRelu layout in Relay
  nnvm/src/top/nn/nn.cc
  src/relay/op/nn/nn.cc
  tests/python/relay/test_pass_alter_op_layout.py
Labels: status: need test case

#3132 [ARITH] Constraint-aware ConstIntBound, Enhance CanonicalSimplify
  src/arithmetic/canonical_simplify.cc
  src/arithmetic/const_int_bound.cc
  src/arithmetic/modular_set.cc
  src/arithmetic/rewrite_simplify.cc
  tests/python/unittest/test_arith_canonical_simplify.py
Labels: status: need review

#3111 [Relay][Frontend] add log op in tf frontend
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#3082 Relay C++ Build Module
  include/tvm/build_module.h
  src/codegen/build_module.cc
  src/relay/backend/build_module.cc
  src/relay/backend/compile_engine.cc
  src/relay/backend/graph_runtime_codegen.cc
  tests/cpp/relay_build_module_test.cc
  tests/python/relay/test_cpp_build_module.py
Labels: status: need review

#3085 [Relay][Op] Adaptive pooling
  docs/api/python/topi.rst
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/nn.h
  nnvm/python/nnvm/top/nn.py
  python/tvm/relay/__init__.py
  python/tvm/relay/contrib.py
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/op/__init__.py
  python/tvm/relay/op/contrib/__init__.py
  python/tvm/relay/op/contrib/_contrib.py
  python/tvm/relay/op/contrib/_make.py
  python/tvm/relay/op/contrib/contrib.py
  python/tvm/relay/op/nn/_nn.py
  src/relay/op/nn/pooling.cc
  tests/python/frontend/mxnet/test_forward.py
  tests/python/relay/test_op_level10.py
  tests/python/relay/test_op_level2.py
  topi/include/topi/nn/pooling.h
  topi/python/topi/cuda/__init__.py
  topi/python/topi/cuda/pooling.py
  topi/python/topi/generic/nn.py
  topi/python/topi/hls/nn.py
  topi/python/topi/nn/pooling.py
  topi/python/topi/opengl/__init__.py
  topi/python/topi/opengl/pooling.py
  topi/python/topi/x86/__init__.py
  topi/python/topi/x86/pooling.py
  topi/src/topi.cc
  topi/tests/python/test_topi_pooling.py
Labels: status: need review

#2889 [Relay][Runtime] Implementation of Relay VM
  CMakeLists.txt
  cmake/config.cmake
  include/tvm/relay/logging.h
  include/tvm/relay/pass.h
  include/tvm/runtime/c_runtime_api.h
  include/tvm/runtime/ndarray.h
  include/tvm/runtime/vm.h
  python/tvm/relay/backend/_vm.py
  python/tvm/relay/backend/interpreter.py
  python/tvm/relay/backend/vm.py
  python/tvm/relay/build_module.py
  python/tvm/relay/expr.py
  python/tvm/relay/ir_pass.py
  python/tvm/relay/module.py
  src/arithmetic/canonical_simplify.cc
  src/relay/backend/build_module.cc
  src/relay/backend/compile_engine.h
  src/relay/backend/interpreter.cc
  src/relay/ir/error.cc
  src/relay/ir/expr.cc
  src/relay/ir/hash.cc
  src/relay/ir/module.cc
  src/relay/ir/type_functor.cc
  src/relay/ir/type_functor.h
  src/relay/op/type_relations.cc
  src/relay/pass/eta_expand.cc
  src/relay/pass/fold_constant.cc
  src/relay/pass/fuse_ops.cc
  src/relay/pass/kind_check.cc
  src/relay/pass/partial_eval.cc
  src/relay/pass/to_a_normal_form.cc
  src/relay/pass/type_infer.cc
  src/runtime/vm/memory_manager.cc
  src/runtime/vm/memory_manager.h
  src/runtime/vm/naive_allocator.h
  src/runtime/vm/object.cc
  src/runtime/vm/vm.cc
  tests/python/relay/test_pass_dead_code_elimination.py
  tests/python/relay/test_pass_eta_expand.py
  tests/python/relay/test_pass_partial_eval.py
  topi/include/topi/transform.h
Labels: status: need review

#3144 [codegen] heterogeneous build for c++
  include/tvm/build_module.h
  src/codegen/build_module.cc
  src/relay/backend/build_module.cc
  tests/cpp/build_module_test.cc
  tests/python/relay/test_cpp_build_module.py
Labels: status: need review

#3165 Fix a tensorflow test bug.
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need test case

#3157 [HybridScript] Capture constant external python variables
  python/tvm/hybrid/__init__.py
  python/tvm/hybrid/module.py
  python/tvm/hybrid/parser.py
  python/tvm/hybrid/preprocessor.py
  python/tvm/hybrid/util.py
  tests/python/unittest/test_hybrid_script.py
Labels: status: need review

#3139 [Relay][Runtime] Add VM compiler.
  include/tvm/relay/pass.h
  include/tvm/runtime/vm.h
  src/relay/backend/vm/compiler.cc
  src/relay/backend/vm/inline_primitives.cc
  src/relay/backend/vm/lambda_lift.cc
  src/relay/backend/vm/vm.cc
  src/relay/op/tensor/reduce.cc
  src/relay/pass/dead_code.cc
  src/runtime/vm/vm.cc
  tests/python/relay/benchmarking/benchmark_vm.py
  tests/python/relay/test_vm.py
Labels: status: need review

#3083 [RELAY][PASS] detect depthwise conv2d in mac_count pass
  src/relay/pass/mac_count.cc
  tests/python/relay/test_pass_mac_count.py
Labels: status: need review

#3174 [Relay][Compilation] replace relay.build_module with C++ BuildModule
  python/tvm/relay/__init__.py
  python/tvm/relay/_build_module.py
  python/tvm/relay/backend/graph_runtime_codegen.py
  python/tvm/relay/build_module.py
  python/tvm/relay/quantize/quantize.py
  src/codegen/build_module.cc
  src/relay/backend/build_module.cc
  src/relay/backend/graph_runtime_codegen.cc
  tests/cpp/relay_build_module_test.cc
  tests/python/frontend/nnvm_to_relay/test_alter_conv2d.py
  tests/python/relay/test_cpp_build_module.py
  tests/python/relay/test_pass_annotation.py
  tests/python/relay/test_pass_quantize.py
Labels: status: need review

#3173 [Relay] Option to select which convolution layers are quantized.
  python/tvm/relay/quantize/_annotate.py
  python/tvm/relay/quantize/quantize.py
  src/relay/pass/quantize.cc
  src/relay/pass/quantize.h
  topi/python/topi/cuda/conv2d.py
Labels: status: need review

#3081 Add the acc16 intrinsic support
  tests/python/contrib/test_gemm_acc16.py
  topi/python/topi/x86/tensor_intrin.py
Labels: status: need review, status: need update

#2995 Get list of unsupported ONNX operators
  nnvm/python/nnvm/frontend/onnx.py
  python/tvm/relay/frontend/onnx.py
Labels: status: need update

#3176 [Relay] Better shape inference in TensorFlow Frontend.
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review, status: need test case

#3194 [CODEGEN][CUDA][OPENCL] Handle INF and NAN
  src/codegen/codegen_cuda.cc
  src/codegen/codegen_cuda.h
  src/codegen/codegen_opencl.cc
  src/codegen/codegen_opencl.h
  tests/python/unittest/test_codegen_cuda.py
  tests/python/unittest/test_codegen_opencl.py
Labels: status: need test case

#3061 [ARM] Fix concat
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/op.py
  topi/python/topi/arm_cpu/injective.py
  topi/tests/python/test_topi_transform.py
Labels: status: need update

#3124 [Relay][TOPI] operator All
  docs/api/python/topi.rst
  docs/langref/relay_op.rst
  include/tvm/expr_operator.h
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/op/_reduce.py
  python/tvm/relay/op/reduce.py
  src/lang/expr_operator.cc
  src/relay/op/tensor/reduce.cc
  tests/python/frontend/tensorflow/test_forward.py
  tests/python/relay/test_op_level4.py
  topi/include/topi/reduction.h
  topi/python/topi/reduction.py
  topi/src/topi.cc
  topi/tests/python/test_topi_reduce.py
Labels: status: accepted

#3141 [TFLite] Convert TFLite NCHW to NHWC
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
  tutorials/frontend/from_tflite.py
Labels: status: need review

#2991 Add packing for int8 1x1 convolution and support the int8 group convolution on X86
  topi/python/topi/generic/nn.py
  topi/python/topi/nn/conv2d.py
  topi/python/topi/x86/conv2d.py
  topi/python/topi/x86/conv2d_avx_1x1.py
  topi/tests/python/test_topi_conv2d_nhwc_pack_int8.py
  topi/tests/python/test_topi_group_conv2d_NCHWc_int8.py
Labels: status: need review, status: need update

#3114 [WIP] [Relay] [NNVM] [Frontend] implement MaxPool-8 and MaxPool-10
  nnvm/python/nnvm/frontend/onnx.py
  python/tvm/relay/frontend/onnx.py
Labels: status: need update

#3225 [AutoTVM] Change to record.pick_best to prevent overwriting previous results.
  python/tvm/autotvm/record.py
Labels: status: need review

#3231 [C++][API] Python-style With, Consistent RAII
  include/tvm/arithmetic.h
  include/tvm/base.h
  include/tvm/build_module.h
  python/tvm/build_module.py
  python/tvm/target.py
  src/api/api_arith.cc
  src/arithmetic/analyzer.cc
  src/arithmetic/rewrite_simplify.cc
  src/arithmetic/stmt_simplify.cc
  src/codegen/build_module.cc
  src/codegen/codegen_aocl.cc
  src/codegen/codegen_vhls.cc
  src/codegen/llvm/codegen_llvm.cc
  src/codegen/spirv/codegen_spirv.cc
  src/relay/backend/build_module.cc
  src/relay/backend/compile_engine.cc
  src/relay/backend/vm/compiler.cc
  src/relay/pass/fold_constant.cc
  src/relay/pass/partial_eval.cc
  tests/cpp/build_module_test.cc
  tests/cpp/relay_build_module_test.cc
  topi/src/topi.cc
Labels: status: need review

#3149 [ARITH] Improve div/mod in rewrite simplifier
  src/arithmetic/modular_set.cc
  src/arithmetic/rewrite_simplify.cc
  tests/python/unittest/test_arith_rewrite_simplify.py
Labels: status: accepted

#2184 [AutoTVM]Core functionality for Graph tuner
  python/tvm/autotvm/graph_tuner/__init__.py
  python/tvm/autotvm/graph_tuner/_base.py
  python/tvm/autotvm/graph_tuner/base_graph_tuner.py
  python/tvm/autotvm/graph_tuner/dynamic_programming_stage.py
  python/tvm/autotvm/graph_tuner/dynamic_programming_tuner.py
  python/tvm/autotvm/graph_tuner/pbqp_tuner.py
  python/tvm/autotvm/graph_tuner/utils/__init__.py
  python/tvm/autotvm/graph_tuner/utils/traverse_graph.py
  python/tvm/autotvm/graph_tuner/utils/utils.py
  python/tvm/autotvm/task/__init__.py
  python/tvm/autotvm/task/topi_integration.py
  tests/python/unittest/test_graph_tuner_core.py
  tests/python/unittest/test_graph_tuner_utils.py
  topi/python/topi/nn/conv2d.py
  topi/python/topi/nn/depthwise_conv2d.py
  topi/python/topi/x86/conv2d.py
  topi/python/topi/x86/depthwise_conv2d.py
  tutorials/autotvm/tune_relay_x86.py
Labels: status: need review, status: need update

#3260 [Relay] Handle float16 constants & fix BatchNorm
  src/relay/pass/pattern_util.h
  src/relay/pass/simplify_inference.cc
  tests/python/relay/test_pass_simplify_inference.py
Labels: status: need review
