Repository apache/tvm, pull requests merged in 2020-03, with the labels that each got.

#4961 [Torch] Upsampling op support and enable registering a user defined op conversion map
  python/tvm/relay/frontend/pytorch.py
  tests/python/frontend/pytorch/test_forward.py
  tutorials/frontend/from_pytorch.py
Labels: status: need review

#4873 [Relay][FastMath] Relay pass to use fast exp/tanh
  include/tvm/relay/transform.h
  python/tvm/relay/transform.py
  src/relay/backend/build_module.cc
  src/relay/op/tensor/unary.cc
  src/relay/pass/fast_math.cc
  src/relay/pass/pattern_util.h
  tests/python/relay/test_pass_fast_math.py
  topi/include/topi/elemwise.h
  topi/python/topi/math.py
  topi/src/topi.cc
Labels: status: need review

#4951 Conditions updated to cover better user scenarios
  src/relay/ir/alpha_equal.cc
  tests/cpp/relay_pass_alpha_equal.cc
  tests/python/relay/test_pass_alpha_equal.py
Labels: status: need review, status: need test case

#4996 [relay][external codegen] outline and inline lifted functions for external codegen
  src/relay/backend/build_module.cc
  src/relay/backend/vm/compiler.cc
  src/relay/backend/vm/inline_primitives.cc
  src/relay/backend/vm/lambda_lift.cc
  src/relay/pass/partition_graph.cc
  src/relay/pass/to_a_normal_form.cc
  tests/python/relay/test_pass_partition_graph.py
Labels: status: need review

#4990 [TF][Relay] BatchNorm support with run-time mean and variance calculation
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_bn_dynamic.py
Labels: status: need update

#4980 [FRONTEND][TENSORFLOW] support multiply outputs
  python/tvm/relay/testing/tf.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need test case

#4964 [Torch] Add initial control flow support
  python/tvm/relay/frontend/pytorch.py
  tests/python/frontend/pytorch/qnn_test.py
  tests/python/frontend/pytorch/test_forward.py
Labels: status: need review

#4978 [TFLITE]Activation functions support
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#5011 [Intrin] Adding a few missing math intrin
  include/tvm/tir/op.h
  python/tvm/tir/__init__.py
  python/tvm/tir/op.py
  src/target/llvm/intrin_rule_llvm.cc
  src/target/llvm/intrin_rule_nvptx.cc
  src/target/llvm/intrin_rule_rocm.cc
  src/target/source/intrin_rule_cuda.cc
  src/target/source/intrin_rule_metal.cc
  src/target/source/intrin_rule_opencl.cc
  src/target/source/intrin_rule_opengl.cc
  src/target/source/intrin_rule_vhls.cc
  tests/python/unittest/test_tvm_intrin.py
Labels: status: need test case

#4949 Conv3D ONNX support and conv3D_ncdhw x86 schedules
  python/tvm/relay/frontend/onnx.py
  python/tvm/relay/op/strategy/x86.py
  tests/python/frontend/onnx/test_forward.py
  topi/python/topi/x86/conv3d.py
  topi/tests/python/test_topi_conv3d_ncdhw.py
Labels: status: need review

#4628 [Object] Add String container
  include/tvm/runtime/container.h
  tests/cpp/container_test.cc
Labels: status: need review, status: need update

#5049 [Relay, TOPI] Refactor Adaptive pool and add 3d support
  include/tvm/relay/attrs/nn.h
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  src/relay/op/nn/pooling.cc
  tests/python/relay/test_op_level10.py
  topi/include/topi/nn/pooling.h
  topi/python/topi/nn/pooling.py
  topi/python/topi/testing/__init__.py
  topi/python/topi/testing/adaptive_pool_python.py
  topi/src/topi.cc
  topi/tests/python/test_topi_pooling.py
Labels: status: need review

#4847 Return empty CSourceModule when no lowered_funcs exists in Relay mod
  src/relay/backend/build_module.cc
  src/target/llvm/llvm_module.cc
Labels: status: need review

#4963 [TEST]Tensorflow/lite scripts upgrade from 1.13.1 to 2.0.0
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/frontend/tensorflow_parser.py
  python/tvm/relay/testing/tf.py
  tests/python/frontend/keras/test_forward.py
  tests/python/frontend/tensorflow/test_control_flow.py
  tests/python/frontend/tensorflow/test_debugging.py
  tests/python/frontend/tensorflow/test_forward.py
  tests/python/frontend/tensorflow/test_no_op.py
  tests/python/frontend/tflite/test_forward.py
  tutorials/frontend/from_tflite.py
Labels: status: need review

#5033 [Relay, TF Frontend] Dilation2D operator support
  docs/api/python/topi.rst
  docs/frontend/tensorflow.rst
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/nn.h
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  python/tvm/relay/op/op_attrs.py
  python/tvm/relay/op/strategy/generic.py
  src/relay/op/nn/convolution.cc
  src/relay/op/nn/convolution.h
  tests/python/frontend/tensorflow/test_forward.py
  tests/python/relay/test_op_level2.py
  topi/python/topi/generic/nn.py
  topi/python/topi/nn/__init__.py
  topi/python/topi/nn/dilation2d.py
Labels: status: need review

#5073 [Relay][Frontend][ONNX] operator support NonZero
  python/tvm/relay/frontend/onnx.py
  tests/python/frontend/onnx/test_forward.py
Labels: status: need review

#5078 [DOC] Add doc for Relay op strategy
  docs/dev/index.rst
  docs/dev/relay_op_strategy.rst
Labels: status: need review

#5005 TVM android camera demo
  apps/android_camera/.gitignore
  apps/android_camera/README.md
  apps/android_camera/app/build.gradle
  apps/android_camera/app/src/main/AndroidManifest.xml
  apps/android_camera/app/src/main/java/org/apache/tvm/android/androidcamerademo/Camera2BasicFragment.java
  apps/android_camera/app/src/main/java/org/apache/tvm/android/androidcamerademo/MainActivity.java
  apps/android_camera/app/src/main/jni/Android.mk
  apps/android_camera/app/src/main/jni/Application.mk
  apps/android_camera/app/src/main/jni/build.sh
  apps/android_camera/app/src/main/jni/make/config.mk
  apps/android_camera/app/src/main/jni/tvm_runtime.h
  apps/android_camera/app/src/main/res/drawable/item_selector.xml
  apps/android_camera/app/src/main/res/layout/activity_main.xml
  apps/android_camera/app/src/main/res/layout/fragment_camera2_basic.xml
  apps/android_camera/app/src/main/res/layout/listview_row.xml
  apps/android_camera/app/src/main/res/values/colors.xml
  apps/android_camera/app/src/main/res/values/strings.xml
  apps/android_camera/app/src/main/res/values/styles.xml
  apps/android_camera/app/src/main/res/xml/provider_paths.xml
  apps/android_camera/app/src/main/rs/yuv420888.rs
  apps/android_camera/build.gradle
  apps/android_camera/dev_tools/gen_keystore.sh
  apps/android_camera/dev_tools/sign_apk.sh
  apps/android_camera/gradle.properties
  apps/android_camera/models/prepare_model.py
  apps/android_camera/settings.gradle
  tests/lint/add_asf_header.py
Labels: status: need review

#5080 [KERAS] conv3d frontend operator support
  python/tvm/relay/frontend/keras.py
  tests/python/frontend/keras/test_forward.py
Labels: status: need review

#5101 [CodeGen][CUDA] Vectorization for intrinsics
  src/target/source/codegen_c.h
  src/target/source/codegen_cuda.cc
  src/target/source/intrin_rule_cuda.cc
  tests/python/unittest/test_target_codegen_cuda.py
Labels: status: need review

#5082 [Relay, Topi] [TF, MXNet] Unravel Index operator
  docs/api/python/topi.rst
  docs/frontend/tensorflow.rst
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/transform.h
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  tests/python/frontend/mxnet/test_forward.py
  tests/python/frontend/tensorflow/test_forward.py
  tests/python/relay/test_op_level3.py
  topi/include/topi/transform.h
  topi/python/topi/transform.py
  topi/src/topi.cc
  topi/tests/python/test_topi_transform.py
Labels: status: need update

#4981 [Relay, Topi, TF Frontend] Isfinite operator
  docs/api/python/topi.rst
  docs/frontend/tensorflow.rst
  include/tvm/tir/expr.h
  include/tvm/tir/op.h
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/op/_tensor.py
  python/tvm/relay/op/tensor.py
  python/tvm/te/__init__.py
  python/tvm/tir/__init__.py
  python/tvm/tir/op.py
  src/relay/op/tensor/unary.cc
  src/relay/op/type_relations.cc
  src/relay/op/type_relations.h
  src/target/intrin_rule.cc
  src/tir/ir/op.cc
  tests/python/frontend/tensorflow/test_forward.py
  tests/python/relay/test_op_level3.py
  topi/include/topi/elemwise.h
  topi/python/topi/math.py
  topi/tests/python/test_topi_math.py
Labels: status: need review

#5115 [Bugfix] Fixed bug where shifting by out-of-bounds value results in no compute code being emitted.
  src/tir/ir/op.cc
  tests/python/unittest/test_tir_nodes.py
Labels: status: need review

#5020 [Frontend][TensorFlow]TensorFlow Parser Control Flow Enhancement
  python/tvm/relay/frontend/common.py
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_control_flow.py
  tests/python/frontend/tensorflow/test_debugging.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#5142 [Torch] Add support for max_pool1d
  python/tvm/relay/frontend/pytorch.py
  src/relay/op/nn/pooling.cc
  tests/python/frontend/pytorch/test_forward.py
Labels: status: review in progress

#5023 [External Codegen] Fix annotate pass static variable
  src/relay/transforms/annotate_target.cc
Labels: status: need update

#5099 [TOPI][Tensor Core] Conv2d and Dense ops support on Tensor Core
  python/tvm/relay/op/strategy/cuda.py
  python/tvm/relay/testing/resnet.py
  src/driver/driver_api.cc
  topi/python/topi/cuda/__init__.py
  topi/python/topi/cuda/conv2d.py
  topi/python/topi/cuda/conv2d_nhwc.py
  topi/python/topi/cuda/conv2d_nhwc_tensorcore.py
  topi/python/topi/cuda/dense_tensorcore.py
  topi/python/topi/cuda/tensor_intrin.py
  topi/tests/python/test_topi_conv2d_nhwc.py
  topi/tests/python/test_topi_conv2d_nhwc_tensorcore.py
  topi/tests/python/test_topi_dense_tensorcore.py
Labels: status: need review

#5042 [TF][Relay] TensorFlow Frontend support with shared params
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need update

#5121 [TE] reverse-mode autodiff without any optimization
  include/tvm/te/autodiff.h
  python/tvm/te/__init__.py
  python/tvm/te/autodiff.py
  src/te/autodiff/ad_util.cc
  src/te/autodiff/ad_util.h
  src/te/autodiff/adjoint.cc
  src/te/autodiff/jacobian.cc
  src/te/operation/compute_op.h
  tests/python/unittest/test_te_autodiff.py
  tests/python/unittest/test_testing.py
Labels: status: need review

#5085 [FRONTEND][KERAS]Max_pool3d and Averagepool3d operator support
  python/tvm/relay/frontend/keras.py
  tests/python/frontend/keras/test_forward.py
Labels: status: need review
