Repository apache/tvm, pull requests merged in 2020-09, with the labels that each got.

#6143 [Relay] support i64 indices
  CMakeLists.txt
  cmake/modules/LibInfo.cmake
  include/tvm/topi/detail/constant_utils.h
  python/tvm/relay/backend/compile_engine.py
  src/arith/bound_deducer.cc
  src/arith/int_set.cc
  src/relay/backend/compile_engine.cc
  src/relay/op/tensor/reduce.cc
  src/support/libinfo.cc
  src/te/operation/op_util.cc
  src/te/schedule/message_passing.cc
  src/te/schedule/schedule_lang.cc
  tests/python/unittest/test_tir_transform_narrow_datatype.py
Labels: status: need review

#6289 [Relay] Enhance relay.split(), allow splitted dim to be dynamic
  include/tvm/topi/transform.h
  python/tvm/relay/op/_transform.py
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_any.py
Labels: status: review in progress

#6381 [TFLite] Support for 'SAME' Padding option for TRANSPOSE_CONV operator of TFLite.
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: review in progress

#6353 [RELAY][DYN] Dynamic UpSampling3D Op
  python/tvm/relay/op/dyn/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  python/tvm/topi/image/resize.py
  python/tvm/topi/nn/upsampling.py
  src/relay/op/dyn/nn/upsampling.cc
  src/relay/op/make_op.h
  src/relay/transforms/dynamic_to_static.cc
  tests/python/relay/dyn/test_dynamic_op_level2.py
  tests/python/relay/test_pass_dynamic_to_static.py
Labels: status: need review

#6251 [ONNX] Add Clip importer to handle when min/max are provided as inputs.
  python/tvm/relay/frontend/onnx.py
  tests/python/frontend/onnx/test_forward.py
Labels: status: review in progress

#6316 Dynamic Strided Slice
  python/tvm/relay/frontend/keras.py
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/frontend/onnx.py
  python/tvm/relay/frontend/pytorch.py
  python/tvm/relay/op/_tensor_grad.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/dyn/_transform.py
  python/tvm/relay/op/transform.py
  python/tvm/topi/cuda/conv2d_alter_op.py
  python/tvm/topi/x86/conv2d_alter_op.py
  src/relay/op/dyn/tensor/transform.cc
  src/relay/op/make_op.h
  src/relay/op/tensor/transform.cc
  src/relay/transforms/combine_parallel_batch_matmul.cc
  src/relay/transforms/combine_parallel_conv2d.cc
  src/relay/transforms/combine_parallel_dense.cc
  src/relay/transforms/dynamic_to_static.cc
  src/relay/transforms/pass_util.h
  tests/python/relay/dyn/test_dynamic_op_level10.py
  tests/python/relay/dyn/test_dynamic_op_level2.py
  tests/python/relay/dyn/test_dynamic_op_level3.py
  tests/python/relay/dyn/test_dynamic_op_level4.py
  tests/python/relay/dyn/test_dynamic_op_level5.py
  tests/python/relay/dyn/test_dynamic_op_level6.py
  tests/python/relay/test_op_level4.py
  tests/python/relay/test_pass_alter_op_layout.py
  tests/python/relay/test_pass_combine_parallel_batch_matmul.py
  tests/python/relay/test_pass_combine_parallel_conv2d.py
  tests/python/relay/test_pass_combine_parallel_dense.py
  tests/python/relay/test_pass_dynamic_to_static.py
Labels: status: need review

#6297 [Ansor][AutoTVM v2.0] Phase 2: Layout Rewrite in AutoScheduler
  include/tvm/auto_scheduler/auto_schedule.h
  include/tvm/auto_scheduler/compute_dag.h
  include/tvm/auto_scheduler/cost_model.h
  include/tvm/auto_scheduler/feature.h
  include/tvm/auto_scheduler/loop_state.h
  include/tvm/auto_scheduler/measure.h
  include/tvm/auto_scheduler/measure_record.h
  include/tvm/auto_scheduler/search_policy.h
  include/tvm/auto_scheduler/search_task.h
  include/tvm/auto_scheduler/transform_step.h
  python/tvm/auto_scheduler/compute_dag.py
  python/tvm/auto_scheduler/measure.py
  src/auto_scheduler/auto_schedule.cc
  src/auto_scheduler/compute_dag.cc
  src/auto_scheduler/cost_model.cc
  src/auto_scheduler/feature.cc
  src/auto_scheduler/loop_state.cc
  src/auto_scheduler/measure.cc
  src/auto_scheduler/measure_record.cc
  src/auto_scheduler/search_task.cc
  src/auto_scheduler/transform_step.cc
  src/auto_scheduler/utils.cc
  src/auto_scheduler/utils.h
  tests/python/unittest/test_auto_scheduler_common.py
  tests/python/unittest/test_auto_scheduler_layout_rewrite.py
Labels: status: review in progress

#6433 [Relay, Torch] Fix stack op axis check, support torch::stack conversion for a static list
  python/tvm/relay/frontend/pytorch.py
  src/relay/op/tensor/transform.cc
  tests/python/frontend/pytorch/test_forward.py
  tests/python/frontend/pytorch/test_lstm.py
  tests/python/relay/test_op_level3.py
Labels: status: need review

#6400 [Relay] Add Defunctionalization Pass
  python/tvm/relay/transform/transform.py
  src/relay/transforms/defunctionalization.cc
  tests/python/relay/test_pass_defunctionalization.py
Labels: status: need review

#6420 [QNN][Relay] Fixed bug in quantized conv2d.
  src/relay/qnn/op/convolution.cc
  tests/python/relay/test_op_qnn_conv2d.py
Labels: status: need review

#6464 [Relay]Some backend improvements for PT OD models
  python/tvm/autotvm/task/task.py
  python/tvm/relay/op/_tensor.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/vision/_vision.py
  python/tvm/topi/scatter.py
  python/tvm/topi/x86/conv2d.py
  python/tvm/topi/x86/dense.py
  python/tvm/topi/x86/roi_align.py
  src/relay/op/tensor/transform.cc
  src/relay/op/tensor/unary.cc
  tests/python/relay/test_any.py
Labels: status: need review

#6355 [BYOC][ETHOSN] Introduce further operator support
  python/tvm/relay/op/contrib/ethosn.py
  src/relay/backend/contrib/ethosn/codegen.cc
  src/relay/backend/contrib/ethosn/codegen_ethosn.h
  src/relay/backend/contrib/ethosn/ethosn_api.cc
  src/relay/backend/contrib/ethosn/ethosn_api.h
  src/runtime/contrib/ethosn/ethosn_runtime.cc
  src/runtime/contrib/ethosn/ethosn_runtime.h
  tests/python/contrib/test_ethosn/infrastructure.py
  tests/python/contrib/test_ethosn/test_addition.py
  tests/python/contrib/test_ethosn/test_conv2d.py
  tests/python/contrib/test_ethosn/test_depth_to_space.py
  tests/python/contrib/test_ethosn/test_fullyconnected.py
  tests/python/contrib/test_ethosn/test_networks.py
  tests/python/contrib/test_ethosn/test_pooling.py
  tests/python/contrib/test_ethosn/test_relu.py
  tests/python/contrib/test_ethosn/test_reshape.py
  tests/python/contrib/test_ethosn/test_sigmoid.py
  tests/python/contrib/test_ethosn/test_topologies.py
Labels: status: need review

#6494 black format master
  python/tvm/contrib/cc.py
  python/tvm/micro/artifact.py
  python/tvm/micro/build.py
  python/tvm/micro/class_factory.py
  python/tvm/micro/compiler.py
  python/tvm/micro/debugger.py
  python/tvm/micro/micro_binary.py
  python/tvm/micro/micro_library.py
  python/tvm/micro/session.py
  python/tvm/micro/transport.py
  python/tvm/relay/frontend/pytorch.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/vision/_vision.py
  python/tvm/rpc/client.py
  python/tvm/target/target.py
  python/tvm/topi/x86/conv2d.py
  tests/lint/add_asf_header.py
  tests/lint/check_file_type.py
  tests/python/frontend/pytorch/test_forward.py
  tests/python/relay/test_any.py
  tests/python/topi/python/test_topi_pooling.py
  tests/python/unittest/test_crt.py
  tests/python/unittest/test_runtime_rpc.py
  tutorials/micro/micro_tflite.py
Labels: status: review in progress

#6449 [Frontend][Pytorch] Improve Pytorch frontend for object detection models
  python/tvm/relay/frontend/pytorch.py
  tests/python/frontend/pytorch/test_forward.py
  tests/python/frontend/pytorch/test_object_detection.py
Labels: status: review in progress

#6472 Add several op mapping in PyTorch frontend
  python/tvm/relay/frontend/pytorch.py
  tests/python/frontend/pytorch/test_forward.py
Labels: status: need review

#6443 [RELAY][OP] roi_align operator alter layout
  python/tvm/relay/op/strategy/cuda.py
  python/tvm/relay/op/strategy/generic.py
  python/tvm/relay/op/strategy/x86.py
  python/tvm/relay/op/vision/_rcnn.py
  src/relay/op/vision/rcnn_op.cc
  tests/python/relay/test_pass_convert_op_layout.py
Labels: status: review in progress

#6302 [tvmc] command line driver 'compile' (part 2/4)
  python/setup.py
  python/tvm/driver/tvmc/__init__.py
  python/tvm/driver/tvmc/__main__.py
  python/tvm/driver/tvmc/common.py
  python/tvm/driver/tvmc/compiler.py
  python/tvm/driver/tvmc/frontends.py
  tests/python/driver/tvmc/conftest.py
  tests/python/driver/tvmc/test_common.py
  tests/python/driver/tvmc/test_compiler.py
  tests/python/driver/tvmc/test_frontends.py
  tests/scripts/task_python_integration.sh
Labels: status: review in progress

#6428 [TOPI] Fix declaration_conv2d_transpose_impl
  python/tvm/topi/nn/conv2d_transpose.py
  tests/python/topi/python/test_topi_conv2d_transpose_nchw.py
Labels: status: need update

#6513 bugfix in BinaryBroadcastLayout + unit test
  src/relay/transforms/infer_layout_util.h
  tests/python/relay/test_pass_convert_op_layout.py
Labels: status: need review

#6456 Enable more warnings when compiling with clang 10.0 or greater
  CMakeLists.txt
  cmake/modules/ClangFlags.cmake
  include/tvm/auto_scheduler/cost_model.h
  include/tvm/ir/attrs.h
  include/tvm/node/container.h
  include/tvm/relay/analysis.h
  include/tvm/topi/nn/pooling.h
  src/arith/const_int_bound.cc
  src/node/attr_registry.h
  src/node/structural_hash.cc
  src/parser/diagnostic.h
  src/relay/backend/graph_plan_memory.cc
  src/relay/transforms/annotate_target.cc
  src/relay/transforms/gradient.cc
  src/relay/transforms/partition_graph.cc
  src/runtime/c_runtime_api.cc
  src/runtime/library_module.cc
  src/support/socket.h
  src/tir/transforms/lower_custom_datatypes.cc
  src/topi/schedule.cc
Labels: status: accepted

#6510 [TOPI] Group conv2d NHWC op implementation
  python/tvm/relay/op/strategy/arm_cpu.py
  python/tvm/relay/op/strategy/generic.py
  python/tvm/relay/op/strategy/x86.py
  python/tvm/topi/generic/nn.py
  python/tvm/topi/nn/conv2d.py
  tests/python/topi/python/test_topi_group_conv2d.py
Labels: status: need review

#6504 [Torch] Clean up usage of try ... infer_value() ... except
  python/tvm/relay/frontend/common.py
  python/tvm/relay/frontend/pytorch.py
Labels: status: need review

#6506 [BYOC][ACL] Add maximum support for float32
  docs/deploy/arm_compute_lib.rst
  python/tvm/relay/op/contrib/arm_compute_lib.py
  src/runtime/contrib/arm_compute_lib/acl_runtime.cc
  tests/python/contrib/test_arm_compute_lib/test_maximum.py
Labels: status: need update

#6429 [Relay/TOPI] Added 'offsets' and 'alignment' attributes to MATRIX_SET_DIAG.
  include/tvm/relay/attrs/transform.h
  include/tvm/topi/transform.h
  python/tvm/relay/op/transform.py
  python/tvm/topi/testing/matrix_set_diag.py
  python/tvm/topi/transform.py
  src/relay/op/tensor/transform.cc
  src/topi/transform.cc
  tests/python/relay/test_op_level10.py
  tests/python/topi/python/test_topi_transform.py
Labels: status: need review

#6541 Add alternate cublaslt library name. CUDA 11.0 uses cublasLt.
  cmake/util/FindCUDA.cmake
Labels: status: need review

#6522 Rename tvm.hybrid.script to tvm.script.
  docs/dev/hybrid_script.rst
  python/tvm/__init__.py
  python/tvm/script/__init__.py
  python/tvm/script/_ffi_api.py
  python/tvm/script/intrin.py
  python/tvm/script/meta_unparser.py
  python/tvm/script/parser.py
  python/tvm/script/registry.py
  python/tvm/script/scope_emitter.py
  python/tvm/script/scope_handler.py
  python/tvm/script/special_stmt.py
  python/tvm/script/ty.py
  python/tvm/script/utils.py
  src/printer/tir_text_printer.cc
  src/printer/tvmscript_printer.cc
  src/tir/ir/stmt.cc
  tests/python/unittest/test_tvmscript_error_report.py
  tests/python/unittest/test_tvmscript_roundtrip.py
Labels: status: need update

#6542 [RELAY][MXNET][FRONTEND] Support "dot" and "LogisticRegressionOutput"
  python/tvm/relay/frontend/mxnet.py
  tests/python/frontend/mxnet/test_forward.py
Labels: status: need review

#6537 [tvmc] Introduce 'tune' subcommand (part 3/4)
  python/tvm/driver/tvmc/__init__.py
  python/tvm/driver/tvmc/autotuner.py
  python/tvm/driver/tvmc/common.py
  tests/python/driver/tvmc/test_autotuner.py
Labels: status: need update

#6560 [BYOC][ETHOSN] Fix tests for new module API
  src/runtime/contrib/ethosn/ethosn_device.cc
  tests/python/contrib/test_ethosn/infrastructure.py
  tests/python/contrib/test_ethosn/test_networks.py
  tests/python/contrib/test_ethosn/test_topologies.py
Labels: status: review in progress
