Repository apache/tvm, pull requests merged in 2020-05, with the labels that each got.

#5485 [TOPI][Winograd] Optimization of Conv2d Winograd algorithm on Tensor …
  python/tvm/relay/op/strategy/cuda.py
  topi/python/topi/cuda/__init__.py
  topi/python/topi/cuda/conv2d_alter_op.py
  topi/python/topi/cuda/conv2d_nhwc_winograd.py
  topi/tests/python/test_topi_conv2d_nhwc_winograd.py
Labels: status: need review

#5453 [RELAY][ONNX]ReduceLogSumExp Operator support
  python/tvm/relay/frontend/onnx.py
  python/tvm/relay/op/reduce.py
  tests/python/frontend/onnx/test_forward.py
  tests/python/relay/test_op_level4.py
Labels: status: need review

#5479 [Relay-TFLite] FP32 and Quantized Object Detection Model
  python/tvm/relay/frontend/tflite.py
  python/tvm/relay/frontend/tflite_flexbuffer.py
  python/tvm/relay/testing/tf.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#5535 Changes to cpp_rpc to make it work on Android (+ Hexagon offloading)
  apps/cpp_rpc/rpc_env.cc
  apps/cpp_rpc/rpc_server.cc
Labels: status: accepted

#5507 [CRT]fix to reduce RAM size during loading model
  src/runtime/crt/graph_runtime.c
Labels: status: need update

#5382 [TE] Fix MakeLoopNest for warp memory
  src/te/operation/op_util.cc
  tests/python/unittest/test_tir_transform_lower_warp_memory.py
Labels: status: need review

#5483 [TIR][Printer] text format printer considering future parsing use
  include/tvm/ir/module.h
  src/printer/meta_data.h
  src/printer/relay_text_printer.cc
  src/printer/text_printer.cc
  src/printer/text_printer.h
  src/printer/tir_text_printer.cc
  tests/python/unittest/test_arith_deduce_bound.py
  tests/python/unittest/test_te_schedule.py
  tests/python/unittest/test_tir_nodes.py
Labels: status: need review

#5498 [Optimization] Warp level reduction support for CUDA
  include/tvm/tir/expr.h
  src/target/source/codegen_cuda.cc
  src/target/source/codegen_cuda.h
  src/target/source/intrin_rule_cuda.cc
  src/target/source/intrin_rule_opencl.cc
  src/target/source/literal/cuda_half_t.h
  src/tir/transforms/lower_thread_allreduce.cc
  src/tir/transforms/lower_warp_memory.cc
  tests/python/integration/test_reduce.py
Labels: status: need review

#5502 [TOPI][RELAY][TENSORFLOW]Math ops added
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/op/_tensor.py
  python/tvm/relay/op/_tensor_grad.py
  python/tvm/relay/op/tensor.py
  python/tvm/te/__init__.py
  src/relay/op/tensor/unary.cc
  tests/python/frontend/tensorflow/test_forward.py
  tests/python/relay/test_op_grad_level1.py
  topi/include/topi/elemwise.h
  topi/python/topi/math.py
  topi/src/elemwise.cc
Labels: status: need review

#5492 [RUNTIME] Hexagon driver for offloading kernels to simulator
  cmake/modules/Hexagon.cmake
  src/runtime/hexagon/sim/driver/CMakeLists.txt
  src/runtime/hexagon/sim/driver/README.md
  src/runtime/hexagon/sim/driver/fake_pthread.cc
  src/runtime/hexagon/sim/driver/pthread.h
  src/runtime/hexagon/sim/driver/sched.h
  src/runtime/hexagon/sim/driver/sim_device.cc
  src/runtime/threading_backend.cc
Labels: status: need review

#5357 [Relay] enable blocking format in x86 conv2d and fold scale axis
  python/tvm/relay/op/strategy/x86.py
  src/relay/op/tensor/transform.h
  src/relay/transforms/fold_scale_axis.cc
  tests/python/relay/test_pass_fold_scale_axis.py
  topi/python/topi/x86/conv2d_alter_op.py
Labels: status: need review

#5586 [Autotvm]Fix the runtime raise error
  python/tvm/autotvm/measure/measure_methods.py
Labels: status: need review

#5422 [RELAY][Convert Layout] Specify additional layouts in convert layout pass
  docs/dev/convert_layout.rst
  include/tvm/relay/op_attr_types.h
  include/tvm/relay/transform.h
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/qnn/op/layout_conversions.py
  python/tvm/relay/transform/transform.py
  src/relay/transforms/convert_layout.cc
  tests/python/relay/test_pass_convert_op_layout.py
Labels: status: need review, status: need update

#5144 [Relay][VM] Memory planner (part 1)
  include/tvm/runtime/ndarray.h
  include/tvm/runtime/vm.h
  python/tvm/relay/__init__.py
  python/tvm/relay/expr.py
  python/tvm/relay/op/memory/memory.py
  python/tvm/relay/transform/__init__.py
  python/tvm/relay/transform/memory_alloc.py
  python/tvm/relay/transform/memory_plan.py
  src/relay/backend/vm/compiler.cc
  src/relay/op/memory/memory.cc
  src/runtime/ndarray.cc
  src/runtime/vm/executable.cc
  src/runtime/vm/memory_manager.cc
  src/runtime/vm/vm.cc
  tests/python/frontend/onnx/test_forward.py
  tests/python/relay/test_memory_passes.py
Labels: status: need update

#5231 Pattern Language, Matcher, Rewriter, and Function Paritioner
  docs/langref/index.rst
  docs/langref/relay_pattern.rst
  include/tvm/relay/dataflow_matcher.h
  include/tvm/relay/dataflow_pattern.h
  include/tvm/relay/dataflow_pattern_functor.h
  python/tvm/relay/dataflow_pattern/__init__.py
  python/tvm/relay/dataflow_pattern/_ffi.py
  src/relay/ir/dataflow_matcher.cc
  src/relay/ir/dataflow_pattern.cc
  src/relay/ir/dataflow_pattern_functor.cc
  src/relay/ir/expr_functor.cc
  src/relay/ir/indexed_graph.cc
  src/relay/ir/indexed_graph.h
  tests/python/relay/test_dataflow_pattern.py
Labels: status: need review

#5598 [LLVM] Represent alignment information in LLVM IR
  src/target/llvm/codegen_cpu.cc
  src/target/llvm/codegen_llvm.cc
  tests/python/unittest/test_target_codegen_llvm.py
Labels: status: need review

#5581 Add debug mode to tempdir()
  python/tvm/contrib/util.py
  tests/python/contrib/test_util.py
Labels: status: need update

#5508 [TFLITE]GATHER_ND
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#5606 [CUDA] Fix codegen for warp shuffle intrinsics
  src/target/source/intrin_rule_cuda.cc
  tests/python/unittest/test_tir_transform_lower_warp_memory.py
Labels: status: need review, status: need test case

#5098 [KERAS]Global MaxPool3d and AvgPool3d support
  python/tvm/relay/frontend/keras.py
  python/tvm/relay/op/nn/nn.py
  tests/python/frontend/keras/test_forward.py
Labels: status: need review, status: need update

#5588 [Frontend][Tensorflow] Gather nd bug fix for one dim support in tensorflow
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/op/op_attrs.py
  src/relay/op/tensor/transform.cc
  tests/python/frontend/mxnet/test_forward.py
  tests/python/frontend/tensorflow/test_forward.py
  tests/python/frontend/tflite/test_forward.py
  topi/include/topi/transform.h
Labels: status: need update

#5657 [Relay,Topi][OP] affine_grid and grid_sample
  include/tvm/relay/attrs/image.h
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/op/image/_image.py
  python/tvm/relay/op/image/image.py
  src/relay/op/image/grid_sample.cc
  tests/python/frontend/mxnet/test_forward.py
  tests/python/relay/test_op_level5.py
  topi/python/topi/image/__init__.py
  topi/python/topi/image/grid_sample.py
  topi/python/topi/testing/__init__.py
  topi/python/topi/testing/grid_sample_python.py
  topi/tests/python/test_topi_image.py
Labels: status: need review

#5600 [TOPI] Improve CUDA softmax scheduling
  src/target/llvm/codegen_llvm.cc
  src/target/llvm/llvm_common.h
  src/tir/transforms/lower_warp_memory.cc
  tests/python/unittest/test_tir_transform_lower_warp_memory.py
  topi/python/topi/cuda/softmax.py
Labels: status: need review

#5659 [TARGET] enable amd_apu device on vulkan target
  apps/benchmark/gpu_imagenet_bench.py
  python/tvm/autotvm/measure/measure_methods.py
  python/tvm/autotvm/tophub.py
  src/runtime/vulkan/vulkan.cc
Labels: status: need review

#5511 [AutoTVM][TOPI] AutoTVM incorrect measurement
  topi/python/topi/mali/conv2d.py
Labels: status: need review

#5596 [TIR][REFACTOR] std::string -> String Migration in TIR nodes
  include/tvm/tir/stmt.h
  include/tvm/tir/var.h
  python/tvm/ir/json_compact.py
  src/printer/tir_text_printer.cc
  src/tir/ir/data_layout.cc
  src/tir/ir/expr.cc
Labels: status: need review

#5684 [AutoTVM][TOPI] Fix bifrost spatial packing conv2d auto tune
  topi/python/topi/arm_cpu/conv2d.py
  topi/python/topi/arm_cpu/conv2d_spatial_pack.py
  topi/python/topi/bifrost/conv2d.py
  topi/python/topi/mali/conv2d.py
Labels: status: need update
