Repository apache/tvm, pull requests merged in 2020-01, with the labels that each got.

#4610 [TOPI, Relay] Add half_pixel option to Resize op
  include/tvm/relay/attrs/image.h
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/frontend/onnx.py
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/frontend/tflite.py
  python/tvm/relay/op/image/_image.py
  python/tvm/relay/op/image/image.py
  src/relay/op/image/resize.cc
  tests/python/frontend/onnx/test_forward.py
  tests/python/relay/test_op_level5.py
  topi/python/topi/image/resize.py
  topi/python/topi/nn/upsampling.py
  topi/python/topi/testing/bilinear_resize_python.py
  topi/tests/python/test_topi_resize.py
  topi/tests/python/test_topi_upsampling.py
Labels: status: accepted

#4589 [Quantization] Make calibration faster and more memory usage friendly
  python/tvm/relay/quantize/_calibrate.py
  python/tvm/relay/quantize/kl_divergence.py
  python/tvm/relay/quantize/quantize.py
  src/relay/pass/quantize/calibrate.cc
  src/relay/pass/quantize/quantize.h
  tests/python/relay/test_pass_auto_quantize.py
Labels: status: need review

#4616 [REFACTOR] Initialize Unified IR Type Data Structures
  CMakeLists.txt
  include/tvm/ir/span.h
  include/tvm/ir/type.h
  include/tvm/relay/base.h
  include/tvm/relay/type.h
  src/ir/span.cc
  src/ir/type.cc
  src/relay/ir/base.cc
  src/relay/ir/hash.cc
  src/relay/ir/module.cc
  src/relay/ir/type.cc
  tests/cpp/relay_pass_type_infer_test.cc
Labels: status: need review

#4624 Added declare of aluBits for TensorAlu
  vta/hardware/chisel/src/main/scala/core/TensorAlu.scala
Labels: status: need review

#4630 [FRONTEND][Keras] Add support for tf.Keras networks in Relay Keras frontend
  python/tvm/relay/frontend/keras.py
  tests/python/frontend/keras/test_forward.py
Labels: status: need review

#4663 [Relay/Topi][Op] 1D Pooling
  include/tvm/relay/attrs/nn.h
  python/tvm/relay/frontend/onnx.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  python/tvm/relay/op/op_attrs.py
  src/relay/op/nn/pooling.cc
  tests/python/frontend/onnx/test_forward.py
  tests/python/relay/test_op_level2.py
  topi/include/topi/nn/pooling.h
  topi/python/topi/nn/pooling.py
  topi/python/topi/testing/__init__.py
  topi/python/topi/testing/pool1d_python.py
  topi/src/topi.cc
  topi/tests/python/test_topi_pooling.py
Labels: status: need review

#4634 [Relay][Frontend][TFlite] Add parses support for unary elemwise ops
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#4656 fix topi.nn.global_pool layout="NHWC"
  topi/src/topi.cc
  topi/tests/python/test_topi_pooling.py
Labels: status: need test case

#4502 [Relay][Frontend][TFlite] Add parses support for SLICE
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need update

#4643 [REFACTOR] Replace TensorObj and TensorValue with NDArray
  docs/api/python/dev.rst
  docs/dev/codebase_walkthrough.rst
  include/tvm/relay/interpreter.h
  include/tvm/runtime/vm.h
  python/tvm/__init__.py
  python/tvm/_ffi/_ctypes/function.py
  python/tvm/_ffi/_ctypes/object.py
  python/tvm/_ffi/_cython/function.pxi
  python/tvm/_ffi/_cython/object.pxi
  python/tvm/_ffi/function.py
  python/tvm/_ffi/node.py
  python/tvm/_ffi/object.py
  python/tvm/_ffi/object_generic.py
  python/tvm/api.py
  python/tvm/arith.py
  python/tvm/attrs.py
  python/tvm/build_module.py
  python/tvm/container.py
  python/tvm/expr.py
  python/tvm/ir_builder.py
  python/tvm/object.py
  python/tvm/relay/_module.pyi
  python/tvm/relay/adt.py
  python/tvm/relay/backend/compile_engine.py
  python/tvm/relay/backend/interpreter.py
  python/tvm/relay/backend/vm.py
  python/tvm/relay/backend/vmobj.py
  python/tvm/relay/base.py
  python/tvm/relay/expr.pyi
  python/tvm/relay/quantize/quantize.py
  python/tvm/relay/testing/py_converter.py
  python/tvm/relay/transform.pyi
  python/tvm/relay/ty.pyi
  python/tvm/schedule.py
  python/tvm/stmt.py
  python/tvm/target.py
  python/tvm/tensor.py
  python/tvm/tensor_intrin.py
  src/relay/backend/interpreter.cc
  src/relay/backend/vm/compiler.cc
  src/relay/pass/fold_constant.cc
  src/relay/pass/partial_eval.cc
  src/runtime/vm/executable.cc
  src/runtime/vm/object.cc
  src/runtime/vm/vm.cc
  tests/python/frontend/tensorflow/test_control_flow.py
  tests/python/frontend/tensorflow/test_forward.py
  tests/python/relay/test_adt.py
  tests/python/relay/test_backend_interpreter.py
  tests/python/relay/test_py_converter.py
  tests/python/relay/test_vm.py
  tests/python/relay/test_vm_object.py
  tests/python/unittest/test_pass_inject_double_buffer.py
  tests/python/unittest/test_pass_inject_vthread.py
  tests/python/unittest/test_pass_storage_flatten.py
Labels: status: need review

#4678 [REFACTOR][IR] Allow Module to store BaseFunc
  include/tvm/relay/module.h
  src/relay/backend/build_module.cc
  src/relay/backend/vm/compiler.cc
  src/relay/backend/vm/inline_primitives.cc
  src/relay/backend/vm/lambda_lift.cc
  src/relay/ir/module.cc
  src/relay/ir/pretty_printer.cc
  src/relay/pass/eta_expand.cc
  src/relay/pass/fold_constant.cc
  src/relay/pass/gradient.cc
  src/relay/pass/partial_eval.cc
  src/relay/pass/pass_manager.cc
  src/relay/pass/quantize/realize.cc
  src/relay/pass/to_cps.cc
  tests/cpp/relay_transform_sequential.cc
Labels: status: need review

#4667 [Tutorial] Deploy Quantized Model on CUDA
  tutorials/frontend/deploy_quantized.py
Labels: status: need review

#4699 [REFACTOR][IR] Unified IR IRModule structure.
  docs/dev/relay_pass_infra.rst
  include/tvm/ir/module.h
  include/tvm/ir/type_relation.h
  include/tvm/ir_pass.h
  include/tvm/relay/analysis.h
  include/tvm/relay/base.h
  include/tvm/relay/error.h
  include/tvm/relay/feature.h
  include/tvm/relay/interpreter.h
  include/tvm/relay/transform.h
  src/ir/module.cc
  src/relay/backend/build_module.cc
  src/relay/backend/compile_engine.cc
  src/relay/backend/contrib/codegen_c/codegen.cc
  src/relay/backend/graph_runtime_codegen.cc
  src/relay/backend/interpreter.cc
  src/relay/backend/vm/compiler.cc
  src/relay/backend/vm/compiler.h
  src/relay/backend/vm/inline_primitives.cc
  src/relay/backend/vm/lambda_lift.cc
  src/relay/backend/vm/removed_unused_funcs.cc
  src/relay/ir/alpha_equal.cc
  src/relay/ir/error.cc
  src/relay/ir/pretty_printer.cc
  src/relay/op/tensor/transform.h
  src/relay/pass/alter_op_layout.cc
  src/relay/pass/canonicalize_cast.cc
  src/relay/pass/canonicalize_ops.cc
  src/relay/pass/combine_parallel_conv2d.cc
  src/relay/pass/combine_parallel_dense.cc
  src/relay/pass/combine_parallel_op_batch.cc
  src/relay/pass/convert_layout.cc
  src/relay/pass/dead_code.cc
  src/relay/pass/device_annotation.cc
  src/relay/pass/eliminate_common_subexpr.cc
  src/relay/pass/eta_expand.cc
  src/relay/pass/feature.cc
  src/relay/pass/fold_constant.cc
  src/relay/pass/fold_scale_axis.cc
  src/relay/pass/fuse_ops.cc
  src/relay/pass/gradient.cc
  src/relay/pass/kind_check.cc
  src/relay/pass/legalize.cc
  src/relay/pass/match_exhaustion.cc
  src/relay/pass/partial_eval.cc
  src/relay/pass/pass_manager.cc
  src/relay/pass/print_ir.cc
  src/relay/pass/quantize/annotate.cc
  src/relay/pass/quantize/partition.cc
  src/relay/pass/quantize/realize.cc
  src/relay/pass/simplify_inference.cc
  src/relay/pass/to_a_normal_form.cc
  src/relay/pass/to_cps.cc
  src/relay/pass/to_graph_normal_form.cc
  src/relay/pass/type_infer.cc
  src/relay/pass/type_solver.cc
  src/relay/pass/type_solver.h
  src/relay/pass/util.cc
  tests/cpp/relay_pass_type_infer_test.cc
  tests/cpp/relay_transform_sequential.cc
Labels: status: need review

#4702 [REFACTOR][IR] Initialize Unified IR Pass Infra
  include/tvm/ir/transform.h
  include/tvm/relay/transform.h
  src/ir/transform.cc
  src/relay/ir/transform.cc
Labels: status: need review

#4570 [relay] Relay annotation and partitioning for external compilers
  include/tvm/relay/attrs/annotation.h
  include/tvm/relay/op_attr_types.h
  include/tvm/relay/transform.h
  python/tvm/relay/op/annotation/annotation.py
  python/tvm/relay/transform.py
  src/relay/backend/contrib/dnnl/codegen.cc
  src/relay/op/annotation/annotation.cc
  src/relay/pass/fuse_ops.cc
  src/relay/pass/partition_graph.cc
  tests/python/relay/test_pass_partition_graph.py
Labels: status: api design review

#4705 [REFACTOR][IR] Polish ir/type
  include/tvm/ir/adt.h
  include/tvm/ir/env_func.h
  include/tvm/ir/expr.h
  include/tvm/ir/module.h
  include/tvm/ir/op.h
  include/tvm/ir/transform.h
  include/tvm/ir/type.h
  include/tvm/ir/type_relation.h
  include/tvm/relay/type.h
  src/api/api_test.cc
  src/ir/env_func.cc
  src/ir/type.cc
  src/ir/type_relation.cc
  src/relay/backend/compile_engine.cc
  src/relay/ir/expr.cc
  src/relay/ir/type.cc
  src/relay/ir/type_functor.cc
  src/relay/op/algorithm/topk.cc
  src/relay/op/memory/memory.cc
  src/relay/op/nn/nn.cc
  src/relay/op/nn/sparse.cc
  src/relay/op/tensor/transform.cc
  src/relay/op/vision/multibox_op.cc
  src/relay/op/vision/nms.cc
  src/relay/pass/de_duplicate.cc
  src/relay/pass/eta_expand.cc
  src/relay/pass/gradient.cc
  src/relay/pass/to_cps.cc
  src/relay/pass/type_infer.cc
  src/relay/pass/type_solver.cc
  tests/cpp/relay_pass_type_infer_test.cc
Labels: status: need review

#4666 [Relay][Frontend][TFLite] Add constant input support for elemwise ops
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#4709 [REFACTOR][IR] attrs.h -> ir
  include/tvm/expr_operator.h
  include/tvm/ir.h
  include/tvm/ir/attrs.h
  include/tvm/ir/expr.h
  include/tvm/ir/op.h
  include/tvm/ir/type_relation.h
  include/tvm/relay/adt.h
  include/tvm/relay/attrs/algorithm.h
  include/tvm/relay/attrs/annotation.h
  include/tvm/relay/attrs/bitserial.h
  include/tvm/relay/attrs/debug.h
  include/tvm/relay/attrs/device_copy.h
  include/tvm/relay/attrs/image.h
  include/tvm/relay/attrs/memory.h
  include/tvm/relay/attrs/nn.h
  include/tvm/relay/attrs/reduce.h
  include/tvm/relay/attrs/transform.h
  include/tvm/relay/attrs/vision.h
  include/tvm/relay/expr.h
  include/tvm/relay/qnn/attrs.h
  include/tvm/relay/type.h
  src/api/api_ir.cc
  src/api/api_pass.cc
  src/api/api_test.cc
  src/arithmetic/const_fold.h
  src/autotvm/touch_extractor.cc
  src/codegen/llvm/codegen_x86_64.cc
  src/ir/attr_functor.h
  src/ir/attrs.cc
  src/ir/expr.cc
  src/ir/op.cc
  src/lang/expr.cc
  src/lang/expr_operator.cc
  src/lang/ir.cc
  src/node/reflection.cc
  src/node/serialization.cc
  src/pass/storage_access.h
  src/relay/ir/alpha_equal.cc
  src/relay/ir/hash.cc
  src/relay/ir/pretty_printer.cc
  tests/cpp/attrs_test.cc
Labels: status: need review

#4721 [REFACTOR] Introduce include/tvm/target
  .gitignore
  CMakeLists.txt
  include/tvm/build_module.h
  include/tvm/target/target.h
  include/tvm/target/target_info.h
  src/codegen/build_module.cc
  src/pass/storage_access.cc
  src/pass/storage_flatten.cc
  src/pass/storage_rewrite.cc
  src/pass/tensor_core.cc
  src/target/target.cc
  src/target/target_info.cc
Labels: status: need review

#4652 [Relay][Frontend][TFLite] Add parser support for squared difference
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need update

#4602 [Docs] Bring Your Own Codegen Guide -- Part 1
  docs/dev/index.rst
  docs/dev/relay_bring_your_own_codegen.rst
Labels: status: need review

#4664 [Docs] Convert Layout pass.
  docs/dev/convert_layout.rst
  docs/dev/index.rst
Labels: status: need review

#4723 [Relay] Invoke tvm::build from relay compile_engine and interpreter
  src/relay/backend/compile_engine.cc
  src/relay/backend/interpreter.cc
Labels: status: need review

#4407 [VTA][TSIM] Enable TSIM CI Testing
  Makefile
  tests/scripts/task_python_vta.sh
  tests/scripts/task_python_vta_fsim.sh
  tests/scripts/task_python_vta_tsim.sh
  vta/hardware/chisel/Makefile
  vta/hardware/chisel/src/main/scala/core/LoadUop.scala
  vta/hardware/dpi/tsim_device.cc
  vta/tutorials/frontend/deploy_vision_on_vta.py
Labels: status: need review

#4736 [CodeGen][CUDA] Improve CUDA vectorizer
  include/tvm/runtime/data_type.h
  src/codegen/codegen_cuda.cc
  src/codegen/literal/cuda_half_t.h
  tests/python/unittest/test_codegen_cuda.py
Labels: status: need review

#4693 [runtime][refactor] Unify vm and interpreter objects
  apps/lldb/tvm.py
  include/tvm/relay/interpreter.h
  include/tvm/runtime/object.h
  include/tvm/runtime/vm.h
  python/tvm/container.py
  python/tvm/relay/__init__.py
  python/tvm/relay/backend/_vmobj.py
  python/tvm/relay/backend/interpreter.py
  python/tvm/relay/backend/vm.py
  python/tvm/relay/backend/vmobj.py
  python/tvm/relay/frontend/common.py
  python/tvm/relay/testing/__init__.py
  python/tvm/relay/testing/py_converter.py
  src/relay/backend/interpreter.cc
  src/relay/pass/fold_constant.cc
  src/relay/pass/partial_eval.cc
  src/runtime/container.cc
  src/runtime/vm/vm.cc
  tests/python/frontend/tensorflow/test_forward.py
  tests/python/relay/benchmarking/benchmark_vm.py
  tests/python/relay/test_adt.py
  tests/python/relay/test_backend_interpreter.py
  tests/python/relay/test_py_converter.py
  tests/python/relay/test_vm.py
  tests/python/relay/test_vm_object.py
  tests/python/unittest/test_container.py
Labels: status: accepted

#4746 [REFACTOR][TYPE] Finish move all types to IR.
  include/tvm/ir/tensor_type.h
  include/tvm/ir/type.h
  include/tvm/ir/type_functor.h
  include/tvm/relay/type.h
  include/tvm/runtime/object.h
  src/ir/tensor_type.cc
  src/ir/type.cc
  src/ir/type_functor.cc
  src/relay/backend/compile_engine.cc
  src/relay/backend/interpreter.cc
  src/relay/ir/alpha_equal.cc
  src/relay/ir/expr.cc
  src/relay/ir/expr_functor.cc
  src/relay/ir/hash.cc
  src/relay/ir/pretty_printer.cc
  src/relay/op/algorithm/argsort.cc
  src/relay/op/algorithm/topk.cc
  src/relay/op/image/resize.cc
  src/relay/op/memory/memory.cc
  src/relay/op/nn/bitserial.cc
  src/relay/op/nn/convolution.cc
  src/relay/op/nn/convolution.h
  src/relay/op/nn/nn.cc
  src/relay/op/nn/nn.h
  src/relay/op/nn/pad.cc
  src/relay/op/nn/pooling.cc
  src/relay/op/nn/sparse.cc
  src/relay/op/nn/upsampling.cc
  src/relay/op/tensor/reduce.cc
  src/relay/op/tensor/transform.cc
  src/relay/op/tensor/transform.h
  src/relay/op/tensor/unary.cc
  src/relay/op/type_relations.cc
  src/relay/op/vision/multibox_op.cc
  src/relay/op/vision/nms.cc
  src/relay/op/vision/rcnn_op.cc
  src/relay/op/vision/yolo.cc
  src/relay/pass/de_duplicate.cc
  src/relay/pass/eta_expand.cc
  src/relay/pass/gradient.cc
  src/relay/pass/kind_check.cc
  src/relay/pass/partial_eval.cc
  src/relay/pass/quantize/quantize.cc
  src/relay/pass/to_cps.cc
  src/relay/pass/type_infer.cc
  src/relay/pass/type_solver.cc
  src/relay/pass/util.cc
  src/relay/qnn/op/dequantize.cc
  src/relay/qnn/op/quantize.cc
  src/relay/qnn/op/requantize.cc
  src/relay/qnn/util.h
  tests/cpp/relay_build_module_test.cc
  tests/cpp/relay_pass_type_infer_test.cc
  tests/cpp/relay_transform_sequential.cc
  tests/cpp/utvm_runtime_standalone_test.cc
  tests/python/frontend/mxnet/test_forward.py
Labels: status: need review

#4752 [REFACTOR] Establish printer in the source folder
  CMakeLists.txt
  apps/lldb/tvm.py
  include/tvm/ir/module.h
  include/tvm/node/functor.h
  include/tvm/node/node.h
  include/tvm/node/repr_printer.h
  include/tvm/relay/expr.h
  src/arith/const_int_bound.cc
  src/arith/int_set.cc
  src/arith/modular_set.cc
  src/ir/adt.cc
  src/ir/attrs.cc
  src/ir/env_func.cc
  src/ir/error.cc
  src/ir/expr.cc
  src/ir/module.cc
  src/ir/op.cc
  src/ir/span.cc
  src/ir/tensor_type.cc
  src/ir/transform.cc
  src/ir/type.cc
  src/ir/type_relation.cc
  src/node/repr_printer.cc
  src/printer/doc.cc
  src/printer/doc.h
  src/printer/meta_data.h
  src/printer/relay_text_printer.cc
  src/relay/backend/interpreter.cc
  src/relay/ir/adt.cc
  src/relay/ir/doc.cc
  src/relay/ir/doc.h
  src/relay/ir/expr.cc
  src/relay/ir/transform.cc
  src/relay/pass/fuse_ops.cc
  src/relay/pass/quantize/quantize.cc
  src/target/generic_func.cc
  src/target/target.cc
  src/target/target_info.cc
  src/tir/ir/buffer.cc
  src/tir/ir/data_layout.cc
  src/tir/ir/expr.cc
  src/tir/ir/lowered_func.cc
  src/tir/ir/stmt.cc
  src/top/operation/compute_op.cc
  src/top/operation/extern_op.cc
  src/top/operation/hybrid_op.cc
  src/top/operation/placeholder_op.cc
  src/top/operation/scan_op.cc
  src/top/operation/tensor_compute_op.cc
  src/top/schedule/schedule_lang.cc
  src/top/tensor.cc
Labels: status: need review

#4760 [REFACTOR] driver.h -> driver_api.h
  include/tvm/driver/driver_api.h
  src/README.md
  src/api/api_lang.cc
  src/driver/driver_api.cc
  src/relay/backend/build_module.cc
  src/relay/backend/compile_engine.cc
  src/relay/backend/interpreter.cc
  src/relay/backend/utils.h
  src/relay/backend/vm/compiler.cc
  tests/cpp/build_module_test.cc
  tests/cpp/relay_build_module_test.cc
  tests/cpp/relay_transform_sequential.cc
  tests/cpp/utvm_runtime_standalone_test.cc
Labels: status: need review

#4738 Fix padding in pooling op
  src/relay/op/nn/pooling.cc
  tests/python/relay/test_op_level2.py
  topi/python/topi/testing/pool3d_python.py
Labels: status: need review, status: need test case

#4703 [VTA] Support network which have no unique operator as start/stop name for graph pack.
  vta/python/vta/top/graphpack.py
Labels: status: need review

#4518 [Bugfix][Frontend][TF] Fix incorrect calculations in tf SLICE
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need update

#4695 [Relay][Frontend][TFlite] Add parser support for relational ops
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need update

#4795 [Relay][Topi] Use SimplifyInference for L2 Normalization.
  python/tvm/relay/op/nn/_nn.py
  src/relay/pass/pattern_util.h
  src/relay/pass/simplify_inference.cc
  topi/include/topi/cuda/normalization.h
  topi/include/topi/nn/l2_normalize.h
  topi/include/topi/rocm/normalization.h
  topi/python/topi/cuda/__init__.py
  topi/python/topi/cuda/nn.py
  topi/python/topi/generic/nn.py
  topi/python/topi/nn/__init__.py
  topi/python/topi/nn/l2_normalize.py
  topi/python/topi/rocm/nn.py
  topi/src/topi.cc
  topi/tests/python/test_topi_l2norm.py
Labels: status: need review
