Repository apache/tvm, pull requests merged in 2020-04, with the labels that each got.

#5175 [BUGFIX]bugfix in tensorflow space_to_batch_nd
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need test case

#5092 [TIR][PASS] dtype rewrite for indexing variables
  include/tvm/arith/analyzer.h
  include/tvm/tir/ir_pass.h
  include/tvm/tir/transform.h
  python/tvm/driver/build_module.py
  python/tvm/tir/expr.py
  python/tvm/tir/ir_builder.py
  python/tvm/tir/transform/transform.py
  src/arith/const_int_bound.cc
  src/target/llvm/codegen_cpu.cc
  src/target/llvm/codegen_llvm.cc
  src/tir/ir/buffer.cc
  src/tir/pass/ffi_api.cc
  src/tir/pass/loop_partition.cc
  src/tir/pass/unroll_loop.cc
  src/tir/transforms/narrow_datatype.cc
  tests/python/unittest/test_tir_transform_narrow_datatype.py
Labels: status: need review, status: need update

#5209 [CodeGen][CUDA] Fix bugs
  src/target/source/codegen_cuda.cc
  src/target/source/codegen_cuda.h
  tests/python/unittest/test_target_codegen_cuda.py
Labels: status: need review

#5125 [KERAS]Upsample3d & ZeroPadding3d op
  python/tvm/relay/frontend/keras.py
  tests/python/frontend/keras/test_forward.py
Labels: status: need review

#4886 [RELAY] Non-recursive Graph Vistor and Rewriter
  include/tvm/relay/analysis.h
  include/tvm/relay/expr_functor.h
  src/relay/analysis/util.cc
  src/relay/ir/expr_functor.cc
  src/relay/transforms/canonicalize_ops.cc
  src/relay/transforms/dead_code.cc
  src/relay/transforms/fast_math.cc
  src/relay/transforms/forward_rewrite.cc
  src/relay/transforms/pass_util.h
  tests/cpp/relay_build_module_test.cc
Labels: status: need review, status: need update

#5193 [TE] Support mixing normal and cross-thread reduction
  src/te/operation/compute_op.cc
  src/te/operation/cross_thread_reduction.cc
  tests/python/unittest/test_target_codegen_cuda.py
Labels: status: need review

#5135 [ONNX]Pool3d & upsample3d op support
  python/tvm/relay/frontend/onnx.py
  tests/python/frontend/onnx/test_forward.py
Labels: status: review in progress

#5103 [Relay][ADT]Static Tensor Array
  python/tvm/relay/prelude.py
  tests/python/relay/test_adt.py
Labels: status: need review

#5237 [Fix][VM] Fix copy constructor
  src/runtime/vm/vm.cc
Labels: status: need review

#5186 [Relay][Topi][AutoTVM] Winograd support for Conv3D
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/nn.h
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  python/tvm/relay/op/nn/util.py
  python/tvm/relay/op/op_attrs.py
  python/tvm/relay/op/strategy/cuda.py
  python/tvm/relay/op/strategy/generic.py
  src/relay/op/nn/convolution.cc
  src/relay/op/nn/convolution.h
  tests/python/relay/test_op_level2.py
  topi/python/topi/cuda/__init__.py
  topi/python/topi/cuda/conv3d_alter_op.py
  topi/python/topi/cuda/conv3d_winograd.py
  topi/python/topi/generic/nn.py
  topi/python/topi/nn/conv3d.py
  topi/tests/python/test_topi_conv3d_winograd.py
Labels: status: need review

#4459 [RUNTIME] Implement TVMDSOOp(TensorFlow custom op) for TVM runtime
  CMakeLists.txt
  apps/tf_tvmdsoop/CMakeLists.txt
  apps/tf_tvmdsoop/prepare_and_test_tfop_module.sh
  apps/tf_tvmdsoop/tests/test_tfop_module.py
  cmake/config.cmake
  cmake/modules/contrib/TF_TVMDSOOP.cmake
  python/tvm/contrib/tf_op/__init__.py
  python/tvm/contrib/tf_op/module.py
  src/contrib/tf_op/tvm_dso_op_kernels.cc
  src/contrib/tf_op/tvm_dso_ops.cc
  tests/scripts/task_python_integration.sh
Labels: status: need review, status: need test case, status: need update

#5190 Create loops according to storage scope and thread hierarchies
  src/te/operation/op_util.cc
  tests/python/unittest/test_te_schedule_ops.py
Labels: status: need review

#5180 [TENSORFLOW]reduce ops updated
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#5296 Legalize - Use Non-recursive Rewriter.
  include/tvm/relay/expr_functor.h
  src/relay/transforms/legalize.cc
Labels: status: need review

#5252 [RUNTIME] Initial implementation of Hexagon runtime support
  CMakeLists.txt
  cmake/config.cmake
  cmake/modules/Hexagon.cmake
  include/tvm/runtime/c_runtime_api.h
  include/tvm/runtime/device_api.h
  include/tvm/target/target.h
  jvm/core/src/main/java/org/apache/tvm/TVMContext.java
  python/tvm/__init__.py
  python/tvm/_ffi/runtime_ctypes.py
  python/tvm/runtime/ndarray.py
  python/tvm/target/__init__.py
  python/tvm/target/target.py
  src/runtime/hexagon/README.md
  src/runtime/hexagon/hexagon_device_api.cc
  src/runtime/hexagon/hexagon_module.cc
  src/runtime/hexagon/hexagon_module.h
  src/runtime/hexagon/hexagon_posix.cc
  src/runtime/hexagon/sim/hexagon_device_sim.cc
  src/runtime/hexagon/sim/hexagon_sim_proto.h
  src/runtime/hexagon/target/fastrpc/tvm_hexagon_remote.h
  src/runtime/hexagon/target/fastrpc/tvm_hexagon_remote_nd.h
  src/runtime/hexagon/target/hexagon_device_target.cc
  src/runtime/hexagon/target/hexagon_dsprpcapi.cc
  src/runtime/hexagon/target/hexagon_dsprpcapi.h
  src/runtime/hexagon/target/hexagon_stubapi.cc
  src/runtime/hexagon/target/hexagon_stubapi.h
  src/runtime/hexagon/target/hexagon_target_log.h
  src/target/opt/build_hexagon_off.cc
  src/target/target.cc
Labels: status: need review

#5171 [Arith] linear system and equation solver
  include/tvm/arith/analyzer.h
  include/tvm/arith/int_solver.h
  include/tvm/arith/util.h
  python/tvm/arith/__init__.py
  python/tvm/arith/int_solver.py
  src/arith/analyzer.cc
  src/arith/int_constraints.cc
  src/arith/solve_linear_equation.cc
  src/arith/util.cc
  tests/python/unittest/test_arith_solve_linear_system.py
Labels: status: need review

#5243 [Frontend][TensorFlow]Improve TensorFlow Static Shape Tensor Array
  python/tvm/relay/frontend/common.py
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/prelude.py
  tests/python/frontend/tensorflow/test_forward.py
  topi/python/topi/util.py
Labels: status: need review

#5137 [Rust][CI] Restore Rust CI
  rust/.rustfmt.toml
  rust/common/src/lib.rs
  rust/common/src/packed_func.rs
  rust/frontend/src/context.rs
  rust/frontend/src/function.rs
  rust/frontend/src/lib.rs
  rust/frontend/src/module.rs
  rust/frontend/src/ndarray.rs
  rust/frontend/src/value.rs
  rust/frontend/tests/callback/src/bin/array.rs
  rust/macros/src/lib.rs
  rust/runtime/src/module/syslib.rs
  rust/runtime/src/threading.rs
  rust/runtime/tests/build_model.py
  rust/runtime/tests/test_graph_serde.rs
  rust/runtime/tests/test_nn/build.rs
  rust/runtime/tests/test_nn/src/build_test_graph.py
  rust/runtime/tests/test_nn/src/main.rs
  tests/scripts/task_rust.sh
Labels: status: need update

#5246 [Frontend|MXNet] SwapAxis operator support
  python/tvm/relay/frontend/mxnet.py
  tests/python/frontend/mxnet/test_forward.py
Labels: status: need update

#4857 Windows Support for cpp_rpc
  CMakeLists.txt
  apps/cpp_rpc/CMakeLists.txt
  apps/cpp_rpc/README.md
  apps/cpp_rpc/main.cc
  apps/cpp_rpc/rpc_env.cc
  apps/cpp_rpc/rpc_env.h
  apps/cpp_rpc/rpc_server.cc
  apps/cpp_rpc/rpc_server.h
  apps/cpp_rpc/win32_process.cc
  apps/cpp_rpc/win32_process.h
  src/runtime/rpc/rpc_socket_impl.cc
  src/support/ring_buffer.h
Labels: status: need review

#5334 [TOPI] Using x86 schedules for ARM conv2d
  python/tvm/relay/op/strategy/arm_cpu.py
  topi/python/topi/arm_cpu/conv2d_alter_op.py
  topi/python/topi/x86/conv2d.py
Labels: status: need review

#5346 [Hexagon] Add hexagon_posix.cc to TVM/RT sources in the right place
  CMakeLists.txt
Labels: status: accepted

#5307 [TIR] Make lower_warp_memory support extent(threadIdx.x) < warp_size
  include/tvm/tir/expr.h
  src/target/source/intrin_rule_cuda.cc
  src/target/source/intrin_rule_opencl.cc
  src/tir/transforms/lower_warp_memory.cc
  tests/python/unittest/test_tir_transform_lower_warp_memory.py
Labels: status: need review

#5355 Factor out import of common tflite.Operator in tflite frontend.
  python/tvm/relay/frontend/tflite.py
Labels: status: need review

#5283 [RUNTIME][CONTRIB] CoreML Runtime
  CMakeLists.txt
  apps/ios_rpc/tvmrpc.xcodeproj/project.pbxproj
  apps/ios_rpc/tvmrpc/TVMRuntime.mm
  cmake/modules/contrib/CoreML.cmake
  python/tvm/contrib/coreml_runtime.py
  python/tvm/contrib/xcode.py
  src/runtime/contrib/coreml/coreml_runtime.h
  src/runtime/contrib/coreml/coreml_runtime.mm
  tests/python/contrib/test_coreml_runtime.py
Labels: status: need review

#4803 [Frontend] Asymmetric padding of convolution support
  python/tvm/relay/frontend/coreml.py
  python/tvm/relay/frontend/keras.py
  python/tvm/relay/frontend/tflite.py
Labels: status: need review

#5319 [cuDNN] Add cuDNN grouped convolution support
  python/tvm/contrib/cudnn.py
  python/tvm/relay/op/strategy/cuda.py
  src/runtime/contrib/cudnn/conv_forward.cc
  src/runtime/contrib/cudnn/cudnn_utils.h
  tests/python/contrib/test_cudnn.py
  topi/python/topi/cuda/conv2d.py
  topi/python/topi/testing/conv2d_nhwc_python.py
  topi/python/topi/testing/conv3d_ncdhw_python.py
  topi/tests/python/test_topi_conv2d_nchw.py
Labels: status: accepted

#4788 [FRONTEND][TFLITE]Gather, StridedSlice op support added
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review, status: need update

#5367 Improve IntervalSet's floormod
  include/tvm/arith/analyzer.h
  include/tvm/arith/int_set.h
  src/arith/analyzer.cc
  src/arith/const_int_bound.cc
  src/arith/int_set.cc
  src/te/operation/compute_op.cc
  src/te/schedule/bound.cc
  src/te/schedule/message_passing.cc
  tests/python/unittest/test_arith_intset.py
  tests/python/unittest/test_te_schedule_bound_inference_tiling.py
Labels: status: need review

#5331 [relay][topi] Add operation relay.nn.dilate() which calls topi.nn.dilate()
  include/tvm/relay/attrs/nn.h
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  python/tvm/relay/op/op_attrs.py
  src/relay/op/nn/nn.cc
  tests/python/relay/test_any.py
Labels: status: need review

#5454 Add RoiAlign to Onnx frontend
  python/tvm/relay/frontend/onnx.py
  src/relay/op/vision/rcnn_op.cc
  tests/python/frontend/onnx/test_forward.py
Labels: status: need review
