Repository apache/tvm, pull requests merged in 2020-07, with the labels that each got.

#5826 [DYNAMIC] Add Dynamic reshape to a dynamic namespace and add DynamicToStatic Pass
  include/tvm/relay/attrs/transform.h
  python/tvm/relay/__init__.py
  python/tvm/relay/_parser.py
  python/tvm/relay/op/_tensor_grad.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/dyn/__init__.py
  python/tvm/relay/op/dyn/_make.py
  python/tvm/relay/op/dyn/_transform.py
  python/tvm/relay/op/transform.py
  python/tvm/relay/transform/transform.py
  src/relay/analysis/util.cc
  src/relay/op/dyn/tensor/transform.cc
  src/relay/op/dyn/tensor/transform.h
  src/relay/op/tensor/transform.cc
  src/relay/op/tensor/transform.h
  src/relay/transforms/dynamic_to_static.cc
  src/relay/transforms/fold_scale_axis.cc
  src/relay/transforms/pattern_util.h
  tests/python/relay/dyn/test_dynamic_op_level3.py
  tests/python/relay/test_any.py
  tests/python/relay/test_pass_dynamic_to_static.py
  vta/python/vta/top/graphpack.py
Labels: status: need review

#5618 [Arith] Inequalities solver
  include/tvm/arith/analyzer.h
  include/tvm/arith/int_solver.h
  python/tvm/arith/__init__.py
  python/tvm/arith/analyzer.py
  python/tvm/arith/int_solver.py
  python/tvm/testing.py
  src/arith/analyzer.cc
  src/arith/int_constraints.cc
  src/arith/int_operator.h
  src/arith/solve_linear_inequality.cc
  tests/python/unittest/test_arith_solve_linear_equations.py
  tests/python/unittest/test_arith_solve_linear_inequality.py
Labels: status: need review, status: need update

#5932 [Frontend][Relay] Add Parser 2.0
  CMakeLists.txt
  include/tvm/ir/span.h
  include/tvm/parser/parser.h
  python/tvm/__init__.py
  python/tvm/parser/__init__.py
  python/tvm/parser/_ffi_api.py
  src/ir/span.cc
  src/node/structural_equal.cc
  src/parser/diagnostic.h
  src/parser/op_table.h
  src/parser/parser.cc
  src/parser/token.h
  src/parser/tokenizer.h
  tests/python/relay/test_ir_nodes.py
  tests/python/relay/test_ir_parser2.py
Labels: status: need review

#5919 [BYOC] JSON Runtime with DNNL End-to-End Flow
  cmake/modules/contrib/DNNL.cmake
  src/relay/backend/contrib/codegen_json/codegen_json.h
  src/relay/backend/contrib/dnnl/codegen.cc
  src/relay/backend/graph_runtime_codegen.cc
  src/relay/backend/utils.h
  src/runtime/contrib/dnnl/dnnl_json_runtime.cc
  src/runtime/contrib/json/json_node.h
  src/runtime/contrib/json/json_runtime.h
  tests/python/relay/test_external_runtime.py
  tests/python/relay/test_json_runtime.py
  tests/python/relay/test_pass_partition_graph.py
  tests/scripts/task_config_build_cpu.sh
Labels: status: need review

#5921 µTVM CRT modifications for on-device RPC server
  CMakeLists.txt
  Makefile
  apps/bundle_deploy/Makefile
  apps/bundle_deploy/build_model.py
  apps/bundle_deploy/bundle.c
  apps/bundle_deploy/bundle_static.c
  apps/bundle_deploy/crt_config/crt_config.h
  cmake/config.cmake
  cmake/modules/StandaloneCrt.cmake
  include/tvm/runtime/c_backend_api.h
  include/tvm/runtime/crt/crt.h
  include/tvm/runtime/crt/error_codes.h
  include/tvm/runtime/crt/func_registry.h
  include/tvm/runtime/crt/graph_runtime.h
  include/tvm/runtime/crt/module.h
  include/tvm/runtime/crt/packed_func.h
  include/tvm/runtime/crt/platform.h
  python/tvm/micro/func_registry.py
  src/runtime/crt/.gitignore
  src/runtime/crt/Makefile
  src/runtime/crt/common/crt_backend_api.c
  src/runtime/crt/common/crt_runtime_api.c
  src/runtime/crt/common/func_registry.c
  src/runtime/crt/common/memory.c
  src/runtime/crt/common/ndarray.c
  src/runtime/crt/common/packed_func.c
  src/runtime/crt/crt_backend_api.c
  src/runtime/crt/crt_runtime_api.c
  src/runtime/crt/graph_runtime.h
  src/runtime/crt/graph_runtime/graph_runtime.c
  src/runtime/crt/graph_runtime/load_json.c
  src/runtime/crt/host/crt_config.h
  src/runtime/crt/include/tvm/runtime/crt/internal/common/func_registry.h
  src/runtime/crt/include/tvm/runtime/crt/internal/common/logging.h
  src/runtime/crt/include/tvm/runtime/crt/internal/common/memory.h
  src/runtime/crt/include/tvm/runtime/crt/internal/common/ndarray.h
  src/runtime/crt/include/tvm/runtime/crt/internal/graph_runtime/graph_runtime.h
  src/runtime/crt/include/tvm/runtime/crt/internal/graph_runtime/load_json.h
  src/runtime/library_module.cc
  src/tir/transforms/make_packed_api.cc
  tests/crt/func_registry_test.cc
  tests/crt/memory_test.cc
  tests/lint/git-clang-format.sh
  tests/python/unittest/test_tir_transform_make_packed_api.py
  tests/scripts/task_config_build_cpu.sh
  tests/scripts/task_config_build_gpu.sh
  tests/scripts/task_config_build_gpu_vulkan.sh
  tests/scripts/task_config_build_i386.sh
  tests/scripts/task_config_build_wasm.sh
  tests/scripts/task_cpp_unittest.sh
Labels: status: need review, status: need update

#5992 Add support for tflite arg_min and arg_max
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#5991 [IR] Fix a primitive check error
  include/tvm/ir/op.h
Labels: status: need update

#5989 [BYOC][COREML] Handle one symbol for each runtime
  python/tvm/contrib/coreml_runtime.py
  python/tvm/contrib/target/coreml.py
  src/runtime/contrib/coreml/coreml_runtime.h
  src/runtime/contrib/coreml/coreml_runtime.mm
  tests/python/contrib/test_coreml_runtime.py
Labels: status: need review

#5962 [Ansor][AutoTVM v2.0] Part 0: Ansor minimum system for auto schedule generating
  CMakeLists.txt
  python/tvm/auto_schedule/__init__.py
  python/tvm/auto_schedule/_ffi_api.py
  python/tvm/auto_schedule/auto_schedule.py
  python/tvm/auto_schedule/compute_dag.py
  python/tvm/auto_schedule/loop_state.py
  python/tvm/auto_schedule/measure.py
  python/tvm/auto_schedule/measure_record.py
  python/tvm/auto_schedule/utils.py
  python/tvm/auto_schedule/workload_registry.py
  src/auto_schedule/auto_schedule.cc
  src/auto_schedule/auto_schedule.h
  src/auto_schedule/compute_dag.cc
  src/auto_schedule/compute_dag.h
  src/auto_schedule/loop_state.cc
  src/auto_schedule/loop_state.h
  src/auto_schedule/measure.cc
  src/auto_schedule/measure.h
  src/auto_schedule/measure_record.cc
  src/auto_schedule/measure_record.h
  src/auto_schedule/search_policy/empty_policy.cc
  src/auto_schedule/search_policy/empty_policy.h
  src/auto_schedule/search_policy/search_policy.cc
  src/auto_schedule/search_policy/search_policy.h
  src/auto_schedule/search_task.cc
  src/auto_schedule/search_task.h
  src/auto_schedule/transform_step.cc
  src/auto_schedule/transform_step.h
  src/auto_schedule/utils.cc
  src/auto_schedule/utils.h
  tests/python/unittest/test_auto_schedule_common.py
  tests/python/unittest/test_auto_schedule_compute_dag.py
  tests/python/unittest/test_auto_schedule_loop_state.py
  tests/python/unittest/test_auto_schedule_measure.py
  tests/python/unittest/test_auto_schedule_search_policy.py
Labels: status: need review

#5753 [RUNTIME] Support module based interface runtime
  python/tvm/contrib/debugger/debug_runtime.py
  python/tvm/contrib/graph_runtime.py
  python/tvm/relay/backend/graph_runtime_factory.py
  python/tvm/relay/build_module.py
  src/runtime/graph/graph_runtime_factory.cc
  src/runtime/graph/graph_runtime_factory.h
  src/runtime/module.cc
  tests/python/unittest/test_runtime_module_based_interface.py
Labels: status: WIP, status: need update

#5914 [clflush] Enable x86 cpu cache flush
  python/tvm/autotvm/measure/measure_methods.py
  python/tvm/runtime/module.py
  src/runtime/rpc/rpc_module.cc
  src/runtime/rpc/rpc_session.h
  tutorials/autotvm/tune_relay_x86.py
Labels: status: need update

#6044 [RUNTIME][CRT] init TVMPackedFunc's name
  src/runtime/crt/common/packed_func.c
Labels: status: need review

#5963 [TF]Refine LSTMBlockCell to support dynamic rnn
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/testing/tf.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#5980 Fixed point multiplication improvements for AArch64
  include/tvm/relay/attrs/transform.h
  include/tvm/tir/builtin.h
  include/tvm/tir/op.h
  python/tvm/relay/op/_tensor.py
  python/tvm/relay/op/tensor.py
  python/tvm/tir/__init__.py
  python/tvm/tir/op.py
  src/relay/op/tensor/unary.cc
  src/relay/qnn/op/requantize.cc
  src/relay/qnn/util.cc
  src/relay/qnn/util.h
  src/relay/quantize/realize.cc
  src/relay/transforms/pattern_util.h
  src/target/intrin_rule.cc
  src/tir/op/builtin.cc
  src/tir/op/op.cc
  src/tir/transforms/lower_intrin.cc
  tests/python/relay/test_op_level3.py
  topi/python/topi/arm_cpu/conv2d_gemm.py
  topi/python/topi/arm_cpu/conv2d_int8.py
  topi/python/topi/arm_cpu/injective.py
  topi/python/topi/arm_cpu/tensor_intrin.py
  topi/python/topi/math.py
Labels: status: need review

#6077 [Ansor][AutoTVM v2.0] Phase 1: Add RPC Runner
  python/tvm/auto_scheduler/__init__.py
  python/tvm/auto_scheduler/measure.py
  python/tvm/auto_scheduler/utils.py
  python/tvm/rpc/server.py
  src/auto_scheduler/measure.cc
  src/auto_scheduler/measure.h
  tests/python/unittest/test_auto_scheduler_measure.py
Labels: status: need review

#6073 [Ansor][AutoTVM v2.0] Phase 1: Add annotation/compute_at/compute_root/compute_inline steps
  python/tvm/auto_scheduler/loop_state.py
  src/auto_scheduler/compute_dag.cc
  src/auto_scheduler/loop_state.cc
  src/auto_scheduler/loop_state.h
  src/auto_scheduler/measure_record.cc
  src/auto_scheduler/transform_step.cc
  src/auto_scheduler/transform_step.h
  src/auto_scheduler/utils.h
  tests/python/unittest/test_auto_scheduler_common.py
  tests/python/unittest/test_auto_scheduler_loop_state.py
  tests/python/unittest/test_auto_scheduler_measure.py
Labels: status: need review

#5955 Register Shape Func for Some Operators to Handle Dynamic Shapes
  python/tvm/relay/op/_tensor.py
  python/tvm/relay/op/image/_image.py
  python/tvm/relay/op/nn/_nn.py
  tests/python/relay/test_any.py
Labels: status: need review

#5235 [RELAY][Fix] i64 indices
  src/te/schedule/operation_inline.cc
  tests/python/relay/test_pass_fuse_ops.py
Labels: status: need review

#5795 [Relay] Keep fixed dim when unifying dynamic shape
  src/relay/analysis/type_solver.cc
  tests/python/relay/test_any.py
  tests/python/relay/test_type_infer.py
Labels: status: need review

#6084 [Flaky] TFLite quantized conv test
  tests/python/frontend/tflite/test_forward.py
Labels: status: need update

#6103 [Ansor][AutoTVM v2.0] Phase 1: Access Analyzer
  include/tvm/auto_scheduler/auto_schedule.h
  include/tvm/auto_scheduler/compute_dag.h
  include/tvm/auto_scheduler/loop_state.h
  include/tvm/auto_scheduler/measure.h
  include/tvm/auto_scheduler/measure_record.h
  include/tvm/auto_scheduler/search_policy.h
  include/tvm/auto_scheduler/search_task.h
  include/tvm/auto_scheduler/transform_step.h
  python/tvm/auto_scheduler/auto_schedule.py
  python/tvm/auto_scheduler/workload_registry.py
  src/auto_scheduler/auto_schedule.cc
  src/auto_scheduler/compute_dag.cc
  src/auto_scheduler/compute_dag.h
  src/auto_scheduler/loop_state.cc
  src/auto_scheduler/measure.cc
  src/auto_scheduler/measure_record.cc
  src/auto_scheduler/search_policy/empty_policy.cc
  src/auto_scheduler/search_policy/empty_policy.h
  src/auto_scheduler/search_policy/search_policy.cc
  src/auto_scheduler/search_task.cc
  src/auto_scheduler/transform_step.cc
  src/auto_scheduler/utils.h
  tests/cpp/auto_scheduler_test.cc
  tests/python/unittest/test_auto_scheduler_compute_dag.py
Labels: status: need review

#6107 [Ansor][AutoTVM v2.0] Phase 1: Add cache_read/cache_write steps
  include/tvm/auto_scheduler/compute_dag.h
  include/tvm/auto_scheduler/loop_state.h
  include/tvm/auto_scheduler/transform_step.h
  python/tvm/auto_scheduler/compute_dag.py
  python/tvm/auto_scheduler/loop_state.py
  src/auto_scheduler/compute_dag.cc
  src/auto_scheduler/loop_state.cc
  src/auto_scheduler/transform_step.cc
  tests/python/unittest/test_auto_scheduler_loop_state.py
  tests/python/unittest/test_auto_scheduler_measure.py
Labels: status: need review

#6085 [Relay][OP] Support NMSv4
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review, status: need update

#5892 Add TVM application extension with WASM runtime
  apps/README.md
  apps/wasm-standalone/.gitignore
  apps/wasm-standalone/README.md
  apps/wasm-standalone/wasm-graph/.cargo/config
  apps/wasm-standalone/wasm-graph/Cargo.toml
  apps/wasm-standalone/wasm-graph/build.rs
  apps/wasm-standalone/wasm-graph/src/lib.rs
  apps/wasm-standalone/wasm-graph/src/types.rs
  apps/wasm-standalone/wasm-graph/src/utils.rs
  apps/wasm-standalone/wasm-graph/tools/build_graph_lib.py
  apps/wasm-standalone/wasm-runtime/Cargo.toml
  apps/wasm-standalone/wasm-runtime/src/graph.rs
  apps/wasm-standalone/wasm-runtime/src/lib.rs
  apps/wasm-standalone/wasm-runtime/src/types.rs
  apps/wasm-standalone/wasm-runtime/tests/test_graph_resnet50/Cargo.toml
  apps/wasm-standalone/wasm-runtime/tests/test_graph_resnet50/src/main.rs
  rust/tvm-graph-rt/src/array.rs
  rust/tvm-macros/src/external.rs
  tests/lint/check_file_type.py
Labels: status: need review

#5666 [TIR][Bugfix] Improved massive build times caused by tir.floormod and tir.floordiv. Fixed Topi testcase.
  src/target/llvm/codegen_llvm.cc
  src/target/llvm/codegen_llvm.h
  src/target/source/codegen_c.cc
  src/target/source/codegen_c.h
  src/target/spirv/codegen_spirv.cc
  src/target/spirv/codegen_spirv.h
  src/tir/transforms/lower_intrin.cc
  src/tir/transforms/split_host_device.cc
  topi/tests/python/test_topi_broadcast.py
Labels: status: need review
