Repository apache/tvm, pull requests merged in 2020-12, with the labels that each got.

#6855 [TVMC] use target_host when it is set
  python/tvm/driver/tvmc/compiler.py
  tests/python/driver/tvmc/conftest.py
  tests/python/driver/tvmc/test_compiler.py
Labels: status: need test case

#6987 [AutoScheduler] Support layout rewrite for whole networks
  include/tvm/ir/transform.h
  include/tvm/relay/attrs/nn.h
  include/tvm/relay/attrs/transform.h
  include/tvm/relay/transform.h
  include/tvm/topi/transform.h
  python/tvm/auto_scheduler/__init__.py
  python/tvm/auto_scheduler/compute_dag.py
  python/tvm/auto_scheduler/measure.py
  python/tvm/auto_scheduler/relay_integration.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/strategy/generic.py
  python/tvm/relay/op/strategy/x86.py
  python/tvm/te/tensor.py
  python/tvm/topi/nn/conv2d.py
  src/auto_scheduler/compute_dag.cc
  src/ir/transform.cc
  src/relay/backend/build_module.cc
  src/relay/backend/compile_engine.cc
  src/relay/backend/compile_engine.h
  src/relay/backend/utils.h
  src/relay/op/make_op.h
  src/relay/op/nn/convolution.h
  src/relay/op/tensor/transform.cc
  src/relay/transforms/auto_scheduler_layout_rewrite.cc
  src/relay/transforms/auto_scheduler_layout_rewrite.h
  tests/python/relay/test_auto_scheduler_layout_rewrite.py
Labels: status: need review

#6910 [TVMSCRIPT] Attach span information to tir nodes in tvmscript
  include/tvm/ir/expr.h
  include/tvm/runtime/packed_func.h
  include/tvm/tir/buffer.h
  include/tvm/tir/expr.h
  include/tvm/tir/op.h
  include/tvm/tir/stmt.h
  include/tvm/tir/var.h
  include/tvm/topi/nn.h
  include/tvm/topi/reduction.h
  python/tvm/driver/build_module.py
  python/tvm/ir/expr.py
  python/tvm/runtime/object_generic.py
  python/tvm/script/intrin.py
  python/tvm/script/parser.py
  python/tvm/script/scope_handler.py
  python/tvm/script/special_stmt.py
  python/tvm/script/utils.py
  python/tvm/te/operation.py
  python/tvm/tir/buffer.py
  python/tvm/tir/expr.py
  python/tvm/tir/generic.py
  python/tvm/tir/op.py
  python/tvm/tir/stmt.py
  python/tvm/topi/cuda/nms.py
  python/tvm/topi/cuda/sort.py
  python/tvm/topi/cuda/ssd/multibox.py
  python/tvm/topi/math.py
  src/ir/expr.cc
  src/te/operation/compute_op.cc
  src/te/schedule/schedule_dataflow_rewrite.cc
  src/tir/ir/buffer.cc
  src/tir/ir/expr.cc
  src/tir/op/op.cc
  src/tir/transforms/arg_binder.cc
  src/tir/transforms/inject_double_buffer.cc
  src/tir/transforms/inject_virtual_thread.cc
  src/tir/transforms/storage_rewrite.cc
  tests/python/relay/test_json_compact.py
  tests/python/unittest/test_node_reflection.py
  tests/python/unittest/test_tvmscript_spans.py
Labels: status: need review

#6839 [ONNX] NMS in ONNX
  include/tvm/relay/attrs/vision.h
  python/tvm/relay/frontend/onnx.py
  python/tvm/relay/op/strategy/generic.py
  python/tvm/relay/op/vision/nms.py
  python/tvm/topi/cuda/nms.py
  python/tvm/topi/cuda/sort.py
  python/tvm/topi/vision/nms.py
  src/relay/backend/vm/compiler.cc
  src/relay/backend/vm/lambda_lift.cc
  src/relay/op/tensor/transform.h
  src/relay/op/vision/nms.cc
  tests/python/frontend/onnx/test_forward.py
  tests/python/relay/test_op_level5.py
  tests/python/relay/test_pass_lambda_lift.py
Labels: status: need review

#7087 [Relay][ConvertLayout] Support deformable conv2d
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/strategy/cuda.py
  python/tvm/relay/op/strategy/generic.py
  src/relay/op/nn/convolution.cc
  src/relay/op/nn/convolution.h
  tests/python/relay/test_pass_convert_op_layout.py
Labels: status: need review

#7070 Add autoscheduler support to tvmc
  python/tvm/driver/tvmc/autotuner.py
  python/tvm/driver/tvmc/compiler.py
  tests/python/driver/tvmc/test_autoscheduler.py
  tests/python/driver/tvmc/test_autotuner.py
Labels: status: need update

#6959 [CONTRIB] PopenPoolExecutor
  python/tvm/contrib/popen_pool.py
  python/tvm/exec/popen_worker.py
  python/tvm/testing.py
  tests/python/contrib/test_popen_pool.py
Labels: status: need review

#7127 Added additional information to the from_onnx tutorial
  tutorials/frontend/from_onnx.py
Labels: status: need review

#7099 [CUDA] Parallel Cuda Mergesort
  python/tvm/driver/build_module.py
  python/tvm/topi/cuda/sort.py
  tests/python/relay/test_any.py
  tests/python/relay/test_op_level6.py
  tests/python/topi/python/test_topi_argwhere.py
Labels: status: accepted

#7093 [TFLite] add support for float16
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: accepted

#6984 [TFLite] pack operation extedned with const args
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#7121 [BYOC] [ACL] include_non_call_ops = False
  python/tvm/relay/op/contrib/arm_compute_lib.py
  tests/python/contrib/test_arm_compute_lib/test_network.py
Labels: status: need review

#6964 [µTVM] Add platform timer and RPCTimeEvaluator to enable AutoTVM
  apps/bundle_deploy/bundle.c
  apps/bundle_deploy/bundle_static.c
  include/tvm/runtime/c_runtime_api.h
  include/tvm/runtime/crt/error_codes.h
  include/tvm/runtime/crt/platform.h
  python/tvm/micro/session.py
  src/runtime/c_runtime_api.cc
  src/runtime/crt/common/crt_runtime_api.c
  src/runtime/crt/host/crt_config.h
  src/runtime/crt/host/main.cc
  src/runtime/graph/debug/graph_runtime_debug.cc
  src/runtime/minrpc/minrpc_server.h
  tests/micro/qemu/test_zephyr.py
  tests/micro/qemu/zephyr-runtime/src/main.c
  tests/python/unittest/test_crt.py
Labels: status: accepted

#7142 Asymmetric padding and dilation in conv2d workload
  python/tvm/topi/arm_cpu/conv2d_int8.py
  python/tvm/topi/cuda/conv2d_int8.py
  python/tvm/topi/generic/conv2d.py
  python/tvm/topi/nn/conv2d.py
  python/tvm/topi/nn/depthwise_conv2d.py
  python/tvm/topi/testing/depthwise_conv2d_python.py
  python/tvm/topi/x86/conv2d.py
  python/tvm/topi/x86/conv2d_alter_op.py
  python/tvm/topi/x86/conv2d_avx_1x1.py
  python/tvm/topi/x86/conv2d_avx_common.py
  python/tvm/topi/x86/conv2d_int8.py
  python/tvm/topi/x86/depthwise_conv2d.py
  tests/python/topi/python/test_topi_conv2d_int8.py
  tests/python/topi/python/test_topi_conv2d_nchw.py
  tests/python/topi/python/test_topi_depthwise_conv2d.py
Labels: status: need test case, status: need update

#7086 [Relay][Op] Remove reverse attribute from reshape and reverse_reshape operators.
  include/tvm/relay/attrs/transform.h
  src/relay/op/dyn/tensor/transform.cc
  src/relay/op/tensor/transform.cc
  src/relay/op/tensor/transform.h
  tests/python/contrib/test_arm_compute_lib/test_reshape.py
Labels: status: need update
