Repository apache/tvm, pull requests merged in 2020-10, with the labels that each got.

#6485 Add ci_qemu docker image
  docker/Dockerfile.ci_qemu
  docker/install/ubuntu1804_install_python_venv.sh
  docker/install/ubuntu_install_qemu.sh
  docker/install/ubuntu_install_zephyr.sh
Labels: status: WIP

#6597 [tvmc][docs] Getting started tutorial for TVMC
  tutorials/get_started/tvmc_command_line_driver.py
Labels: status: need update, status: review in progress

#6351 Dynamic ONNX Importer
  include/tvm/relay/transform.h
  include/tvm/topi/broadcast.h
  python/tvm/relay/frontend/onnx.py
  python/tvm/relay/op/_tensor.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/strategy/generic.py
  python/tvm/relay/op/strategy/x86.py
  python/tvm/topi/cuda/batch_matmul.py
  python/tvm/topi/nn/batch_matmul.py
  python/tvm/topi/x86/batch_matmul.py
  src/relay/backend/build_module.cc
  src/relay/op/dyn/tensor/transform.cc
  src/relay/op/nn/convolution.h
  src/relay/op/nn/nn.cc
  src/relay/op/nn/nn.h
  src/relay/op/tensor/transform.cc
  src/relay/transforms/dynamic_to_static.cc
  tests/python/frontend/onnx/test_forward.py
  tests/python/relay/dyn/test_dynamic_op_level10.py
  tests/python/relay/test_op_level10.py
  tutorials/frontend/from_onnx.py
Labels: status: need review

#6616 [Topi] Allow batch_matmul to broadcast along batch dimension.
  include/tvm/topi/nn/batch_matmul.h
  python/tvm/relay/frontend/onnx.py
  python/tvm/topi/nn/batch_matmul.py
  python/tvm/topi/testing/batch_matmul.py
  python/tvm/topi/x86/batch_matmul.py
  src/relay/op/nn/nn.cc
  src/topi/nn.cc
  tests/python/frontend/onnx/test_forward.py
  tests/python/topi/python/test_topi_batch_matmul.py
Labels: status: need review

#6532 [BYOC][ACL] Support add operation
  docs/deploy/arm_compute_lib.rst
  python/tvm/relay/op/contrib/arm_compute_lib.py
  src/runtime/contrib/arm_compute_lib/acl_runtime.cc
  tests/python/contrib/test_arm_compute_lib/test_add.py
Labels: status: need update

#5952 [autotune bugfix]filter out error features
  python/tvm/autotvm/tuner/xgboost_cost_model.py
Labels: status: need review

#6641 [BYOC] Support control flow in annotate_target
  src/relay/transforms/annotate_target.cc
  tests/python/relay/test_pass_annotate_target.py
Labels: status: review in progress

#6662 Adjust Vulkan queue selection and creation logic
  src/runtime/vulkan/vulkan.cc
Labels: status: need update

#6602 [Torch, Quantization] Necessary workaround to prepare for 1.6 update
  python/tvm/relay/frontend/pytorch.py
  python/tvm/relay/frontend/pytorch_utils.py
  python/tvm/relay/frontend/qnn_torch.py
Labels: status: need review

#6699 [Frontend][Relay] Fix MXNet frontend to support NLP backbones in GluonNLP
  python/tvm/relay/frontend/mxnet.py
  python/tvm/topi/x86/batch_matmul.py
  tests/python/frontend/mxnet/test_forward.py
  tests/python/relay/test_op_level1.py
Labels: status: need review

#6395 [BYOC][TensorRT] TensorRT BYOC integration
  CMakeLists.txt
  cmake/config.cmake
  cmake/modules/contrib/TensorRT.cmake
  docs/deploy/index.rst
  docs/deploy/tensorrt.rst
  python/tvm/relay/op/contrib/__init__.py
  python/tvm/relay/op/contrib/tensorrt.py
  src/relay/backend/contrib/tensorrt/codegen.cc
  src/runtime/contrib/tensorrt/tensorrt_builder.cc
  src/runtime/contrib/tensorrt/tensorrt_builder.h
  src/runtime/contrib/tensorrt/tensorrt_logger.h
  src/runtime/contrib/tensorrt/tensorrt_ops.cc
  src/runtime/contrib/tensorrt/tensorrt_ops.h
  src/runtime/contrib/tensorrt/tensorrt_runtime.cc
  src/runtime/contrib/tensorrt/tensorrt_utils.h
  tests/python/contrib/test_tensorrt.py
  tests/scripts/task_config_build_gpu.sh
Labels: status: need review, status: need update

#6728 [AutoScheduler] Use tempfile in tutorials
  tests/scripts/task_python_docs.sh
  tutorials/auto_scheduler/tune_conv2d_layer_cuda.py
  tutorials/auto_scheduler/tune_matmul_x86.py
Labels: status: need review

#6713 [AutoScheduler] Guarantee init population sampling outputs a valid set
  python/tvm/auto_scheduler/cost_model/xgb_model.py
  python/tvm/auto_scheduler/search_policy.py
  src/auto_scheduler/compute_dag.cc
  src/auto_scheduler/search_policy/sketch_policy.cc
  src/auto_scheduler/search_policy/sketch_policy.h
  tests/python/unittest/test_auto_scheduler_evolutionary_search.py
  tests/scripts/task_python_docs.sh
  tutorials/auto_scheduler/conv2d.json
  tutorials/auto_scheduler/matmul.json
  tutorials/auto_scheduler/tune_conv2d_layer_cuda.py
  tutorials/auto_scheduler/tune_matmul_x86.py
Labels: status: need review

#6729 [Relay] Minor fix for some TF OD models
  include/tvm/topi/transform.h
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/op/_transform.py
  tests/python/topi/python/test_topi_transform.py
Labels: status: need review

#6718 [Hexagon] Use nullptr instead of 0 in hexagon_device_sim.cc
  src/runtime/hexagon/sim/hexagon_device_sim.cc
Labels: status: review in progress

#6706 [CI] Tensorflow version support upgrade from 2.1.0 to 2.3.1
  docker/install/ubuntu_install_tensorflow.sh
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#6726 add onnx resize v10 and unit test
  python/tvm/relay/frontend/onnx.py
  tests/python/frontend/onnx/test_forward.py
Labels: status: need review

#6749 [BUGFIX] Fix topi matrix multiplication using tensorcore to run faster
  python/tvm/topi/cuda/dense_tensorcore.py
Labels: status: need review

#6759 [Relay, TOPI] Complete rewrite of where op to support broadcasting
  include/tvm/topi/transform.h
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  src/relay/op/type_relations.cc
  src/relay/op/type_relations.h
  tests/python/frontend/pytorch/test_lstm.py
  tests/python/relay/test_any.py
  tests/python/relay/test_op_level4.py
Labels: status: need review

#6739 [Relay] Fix dynamic case for Squeeze and Split
  include/tvm/topi/transform.h
  python/tvm/relay/op/_transform.py
  tests/python/relay/test_any.py
Labels: status: need review

#6533 Scatter on Cuda
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/strategy/cuda.py
  python/tvm/relay/op/strategy/generic.py
  python/tvm/topi/cuda/__init__.py
  python/tvm/topi/cuda/scatter.py
  tests/python/relay/test_op_level3.py
Labels: status: need review

#6771 [ARITH] Tight bound for floormod
  src/arith/const_int_bound.cc
  tests/python/unittest/test_arith_const_int_bound.py
Labels: status: need test case

#6722 [OpenCL] Only use thrust for cuda targets
  python/tvm/relay/op/strategy/cuda.py
  python/tvm/topi/cuda/nms.py
Labels: status: need review

#6671 [FIX,AUTOSCHEDULER] Fix auto_scheduler to run with multiprocessing's spawn start method
  python/tvm/auto_scheduler/measure.py
  python/tvm/auto_scheduler/measure_record.py
  python/tvm/auto_scheduler/utils.py
  python/tvm/auto_scheduler/workload_registry.py
  python/tvm/testing.py
  src/auto_scheduler/measure_record.cc
  tests/python/unittest/test_auto_scheduler_measure.py
  tests/python/unittest/test_auto_scheduler_search_policy.py
  tests/python/unittest/test_auto_scheduler_task_scheduler.py
  tests/python/unittest/test_autotvm_dispatch_context.py
  tests/python/unittest/test_runtime_rpc.py
Labels: status: need review

#6697 [BYOC] Allow custom codegens to register their own constant updater
  src/relay/backend/contrib/ethosn/codegen_ethosn.h
  src/relay/backend/graph_runtime_codegen.cc
  src/relay/backend/utils.h
  src/relay/backend/vm/compiler.cc
  tests/python/contrib/test_ethosn/test_constant_duplication.py
  tests/python/relay/test_external_codegen.py
Labels: status: need RFC, status: need review

#6710 [AutoScheduler] Relay integration : Task extraction
  python/tvm/auto_scheduler/__init__.py
  python/tvm/auto_scheduler/compute_dag.py
  python/tvm/auto_scheduler/cost_model/xgb_model.py
  python/tvm/auto_scheduler/dispatcher.py
  python/tvm/auto_scheduler/env.py
  python/tvm/auto_scheduler/measure.py
  python/tvm/auto_scheduler/relay_integration.py
  python/tvm/auto_scheduler/search_policy.py
  python/tvm/auto_scheduler/utils.py
  python/tvm/auto_scheduler/workload_registry.py
  python/tvm/relay/backend/compile_engine.py
  python/tvm/relay/op/op.py
  python/tvm/relay/op/strategy/cuda.py
  python/tvm/relay/op/strategy/generic.py
  src/auto_scheduler/search_policy/sketch_policy.cc
  src/auto_scheduler/search_policy/sketch_policy.h
  src/relay/backend/compile_engine.cc
  tests/python/relay/test_auto_scheduler_task_extraction.py
  tests/python/relay/test_auto_scheduler_tuning.py
  tests/python/unittest/test_auto_scheduler_cost_model.py
  tests/python/unittest/test_auto_scheduler_evolutionary_search.py
Labels: status: need review
