Repository apache/tvm, pull requests merged in 2020-02, with the labels that each got.

#4747 [ThreadPool] Solve ARM BIG.LITTLE heterogeneous multicores
  src/runtime/threading_backend.cc
Labels: status: need review

#4714 Mxnet parser for Qnn dialect
  python/tvm/relay/frontend/__init__.py
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/frontend/mxnet_qnn_op_utils.py
  tests/python/frontend/mxnet/test_forward.py
  tests/python/frontend/mxnet/test_qnn_ops_utils.py
Labels: status: need review

#4642 [Relay][Frontend][TFLite] Add parser support for logical operators
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#4564 [Doc] Introduction to module serialization
  docs/dev/index.rst
  docs/dev/introduction_to_module_serialization.rst
Labels: status: need review

#4696 [Relay][Frontend][TFlite] Add support for quantized LOGISTIC
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need update

#4842 [Doc][AutoTVM] Fix bugs that override n_trials
  tutorials/autotvm/tune_relay_arm.py
  tutorials/autotvm/tune_relay_cuda.py
  tutorials/autotvm/tune_relay_mobile_gpu.py
  vta/tutorials/autotvm/tune_relay_vta.py
Labels: status: need review

#4852 [Bugfix] Fixed crash caused by reversing bitwise operations
  python/tvm/expr.py
  tests/python/unittest/test_lang_basic.py
Labels: status: accepted

#4855 [Refactor] move vm.py under runtime and adt to runtime.container.py
  python/tvm/container.py
  python/tvm/relay/__init__.py
  python/tvm/relay/backend/interpreter.py
  python/tvm/relay/backend/vm.py
  python/tvm/relay/testing/py_converter.py
  python/tvm/runtime/container.py
  python/tvm/runtime/profiler_vm.py
  python/tvm/runtime/vm.py
  src/runtime/container.cc
  src/runtime/vm/executable.cc
  src/runtime/vm/profiler/vm.cc
  src/runtime/vm/vm.cc
  tests/python/frontend/tensorflow/test_forward.py
  tests/python/relay/benchmarking/benchmark_vm.py
  tests/python/relay/test_adt.py
  tests/python/relay/test_backend_interpreter.py
  tests/python/relay/test_external_codegen.py
  tests/python/relay/test_pass_partition_graph.py
  tests/python/relay/test_py_converter.py
  tests/python/relay/test_vm.py
  tests/python/relay/test_vm_serialization.py
  tests/python/unittest/test_container.py
  tests/python/unittest/test_runtime_vm_profiler.py
Labels: status: need update

#4543 [FRONTEND][TFLITE] Add support for TFLite_Detection_PostProcess
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#4866 Optimize x86 conv3d_ndhwc using data packing approach.
  python/tvm/autotvm/task/relay_integration.py
  python/tvm/autotvm/task/topi_integration.py
  topi/python/topi/nn/util.py
  topi/python/topi/x86/conv3d.py
  topi/tests/python/test_topi_conv3d_ndhwc.py
Labels: status: need review

#4868 [doc][VM] Update the vm doc
  docs/dev/virtual_machine.rst
Labels: status: need review

#4867 [TOPI][CUDA] Enable vectorization on fp16 type
  topi/python/topi/cuda/injective.py
  topi/tests/python/test_topi_relu.py
  topi/tests/python/test_topi_tensor.py
Labels: status: need review

#4874 [QNN] More doc fix on quantize and convolution
  python/tvm/relay/qnn/op/qnn.py
  tests/python/relay/test_op_qnn_conv2d.py
  tests/python/relay/test_pass_qnn_legalize.py
Labels: status: need review

#4870 [AutoTVM] Support range in index based tuners
  python/tvm/autotvm/tuner/__init__.py
  python/tvm/autotvm/tuner/gridsearch_tuner.py
  python/tvm/autotvm/tuner/index_based_tuner.py
  tests/python/unittest/test_autotvm_common.py
  tests/python/unittest/test_autotvm_index_tuner.py
  tests/python/unittest/test_autotvm_measure.py
Labels: status: need review

#4876 [CodeGen][CUDA] Fix issues in cuda codegen
  python/tvm/contrib/nvcc.py
  src/target/source/codegen_c.cc
  src/target/source/codegen_c.h
  src/target/source/codegen_cuda.cc
  src/target/source/codegen_cuda.h
  tests/python/unittest/test_codegen_cuda.py
  topi/tests/python/test_topi_relu.py
  topi/tests/python/test_topi_tensor.py
Labels: status: need review

#4879 [Relay][Pass] Fix bug in re-processing call node in MergeComposite pass
  src/relay/pass/merge_composite.cc
  tests/python/relay/test_pass_merge_composite.py
Labels: status: need test case, status: need update

#4546 [CODEGEN] Support cuda tensorcore subbyte int data type in auto tensorcore
  include/tvm/runtime/data_type.h
  include/tvm/tir/expr.h
  src/runtime/ndarray.cc
  src/target/source/codegen_c.cc
  src/target/source/codegen_cuda.cc
  src/tir/pass/arg_binder.cc
  src/tir/pass/infer_fragment.cc
  src/tir/pass/tensor_core.cc
  tutorials/optimize/opt_matmul_auto_tensorcore.py
Labels: status: need review, status: need update

#4891 [TEST][FLAKY] topi/tests/python/test_topi_sort.py::test_argsort
  topi/tests/python/test_topi_sort.py
Labels: status: need update

#4901 [Fix] Fix get_valid_count flaky test for cuda
  tests/python/relay/test_op_level5.py
  topi/python/topi/cuda/nms.py
  topi/tests/python/test_topi_vision.py
Labels: status: accepted

#4497 [Relay] Add a PyTorch to Relay Parser
  docs/api/python/relay/frontend.rst
  python/tvm/relay/frontend/__init__.py
  python/tvm/relay/frontend/pytorch.py
  tests/python/frontend/pytorch/test_forward.py
  tests/scripts/task_python_frontend.sh
Labels: status: need review

#4651 Tensor Expression Debug Display (TEDD)
  python/tvm/contrib/tedd.py
  tests/python/contrib/test_tedd.py
  tutorials/language/tedd.py
Labels: status: need review

#4922 [Relay][pass] call graph for relay
  python/tvm/relay/__init__.py
  python/tvm/relay/call_graph.py
  src/relay/pass/call_graph.cc
  src/relay/pass/call_graph.h
  tests/python/relay/test_call_graph.py
Labels: status: accepted

#4887 [VTA] YoloV3 Support
  vta/python/vta/top/graphpack.py
  vta/tutorials/frontend/deploy_classification.py
  vta/tutorials/frontend/deploy_detection.py
Labels: status: need review

#4944 [Relay, Torch] Clean up and refactor PyTorch frontend
  python/tvm/relay/frontend/pytorch.py
  tests/python/frontend/pytorch/test_forward.py
  tutorials/frontend/from_pytorch.py
Labels: status: need review

#4970 Added CopyFromBytes and CopyToBytes convenience methods to NDArray. Fixed typos.
  include/tvm/runtime/ndarray.h
  src/runtime/ndarray.cc
Labels: status: need update
