Repository apache/tvm, pull requests merged in 2020-11, with the labels that each got.

#5767 [TENSORFLOW]Sparse2Dense support
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#6711 Improve AArch64 depthwise convolution through smlal/smlal2 intrinsic
  python/tvm/topi/arm_cpu/depthwise_conv2d.py
  python/tvm/topi/arm_cpu/tensor_intrin.py
  tests/python/topi/python/test_topi_depthwise_conv2d.py
Labels: status: need review

#6786 [BYOC] FTVMAnnotateTarget method signature update
  include/tvm/relay/op_attr_types.h
  python/tvm/relay/op/contrib/arm_compute_lib.py
  python/tvm/relay/op/contrib/coreml.py
  python/tvm/relay/op/contrib/dnnl.py
  python/tvm/relay/op/contrib/ethosn.py
  python/tvm/relay/op/contrib/tensorrt.py
  src/relay/transforms/annotate_target.cc
  tests/python/relay/test_pass_annotate_target.py
  tests/python/relay/test_pass_partition_graph.py
Labels: status: review in progress

#6373 Register shape functions for some image related ops
  python/tvm/relay/op/image/_image.py
  tests/python/relay/test_any.py
Labels: status: need review

#6703 [µTVM] Add virtual machine, test zephyr runtime on real hardware
  apps/microtvm/README.md
  apps/microtvm/reference-vm/.gitignore
  apps/microtvm/reference-vm/README.md
  apps/microtvm/reference-vm/base-box-tool.py
  apps/microtvm/reference-vm/zephyr/.gitignore
  apps/microtvm/reference-vm/zephyr/Vagrantfile
  apps/microtvm/reference-vm/zephyr/base-box/.gitignore
  apps/microtvm/reference-vm/zephyr/base-box/Vagrantfile.packer-template
  apps/microtvm/reference-vm/zephyr/base-box/setup.sh
  apps/microtvm/reference-vm/zephyr/pyproject.toml
  apps/microtvm/reference-vm/zephyr/rebuild-tvm.sh
  apps/microtvm/reference-vm/zephyr/setup.sh
  src/target/source/codegen_c_host.cc
  src/target/source/codegen_c_host.h
  tests/lint/check_file_type.py
  tutorials/micro/micro_reference_vm.py
Labels: status: review in progress

#6724 [BYOC] [ACL] 20.05 memory corruption temporarely fix
  python/tvm/relay/op/contrib/arm_compute_lib.py
  src/runtime/contrib/arm_compute_lib/acl_utils.cc
  tests/python/contrib/test_arm_compute_lib/infrastructure.py
  tests/python/contrib/test_arm_compute_lib/test_dense.py
  tests/python/contrib/test_arm_compute_lib/test_maximum.py
  tests/python/contrib/test_arm_compute_lib/test_network.py
  tests/python/contrib/test_arm_compute_lib/test_pooling.py
  tests/python/contrib/test_arm_compute_lib/test_reshape.py
Labels: status: need update, status: review in progress

#6343 [BYOC][CONTRIB] Vitis-AI codegen integration
  CMakeLists.txt
  cmake/config.cmake
  cmake/modules/contrib/VitisAI.cmake
  docs/deploy/index.rst
  docs/deploy/vitis_ai.rst
  python/tvm/contrib/target/vitis_ai.py
  python/tvm/relay/op/contrib/vitis_ai.py
  src/relay/backend/contrib/vitis_ai/config_vitis_ai.cc
  src/runtime/contrib/vitis_ai/vitis_ai_runtime.cc
  src/runtime/contrib/vitis_ai/vitis_ai_runtime.h
  tests/python/contrib/test_vitis_ai/__init__.py
  tests/python/contrib/test_vitis_ai/infrastructure.py
  tests/python/contrib/test_vitis_ai/test_vitis_ai_codegen.py
  tests/python/contrib/test_vitis_ai/test_vitis_ai_runtime_cpu_part.py
  tests/scripts/task_config_build_cpu.sh
Labels: status: need update, status: review in progress

#6704 [Relay] Mix mode type inference
  include/tvm/relay/expr_functor.h
  src/relay/ir/expr_functor.cc
  src/relay/op/algorithm/topk.cc
  src/relay/transforms/type_infer.cc
Labels: status: review in progress

#6802 Add smmla/ummla support in quantized Conv2d
  python/tvm/topi/arm_cpu/arm_utils.py
  python/tvm/topi/arm_cpu/conv2d_gemm.py
  python/tvm/topi/arm_cpu/tensor_intrin.py
  tests/python/topi/python/test_topi_conv2d_int8.py
Labels: status: need review

#6714 More flexible conv2d_NCHWc_int8 generic operator.
  python/tvm/topi/generic/conv2d.py
  python/tvm/topi/nn/conv2d.py
Labels: status: need review

#6516 [RELAY][OP] roi_pool operator alter layout
  python/tvm/relay/op/vision/_rcnn.py
  src/relay/op/vision/rcnn_op.cc
  tests/python/relay/test_pass_convert_op_layout.py
Labels: status: need review

#6885 [Relay][TF] Keep node name in span
  python/tvm/relay/expr.py
  python/tvm/relay/expr_functor.py
  python/tvm/relay/frontend/tensorflow.py
  src/printer/relay_text_printer.cc
  src/printer/text_printer.h
  src/relay/ir/expr.cc
  src/relay/transforms/fuse_ops.cc
  tests/python/relay/test_ir_text_printer.py
Labels: status: accepted

#6831 [TVMC] add cl support in tvmc runner
  python/tvm/driver/tvmc/runner.py
Labels: status: need update

#6887 Fix bug of generate-unmatched-brackets in CodeGenC::PrintSSAAssign
  src/target/source/codegen_c.cc
Labels: status: need update

#6926 [CI] Update actions miniconda
  .github/workflows/main.yml
Labels: status: need backport

#6903 [AutoSchedule] Extract tasks via compile engine
  python/tvm/auto_scheduler/__init__.py
  python/tvm/auto_scheduler/dispatcher.py
  python/tvm/auto_scheduler/env.py
  python/tvm/auto_scheduler/relay_integration.py
  python/tvm/auto_scheduler/workload_registry.py
  python/tvm/relay/backend/compile_engine.py
  python/tvm/relay/build_module.py
  python/tvm/relay/op/op.py
  python/tvm/relay/op/strategy/cuda.py
  python/tvm/topi/cuda/conv2d_alter_op.py
  src/relay/backend/compile_engine.cc
  tests/python/relay/test_auto_scheduler_task_extraction.py
  tests/python/relay/test_auto_scheduler_tuning.py
  tutorials/auto_scheduler/ci_logs/resnet-18-NHWC-B1.json
  tutorials/auto_scheduler/tune_network_cuda.py
Labels: status: need review

#6909 Make AutoScheduler handling of errors during measure consistent with AutoTvm
  python/tvm/autotvm/tuner/tuner.py
  src/auto_scheduler/measure.cc
Labels: status: need review

#6477 [Relay] Add space_to_batch_nd and batch_to_space_nd operators
  include/tvm/relay/attrs/nn.h
  include/tvm/topi/nn.h
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/frontend/tflite.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  python/tvm/relay/op/op_attrs.py
  python/tvm/topi/nn/__init__.py
  python/tvm/topi/nn/batch_to_space_nd.py
  python/tvm/topi/nn/space_to_batch_nd.py
  python/tvm/topi/testing/__init__.py
  python/tvm/topi/testing/batch_to_space_nd.py
  python/tvm/topi/testing/space_to_batch_nd.py
  src/relay/op/nn/nn.cc
  src/topi/nn.cc
  tests/python/relay/test_op_level5.py
  tests/python/topi/python/test_topi_batch_to_space_nd.py
  tests/python/topi/python/test_topi_space_to_batch_nd.py
Labels: status: need review

#6930 [µTVM] Fix problems with the debug flow
  python/tvm/micro/debugger.py
  python/tvm/micro/session.py
  python/tvm/micro/transport/__init__.py
  python/tvm/micro/transport/base.py
  python/tvm/micro/transport/debug.py
  python/tvm/micro/transport/file_descriptor.py
  python/tvm/micro/transport/serial.py
  python/tvm/micro/transport/wakeup.py
  src/runtime/micro/micro_session.cc
  tests/python/unittest/test_micro_transport.py
Labels: status: need review

#6946 [Relay] Add DefuseOps pass
  python/tvm/relay/transform/transform.py
  src/relay/transforms/defuse_ops.cc
  tests/python/relay/test_pass_defuse_ops.py
  tests/python/relay/test_pass_fuse_ops.py
Labels: status: need review

#6907 AArch64 base algorithm refactoring in LLVM
  python/tvm/topi/arm_cpu/conv2d_gemm.py
  python/tvm/topi/arm_cpu/tensor_intrin.py
Labels: status: review in progress

#6899 Add initial support for quantized transpose convolution in Relay
  python/tvm/relay/frontend/tflite.py
  python/tvm/relay/qnn/op/legalizations.py
  python/tvm/relay/qnn/op/qnn.py
  src/relay/qnn/op/convolution_transpose.cc
  tests/python/frontend/tflite/test_forward.py
  tests/python/relay/test_op_qnn_conv2_transpose.py
Labels: status: need review
