Repository apache/tvm, pull requests merged in 2020-08, with the labels that each got.

#6128 [Fix] avoid unexpected throw in AttrInitEntry
  include/tvm/ir/attrs.h
Labels: status: need update

#6066 [TIR][Transform] HoistIfThenElse added
  include/tvm/tir/transform.h
  python/tvm/driver/build_module.py
  python/tvm/tir/transform/transform.py
  src/tir/transforms/hoist_if_then_else.cc
  tests/python/unittest/test_te_build_lower.py
  tests/python/unittest/test_tir_transform_hoist_if.py
Labels: status: need review

#6152 [RELAY] Basic block normal form
  include/tvm/relay/analysis.h
  include/tvm/relay/transform.h
  python/tvm/relay/analysis/analysis.py
  python/tvm/relay/transform/transform.py
  src/relay/analysis/dependency_graph.cc
  src/relay/backend/build_module.cc
  src/relay/backend/vm/compiler.cc
  src/relay/transforms/let_list.h
  src/relay/transforms/pass_util.h
  src/relay/transforms/to_a_normal_form.cc
  src/relay/transforms/to_basic_block_normal_form.cc
  tests/python/relay/test_analysis_basic_block_normal_form.py
  tests/python/relay/test_pass_to_basic_block_normal_form.py
Labels: status: need review

#6227 [TIR][Hybrid] Hybrid Script Support for TIR
  python/tvm/__init__.py
  python/tvm/hybrid/__init__.py
  python/tvm/hybrid/_ffi_api.py
  python/tvm/hybrid/intrin.py
  python/tvm/hybrid/meta_unparser.py
  python/tvm/hybrid/parser.py
  python/tvm/hybrid/registry.py
  python/tvm/hybrid/scope_emitter.py
  python/tvm/hybrid/scope_handler.py
  python/tvm/hybrid/special_stmt.py
  python/tvm/hybrid/ty.py
  python/tvm/hybrid/utils.py
  src/printer/tir_hybrid_printer.cc
  tests/python/unittest/test_hybrid_error_report.py
  tests/python/unittest/test_hybrid_roundtrip.py
Labels: status: need review

#6225 fix cuda half math function is undefined: hpow, htanh
  src/target/source/literal/cuda_half_t.h
Labels: status: need review

#6243 [TFLite] Implemented EXPAND_DIMS Operator for TFLite.
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#6190 [Ansor][AutoTVM v2.0] Phase 1: feature extraction for cost models
  include/tvm/auto_scheduler/feature.h
  python/tvm/auto_scheduler/__init__.py
  python/tvm/auto_scheduler/feature.py
  src/auto_scheduler/compute_dag.cc
  src/auto_scheduler/feature.cc
  tests/python/unittest/test_auto_scheduler_compute_dag.py
  tests/python/unittest/test_auto_scheduler_feature.py
Labels: status: need review, status: need update

#6018 Added support for tflite quantized maximum and minimum
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#6218 [Target] Creating Target from JSON-like Configuration
  include/tvm/target/target.h
  include/tvm/target/target_kind.h
  src/target/target.cc
  src/target/target_kind.cc
  tests/cpp/target_test.cc
Labels: status: need review

#6280 [Build] Reflect Compile-Time CMake Options into libtvm.so
  CMakeLists.txt
  cmake/modules/Git.cmake
  python/tvm/__init__.py
  python/tvm/support.py
  src/support/libinfo.cc
Labels: status: need update

#5940 Add Quantize/Dequantize Partitioning
  python/tvm/relay/analysis/analysis.py
  python/tvm/relay/quantize/_partition_conversions.py
  python/tvm/relay/quantize/quantize.py
  python/tvm/relay/scope_builder.py
  src/relay/analysis/util.cc
  src/relay/quantize/quantize.cc
  src/relay/quantize/quantize.h
  tests/python/relay/test_pass_auto_quantize.py
Labels: status: need update

#6112 TVMC - a command line driver for TVM (Part 1)
  python/setup.py
  python/tvm/driver/tvmc/__init__.py
  python/tvm/driver/tvmc/__main__.py
  python/tvm/driver/tvmc/common.py
  python/tvm/driver/tvmc/main.py
Labels: status: need review

#5913 [random] support random fill
  cmake/config.cmake
  src/runtime/contrib/random/mt_random_engine.cc
  src/runtime/contrib/random/random.cc
  tests/python/contrib/test_random.py
Labels: status: need update

#6168 Gather operation with indices as tensor expr in TFLite frontend
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#6275 [Support] Add parallel_for support to run a loop in parallel
  include/tvm/support/parallel_for.h
  src/support/parallel_for.cc
  tests/cpp/parallel_for_test.cc
Labels: status: need update

#6261 [Hexagon] Initial support for Hexagon codegen
  python/tvm/contrib/hexagon.py
  python/tvm/target/target.py
  src/runtime/hexagon/hexagon_module.cc
  src/runtime/module.cc
  src/target/llvm/codegen_hexagon.cc
  src/target/llvm/intrin_rule_hexagon.cc
  src/target/target_kind.cc
  tests/python/unittest/test_target_codegen_hexagon.py
Labels: status: need review

#6124 [Relay] change device annotation from post DFS to recursive
  src/relay/transforms/device_annotation.cc
  tests/python/relay/test_pass_annotation.py
Labels: status: need test case

#6314 [Relay] Support for PyTorch Non-Maximum Suppression
  python/tvm/relay/frontend/pytorch.py
  tests/python/frontend/pytorch/test_forward.py
Labels: status: need update

#6327 [OpFusion] Make the max number of fused ops configurable
  src/relay/transforms/fuse_ops.cc
  tests/python/relay/test_pass_fuse_ops.py
Labels: status: need review

#6278 [Frontend][Relay] Keras softmax and prelu fix under NHWC
  python/tvm/relay/frontend/keras.py
  tests/python/frontend/keras/test_forward.py
Labels: status: need review

#6279 [BYOC][ACL] Enable remote device via environment variables
  docs/deploy/arm_compute_lib.rst
  tests/python/contrib/test_arm_compute_lib/infrastructure.py
  tests/python/contrib/test_arm_compute_lib/test_config.json
  tests/python/contrib/test_arm_compute_lib/test_conv2d.py
  tests/python/contrib/test_arm_compute_lib/test_dense.py
  tests/python/contrib/test_arm_compute_lib/test_network.py
  tests/python/contrib/test_arm_compute_lib/test_pooling.py
  tests/python/contrib/test_arm_compute_lib/test_reshape.py
  tests/python/contrib/test_arm_compute_lib/test_runtime.py
Labels: status: need review

#6117 Use auto-tuner to improve conv2d_gemm performance
  python/tvm/topi/arm_cpu/conv2d_gemm.py
  python/tvm/topi/arm_cpu/conv2d_int8.py
  python/tvm/topi/arm_cpu/tensor_intrin.py
Labels: status: need review, status: need update

#6293 [DYN][RELAY] Resize support for NCHW-convertible layouts
  python/tvm/relay/op/dyn/image/_image.py
Labels: status: need review

#6138 Add `init` member to ReduceNode
  include/tvm/tir/expr.h
  include/tvm/tir/op.h
  include/tvm/topi/reduction.h
  python/tvm/tir/expr.py
  python/tvm/tir/op.py
  src/arith/canonical_simplify.cc
  src/printer/tir_text_printer.cc
  src/te/autodiff/ad_simplify.cc
  src/te/autodiff/ad_util.cc
  src/te/autodiff/jacobian.cc
  src/te/operation/compute_op.cc
  src/te/operation/cross_thread_reduction.cc
  src/te/operation/tensorize.cc
  src/te/schedule/schedule_dataflow_rewrite.cc
  src/tir/ir/expr.cc
  src/tir/ir/expr_functor.cc
  src/tir/op/op.cc
  tests/python/integration/test_reduce.py
  tests/python/unittest/test_arith_canonical_simplify.py
  tests/python/unittest/test_te_autodiff.py
Labels: status: need update

#6303 [Relay/TOPI][TFLite] Implemented MATRIX_SET_DIAG Operator for Relay/TOPI and TFLite Frontend.
  include/tvm/topi/transform.h
  python/tvm/relay/frontend/tflite.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/transform.py
  python/tvm/topi/testing/__init__.py
  python/tvm/topi/testing/matrix_set_diag.py
  python/tvm/topi/transform.py
  src/relay/op/tensor/transform.cc
  src/topi/transform.cc
  tests/python/frontend/tflite/test_forward.py
  tests/python/relay/test_op_level10.py
  tests/python/topi/python/test_topi_transform.py
Labels: status: need review

#6206 [Caffe Frontend] introduce caffe frontend for tvm
  python/tvm/relay/frontend/__init__.py
  python/tvm/relay/frontend/caffe.py
  tests/python/frontend/caffe/test_forward.py
  tests/scripts/task_python_frontend_cpu.sh
Labels: status: need review, status: need update

#6248 [BYOC][ACL] Improved pooling support
  docs/deploy/arm_compute_lib.rst
  python/tvm/relay/op/contrib/arm_compute_lib.py
  src/relay/backend/contrib/arm_compute_lib/codegen.cc
  src/runtime/contrib/arm_compute_lib/acl_runtime.cc
  src/runtime/contrib/arm_compute_lib/acl_utils.cc
  src/runtime/contrib/arm_compute_lib/acl_utils.h
  tests/python/contrib/test_arm_compute_lib/infrastructure.py
  tests/python/contrib/test_arm_compute_lib/test_conv2d.py
  tests/python/contrib/test_arm_compute_lib/test_network.py
  tests/python/contrib/test_arm_compute_lib/test_pooling.py
  tests/python/contrib/test_arm_compute_lib/test_reshape.py
Labels: status: review in progress

#6127 quanitze operation expanded to take const argument
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need review

#6339 Improve Rust bindings: Map, Array, String, various IR nodes
  rust/tvm-macros/src/object.rs
  rust/tvm-rt/src/array.rs
  rust/tvm-rt/src/function.rs
  rust/tvm-rt/src/lib.rs
  rust/tvm-rt/src/map.rs
  rust/tvm-rt/src/object/mod.rs
  rust/tvm-rt/src/object/object_ptr.rs
  rust/tvm-rt/src/string.rs
  rust/tvm-sys/src/datatype.rs
  rust/tvm-sys/src/packed_func.rs
  rust/tvm/src/ir/arith.rs
  rust/tvm/src/ir/mod.rs
  rust/tvm/src/ir/relay/mod.rs
  rust/tvm/src/ir/tir.rs
  rust/tvm/src/transform.rs
Labels: status: need review
