Repository apache/tvm, pull requests merged in 2020-06, with the labels that each got.

#5447 [TOPI,RELAY][TFLITE] Sparse to dense operator
  docs/api/python/topi.rst
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/transform.h
  python/tvm/relay/frontend/tflite.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  tests/python/frontend/tflite/test_forward.py
  tests/python/relay/test_op_level3.py
  topi/include/topi/transform.h
  topi/python/topi/transform.py
  topi/src/transform.cc
  topi/tests/python/test_topi_transform.py
Labels: status: need review, status: need update

#5727 ROCm warp shuffles and reductions
  src/target/llvm/intrin_rule_rocm.cc
  src/target/target.cc
  src/tir/transforms/lower_thread_allreduce.cc
  tests/python/integration/test_reduce.py
  tests/python/unittest/test_target_codegen_cuda.py
  tests/python/unittest/test_target_codegen_rocm.py
  tests/python/unittest/test_tir_transform_lower_warp_memory.py
  topi/python/topi/cuda/softmax.py
Labels: status: need review

#5716 [topi][relay] Add operation gather to relay.
  docs/api/python/topi.rst
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/transform.h
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/op_attrs.py
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_op_level3.py
  topi/include/topi/transform.h
  topi/python/topi/testing/__init__.py
  topi/python/topi/testing/gather_python.py
  topi/python/topi/transform.py
  topi/src/transform.cc
  topi/tests/python/test_topi_transform.py
Labels: status: need review

#5766 [BYOC][FIX] Infer types in MergeComposite
  src/relay/transforms/merge_composite.cc
  tests/python/relay/test_pass_merge_composite.py
Labels: status: need review

#5776 [PYTORCH]aten::norm support added
  python/tvm/relay/frontend/pytorch.py
  tests/python/frontend/pytorch/test_forward.py
Labels: status: need review

#5775 [TENSORFLOW]Conv3d Transpose OP added
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#5762 [TF] Support symbolic inputs of Fill
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#5755 Edit onnx parser to infer values in post order
  python/tvm/relay/frontend/onnx.py
Labels: status: need review

#5787 support aten::type_as in the pytorch frontend
  python/tvm/relay/frontend/pytorch.py
  tests/python/frontend/pytorch/test_forward.py
Labels: status: need update

#5800 [ONNX] Skip multiply with 1.0f constant for GEMM import
  python/tvm/relay/frontend/onnx.py
Labels: status: need review

#5801 [QUANTIZE] Add config switch for nn.dense layer type.
  python/tvm/relay/quantize/_annotate.py
  python/tvm/relay/quantize/quantize.py
  src/relay/quantize/quantize.h
Labels: status: need review

#5782 [topi] fix strategy for sparse dense cuda
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/strategy/cuda.py
  python/tvm/relay/op/strategy/generic.py
  python/tvm/relay/op/strategy/x86.py
  topi/python/topi/cuda/sparse.py
  topi/python/topi/x86/sparse.py
Labels: status: need update

#4805 [Frontend][TFlite] Add parser support for relu6, leaky_relu, relu_n1_to_1, log_softmax
  python/tvm/relay/frontend/tflite.py
  tests/python/frontend/tflite/test_forward.py
Labels: status: need update

#5780 [Fix] Fix recursive let for well formed check
  src/relay/analysis/util.cc
  src/relay/analysis/well_formed.cc
Labels: status: need review, status: need test case

#5495 [Relay, Topi] [Frontend][TFLite, MXNet] ReverseSequence operator
  docs/api/python/topi.rst
  docs/langref/relay_op.rst
  include/tvm/relay/attrs/transform.h
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/frontend/tflite.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/op_attrs.py
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  tests/python/frontend/mxnet/test_forward.py
  tests/python/frontend/tflite/test_forward.py
  tests/python/relay/test_op_level3.py
  topi/include/topi/transform.h
  topi/python/topi/transform.py
  topi/src/transform.cc
  topi/tests/python/test_topi_transform.py
Labels: status: need review

#5819 [Frontend][MXNet] Support a few contrib ops in mxnet
  python/tvm/relay/frontend/mxnet.py
  python/tvm/relay/frontend/nnvm_common.py
  tests/python/frontend/mxnet/test_forward.py
Labels: status: need review

#5770 [RUNTIME] Introduce MetadataModule to separate code compilation/interpretation and weight initialization
  python/tvm/contrib/graph_runtime.py
  python/tvm/runtime/vm.py
  src/relay/backend/build_module.cc
  src/relay/backend/compile_engine.cc
  src/relay/backend/contrib/codegen_c/codegen.cc
  src/relay/backend/contrib/codegen_c/codegen_c.h
  src/relay/backend/contrib/dnnl/codegen.cc
  src/relay/backend/graph_runtime_codegen.cc
  src/relay/backend/utils.h
  src/relay/backend/vm/compiler.cc
  src/runtime/graph/graph_runtime.cc
  src/runtime/meta_data.h
  src/runtime/metadata_module.cc
  src/target/source/codegen_source_base.h
  src/target/source/source_module.cc
  tests/python/frontend/onnx/test_forward.py
  tests/python/relay/test_external_codegen.py
  tests/python/relay/test_external_runtime.py
  tests/python/unittest/test_runtime_module_export.py
Labels: status: accepted

#5740 [Object] Introduce POD-C Compliant tvm::Map
  3rdparty/compiler-rt/builtin_fp16.h
  CMakeLists.txt
  apps/android_deploy/app/src/main/jni/Android.mk
  apps/android_rpc/app/src/main/jni/Android.mk
  apps/howto_deploy/Makefile
  cmake/config.cmake
  include/tvm/node/container.h
  include/tvm/runtime/container.h
  include/tvm/runtime/object.h
  src/ir/expr.cc
  src/ir/module.cc
  src/node/container.cc
  src/node/reflection.cc
  src/node/serialization.cc
  src/runtime/object_internal.h
  src/tir/ir/transform.cc
  src/tir/transforms/split_host_device.cc
  tests/cpp/container_test.cc
Labels: status: accepted

#5601 [DataType] Add bfloat16
  include/tvm/runtime/data_type.h
  include/tvm/tir/op.h
  include/tvm/tir/transform.h
  python/tvm/_ffi/runtime_ctypes.py
  python/tvm/driver/build_module.py
  python/tvm/tir/transform/transform.py
  src/driver/driver_api.cc
  src/tir/transforms/bf16_legalize.cc
  tests/python/unittest/test_target_codegen_llvm.py
  tests/python/unittest/test_tir_transform_bf16_legalize.py
Labels: status: need review

#5847 [DOCS] Update has_dtype/has_shape to pattern lang doc
  docs/langref/relay_pattern.rst
Labels: status: need review

#5838 [Target] Introduce Target Id Registry
  include/tvm/ir/op.h
  include/tvm/node/attr_registry_map.h
  include/tvm/runtime/registry.h
  include/tvm/target/target_id.h
  src/node/attr_registry.h
  src/target/target_id.cc
  tests/cpp/target_test.cc
Labels: status: need review

#5805 [QUANTIZE] Add nn.batch_flatten as quantizable.
  python/tvm/relay/quantize/_partition.py
  src/relay/quantize/realize.cc
  tests/python/relay/test_pass_auto_quantize.py
Labels: status: need review

#5834 Improve type handling in PyTorch frontend
  python/tvm/relay/frontend/pytorch.py
  tests/python/frontend/pytorch/qnn_test.py
  tests/python/frontend/pytorch/test_forward.py
Labels: status: need review

#5887 keep parameter names from PyTorch
  python/tvm/relay/frontend/pytorch.py
  tests/python/frontend/pytorch/test_forward.py
Labels: status: need review

#5655 Add MicroTVM tutorial using the STM32F746 discovery board
  docs/conf.py
  tutorials/micro/README.txt
  tutorials/micro/micro_tflite.py
Labels: status: need review

#5918 [Thread Backend]Fix CPU Thread Binding for Multiple Sockets
  src/runtime/threading_backend.cc
Labels: status: need review

#5922 [BACKPORT-0.6][Bugfix][Arith] keep div_mode during floordiv simplify
  src/arith/canonical_simplify.cc
  tests/python/unittest/test_arith_canonical_simplify.py
Labels: status: need test case

#5924 [Arith][GPU]Rewrite simplify fix for Vectorized Cooperative Fetching
  src/arith/rewrite_simplify.cc
  tests/python/unittest/test_arith_rewrite_simplify.py
  tests/python/unittest/test_target_codegen_cuda.py
Labels: status: need test case, status: need update

#5926 [Runtime] Only initialize required module
  src/runtime/metadata_module.cc
Labels: status: need review

#5934 [CODEGEN][CONTRIB] Various update for CoreML codegen
  apps/ios_rpc/tvmrpc/TVMRuntime.mm
  python/tvm/contrib/target/coreml.py
  src/runtime/contrib/coreml/coreml_runtime.mm
  tests/python/contrib/test_coreml_codegen.py
Labels: status: need review

#5933 Fix string argument mismatch in GraphRuntimeCodegen
  python/tvm/autotvm/task/relay_integration.py
  src/relay/backend/graph_runtime_codegen.cc
Labels: status: need update

#5844 [Relay] symbolic max_output_size
  include/tvm/relay/attrs/vision.h
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/op/strategy/generic.py
  python/tvm/relay/op/vision/nms.py
  src/relay/op/vision/nms.cc
  tests/python/frontend/tensorflow/test_forward.py
  tests/python/relay/test_op_level5.py
  topi/python/topi/cuda/nms.py
  topi/python/topi/vision/nms.py
  topi/tests/python/test_topi_vision.py
Labels: status: need update

#5857 [OpenCL] Fix OpenCL get_valid_counts errors due to intrinsic atomic_add
  src/target/source/codegen_opencl.cc
  src/target/source/codegen_opencl.h
  tests/python/relay/test_op_level5.py
  topi/python/topi/cuda/nms.py
Labels: status: need review, status: need update

#5946 [RELAY][GRAD] handle Tuple/TupleGetItem in first order gradient
  src/relay/transforms/gradient.cc
  src/relay/transforms/pattern_util.h
  tests/python/relay/test_pass_gradient.py
Labels: status: need review

#5941 Amendments for gradients
  python/tvm/relay/op/_tensor_grad.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/transform.py
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_op_grad_level1.py
  tests/python/relay/test_op_grad_level10.py
  tests/python/relay/test_op_grad_level3.py
  tests/python/relay/test_op_level10.py
Labels: status: need review

#5758 Fix the meaning of conv{1,2}d_transpose output_padding parameter.
  python/tvm/autotvm/tophub.py
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  python/tvm/relay/op/strategy/generic.py
  tests/python/relay/test_op_level2.py
  topi/python/topi/arm_cpu/conv2d_transpose.py
  topi/python/topi/cuda/conv1d_transpose_ncw.py
  topi/python/topi/cuda/conv2d_transpose_nchw.py
  topi/python/topi/nn/conv1d_transpose.py
  topi/python/topi/nn/conv2d_transpose.py
  topi/python/topi/testing/conv1d_transpose_ncw_python.py
  topi/python/topi/testing/conv2d_transpose_python.py
  topi/python/topi/x86/conv2d_transpose.py
  topi/tests/python/test_topi_conv1d_transpose_ncw.py
  topi/tests/python/test_topi_conv2d_transpose_nchw.py
  vta/python/vta/top/vta_conv2d_transpose.py
  vta/scripts/tune_conv2d_transpose.py
  vta/tests/python/integration/test_benchmark_topi_conv2d_transpose.py
Labels: status: need review

#5925 Fix small typo in nn.conv2d_gemm_weight_transform
  topi/python/topi/arm_cpu/conv2d_gemm.py
  topi/python/topi/nn/conv2d.py
  topi/tests/python/test_topi_conv2d_int8.py
Labels: status: need test case
