Repository apache/tvm, pull requests merged in 2021-11, with the labels that each got.

#9394 [docs][bug] Add redirects for moved pages
  docs/conf.py
  docs/legacy_redirect.py
Labels: type: doc

#8777 [PyTorch]Add PyTorchTVM: compile torchscript to tvm and export as pytorch_op
  CMakeLists.txt
  apps/pt_tvmdsoop/CMakeLists.txt
  apps/pt_tvmdsoop/prepare_and_test_pt_tvm_class.sh
  apps/pt_tvmdsoop/tests/test_torch_compile_cpu.py
  apps/pt_tvmdsoop/tests/test_torch_compile_gpu.py
  apps/pt_tvmdsoop/tests/test_torch_graph_module.py
  apps/pt_tvmdsoop/tests/test_torch_script.py
  apps/pt_tvmdsoop/tests/test_torch_vm_module.py
  apps/pt_tvmdsoop/tests/test_trace_tvm_module.py
  cmake/config.cmake
  cmake/modules/LibInfo.cmake
  cmake/modules/contrib/PT_TVMDSOOP.cmake
  python/tvm/contrib/torch/__init__.py
  python/tvm/contrib/torch/module.py
  python/tvm/contrib/torch/pytorch_tvm.py
  src/contrib/torch/pt_call_tvm/tvm_class.cc
  src/contrib/torch/utils.h
Labels: status: need review

#9472 [CI] Make `version.py` to rely on repository metadata to generate version string
  version.py
Labels: type:ci

#9360 [TensorIR] Cross-Thread Reduction
  include/tvm/tir/transform.h
  python/tvm/tir/transform/transform.py
  src/driver/driver_api.cc
  src/tir/schedule/analysis.h
  src/tir/schedule/analysis/analysis.cc
  src/tir/schedule/primitive/reduction.cc
  src/tir/transforms/lower_cross_thread_reduction.cc
  tests/python/unittest/test_tir_transform_lower_cross_thread_reduction.py
Labels: status: need review
