Repository apache/tvm, pull requests merged in 2021-04, with the labels that each got.

#7692 [TE] Bugfix for reduction that involves multi-outs with where cond
  src/te/operation/compute_op.cc
  tests/python/unittest/test_te_tensor.py
Labels: status: need review

#7760 [ARITH] Subspace division
  include/tvm/arith/iter_affine_map.h
  python/tvm/arith/__init__.py
  python/tvm/arith/iter_affine_map.py
  src/arith/iter_affine_map.cc
  tests/python/unittest/test_arith_iter_affine_map.py
Labels: status: need review

#7784 [Hexagon] Reenable compilation of TVM runtime for Hexagon
  CMakeLists.txt
  cmake/modules/Hexagon.cmake
  src/runtime/hexagon/sim/driver/CMakeLists.txt
  src/support/utils.h
Labels: status: need review

#7739 [TVMC] Separate model loading from model compilation in TVMC.
  python/tvm/driver/tvmc/compiler.py
  tests/python/driver/tvmc/conftest.py
  tests/python/driver/tvmc/test_compiler.py
Labels: status: accepted

#7768 [docs] Getting Started With TVM: Tensor Expressions
  tutorials/get_started/tensor_expr_get_started.py
Labels: status: accepted

#7791 [Target] Fix empty target and host for autotvm task
  python/tvm/autotvm/task/task.py
  python/tvm/target/target.py
  tests/python/integration/test_tuning.py
  tests/python/unittest/test_target_target.py
Labels: status: accepted

#7776 [CI] docker images build script cmd line args optional
  docker/README.md
  docker/build.sh
Labels: status: need review

#7767 [docs] Getting Started with TVM: Auto Tuning with Python
  docs/conf.py
  tutorials/get_started/auto_tuning_with_python.py
Labels: status: need update, status: review in progress

#7765 [M1b] Scaffolding ScheduleState data structure
  include/tvm/runtime/object.h
  include/tvm/tir/schedule/block_scope.h
  include/tvm/tir/schedule/state.h
  python/tvm/tir/__init__.py
  python/tvm/tir/schedule/__init__.py
  python/tvm/tir/schedule/_ffi_api_schedule.py
  python/tvm/tir/schedule/block_scope.py
  python/tvm/tir/schedule/state.py
  python/tvm/tir/stmt.py
  src/printer/tvmscript_printer.cc
  src/tir/analysis/var_touch.cc
  src/tir/ir/stmt.cc
  src/tir/schedule/analysis.h
  src/tir/schedule/analysis/analysis.cc
  src/tir/schedule/analysis/verify.cc
  src/tir/schedule/block_scope.cc
  src/tir/schedule/state.cc
  src/tir/schedule/utils.h
  tests/python/unittest/test_tir_block_scope.py
  tests/python/unittest/test_tir_schedule_state.py
Labels: status: need review

#7577 [TVMC][VitisAI] Enable Vitis AI target through TVMC
  docker/install/ubuntu_install_vitis_ai_core.sh
  docs/deploy/vitis_ai.rst
  python/tvm/contrib/target/vitis_ai.py
  python/tvm/driver/tvmc/autotuner.py
  python/tvm/driver/tvmc/compiler.py
  python/tvm/driver/tvmc/composite_target.py
  python/tvm/relay/op/contrib/arm_compute_lib.py
  python/tvm/relay/op/contrib/ethosn.py
  python/tvm/relay/op/contrib/vitis_ai.py
  src/relay/backend/contrib/vitis_ai/config_vitis_ai.cc
  src/runtime/contrib/vitis_ai/vitis_ai_runtime.cc
  src/runtime/contrib/vitis_ai/vitis_ai_runtime.h
  tests/python/contrib/test_vitis_ai/infrastructure.py
  tests/python/driver/tvmc/test_compiler.py
  tests/python/driver/tvmc/test_composite_target.py
Labels: status: accepted

#7503 [Rust] Make TVM Rust bindings installable via Cargo.
  rust/tvm-graph-rt/Cargo.toml
  rust/tvm-graph-rt/README.md
  rust/tvm-macros/Cargo.toml
  rust/tvm-macros/README.md
  rust/tvm-rt/Cargo.toml
  rust/tvm-rt/src/ndarray.rs
  rust/tvm-sys/Cargo.toml
  rust/tvm-sys/README.md
  rust/tvm-sys/build.rs
  rust/tvm-sys/src/byte_array.rs
  rust/tvm-sys/src/lib.rs
  rust/tvm/Cargo.toml
  rust/tvm/README.md
  tests/scripts/task_rust.sh
Labels: status: need update

#7789 [TF frontend][bugfix]Avoid making a new node when already has span info
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#7717 [Vulkan] Support uniform buffer object for passing many scalar arguments
  src/runtime/vulkan/vulkan.cc
  src/runtime/vulkan/vulkan_common.h
  src/target/spirv/codegen_spirv.cc
  src/target/spirv/ir_builder.cc
  src/target/spirv/ir_builder.h
Labels: status: need review

#7816 [TVMC] --disable-pass option added to compile mode
  python/tvm/driver/tvmc/common.py
  python/tvm/driver/tvmc/compiler.py
  tests/python/driver/tvmc/test_common.py
  tests/python/driver/tvmc/test_compiler.py
Labels: status: accepted

#7826 [RUNTIME] Add clear() function in tvm::Map class
  include/tvm/runtime/container.h
  tests/cpp/container_test.cc
Labels: status: need review

#7844 [ONNX] Make input shape immutable
  python/tvm/relay/frontend/onnx.py
Labels: status: review in progress

#7846 [BugFix] Print doubles with precision 17 in SaveJSON and TVM script printer
  src/node/serialization.cc
  src/printer/tvmscript_printer.cc
  tests/python/unittest/test_node_reflection.py
Labels: status: review in progress

#7796 [TOPI, Relay] A new NMS op variant for ONNX NMS / TF Combined NMS
  include/tvm/relay/attrs/vision.h
  python/tvm/relay/frontend/onnx.py
  python/tvm/relay/op/op_attrs.py
  python/tvm/relay/op/strategy/cuda.py
  python/tvm/relay/op/strategy/generic.py
  python/tvm/relay/op/vision/_vision.py
  python/tvm/relay/op/vision/nms.py
  python/tvm/topi/cuda/__init__.py
  python/tvm/topi/cuda/nms.py
  python/tvm/topi/cuda/scan.py
  python/tvm/topi/cuda/sort.py
  python/tvm/topi/cuda/vision.py
  python/tvm/topi/vision/nms.py
  python/tvm/topi/vision/nms_util.py
  src/relay/op/vision/nms.cc
  tests/python/frontend/onnx/test_forward.py
  tests/python/relay/test_op_level5.py
  tests/python/topi/python/test_topi_vision.py
Labels: status: need review

#7845 Fix PyTorch matmul conversion when given (2-dim, N-dim) input pair
  python/tvm/relay/frontend/pytorch.py
  tests/python/frontend/pytorch/test_forward.py
Labels: status: review in progress

#7835 [ConvertLayout] Squeeze and reduce ops
  src/relay/op/tensor/reduce.cc
  src/relay/op/tensor/transform.cc
  src/relay/transforms/convert_layout.cc
  tests/python/relay/test_pass_convert_op_layout.py
Labels: status: review in progress

#7833 [Vulkan] Support uniform buffer object for passing many scalar arguments (Take 2)
  src/runtime/vulkan/vulkan.cc
  src/runtime/vulkan/vulkan_common.h
  src/target/spirv/build_vulkan.cc
  src/target/spirv/codegen_spirv.cc
  src/target/spirv/codegen_spirv.h
  src/target/spirv/ir_builder.cc
  src/target/spirv/ir_builder.h
Labels: status: need review

#7825 [TIR] Add a new intrinsic count leading zeros for LLVM and SPIR-V
  include/tvm/tir/op.h
  python/tvm/tir/__init__.py
  python/tvm/tir/op.py
  src/target/llvm/intrin_rule_llvm.cc
  src/target/spirv/intrin_rule_spirv.cc
  src/tir/op/op.cc
  tests/python/unittest/test_tir_intrin.py
Labels: status: need review

#7848 [TensorIR][M1c] LCA detector
  include/tvm/tir/analysis.h
  python/tvm/tir/analysis/analysis.py
  src/tir/analysis/buffer_access_lca_detector.cc
  tests/python/unittest/test_tir_analysis_detect_buffer_access_lca.py
Labels: status: need update, status: review in progress

#7819 [METAL] Fix issue with GPU fails
  python/tvm/_ffi/runtime_ctypes.py
  python/tvm/auto_scheduler/measure.py
  src/runtime/c_runtime_api.cc
  src/runtime/crt/common/crt_runtime_api.c
  src/runtime/metal/metal_common.h
  src/runtime/metal/metal_device_api.mm
  src/runtime/metal/metal_module.mm
  src/runtime/minrpc/minrpc_server.h
  src/runtime/minrpc/rpc_reference.h
  src/runtime/rpc/rpc_device_api.cc
  src/runtime/rpc/rpc_endpoint.cc
Labels: status: need review

#7847 [TensorIR][M1b] Schedule class
  include/tvm/tir/schedule/schedule.h
  python/tvm/error.py
  python/tvm/tir/__init__.py
  python/tvm/tir/schedule/__init__.py
  python/tvm/tir/schedule/schedule.py
  src/tir/schedule/analysis.h
  src/tir/schedule/analysis/analysis.cc
  src/tir/schedule/concrete_schedule.cc
  src/tir/schedule/concrete_schedule.h
  src/tir/schedule/schedule.cc
  tests/python/unittest/test_tir_schedule_utilities.py
Labels: status: need review

#7832 [Relay] Recursive destructor call replaced with non-recursive for Call nodes.
  include/tvm/relay/expr.h
  src/relay/ir/expr.cc
  tests/cpp/relay_dismantler_test.cc
Labels: status: need review

#7873 [TensorIR][PASS][M1c] PlanUpdateBufferAllocationLocation
  include/tvm/tir/transform.h
  python/tvm/tir/transform/transform.py
  src/tir/transforms/plan_update_buffer_allocation_location.cc
  tests/python/unittest/test_tir_transform_plan_update_buffer_allocation_location.py
Labels: status: need review

#7842 [ONNX] Fix more upstream tests
  include/tvm/topi/transform.h
  python/tvm/relay/frontend/onnx.py
  python/tvm/relay/op/dyn/_transform.py
  tests/python/frontend/onnx/test_forward.py
  tests/python/relay/dyn/test_dynamic_op_level4.py
Labels: status: need review

#7797 [PROFILER] Add CSV output to profiler
  include/tvm/runtime/profiling.h
  python/tvm/runtime/__init__.py
  python/tvm/runtime/profiling.py
  src/node/structural_hash.cc
  src/runtime/graph_executor/debug/graph_executor_debug.cc
  src/runtime/profiling.cc
  src/runtime/vm/profiler/vm.cc
  tests/python/unittest/test_runtime_profiling.py
  tests/python/unittest/test_runtime_vm_profiler.py
Labels: status: need review

#7869 Update ICHECK error message with link to documentation page.
  docs/errors.rst
  docs/index.rst
  include/tvm/runtime/logging.h
Labels: status: need update

#7817 RelayTextPrinter is now non-recursive. ExpandDataflow refactored
  include/tvm/relay/expr_functor.h
  src/printer/relay_text_printer.cc
  src/printer/text_printer.h
  src/relay/analysis/dependency_graph.cc
  tests/cpp/relay_text_printer_test.cc
Labels: status: need review

#7895 [ConvertLayout] Keep span in ConvertLayout
  src/relay/transforms/convert_layout.cc
  src/relay/transforms/forward_rewrite.cc
  src/relay/transforms/transform_layout.h
  tests/python/relay/test_pass_convert_op_layout.py
Labels: status: need review

#7880 [BugFix]: Convert tuple to int
  python/tvm/topi/testing/conv2d_hwcn_python.py
  tests/python/topi/python/test_topi_conv2d_hwcn.py
Labels: status: accepted

#7911 [CodeGenC] Fix bugs when calling extern functions
  python/tvm/runtime/module.py
  src/target/source/codegen_c.cc
  src/target/source/codegen_c_host.cc
  src/target/source/codegen_c_host.h
  tests/python/contrib/test_cblas.py
  tests/python/unittest/test_target_codegen_c_host.py
Labels: status: need review

#7795 [FIX] skip_conv_layers will affect quantization of nn.dense
  python/tvm/relay/quantize/quantize.py
  src/relay/quantize/quantize.cc
  tests/python/relay/test_pass_auto_quantize.py
Labels: status: need review

#7890 Remove pointer arithmetic in StorageObj::AllocNDArray
  src/runtime/vm/memory_manager.cc
Labels: status: need review

#7920 [Tensorize] Fix compute reusing
  src/te/operation/tensorize.cc
  tests/python/unittest/test_te_schedule_tensorize.py
Labels: status: need review

#7923 [TensorIR][PASS][M1c] CompactBufferAllocation
  include/tvm/tir/expr.h
  include/tvm/tir/stmt.h
  include/tvm/tir/transform.h
  python/tvm/tir/transform/transform.py
  src/support/utils.h
  src/tir/ir/stmt.cc
  src/tir/transforms/compact_buffer_region.cc
  src/tir/transforms/convert_blocks_to_opaque.cc
  tests/python/unittest/test_tir_transform_compact_buffer_region.py
  tests/python/unittest/test_tir_transform_convert_blocks_to_opaque.py
Labels: status: accepted
