Repository apache/tvm, pull requests merged in 2021-03, with the labels that each got.

#7553 [TensorIR] introduce Block and BlockRealize
  include/tvm/tir/stmt.h
  include/tvm/tir/stmt_functor.h
  python/tvm/tir/__init__.py
  python/tvm/tir/stmt.py
  src/tir/ir/stmt.cc
  src/tir/ir/stmt_functor.cc
  tests/cpp/ir_functor_test.cc
  tests/python/unittest/test_tir_nodes.py
Labels: status: need review

#7561 [Codegen][CUDA] Fix: cuda codegen vectorize cast
  src/target/source/codegen_cuda.cc
  tests/python/unittest/test_target_codegen_cuda.py
Labels: status: need review

#7425 [TIR] Add TIR While node
  include/tvm/tir/stmt.h
  include/tvm/tir/stmt_functor.h
  python/tvm/tir/ir_builder.py
  python/tvm/tir/stmt.py
  python/tvm/topi/cuda/nms.py
  src/printer/text_printer.h
  src/printer/tir_text_printer.cc
  src/target/llvm/codegen_llvm.cc
  src/target/llvm/codegen_llvm.h
  src/target/source/codegen_c.cc
  src/target/source/codegen_c.h
  src/tir/ir/stmt.cc
  src/tir/ir/stmt_functor.cc
  src/tir/transforms/coproc_sync.cc
  src/tir/transforms/inject_virtual_thread.cc
  src/tir/transforms/lift_attr_scope.cc
  src/tir/transforms/storage_access.cc
  src/tir/transforms/storage_access.h
  src/tir/transforms/storage_rewrite.cc
  src/tir/transforms/vectorize_loop.cc
  tests/python/unittest/test_tir_ir_builder.py
  tests/python/unittest/test_tir_transform_storage_rewrite.py
  tests/python/unittest/test_tir_transform_vectorize.py
Labels: status: need review, status: need test case, status: need update

#7497 [Tensorize] Support conds depend on outer loop vars inside tensorize scope
  src/te/operation/op_utils.cc
  src/te/operation/op_utils.h
  src/te/operation/tensorize.cc
  tests/python/unittest/test_te_schedule_tensorize.py
Labels: status: need review

#7432 [Relay][Quantization] Fix Bug Which Cause Negative Left Shift Op
  src/relay/quantize/realize.cc
Labels: status: need test case

#7570 [RUNTIME] Move Map into runtime
  include/tvm/arith/bound.h
  include/tvm/arith/pattern.h
  include/tvm/ir/adt.h
  include/tvm/ir/expr.h
  include/tvm/ir/module.h
  include/tvm/ir/transform.h
  include/tvm/ir/type.h
  include/tvm/node/attr_registry_map.h
  include/tvm/node/container.h
  include/tvm/node/node.h
  include/tvm/node/structural_equal.h
  include/tvm/node/structural_hash.h
  include/tvm/relay/feature.h
  include/tvm/runtime/container.h
  include/tvm/runtime/packed_func.h
  include/tvm/te/tensor.h
  include/tvm/tir/buffer.h
  include/tvm/tir/expr.h
  include/tvm/tir/stmt_functor.h
  python/tvm/ir/container.py
  python/tvm/runtime/object_generic.py
  rust/tvm-rt/src/array.rs
  rust/tvm-rt/src/map.rs
  rust/tvm/src/ir/diagnostics/mod.rs
  src/node/container.cc
  src/node/reflection.cc
  src/node/serialization.cc
  src/node/structural_hash.cc
  src/printer/meta_data.h
  src/relay/backend/contrib/codegen_json/codegen_json.h
  src/relay/op/nn/nn.h
  src/runtime/container.cc
  src/runtime/file_utils.cc
  src/runtime/file_utils.h
  src/runtime/graph/graph_runtime_factory.cc
  src/runtime/metadata_module.cc
  src/support/libinfo.cc
Labels: status: need review

#7506 [ETHOSN] Add support for 20.11 Ethos-N driver stack release
  cmake/utils/FindEthosN.cmake
  src/relay/backend/contrib/ethosn/capabilities.h
  src/relay/backend/contrib/ethosn/codegen.cc
  src/relay/backend/contrib/ethosn/codegen_ethosn.h
  src/relay/backend/contrib/ethosn/ethosn_api.cc
  src/relay/backend/contrib/ethosn/ethosn_api_version.h
  tests/python/contrib/test_ethosn/test_networks.py
  tests/python/contrib/test_ethosn/test_reshape.py
Labels: status: need review

#7572 [Vulkan] Support passing 64 bit scalar
  src/runtime/metal/metal_module.mm
  src/runtime/pack_args.h
  src/runtime/vulkan/vulkan.cc
  src/target/source/codegen_metal.cc
  src/target/spirv/intrin_rule_spirv.cc
  tests/python/topi/python/test_topi_cumsum.py
  tests/python/topi/python/test_topi_vision.py
Labels: status: need review

#7566 Fix autotuning, broken in #7337
  python/tvm/autotvm/measure/measure_methods.py
  tests/python/integration/test_tuning.py
Labels: status: accepted

#7472 [RUNTIME] Add device specific timers
  include/tvm/runtime/profiling.h
  src/runtime/cuda/cuda_device_api.cc
  src/runtime/graph/debug/graph_runtime_debug.cc
  src/runtime/profiling.cc
  src/runtime/rocm/rocm_device_api.cc
  src/runtime/vm/profiler/vm.cc
  src/runtime/vm/profiler/vm.h
  tests/cpp/profiling.cc
Labels: status: need review, status: need update

#7313 [AutoSchedule] Sparse dense tuning support with custom sketch rule
  include/tvm/auto_scheduler/measure_record.h
  include/tvm/auto_scheduler/search_task.h
  python/tvm/auto_scheduler/__init__.py
  python/tvm/auto_scheduler/measure.py
  python/tvm/auto_scheduler/search_task.py
  python/tvm/auto_scheduler/utils.py
  python/tvm/topi/nn/sparse.py
  src/auto_scheduler/feature.cc
  src/auto_scheduler/measure_record.cc
  src/auto_scheduler/search_policy/utils.cc
  src/auto_scheduler/search_task.cc
  tests/python/unittest/test_auto_scheduler_measure.py
  tests/python/unittest/test_auto_scheduler_search_task.py
  tutorials/auto_scheduler/ci_logs/sparse_dense.json
  tutorials/auto_scheduler/tune_sparse_x86.py
Labels: status: need review

#7014 [CUDA] BF16 support
  include/tvm/runtime/data_type.h
  python/tvm/contrib/nvcc.py
  python/tvm/runtime/ndarray.py
  src/target/source/codegen_cuda.cc
  src/target/source/codegen_cuda.h
  src/target/source/intrin_rule_cuda.cc
  src/target/source/literal/cuda_half_t.h
  tests/python/unittest/test_target_codegen_cuda.py
Labels: status: need review

#7593 [FIX] Fix clang12 warnings
  src/relay/backend/contrib/tensorrt/codegen.cc
  src/runtime/contrib/cublas/cublas.cc
  src/runtime/contrib/cublas/cublas_utils.cc
  src/runtime/contrib/json/json_runtime.h
  src/runtime/micro/micro_session.cc
Labels: status: need update

#7533 Introduce Model Library Format export format
  python/tvm/micro/__init__.py
  python/tvm/micro/model_library_format.py
  python/tvm/relay/backend/graph_runtime_factory.py
  python/tvm/relay/build_module.py
  python/tvm/runtime/module.py
  src/runtime/graph/graph_runtime_factory.cc
  tests/python/unittest/test_micro_model_library_format.py
Labels: status: need review

#7390 fix:getcwd not work on android platform
  apps/cpp_rpc/rpc_env.cc
  apps/cpp_rpc/rpc_server.cc
Labels: status: need review

#7335 Improve tensor mismatch ICHECK message
  src/te/tensor.cc
Labels: status: need review, status: need update

#7556 Remove pytest dependency in arm_compute_lib.py
  python/tvm/relay/op/contrib/arm_compute_lib.py
Labels: status: need update

#7616 [Runtime] Extend Graph Runtime To Support Cuda Graph Launch
  CMakeLists.txt
  cmake/config.cmake
  cmake/modules/CUDA.cmake
  python/tvm/contrib/cuda_graph/__init__.py
  python/tvm/contrib/cuda_graph/cuda_graph_runtime.py
  python/tvm/contrib/nvcc.py
  python/tvm/testing.py
  src/runtime/graph/cuda_graph/graph_runtime_cuda_graph.cc
  src/runtime/graph/graph_runtime_factory.cc
  src/runtime/graph/graph_runtime_factory.h
  tests/python/unittest/test_runtime_graph_cuda_graph.py
  tests/python/unittest/test_runtime_module_based_interface.py
Labels: status: need review

#7496 [Frontend,TOPI] Improve dynamism for BatchMatmul and Dense
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/topi/cuda/batch_matmul.py
  python/tvm/topi/cuda/dense.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review, status: need update

#7677 [Relay][Training][Pass] Factor out first-order AD to a module pass
  python/tvm/relay/transform/transform.py
  src/relay/transforms/first_order_gradient.cc
  src/relay/transforms/gradient.h
  src/relay/transforms/higher_order_gradient.cc
Labels: status: need review

#7670 [CPP_RPC] allow user supplied work dir
  apps/cpp_rpc/main.cc
  apps/cpp_rpc/rpc_env.cc
  apps/cpp_rpc/rpc_env.h
  apps/cpp_rpc/rpc_server.cc
  apps/cpp_rpc/rpc_server.h
Labels: status: need review

#7630 [TensorIR] TVMScript Parser/Printer
  include/tvm/tir/analysis.h
  python/tvm/script/context_maintainer.py
  python/tvm/script/intrin.py
  python/tvm/script/node.py
  python/tvm/script/parser.py
  python/tvm/script/registry.py
  python/tvm/script/scope_handler.py
  python/tvm/script/special_stmt.py
  python/tvm/script/utils.py
  python/tvm/tir/analysis/analysis.py
  src/printer/tir_text_printer.cc
  src/printer/tvmscript_printer.cc
  src/tir/analysis/block_access_region_detector.cc
  src/tir/ir/script/script_complete.cc
  tests/python/unittest/test_tir_analysis_get_block_access_region.py
  tests/python/unittest/test_tvmscript_error_report.py
  tests/python/unittest/test_tvmscript_roundtrip.py
  tests/scripts/task_ci_python_setup.sh
  tests/scripts/task_ci_setup.sh
Labels: status: need review

#7714 [METAL] Fix memory leaks in Metal runtime
  src/runtime/contrib/random/mt_random_engine.cc
  src/runtime/metal/metal_device_api.mm
  src/runtime/metal/metal_module.mm
Labels: status: need review

#6137 Better grouped convolution for CPU targets
  python/tvm/relay/op/strategy/arm_cpu.py
  python/tvm/relay/op/strategy/x86.py
  python/tvm/topi/arm_cpu/__init__.py
  python/tvm/topi/arm_cpu/group_conv2d.py
  python/tvm/topi/x86/__init__.py
  python/tvm/topi/x86/group_conv2d.py
Labels: status: need review, status: need update

#7752 [ARITH] detect iter affine map with predicate
  include/tvm/arith/analyzer.h
  include/tvm/arith/iter_affine_map.h
  include/tvm/tir/analysis.h
  python/tvm/arith/iter_affine_map.py
  src/arith/analyzer.cc
  src/arith/expr_complexity.cc
  src/arith/iter_affine_map.cc
  src/arith/solve_linear_inequality.cc
  tests/python/unittest/test_arith_iter_affine_map.py
Labels: status: need review, status: need update

#7759 [ARITH] normalize iter affine map expr to PrimExpr
  python/tvm/arith/__init__.py
  python/tvm/arith/iter_affine_map.py
  src/arith/iter_affine_map.cc
  src/tir/analysis/expr_complexity.cc
  tests/python/unittest/test_arith_iter_affine_map.py
Labels: status: accepted

#7733 [crt] fix shift out of type bounds
  src/runtime/crt/common/crt_runtime_api.c
Labels: status: need review

#7731 [Relay][Pass] ConcretizeLike and EliminateIdentity rewrites for SimplifyExpr
  src/relay/transforms/dynamic_to_static.cc
  src/relay/transforms/pattern_utils.h
  src/relay/transforms/simplify_expr.cc
  src/relay/transforms/simplify_expr.h
  tests/python/relay/test_pass_simplify_expr.py
Labels: status: accepted
