Repository apache/tvm, pull requests merged in 2021-05, with the labels that each got.

#7834 [OpenCL] Refactor cl_program generation
  src/runtime/opencl/opencl_common.h
  src/runtime/opencl/opencl_module.cc
  src/target/source/codegen_opencl.cc
Labels: status: need review

#7929 [Topi] Fix arm_cpu bitserial schedule with elemwise ops.
  python/tvm/topi/arm_cpu/bitserial_conv2d.py
  tests/python/topi/python/test_topi_bitserial_conv2d_rasp.py
Labels: status: accepted

#7766 Replace 0.0.0.0 with 127.0.0.1 for client connections
  apps/benchmark/arm_cpu_imagenet_bench.py
  apps/benchmark/mobile_gpu_imagenet_bench.py
  docs/deploy/arm_compute_lib.rst
  jvm/README.md
  jvm/core/src/test/java/org/apache/tvm/contrib/GraphExecutorTest.java
  jvm/core/src/test/java/org/apache/tvm/rpc/RPCTest.java
  jvm/core/src/test/scripts/test_rpc_proxy_server.py
  python/tvm/auto_scheduler/measure.py
  python/tvm/autotvm/database.py
  python/tvm/autotvm/graph_tuner/base_graph_tuner.py
  python/tvm/autotvm/measure/measure_methods.py
  python/tvm/error.py
  python/tvm/exec/measure_peak.py
  python/tvm/exec/query_rpc_tracker.py
  python/tvm/exec/rpc_proxy.py
  python/tvm/exec/rpc_server.py
  python/tvm/exec/rpc_tracker.py
  python/tvm/rpc/proxy.py
  python/tvm/rpc/server.py
  python/tvm/rpc/tracker.py
  tests/python/contrib/test_arm_compute_lib/infrastructure.py
  tests/python/contrib/test_arm_compute_lib/test_config.json
  tests/python/contrib/test_bnns/infrastructure.py
  tests/python/contrib/test_coreml_runtime.py
  tests/python/contrib/test_edgetpu_runtime.py
  tests/python/contrib/test_random.py
  tests/python/contrib/test_rpc_tracker.py
  tests/python/contrib/test_tflite_runtime.py
  tests/python/unittest/test_runtime_graph.py
  tests/python/unittest/test_runtime_graph_debug.py
  tests/python/unittest/test_runtime_module_based_interface.py
  tests/python/unittest/test_runtime_rpc.py
  tutorials/auto_scheduler/tune_network_arm.py
  tutorials/auto_scheduler/tune_network_mali.py
  tutorials/autotvm/tune_relay_arm.py
  tutorials/autotvm/tune_relay_cuda.py
  tutorials/autotvm/tune_relay_mobile_gpu.py
  tutorials/frontend/deploy_model_on_android.py
  vta/python/vta/exec/rpc_server.py
  vta/tutorials/autotvm/tune_relay_vta.py
  web/tests/python/webgpu_rpc_test.py
  web/tests/python/websock_rpc_test.py
Labels: status: need review

#7903 [Graph Executor Debugger] Fix parameter dump
  python/tvm/contrib/debugger/debug_executor.py
  python/tvm/contrib/debugger/debug_result.py
  python/tvm/runtime/ndarray.py
  src/runtime/graph_executor/debug/graph_executor_debug.cc
Labels: status: need update

#7823 [TVMC] A simplified TVMC API for python scripting (Part 1).
  python/tvm/auto_scheduler/search_task.py
  python/tvm/auto_scheduler/task_scheduler.py
  python/tvm/driver/tvmc/__init__.py
  python/tvm/driver/tvmc/autotuner.py
  python/tvm/driver/tvmc/common.py
  python/tvm/driver/tvmc/compiler.py
  python/tvm/driver/tvmc/frontends.py
  python/tvm/driver/tvmc/model.py
  python/tvm/driver/tvmc/result_utils.py
  python/tvm/driver/tvmc/runner.py
  src/auto_scheduler/search_task.cc
  tests/python/driver/tvmc/conftest.py
  tests/python/driver/tvmc/test_autoscheduler.py
  tests/python/driver/tvmc/test_autotuner.py
  tests/python/driver/tvmc/test_command_line.py
  tests/python/driver/tvmc/test_compiler.py
  tests/python/driver/tvmc/test_frontends.py
  tests/python/driver/tvmc/test_model.py
  tests/python/driver/tvmc/test_runner.py
  tests/python/driver/tvmc/test_tvmc_common.py
Labels: status: need review

#7939 [FIX] Fix deploy_sparse tutorial
  tutorials/frontend/deploy_sparse.py
Labels: status: need update

#7902 [FIX,VM] Fix get_outputs on the vm with a single output
  src/runtime/vm/vm.cc
  tests/python/relay/test_vm.py
Labels: status: need update

#7938 Improved MLF to contain workspace info
  python/tvm/micro/model_library_format.py
  python/tvm/relay/backend/executor_factory.py
  python/tvm/relay/build_module.py
  src/relay/backend/aot_executor_codegen.cc
  src/relay/backend/build_module.cc
  src/relay/backend/graph_executor_codegen.cc
  src/relay/backend/utils.cc
  src/relay/backend/utils.h
  src/tir/analysis/calculate_workspace.cc
  tests/python/unittest/test_micro_model_library_format.py
Labels: status: need update

#7771 add onnx reverse sequence op
  python/tvm/relay/frontend/onnx.py
  tests/python/frontend/onnx/test_forward.py
Labels: status: need review

#7919 [RUNTIME] Improve signal handling in python env.
  include/tvm/runtime/c_backend_api.h
  include/tvm/runtime/c_runtime_api.h
  include/tvm/runtime/logging.h
  include/tvm/runtime/registry.h
  python/tvm/_ffi/_cython/base.pxi
  python/tvm/_ffi/_cython/packed_func.pxi
  python/tvm/_ffi/base.py
  src/runtime/registry.cc
  src/runtime/runtime_base.h
  src/support/ffi_testing.cc
  src/support/socket.h
Labels: status: need update

#8017 [IR] Add storage scope to PointerType
  include/tvm/ir/type.h
  python/tvm/ir/type.py
  src/ir/type.cc
  src/ir/type_functor.cc
  src/printer/tir_text_printer.cc
  src/printer/tvmscript_printer.cc
  tests/python/unittest/test_tir_constructor.py
  tests/python/unittest/test_tir_nodes.py
Labels: status: need update

#7875 Custom dyld linker for iOS mach-o executable files
  CMakeLists.txt
  apps/ios_rpc/CMakeLists.txt
  apps/ios_rpc/README.md
  apps/ios_rpc/tests/ios_rpc_test.py
  apps/ios_rpc/tvmrpc.xcodeproj/project.pbxproj
  apps/ios_rpc/tvmrpc/TVMRuntime.mm
  apps/ios_rpc/tvmrpc/ViewController.mm
  cmake/config.cmake
  python/tvm/contrib/xcode.py
Labels: status: need review

#7988 [AOT] Remove lookup parameter function in AOT
  include/tvm/tir/builtin.h
  src/relay/backend/aot_executor_codegen.cc
  src/target/source/codegen_c.cc
  src/target/source/codegen_c_host.cc
  src/target/source/codegen_c_host.h
  src/tir/op/builtin.cc
Labels: status: need update

#8041 [Relay][PRNG] Add uniform distribution generator wrt threefry PRNG
  include/tvm/relay/attrs/random.h
  python/tvm/relay/op/op_attrs.py
  python/tvm/relay/op/random/_kernel.py
  python/tvm/relay/op/random/kernel.py
  python/tvm/relay/op/strategy/generic.py
  python/tvm/topi/random/kernel.py
  src/relay/op/random/kernel.cc
  tests/python/relay/test_prng.py
  tests/python/topi/python/test_topi_prng.py
Labels: status: need review

#8091 [Relay][TOPI] Fix compute and schedule bugs for conv2d_winograd_nhwc on mali device.
  python/tvm/relay/op/strategy/mali.py
  python/tvm/topi/mali/conv2d.py
Labels: status: need review
