Repository apache/tvm, pull requests merged in 2021-01, with the labels that each got.

#7218 [RELAY] Fix reshape header file
  src/relay/op/tensor/transform.h
Labels: status: need review

#7220 [AutoScheduler][Relay] Control compile engine cache via PassContext
  python/tvm/auto_scheduler/relay_integration.py
  src/relay/backend/compile_engine.cc
  src/relay/backend/utils.h
Labels: status: need review

#7045 [Arith] Simplify cast
  src/arith/canonical_simplify.cc
  tests/python/unittest/test_arith_canonical_simplify.py
Labels: status: need review, status: need update

#7206 [BYOC][ACL] Depthwise convolution support
  docs/deploy/arm_compute_lib.rst
  python/tvm/relay/op/contrib/arm_compute_lib.py
  python/tvm/relay/testing/__init__.py
  src/relay/backend/contrib/arm_compute_lib/codegen.cc
  src/runtime/contrib/arm_compute_lib/acl_runtime.cc
  src/runtime/contrib/arm_compute_lib/acl_utils.cc
  src/runtime/contrib/arm_compute_lib/acl_utils.h
  tests/python/contrib/test_arm_compute_lib/infrastructure.py
  tests/python/contrib/test_arm_compute_lib/test_conv2d.py
  tests/python/contrib/test_arm_compute_lib/test_dense.py
  tests/python/contrib/test_arm_compute_lib/test_network.py
Labels: status: need update

#7250 Remove check_correctness in AutoTVM, which is busted
  python/tvm/autotvm/measure/measure_methods.py
  tests/python/unittest/test_autotvm_measure.py
  vta/scripts/tune_conv2d.py
  vta/scripts/tune_conv2d_transpose.py
  vta/scripts/tune_dense.py
  vta/scripts/tune_group_conv2d.py
  vta/scripts/tune_resnet.py
  vta/tests/python/integration/test_benchmark_gemm.py
  vta/tutorials/autotvm/tune_relay_vta.py
Labels: status: need review

#7154 [Torch] Restore class-aware NMS for detection models by graph rewrite
  python/tvm/relay/frontend/pytorch.py
  python/tvm/relay/frontend/pytorch_utils.py
  tests/python/frontend/pytorch/test_object_detection.py
Labels: status: need review

#7195 [THRUST] Faster multi dimensional argsort by segmented sort
  python/tvm/topi/cuda/nms.py
  python/tvm/topi/cuda/sort.py
  src/runtime/contrib/thrust/thrust.cu
Labels: status: need review

#7265 [µTVM] Avoid listing links when probing serial ports
  python/tvm/micro/transport/serial.py
Labels: status: need review

#7213 Reorder dynamic to static and simplify inference, lower DynamicToStatic Opt Level
  src/relay/backend/build_module.cc
  src/relay/transforms/dynamic_to_static.cc
  tests/python/relay/test_op_level1.py
Labels: status: need review

#7231 Adding aten::unsqueeze_ to PT Frontend
  python/tvm/relay/frontend/pytorch.py
  tests/python/frontend/pytorch/test_forward.py
Labels: status: need review

#7148 [Frontend][Tensorflow] Sparse_Dense Op CSR scheduling issue resolved for Cuda & X86
  python/tvm/topi/cuda/sparse.py
  python/tvm/topi/nn/sparse.py
  python/tvm/topi/x86/sparse.py
  tests/python/frontend/tensorflow/test_forward.py
  tests/python/topi/python/test_topi_sparse.py
Labels: status: need test case

#7254 [µTVM] Add ST STM32F746 disco board to tflite tutorial script
  tutorials/micro/micro_tflite.py
Labels: status: need review

#7210 [VM] Per-input, data dependence specification for shape func
  include/tvm/relay/op_attr_types.h
  python/tvm/relay/op/dyn/_transform.py
  python/tvm/relay/op/op.py
  src/relay/analysis/util.cc
  src/relay/backend/compile_engine.cc
  src/relay/transforms/fuse_ops.cc
  src/relay/transforms/pass_utils.h
  tests/cpp/relay_build_module_test.cc
Labels: status: need review

#7084 [TIR] Support Return in TIR
  include/tvm/tir/builtin.h
  include/tvm/tir/op.h
  include/tvm/tir/op_attr_types.h
  python/tvm/tir/__init__.py
  python/tvm/tir/op.py
  src/target/llvm/codegen_llvm.cc
  src/tir/op/builtin.cc
  src/tir/op/op.cc
  src/tir/transforms/make_packed_api.cc
  tests/python/unittest/test_tir_base.py
Labels: status: need review, status: need update

#7260 [AutoScheduler] Bug fix & Custom sketch support
  python/tvm/auto_scheduler/__init__.py
  python/tvm/auto_scheduler/search_policy.py
  python/tvm/auto_scheduler/search_task.py
  python/tvm/auto_scheduler/task_scheduler.py
  src/auto_scheduler/search_policy/sketch_policy.cc
  src/auto_scheduler/search_policy/sketch_policy.h
  src/auto_scheduler/search_policy/sketch_policy_rules.cc
  src/auto_scheduler/search_policy/sketch_policy_rules.h
  tests/python/unittest/test_auto_scheduler_search_policy.py
  tests/python/unittest/test_auto_scheduler_sketch_generation.py
Labels: status: need review

#7251 [BYOC][ACL] removed ACL 20.05 limitations
  python/tvm/relay/op/contrib/arm_compute_lib.py
  tests/python/contrib/test_arm_compute_lib/infrastructure.py
  tests/python/contrib/test_arm_compute_lib/test_dense.py
  tests/python/contrib/test_arm_compute_lib/test_network.py
Labels: status: need review

#6998 [TFLite] Strided slice handling of shrink_axis_mask improved
  python/tvm/relay/frontend/tflite.py
  python/tvm/testing.py
  tests/python/frontend/tflite/test_forward.py
  tests/python/integration/test_dot.py
  tests/python/integration/test_reduce.py
Labels: status: need review

#7314 [TOPI] Rewrite GPU argwhere using exclusive scan
  python/tvm/contrib/nvcc.py
  python/tvm/topi/cuda/argwhere.py
Labels: status: review in progress

#7266 [µTVM] Add TVMPlatformGenerateRandom, a non-cryptographic random number generator.
  include/tvm/runtime/crt/platform.h
  include/tvm/runtime/crt/rpc_common/session.h
  src/runtime/crt/common/crt_runtime_api.c
  src/runtime/crt/host/main.cc
  src/runtime/crt/utvm_rpc_common/session.cc
  src/runtime/crt/utvm_rpc_server/rpc_server.cc
  src/runtime/micro/micro_session.cc
  tests/crt/session_test.cc
  tests/micro/qemu/zephyr-runtime/prj.conf
  tests/micro/qemu/zephyr-runtime/src/main.c
Labels: status: review in progress

#7295 Fix an issue with dynamic functions overwritting call arg types
  src/relay/analysis/type_solver.cc
  src/relay/analysis/type_solver.h
  src/relay/transforms/type_infer.cc
  tests/python/relay/test_type_infer.py
Labels: status: need review

#7286 [BYOC][Verilator] add support to dynamically load hardware library
  cmake/config.cmake
  cmake/modules/contrib/Verilator.cmake
  src/relay/backend/contrib/verilator/codegen.cc
  src/runtime/contrib/verilator/verilator_runtime.cc
  tests/python/contrib/test_verilator/infrastructure.py
Labels: status: need review

#7297 [FIX,AUTOTVM] Add flop counts to cublas
  python/tvm/autotvm/task/task.py
  python/tvm/contrib/cublas.py
  python/tvm/topi/cuda/dense.py
Labels: status: review in progress

#7308 [FIX] Infer input shape in sparse_dense_padded's alter_op if one does not exist
  python/tvm/topi/cuda/sparse.py
  src/relay/transforms/alter_op_layout.cc
Labels: status: need review

#7287 [PRNG] Add check to PRNG to make sure that unsigned integer arithmetic is wrapping
  python/tvm/topi/random/kernel.py
  tests/python/topi/python/test_topi_prng.py
Labels: status: need review

#7321 [Autodiff] Deterministic gradient compute
  src/arith/solve_linear_equation.cc
  src/arith/solve_linear_inequality.cc
  src/te/autodiff/ad_simplify.cc
Labels: status: review in progress

#7353 [Relay][Frontend][Onnx] Robustify Loop Importer
  python/tvm/relay/frontend/onnx.py
  python/tvm/topi/x86/injective.py
  tests/python/frontend/onnx/test_forward.py
Labels: status: review in progress

#7354 [Relay] Fold If when the Condition is Constant
  src/relay/transforms/fold_constant.cc
  tests/python/relay/test_pass_fold_constant.py
Labels: status: review in progress

#7331 Update uTVM code to work with the nRF5340DK dev board.
  apps/microtvm/reference-vm/zephyr/pyproject.toml
  python/tvm/micro/contrib/zephyr.py
  python/tvm/target/target.py
  tests/micro/qemu/conftest.py
  tests/micro/qemu/test_zephyr.py
Labels: status: review in progress

#7267 [Frontend][Tensorflow] Sparse dense matmul adjoint option added
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#7152 [RUNTIME] Improve error messages for TypedPackedFunc
  include/tvm/runtime/packed_func.h
  include/tvm/runtime/registry.h
  src/relay/op/nn/nn.cc
  src/relay/op/nn/sparse.cc
  src/relay/op/tensor/reduce.cc
  src/relay/op/tensor/transform.cc
Labels: status: need update

#7351 [BYOC][Verilator] change runtime registry function name
  src/relay/backend/contrib/verilator/codegen.cc
  src/runtime/contrib/verilator/verilator_runtime.cc
Labels: status: review in progress
