Repository apache/tvm, pull requests merged in 2021-07, with the labels that each got.

#8220 [DOCS] Add docs for Pass Instrument
  docs/api/python/ir.rst
  docs/conf.py
  docs/dev/pass_infra.rst
  python/tvm/ir/instrument.py
  python/tvm/ir/transform.py
  tests/python/relay/test_pass_instrument.py
  tutorials/dev/use_pass_infra.py
  tutorials/dev/use_pass_instrument.py
Labels: status: need review

#8400 Revert "Actually add Compute Library tests to the Jenkins File (#8394)"
  Jenkinsfile
  tests/scripts/task_python_arm_compute_library.sh
Labels: status: WIP

#7518 [RFC]TECompiler: Staged refactor and removal of compile engine
  include/tvm/relay/attrs/annotation.h
  python/tvm/auto_scheduler/relay_integration.py
  python/tvm/auto_scheduler/task_scheduler.py
  python/tvm/relay/backend/compile_engine.py
  python/tvm/relay/expr.py
  src/driver/driver_api.cc
  src/relay/backend/aot_executor_codegen.cc
  src/relay/backend/compile_engine.cc
  src/relay/backend/compile_engine.h
  src/relay/backend/graph_executor_codegen.cc
  src/relay/backend/graph_plan_memory.cc
  src/relay/backend/interpreter.cc
  src/relay/backend/te_compiler.cc
  src/relay/backend/te_compiler.h
  src/relay/backend/te_compiler_cache.cc
  src/relay/backend/te_compiler_cache.h
  src/relay/backend/utils.cc
  src/relay/backend/utils.h
  src/relay/backend/vm/compiler.cc
  src/relay/ir/function.cc
  src/relay/transforms/auto_scheduler_layout_rewrite.cc
  src/relay/transforms/device_annotation.cc
  src/relay/transforms/memory_alloc.cc
  src/relay/transforms/type_infer.cc
  src/target/llvm/llvm_module.cc
  src/tir/transforms/legalize_packed_calls.cc
  tests/python/relay/test_auto_scheduler_task_extraction.py
  tests/python/relay/test_backend_graph_executor.py
  tests/python/relay/test_pass_annotation.py
Labels: status: need update

#8438 [Bugfix] Fix broadcast type func with incomplete type
  src/relay/op/tensor/transform.cc
Labels: status: need review

#7983 [PROFILING] Use PAPI to collect hardware performance counters on CPU and CUDA
  CMakeLists.txt
  cmake/modules/contrib/PAPI.cmake
  docs/index.rst
  docs/profiling/index.rst
  docs/profiling/papi.rst
  include/tvm/runtime/contrib/papi.h
  include/tvm/runtime/profiling.h
  include/tvm/runtime/threading_backend.h
  python/tvm/contrib/debugger/debug_executor.py
  python/tvm/runtime/profiler_vm.py
  python/tvm/runtime/profiling/__init__.py
  python/tvm/runtime/profiling/_ffi_api.py
  src/runtime/contrib/papi/papi.cc
  src/runtime/graph_executor/debug/graph_executor_debug.cc
  src/runtime/profiling.cc
  src/runtime/thread_pool.cc
  src/runtime/vm/executable.cc
  src/runtime/vm/profiler/vm.cc
  src/runtime/vm/profiler/vm.h
  tests/python/unittest/test_runtime_profiling.py
Labels: status: need update

#8440 [Relay][ONNX] Batch_matmul to dense optimization
  python/tvm/relay/frontend/onnx.py
  tests/python/frontend/onnx/test_forward.py
Labels: status: accepted

#8113 [AutoTVM] Re-enable `ref_input`
  python/tvm/autotvm/measure/measure_methods.py
  tests/python/unittest/test_autotvm_measure.py
Labels: status: need update

#8266 [Bugfix] [tir] do not simplify 'Any() - Any()' to 0
  python/tvm/tir/expr.py
  src/tir/analysis/deep_equal.cc
  tests/python/unittest/test_arith_rewrite_simplify.py
Labels: status: need update

#8193 Update Docker CI
  Jenkinsfile
  python/tvm/relay/frontend/onnx.py
  tests/python/frontend/onnx/test_forward.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: WIP

#8204 Fix #8093, Enhance Buffer Index Simplify
  src/tir/ir/buffer.cc
  tests/python/unittest/test_tir_buffer.py
Labels: status: need review

#8466 [CUDA] Initial support for dynamic shared memory
  docs/dev/codebase_walkthrough.rst
  include/tvm/tir/function.h
  src/runtime/cuda/cuda_module.cc
  src/runtime/file_utils.cc
  src/runtime/meta_data.h
  src/runtime/metal/metal_module.mm
  src/runtime/opencl/opencl_module.cc
  src/runtime/rocm/rocm_module.cc
  src/runtime/thread_storage_scope.h
  src/runtime/vulkan/vulkan_wrapped_func.cc
  src/runtime/vulkan/vulkan_wrapped_func.h
  src/target/build_common.h
  src/target/llvm/codegen_amdgpu.cc
  src/target/llvm/codegen_llvm.cc
  src/target/llvm/codegen_llvm.h
  src/target/llvm/codegen_nvptx.cc
  src/target/source/codegen_cuda.cc
  src/tir/transforms/lower_device_storage_access_info.cc
  src/tir/transforms/split_host_device.cc
  src/tir/transforms/storage_rewrite.cc
  tests/python/unittest/test_tir_ir_builder.py
  web/src/webgpu.ts
Labels: status: need update

#8499 [TVMSCRIPT]Fix script printters StructuralEqual check failed
  src/printer/tvmscript_printer.cc
  tests/python/unittest/test_tvmscript_roundtrip.py
Labels: status: need test case

#8521 [Bugfix] Visit each input param of the function in ExprVisitor visit_function
  python/tvm/relay/expr_functor.py
Labels: status: accepted

#8548 [FFI] Specifically check handle for recursion during shutdown
  python/tvm/runtime/object.py
Labels: status: accepted

#8558 [Frontend][TENSORFLOW] Add support for unpack with dim 0 after tensorlist stack
  python/tvm/relay/frontend/tensorflow2_ops.py
  python/tvm/relay/prelude.py
  tests/python/frontend/tensorflow2/test_functional_models.py
Labels: status: accepted

#8530 [Bugfix] fix android rpc app undefined reference problem
  apps/android_rpc/app/src/main/jni/tvm_runtime.h
Labels: status: accepted

#8506 [TensorRT, BYOC] Handling a corner case in TRT RemoveDropout pass
  python/tvm/relay/op/contrib/tensorrt.py
Labels: status: accepted

#8566 [BUGFIX] fix illegal memory access bug in reduce op schedule by constriant thread_y
  python/tvm/topi/cuda/reduction.py
Labels: status: accepted

#8539 [Test] Fix AutoScheduler test to cover Conv2D Winograd
  tests/python/relay/test_auto_scheduler_layout_rewrite_networks.py
Labels: status: accepted

#8564 [Fix] Enhance robustness of DefuseOps
  src/relay/transforms/defuse_ops.cc
  tests/python/relay/test_pass_annotate_spans_defuse.py
Labels: status: accepted

#8533 [Contrib] Added default non-verbose to download_testdata(), pass to download()
  python/tvm/autotvm/tophub.py
  python/tvm/contrib/download.py
Labels: status: accepted

#8560 [AutoScheduler] Fix task extraction with TE compiler
  python/tvm/auto_scheduler/relay_integration.py
  tests/python/relay/test_auto_scheduler_task_extraction.py
Labels: status: accepted

#8554 [TOPI][CUDA] minor change on assert statement in conv2d_NCHWc_int8.cuda
  python/tvm/topi/cuda/conv2d_int8.py
Labels: status: accepted

#8541 [TOPI] Fix `nn.pool*d` issue with 'vectorize' function and add unit tests
  python/tvm/topi/testing/poolnd_python.py
  python/tvm/topi/x86/pooling.py
  tests/python/topi/python/test_topi_pooling.py
Labels: status: accepted

#8523 [Bugfix] Preserve IRModule type definition and imports in NameMangleExtFuncs
  src/relay/transforms/partition_graph.cc
  tests/python/relay/test_pass_partition_graph.py
Labels: status: accepted

#8517 [TIR] cast disparate floating point types for binary ops
  src/tir/op/op.cc
  tests/python/unittest/test_tir_base.py
  tests/python/unittest/test_tir_ops.py
Labels: status: accepted

#8516 [Refactor] Remove AttrStmt with storage_scope key
  include/tvm/tir/stmt.h
  python/tvm/contrib/hexagon.py
  python/tvm/script/scope_handler.py
  python/tvm/tir/ir_builder.py
  src/printer/tir_text_printer.cc
  src/printer/tvmscript_printer.cc
  src/relay/backend/aot_executor_codegen.cc
  src/target/source/codegen_c.cc
  src/te/operation/cross_thread_reduction.cc
  src/tir/analysis/verify_gpu_code.cc
  src/tir/ir/stmt.cc
  src/tir/transforms/flatten_buffer.cc
  src/tir/transforms/inject_copy_intrin.cc
  src/tir/transforms/inject_double_buffer.cc
  src/tir/transforms/ir_utils.cc
  src/tir/transforms/lower_device_storage_access_info.cc
  src/tir/transforms/lower_thread_allreduce.cc
  src/tir/transforms/lower_warp_memory.cc
  src/tir/transforms/storage_flatten.cc
  src/tir/transforms/storage_rewrite.cc
  src/tir/transforms/tensorcore_infer_fragment.cc
  src/tir/transforms/update_pointer_storage_scope.cc
  src/tir/transforms/update_pointer_storage_scope.h
  tests/python/unittest/test_tir_ir_builder.py
  tests/python/unittest/test_tir_transform_coproc_sync.py
  tests/python/unittest/test_tir_transform_inject_double_buffer.py
  tests/python/unittest/test_tir_transform_inject_virtual_thread.py
  tests/python/unittest/test_tir_transform_lift_attr_scope.py
  tests/python/unittest/test_tir_transform_loop_partition.py
  tests/python/unittest/test_tir_transform_lower_warp_memory.py
  tests/python/unittest/test_tir_transform_storage_flatten.py
  tests/python/unittest/test_tir_transform_storage_rewrite.py
  tests/python/unittest/test_tir_transform_thread_sync.py
Labels: status: accepted

#8581 [FIX][CI] hotfix check_grad perf regression
  python/tvm/relay/backend/interpreter.py
  python/tvm/relay/testing/__init__.py
  python/tvm/topi/arm_cpu/group_conv2d.py
Labels: status: accepted

#8555 [Dynamic Shape] Use SizeVar instead of Var when convert Any in the GetShape function
  include/tvm/tir/expr.h
  src/relay/backend/te_compiler_cache.cc
Labels: status: accepted

#8525 Fix storage_access not visiting else branch
  src/tir/transforms/storage_access.cc
  tests/python/unittest/test_tir_transform_thread_sync.py
Labels: status: accepted

#8544 [TensorIR][M2a] Reduction Factoring (RFactor)
  include/tvm/tir/analysis.h
  include/tvm/tir/schedule/block_scope.h
  include/tvm/tir/schedule/schedule.h
  include/tvm/tir/stmt.h
  python/tvm/script/special_stmt.py
  python/tvm/tir/schedule/schedule.py
  src/arith/canonical_simplify.cc
  src/arith/detect_linear_equation.cc
  src/printer/tir_text_printer.cc
  src/printer/tvmscript_printer.cc
  src/te/autodiff/ad_simplify.cc
  src/te/operation/compute_op.cc
  src/te/operation/tensorize.cc
  src/tir/analysis/var_touch.cc
  src/tir/ir/expr.cc
  src/tir/schedule/analysis.h
  src/tir/schedule/analysis/analysis.cc
  src/tir/schedule/concrete_schedule.cc
  src/tir/schedule/concrete_schedule.h
  src/tir/schedule/primitive.h
  src/tir/schedule/primitive/compute_inline.cc
  src/tir/schedule/primitive/reduction.cc
  src/tir/schedule/schedule.cc
  src/tir/schedule/state.cc
  src/tir/schedule/utils.h
  src/tir/transforms/loop_partition.cc
  src/tir/transforms/lower_warp_memory.cc
  tests/python/unittest/test_te_schedule.py
  tests/python/unittest/test_tir_schedule_reduction.py
Labels: status: accepted
