Repository apache/tvm, pull requests merged in 2021-02, with the labels that each got.

#7368 Refactor Dynamic to Static
  src/relay/transforms/dynamic_to_static.cc
  tests/python/relay/test_pass_dynamic_to_static.py
Labels: status: need review

#7382 Fix missing round(), floor(), ceil() for target C lowering
  src/target/intrin_rule.cc
  tests/python/unittest/test_target_codegen_c_host.py
Labels: status: need update

#6370 [TOPI] Add einsum operator
  include/tvm/topi/einsum.h
  include/tvm/topi/tags.h
  python/tvm/topi/__init__.py
  python/tvm/topi/einsum.py
  src/topi/transform.cc
  tests/python/topi/python/test_topi_einsum.py
  tests/python/unittest/test_te_autodiff.py
Labels: status: need review

#7289 Generate requirements.txt from Python spec
  python/.gitignore
  python/gen_requirements.py
  python/setup.py
  tests/python/unittest/test_gen_requirements.py
Labels: status: review in progress

#7389 [RPC] Replace timestamp with counter
  python/tvm/rpc/tracker.py
Labels: status: review in progress

#7375 Support negative pad values
  src/relay/op/nn/pad.cc
  tests/python/relay/test_op_level2.py
Labels: status: review in progress

#7397 Fix Bug in Bilinear Interpolation and Add Deform Conv to PT FrontEnd
  include/tvm/topi/detail/tensor_utils.h
  python/tvm/relay/frontend/pytorch.py
  python/tvm/topi/testing/deformable_conv2d_python.py
  python/tvm/topi/testing/roi_align_python.py
  python/tvm/topi/vision/rcnn/roi_align.py
  tests/python/frontend/pytorch/test_forward.py
  tests/python/relay/test_op_level5.py
Labels: status: need review

#7377 [AutoScheduler] Support early_stopping per task
  python/tvm/auto_scheduler/task_scheduler.py
Labels: status: accepted

#7394 [Relay][Frontend][Onnx] Refactor where importer to support dynamic shapes.
  python/tvm/relay/frontend/onnx.py
  tests/python/frontend/onnx/test_forward.py
Labels: status: review in progress

#7386 Fix compilation when __ARM_FEATURE_FP16_SCALAR_ARITHMETIC
  src/runtime/contrib/sort/sort.cc
Labels: status: accepted

#7388 Jenkinsfile changes for #7333.
  Jenkinsfile
  tests/scripts/task_ci_setup.sh
Labels: status: review in progress

#7221 [µTVM] Add VMWare to Reference VM instructions
  apps/microtvm/reference-vm/base-box-tool.py
  apps/microtvm/reference-vm/zephyr/Vagrantfile
  apps/microtvm/reference-vm/zephyr/base-box/Vagrantfile.packer-template
  apps/microtvm/reference-vm/zephyr/base-box/setup.sh
  tutorials/micro/micro_reference_vm.py
Labels: status: need review

#7366 [TVMC] Allow manual shape specification in tvmc
  python/tvm/driver/tvmc/autotuner.py
  python/tvm/driver/tvmc/common.py
  python/tvm/driver/tvmc/compiler.py
  python/tvm/driver/tvmc/frontends.py
  tests/python/driver/tvmc/conftest.py
  tests/python/driver/tvmc/test_common.py
  tests/python/driver/tvmc/test_compiler.py
  tests/python/driver/tvmc/test_frontends.py
  tests/scripts/setup-pytest-env.sh
Labels: status: review in progress

#7376 [AutoScheduler] Add sampling to dispatcher
  python/tvm/auto_scheduler/__init__.py
  python/tvm/auto_scheduler/dispatcher.py
  tests/python/relay/test_auto_scheduler_tuning.py
Labels: status: need review

#7404 [Relay][Topi][CPU] Dense with weight transform
  python/tvm/relay/op/nn/_nn.py
  python/tvm/relay/op/nn/nn.py
  python/tvm/relay/op/strategy/generic.py
  python/tvm/relay/op/strategy/x86.py
  python/tvm/topi/nn/dense.py
  python/tvm/topi/x86/__init__.py
  python/tvm/topi/x86/dense.py
  python/tvm/topi/x86/dense_alter_op.py
  src/relay/op/nn/nn.cc
  src/relay/op/nn/nn.h
  tests/python/relay/test_autotvm_task_extraction.py
  tests/python/relay/test_pass_alter_op_layout.py
  tutorials/micro/micro_tflite.py
Labels: status: need review

#7372 [BYOC][TRT] Fix small bug preventing TRT runtime compilation for versions < 6
  src/runtime/contrib/tensorrt/tensorrt_ops.cc
Labels: status: review in progress

#7427 Make the TVM targets list available in Python
  include/tvm/target/target_kind.h
  python/tvm/target/target.py
  src/target/target_kind.cc
  tests/cpp/target_test.cc
  tests/python/unittest/test_target_target.py
Labels: status: need review

#7333 [µTVM] Use standalone_crt build tree for all µTVM builds
  cmake/modules/StandaloneCrt.cmake
  python/tvm/micro/__init__.py
  python/tvm/micro/build.py
  python/tvm/micro/compiler.py
  tests/micro/qemu/test_zephyr.py
  tests/python/unittest/test_crt.py
  tests/python/unittest/test_link_params.py
  tests/scripts/task_ci_setup.sh
  tutorials/micro/micro_tflite.py
Labels: status: need review

#7453 docker/bash.sh: lookup docker image in Jenkinsfile
  docker/bash.sh
  docker/dev_common.sh
Labels: status: need review

#7304 [TVMC] Add composite target passes for compilation and tuning
  python/tvm/driver/tvmc/autotuner.py
  python/tvm/driver/tvmc/common.py
  python/tvm/driver/tvmc/compiler.py
  python/tvm/driver/tvmc/composite_target.py
  python/tvm/relay/op/contrib/ethosn.py
  tests/python/driver/tvmc/test_common.py
  tests/python/driver/tvmc/test_compiler.py
  tests/python/driver/tvmc/test_composite_target.py
Labels: status: need review

#7445 [Frontend][Tensorflow] Support explicit_paddings for TF 2.x
  python/tvm/relay/frontend/tensorflow.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need update

#7347 [RELAY][Parser] Optimize relay parser to restore calls attrs
  src/parser/parser.cc
  src/printer/relay_text_printer.cc
  tests/python/relay/test_ir_parser.py
Labels: status: need review

#7350 [BYOC][VitisAI] Fix issue in Vitis AI codegen out tensor names matching & update docs and docker
  docker/Dockerfile.demo_vitis_ai
  docker/install/ubuntu_install_vitis_ai_core.sh
  docs/deploy/vitis_ai.rst
  python/tvm/contrib/target/vitis_ai.py
  python/tvm/relay/op/contrib/vitis_ai.py
Labels: status: review in progress

#7337 Introduce module_loader to AutoTVM.
  python/tvm/autotvm/measure/__init__.py
  python/tvm/autotvm/measure/measure_methods.py
  vta/python/vta/__init__.py
  vta/python/vta/autotvm.py
  vta/tutorials/autotvm/tune_relay_vta.py
Labels: status: need review

#7487 [Relay] Enforce static dim for non-concat axis if one or more tensors have static dim
  src/relay/op/tensor/transform.h
  tests/python/relay/test_any.py
Labels: status: need review

#7488 [Runtime] Special Memory Scope Support
  include/tvm/runtime/c_runtime_api.h
  include/tvm/runtime/device_api.h
  include/tvm/runtime/ndarray.h
  python/tvm/runtime/ndarray.py
  src/runtime/c_runtime_api.cc
  src/runtime/cpu_device_api.cc
  src/runtime/crt/common/crt_runtime_api.c
  src/runtime/cuda/cuda_device_api.cc
  src/runtime/hexagon/hexagon_device_api.cc
  src/runtime/metal/metal_common.h
  src/runtime/minrpc/minrpc_server.h
  src/runtime/minrpc/rpc_reference.h
  src/runtime/ndarray.cc
  src/runtime/opencl/opencl_common.h
  src/runtime/rpc/rpc_device_api.cc
  src/runtime/rpc/rpc_endpoint.cc
  src/runtime/rpc/rpc_endpoint.h
  src/runtime/rpc/rpc_local_session.cc
  src/runtime/rpc/rpc_local_session.h
  src/runtime/rpc/rpc_session.cc
  src/runtime/rpc/rpc_session.h
  src/runtime/vulkan/vulkan.cc
  web/emcc/tvmjs_support.cc
  web/emcc/webgpu_runtime.cc
Labels: status: need review
