Repository apache/tvm, pull requests merged in 2021-08, with the labels that each got.

#8373 [BUILD] Add caching to CMake
  CMakeLists.txt
  cmake/config.cmake
  tests/scripts/task_config_build_arm.sh
  tests/scripts/task_config_build_cpu.sh
  tests/scripts/task_config_build_gpu.sh
  tests/scripts/task_config_build_gpu_vulkan.sh
  tests/scripts/task_config_build_i386.sh
  tests/scripts/task_config_build_qemu.sh
  tests/scripts/task_config_build_wasm.sh
Labels: status: need update

#8615 [Meta Schedule][M3a] Instruction and Trace
  include/tvm/tir/schedule/instruction.h
  include/tvm/tir/schedule/schedule.h
  include/tvm/tir/schedule/state.h
  include/tvm/tir/schedule/trace.h
  python/tvm/tir/schedule/__init__.py
  python/tvm/tir/schedule/_ffi_api.py
  python/tvm/tir/schedule/block_scope.py
  python/tvm/tir/schedule/instruction.py
  python/tvm/tir/schedule/schedule.py
  python/tvm/tir/schedule/state.py
  python/tvm/tir/schedule/trace.py
  src/tir/schedule/analysis.h
  src/tir/schedule/analysis/analysis.cc
  src/tir/schedule/concrete_schedule.h
  src/tir/schedule/instruction.cc
  src/tir/schedule/instruction_traits.h
  src/tir/schedule/primitive.h
  src/tir/schedule/primitive/compute_inline.cc
  src/tir/schedule/primitive/get_block_loop.cc
  src/tir/schedule/primitive/loop_transformation.cc
  src/tir/schedule/primitive/reduction.cc
  src/tir/schedule/schedule.cc
  src/tir/schedule/state.cc
  src/tir/schedule/trace.cc
  src/tir/schedule/utils.h
  tests/python/unittest/test_tir_schedule_block_scope.py
  tests/python/unittest/test_tir_schedule_compute_inline.py
  tests/python/unittest/test_tir_schedule_error.py
  tests/python/unittest/test_tir_schedule_instruction.py
  tests/python/unittest/test_tir_schedule_reduction.py
  tests/python/unittest/test_tir_schedule_split_fuse.py
  tests/python/unittest/test_tir_schedule_state.py
  tests/python/unittest/test_tir_schedule_state_cached_flags.py
  tests/python/unittest/test_tir_schedule_trace.py
  tests/python/unittest/test_tir_schedule_utilities.py
Labels: status: accepted

#8580 [runtime] Remove unused parameter.
  src/runtime/crt/graph_executor/graph_executor.c
  src/runtime/crt/include/tvm/runtime/crt/internal/graph_executor/graph_executor.h
  src/runtime/graph_executor/graph_executor.cc
  src/runtime/graph_executor/graph_executor.h
  src/runtime/micro/standalone/microtvm_graph_executor.cc
Labels: status: need review

#8280 Introduce --interface-api={c,packed} parameter
  apps/microtvm/zephyr/aot_demo/src/main.c
  include/tvm/runtime/module.h
  python/tvm/micro/interface_api.py
  python/tvm/micro/model_library_format.py
  src/relay/backend/aot_executor_codegen.cc
  src/runtime/meta_data.h
  src/target/source/source_module.cc
  src/target/target_kind.cc
  tests/micro/zephyr/test_zephyr_aot.py
  tests/python/relay/aot/aot_test.mk
  tests/python/relay/aot/aot_test_utils.py
  tests/python/relay/aot/test_crt_aot.py
  tests/python/unittest/test_micro_model_library_format.py
Labels: status: need update

#8567 [FIX,PROFILING] Add USE_PAPI configuration to config.cmake
  cmake/config.cmake
Labels: status: accepted

#8662 [AutoScheduler] Fix deserization of workload registry entry
  python/tvm/auto_scheduler/workload_registry.py
  tests/python/unittest/test_auto_scheduler_measure.py
Labels: status: accepted

#8529 [Topi][Testing] Float16 unittests for dense, conv2d, depthwise conv2d
  python/tvm/topi/testing/common.py
  python/tvm/topi/testing/conv2d_nchw_python.py
  python/tvm/topi/testing/depthwise_conv2d_python.py
  python/tvm/topi/testing/dilate_python.py
  tests/python/topi/python/test_topi_conv2d_nchw.py
  tests/python/topi/python/test_topi_conv3d_ncdhw.py
  tests/python/topi/python/test_topi_conv3d_winograd.py
  tests/python/topi/python/test_topi_dense.py
  tests/python/topi/python/test_topi_depthwise_conv2d.py
Labels: status: accepted

#8623 [Meta Schedule][M3a] Traced Schedule
  include/tvm/tir/schedule/schedule.h
  include/tvm/tir/schedule/state.h
  python/tvm/tir/schedule/schedule.py
  python/tvm/tir/schedule/state.py
  python/tvm/tir/schedule/testing.py
  src/tir/schedule/concrete_schedule.cc
  src/tir/schedule/concrete_schedule.h
  src/tir/schedule/schedule.cc
  src/tir/schedule/state.cc
  src/tir/schedule/traced_schedule.cc
  src/tir/schedule/traced_schedule.h
  tests/python/unittest/test_te_create_primfunc.py
  tests/python/unittest/test_tir_schedule_block_scope.py
  tests/python/unittest/test_tir_schedule_compute_inline.py
  tests/python/unittest/test_tir_schedule_error.py
  tests/python/unittest/test_tir_schedule_reduction.py
  tests/python/unittest/test_tir_schedule_split_fuse.py
  tests/python/unittest/test_tir_schedule_state.py
  tests/python/unittest/test_tir_schedule_state_cached_flags.py
  tests/python/unittest/test_tir_schedule_trace.py
  tests/python/unittest/test_tir_schedule_utilities.py
Labels: status: need review

#8638 [Docs] Added documentation on pytest target parametrization.
  docs/dev/how_to.rst
  docs/dev/pytest_target_parametrization.rst
Labels: status: need review

#7686 [Texture support][Part 1] TIR lowering and OpenCL support
  include/tvm/tir/builtin.h
  include/tvm/tir/transform.h
  python/tvm/tir/transform/transform.py
  src/driver/driver_api.cc
  src/target/source/codegen_c.cc
  src/target/source/codegen_c.h
  src/target/source/codegen_opencl.cc
  src/target/source/codegen_opencl.h
  src/te/operation/op_utils.cc
  src/tir/op/builtin.cc
  src/tir/transforms/lower_tvm_builtin.cc
  src/tir/transforms/texture_flatten.cc
  src/tir/transforms/vectorize_loop.cc
  tests/python/unittest/test_target_texture_codegen_opencl.py
Labels: status: need review, status: need RFC

#8837 Remove reference to Apache Incubator status.
  CONTRIBUTORS.md
Labels: status: accepted

#8781 [Frontend] [Torch] [ONNX] GRU layer
  python/tvm/relay/frontend/common.py
  python/tvm/relay/frontend/onnx.py
  python/tvm/relay/frontend/pytorch.py
  tests/python/frontend/pytorch/test_lstms.py
  tests/python/frontend/pytorch/test_rnns.py
Labels: status: need review

#8822 [Hexagon] Reuse Hexagon SDK analysis across cmake files
  cmake/config.cmake
  cmake/modules/Hexagon.cmake
  cmake/modules/HexagonSDK.cmake
  src/runtime/hexagon/sim/driver/CMakeLists.txt
  src/runtime/hexagon/target/fastrpc/CMakeLists.txt
Labels: status: need review

#8863 [TensorIR][M2a] CacheRead/Write
  include/tvm/tir/schedule/schedule.h
  include/tvm/tir/schedule/state.h
  python/tvm/tir/schedule/schedule.py
  src/tir/schedule/analysis.h
  src/tir/schedule/analysis/analysis.cc
  src/tir/schedule/concrete_schedule.cc
  src/tir/schedule/concrete_schedule.h
  src/tir/schedule/primitive.h
  src/tir/schedule/primitive/block_annotate.cc
  src/tir/schedule/primitive/cache_read_write.cc
  src/tir/schedule/schedule.cc
  src/tir/schedule/state.cc
  src/tir/schedule/traced_schedule.cc
  src/tir/schedule/traced_schedule.h
  src/tir/schedule/transform.cc
  src/tir/schedule/transform.h
  src/tir/schedule/utils.h
  tests/python/unittest/test_tir_schedule_cache_read_write.py
Labels: status: need review
