Repository apache/tvm, pull requests merged in 2021-06, with the labels that each got.

#7917 allow libbacktrace to be used when cross compiling the runtime
  cmake/libs/Libbacktrace.cmake
  docs/deploy/index.rst
  docs/install/from_source.rst
Labels: status: need review

#8099 [ONNX] [Relay] Update unique operator to match ONNX output (1D only)
  python/tvm/relay/frontend/onnx.py
  python/tvm/relay/frontend/pytorch.py
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/op/_transform.py
  python/tvm/relay/op/transform.py
  python/tvm/topi/cuda/unique.py
  python/tvm/topi/unique.py
  src/relay/op/tensor/transform.cc
  tests/python/frontend/onnx/test_forward.py
  tests/python/relay/test_op_level3.py
  tests/python/topi/python/test_topi_unique.py
Labels: status: need review

#7711 [Texture support][Part 0] Device API and runtime support
  src/runtime/opencl/opencl_common.h
  src/runtime/opencl/opencl_device_api.cc
  src/runtime/opencl/opencl_module.cc
  src/runtime/opencl/texture_pool.cc
  src/runtime/texture.h
  tests/cpp/texture_copy_test.cc
Labels: status: need update

#8166 [Bug Fix] Fix bug in dense_nopack of x86 when using dynamic input shape
  python/tvm/topi/x86/dense.py
Labels: status: need test case

#8142 [Frontend, Tensorflow2] Adding TF2 frontend code with support for control flow ops
  python/tvm/relay/frontend/tensorflow2.py
  tests/python/frontend/tensorflow2/common.py
  tests/python/frontend/tensorflow2/test_functional_models.py
Labels: status: need review

#8144 [Docker] Add external directory mount
  docker/bash.sh
Labels: status: need update

#8207 [QNN] Support dequantizing scalar inputs
  src/relay/qnn/op/dequantize.cc
  tests/python/relay/test_op_qnn_dequantize.py
Labels: status: review in progress

#8208 [Frontend] Speed up Fold Constant
  python/tvm/relay/frontend/common.py
Labels: status: need review

#8200 [RUNTIME] ShapeTuple Container
  include/tvm/runtime/container/shape_tuple.h
  include/tvm/runtime/ndarray.h
  include/tvm/runtime/object.h
  include/tvm/runtime/packed_func.h
  python/tvm/runtime/container.py
  src/node/container_printing.cc
  src/runtime/container.cc
  src/runtime/ndarray.cc
  tests/python/unittest/test_runtime_container.py
Labels: status: need review

#8179 [Frontend, Tensorflow, Tensorflow2] Tensorflow frontend op refactor
  python/tvm/relay/frontend/tensorflow.py
  python/tvm/relay/frontend/tensorflow2.py
  python/tvm/relay/frontend/tensorflow_ops.py
Labels: status: need review

#8206 [Metal] Reduce number of threads for reduction layers
  include/tvm/topi/cuda/reduction.h
  python/tvm/topi/cuda/reduction.py
Labels: status: need review

#8196 [Vulkan][Refactor] Move ownership of per-CPU-thread objects to VulkanDeviceAPI
  src/runtime/thread_map.h
  src/runtime/vulkan/vulkan_buffer.cc
  src/runtime/vulkan/vulkan_buffer.h
  src/runtime/vulkan/vulkan_device.cc
  src/runtime/vulkan/vulkan_device.h
  src/runtime/vulkan/vulkan_device_api.cc
  src/runtime/vulkan/vulkan_device_api.h
  src/runtime/vulkan/vulkan_stream.cc
  src/runtime/vulkan/vulkan_stream.h
  src/runtime/vulkan/vulkan_thread_entry.cc
  src/runtime/vulkan/vulkan_thread_entry.h
  src/runtime/vulkan/vulkan_wrapped_func.cc
Labels: status: need review

#8149 [BYOC][ACL] Prevent dilated pooling
  python/tvm/relay/op/contrib/arm_compute_lib.py
  src/runtime/contrib/arm_compute_lib/acl_runtime.cc
  tests/python/contrib/test_arm_compute_lib/test_pooling.py
Labels: status: need review

#7858 [ETHOSN] Removed support for 20.08 version of the driver stack.
  src/relay/backend/contrib/ethosn/capabilities.h
  src/relay/backend/contrib/ethosn/codegen.cc
  src/relay/backend/contrib/ethosn/codegen_ethosn.h
  src/relay/backend/contrib/ethosn/ethosn_api_version.h
  tests/python/contrib/test_ethosn/infrastructure.py
  tests/python/contrib/test_ethosn/test_conv2d.py
  tests/python/contrib/test_ethosn/test_networks.py
Labels: status: need review

#8215 [TVMSCRIPT] Fix printing of rank 0 buffer access
  python/tvm/script/intrin.py
  python/tvm/script/parser.py
  src/printer/tvmscript_printer.cc
  tests/python/unittest/test_tvmscript_roundtrip.py
Labels: status: need review

#8205 [Relay][Convert Layout] Enable layout transformation for image.resize op
  python/tvm/relay/op/image/_image.py
  src/relay/op/image/resize.cc
  tests/python/relay/test_pass_convert_op_layout.py
Labels: status: accepted

#8203 [Bug Fixed] Make query_rpc_tracker show the correct device server port and customized address
  python/tvm/rpc/server.py
  python/tvm/rpc/tracker.py
  tests/python/unittest/test_runtime_rpc.py
Labels: status: need test case, status: review in progress

#8288 [Auto Scheduler] Make the opt_level of task extraction adjustable
  python/tvm/auto_scheduler/relay_integration.py
  python/tvm/rpc/tracker.py
Labels: status: accepted

#8088 [BYOC][NNAPI]: Add testing package to ci_cpu image
  docker/Dockerfile.ci_cpu
Labels: status: accepted

#8235 [TVMSCRIPT] add more type support in script function parameter
  python/tvm/script/ty.py
  tests/python/unittest/test_tvmscript_ops.py
Labels: status: accepted
