Repository apache/tvm, pull requests merged in 2021-09, with the labels that each got.

#8930 [Bugfix] Add check to avoid calling back() on an empty container
  src/tir/transforms/ir_utils.cc
  tests/python/unittest/test_tir_transform_ir_utils.py
Labels: status: accepted

#8910 [Bugfix] Add a nullptr check to tir.Buffer to fix the illegal memory access
  src/tir/ir/buffer.cc
  tests/python/unittest/test_tir_buffer.py
Labels: status: accepted

#8943 [TensorIR][M2a] Compute-At
  include/tvm/arith/int_set.h
  include/tvm/tir/schedule/schedule.h
  include/tvm/tir/schedule/state.h
  python/tvm/tir/schedule/schedule.py
  src/arith/int_set.cc
  src/relay/transforms/fold_scale_axis.cc
  src/support/nd_int_set.h
  src/tir/schedule/analysis.h
  src/tir/schedule/analysis/analysis.cc
  src/tir/schedule/concrete_schedule.cc
  src/tir/schedule/concrete_schedule.h
  src/tir/schedule/primitive.h
  src/tir/schedule/primitive/block_annotate.cc
  src/tir/schedule/primitive/cache_read_write.cc
  src/tir/schedule/primitive/compute_at.cc
  src/tir/schedule/primitive/compute_inline.cc
  src/tir/schedule/primitive/for_kind.cc
  src/tir/schedule/primitive/get_block_loop.cc
  src/tir/schedule/primitive/loop_transformation.cc
  src/tir/schedule/primitive/reduction.cc
  src/tir/schedule/primitive/sampling.cc
  src/tir/schedule/schedule.cc
  src/tir/schedule/state.cc
  src/tir/schedule/traced_schedule.cc
  src/tir/schedule/traced_schedule.h
  src/tir/schedule/transform.cc
  src/tir/schedule/transform.h
  src/tir/schedule/utils.h
  src/tir/transforms/compact_buffer_region.cc
  tests/python/unittest/test_tir_schedule_compute_at.py
Labels: status: need review

#8808 [BYOC][TensorRT] Add TensorRT own int8 calibration support to TensorRT BYOC integration
  src/runtime/contrib/tensorrt/tensorrt_builder.cc
  src/runtime/contrib/tensorrt/tensorrt_builder.h
  src/runtime/contrib/tensorrt/tensorrt_calibrator.h
  src/runtime/contrib/tensorrt/tensorrt_runtime.cc
  tests/python/contrib/test_tensorrt_int8_exp.py
Labels: status: review in progress

#8996 [Relay][Pass] Add ExtractOperators pass
  python/tvm/relay/analysis/analysis.py
  src/relay/analysis/extract_operators.cc
  tests/python/relay/test_analysis_extract_operators.py
Labels: status: accepted

#8423 Implementation of relay_to_tir target hook
  CMakeLists.txt
  cmake/modules/contrib/ExampleTargetHooks.cmake
  include/tvm/relay/transform.h
  src/relay/backend/contrib/example_target_hooks/relay_to_tir.cc
  src/relay/backend/te_compiler.cc
  src/relay/transforms/target_hooks.cc
  tests/python/relay/test_target_hooks.py
Labels: status: need RFC

#7876 [iOS] Add tracker support into ios-rpc application
  apps/ios_rpc/CMakeLists.txt
  apps/ios_rpc/README.md
  apps/ios_rpc/init_proj.py
  apps/ios_rpc/tests/ios_rpc_mobilenet.py
  apps/ios_rpc/tests/ios_rpc_test.py
  apps/ios_rpc/tvmrpc.xcodeproj/project.pbxproj
  apps/ios_rpc/tvmrpc.xcodeproj/xcshareddata/xcschemes/tvmrpc.xcscheme
  apps/ios_rpc/tvmrpc/Base.lproj/Main.storyboard
  apps/ios_rpc/tvmrpc/RPCArgs.h
  apps/ios_rpc/tvmrpc/RPCArgs.mm
  apps/ios_rpc/tvmrpc/RPCServer.h
  apps/ios_rpc/tvmrpc/RPCServer.mm
  apps/ios_rpc/tvmrpc/TVMRuntime.h
  apps/ios_rpc/tvmrpc/TVMRuntime.mm
  apps/ios_rpc/tvmrpc/ViewController.h
  apps/ios_rpc/tvmrpc/ViewController.mm
  apps/ios_rpc/tvmrpc/main.m
  apps/ios_rpc/tvmrpcLauncher/Info.plist
  apps/ios_rpc/tvmrpcLauncher/tvmrpcLauncher.mm
  python/tvm/contrib/xcode.py
  tests/lint/check_file_type.py
Labels: status: need update
