Repository apache/tvm, pull requests merged in 2022-01, with the labels that each got.

#9884 fix pytorch frontend bug
  python/tvm/relay/frontend/pytorch.py
Labels: status: need update

#6890 [Relay] Fix a bug in tensor_array_scatter
  python/tvm/relay/prelude.py
  tests/python/frontend/tensorflow/test_forward.py
Labels: status: need review

#7006 [frontend][keras] Add support for TimeDistributed
  python/tvm/relay/frontend/keras.py
  tests/python/frontend/keras/test_forward.py
Labels: status: need review, status: need update, needs-triage

#9717 [Bugfix][Op] Fix shape inference of adv_index
  include/tvm/topi/transform.h
  python/tvm/relay/op/_transform.py
  src/relay/op/tensor/transform.cc
  tests/python/relay/test_any.py
  tests/python/relay/test_op_level3.py
  tests/python/topi/python/test_topi_transform.py
Labels: needs-triage
